# R515B Soğutucu Akışkan — Model Eğitimi

Bu notebook, Doymuş ve Kızgın buhar veri setleri için **4 farklı senaryo** ile regresyon modeli eğitimi yapar:

| # | Senaryo | Açıklama |
|---|---------|----------|
| 1 | **Base** | Orijinal veri ile temel eğitim |
| 2 | **SMOGN** | SMOGN ile veri artırma sonrası eğitim |
| 3 | **STGP-EF** | SymbolicTransformer  ve Evolutionary Forest Hibrit Yöntemi ile öznitelik inşası sonrası eğitim |
| 4 | **SMOGN+STGP-EF** | Önce SMOGN, sonra STGP-EF ile birleşik eğitim |

Her senaryo **8 farklı regresyon algoritması** ile değerlendirilir (RF, ET, AdaBoost, GBDT, DART, XGBoost, LightGBM, CatBoost).

---

## 1. Kütüphaneler ve Fonksiyonlar

In [ ]:
import sys
sys.path.insert(0, 'R515B_Ozellikler')

import pandas as pd
from Functions import (
    run_doymus_analysis,
    run_kizgin_analysis,
    build_results_table,
    show_best_results,
    compare_scenarios,
    target_summary,
    save_wide_results
)

print('Fonksiyonlar başarıyla yüklendi.')

c:\Users\SGUZEY\Documents\Yüksek Lisans Dersleri\Veri Mühendisliği\Data_Engineering_Project\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Fonksiyonlar başarıyla yüklendi.

## 2. Veri Yükleme

In [2]:
df_doymus = pd.read_csv('R515B_Ozellikler/R515B_Doymus_Ozellikleri.csv')
df_kizgin = pd.read_csv('R515B_Ozellikler/R515B_Kizgin_Buhar.csv')

print(f'Doymuş Buhar: {df_doymus.shape}')
print(f'Kızgın Buhar: {df_kizgin.shape}')
print(f'\nDoymuş Sütunlar: {list(df_doymus.columns)}')
print(f'Kızgın Sütunlar: {list(df_kizgin.columns)}')

Doymuş Buhar: (136, 8)
Kızgın Buhar: (578, 5)

Doymuş Sütunlar: ['T(girdi)', 'P(çıktı)', 'v sıvı (çıktı)', 'v buhar (çıktı)', 'h sıvı (çıktı)', 'h buhar (çıktı)', 's sıvı (çıktı)', 's buhar (çıktı)']
Kızgın Sütunlar: ['T (girdi)', 'P (girdi)', 'v (çıktı)', 'h (çıktı)', 's (çıktı)']

In [3]:
df_doymus.head()

   T(girdi)  P(çıktı)  v sıvı (çıktı)  v buhar (çıktı)  h sıvı (çıktı)  h buhar (çıktı)  s sıvı (çıktı)  s buhar (çıktı)
0       -30   61.2210          0.0007           0.2726          2.7282         198.2000          0.0446           0.8486
1       -29   64.2350          0.0007           0.2606          3.9422         198.8900          0.0496           0.8481
2       -28   67.3670          0.0007           0.2492          5.1587         199.5800          0.0546           0.8476
3       -27   70.6200          0.0007           0.2385          6.3775         200.2700          0.0595           0.8472
4       -26   73.9960          0.0008           0.2282          7.5988         200.9500          0.0645           0.8468

In [4]:
df_kizgin.head()

   T (girdi)  P (girdi)  v (çıktı)  h (çıktı)  s (çıktı)
0        -30         50     0.3357   198.5500     0.8639
1        -25         50     0.3433   202.4500     0.8798
2        -20         50     0.3508   206.4000     0.8956
3        -15         50     0.3582   210.4000     0.9112
4        -10         50     0.3656   214.4300     0.9267

---
## 3. Doymuş Buhar — Eğitim

**Girdi:** T(girdi)  
**Çıktılar (her biri ayrı ayrı):** P, v sıvı, v buhar, h sıvı, h buhar, s sıvı, s buhar

In [5]:
doymus_results = run_doymus_analysis(df_doymus)

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  DOYMUŞ BUHAR ANALİZİ
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

============================================================
  Hedef: P(çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...
    SMOGN hatası: SMOGN işlemi 'balance' parametresi ile başarısız oldu: redefine phi relevance function: all points are 1
  [3/4] STGP-EF eğitim...
  [4/4] SMOGN + STGP-EF eğitim...
    SMOGN+STGP-EF hatası: SMOGN işlemi 'balance' parametresi ile başarısız oldu: redefine phi relevance function: all points are 1
  Tamamlandı.


============================================================
  Hedef: v sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 14/14 [00:00<00:00, 960.11it/s]
synth_matrix: 100%|##########| 14/14 [00:00<00:00, 595.43it/s]
r_index: 100%|##########| 5/5 [00:00<00:00, 1250.61it/s]

  [3/4] STGP-EF eğitim...
  [4/4] SMOGN + STGP-EF eğitim...
  Tamamlandı.


============================================================
  Hedef: v buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 18/18 [00:00<00:00, 680.32it/s]
synth_matrix: 100%|##########| 18/18 [00:00<00:00, 1370.61it/s]
r_index: 100%|##########| 11/11 [00:00<00:00, 1203.12it/s]

  [3/4] STGP-EF eğitim...
  [4/4] SMOGN + STGP-EF eğitim...
  Tamamlandı.


============================================================
  Hedef: h sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...
    SMOGN hatası: SMOGN işlemi 'balance' parametresi ile başarısız oldu: redefine phi relevance function: all points are 1
  [3/4] STGP-EF eğitim...
  [4/4] SMOGN + STGP-EF eğitim...
    SMOGN+STGP-EF hatası: SMOGN işlemi 'balance' parametresi ile başarısız oldu: redefine phi relevance function: all points are 1
  Tamamlandı.


============================================================
  Hedef: h buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...
    SMOGN hatası: SMOGN işlemi 'balance' parametresi ile başarısız oldu: redefine phi relevance function: all points are 1
  [3/4] STGP-EF eğitim...
  [4/4] SMOGN + STGP-EF eğitim...
    SMOGN+STGP-EF hatası: SMOGN işlemi 'balance' parametresi ile başarısız oldu: redefine phi relevance function: all points are 1
  Tamamlandı.


============================================================
  Hedef: s sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...
    SMOGN hatası: SMOGN işlemi 'balance' parametresi ile başarısız oldu: redefine phi relevance function: all points are 1
  [3/4] STGP-EF eğitim...
  [4/4] SMOGN + STGP-EF eğitim...
    SMOGN+STGP-EF hatası: SMOGN işlemi 'balance' parametresi ile başarısız oldu: redefine phi relevance function: all points are 1
  Tamamlandı.


============================================================
  Hedef: s buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 5/5 [00:00<00:00, 1248.16it/s]
synth_matrix: 100%|##########| 5/5 [00:00<00:00, 267.65it/s]
r_index: 100%|##########| 2/2 [00:00<00:00, 999.71it/s]

  [3/4] STGP-EF eğitim...
  [4/4] SMOGN + STGP-EF eğitim...
  Tamamlandı.

### 3.1 Doymuş Buhar — Sonuç Tablosu

In [6]:
df_doymus_results = build_results_table(doymus_results)
df_doymus_results

               Hedef        Senaryo Algoritma  Train_R2  Test_R2  Train_RMSE  Test_RMSE  Train_MAPE  Test_MAPE
0           P(çıktı)           Base  AdaBoost    0.9964   0.9959      0.0598     0.0653      0.0706     0.1070
1           P(çıktı)           Base  CatBoost    0.9998   0.9991      0.0123     0.0300      0.0484     0.0844
2           P(çıktı)           Base      DART    0.9387   0.9541      0.2475     0.2177      0.2042     0.1343
3           P(çıktı)           Base        EF    1.0000   1.0000      0.0000     0.0054      0.0000     0.0077
4           P(çıktı)           Base        ET    1.0000   1.0000      0.0000     0.0035      0.0000     0.0034
..               ...            ...       ...       ...      ...         ...        ...         ...        ...
303  s buhar (çıktı)  SMOGN+STGP-EF        GP    0.9705   0.6063      0.3162     0.4783      0.7271     1.1128
304  s buhar (çıktı)  SMOGN+STGP-EF       KNN    0.9972   0.8995      0.0979     0.2417      0.2470     0.6403
305  s buhar (çıktı)  SMOGN+STGP-EF  LightGBM    0.9948   0.8822      0.1332     0.2617      0.4324     0.6919
306  s buhar (çıktı)  SMOGN+STGP-EF        RF    0.9998   0.8965      0.0249     0.2453      0.0397     0.3615
307  s buhar (çıktı)  SMOGN+STGP-EF   XGBoost    1.0000   0.9164      0.0018     0.2204      0.0021     0.5231

[308 rows x 9 columns]

### 3.2 Doymuş Buhar — Senaryo Karşılaştırması

In [7]:
compare_scenarios(df_doymus_results)

Senaryo                    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Hedef          Algoritma
P(çıktı)       AdaBoost  0.9959    NaN   0.9939            NaN
               CatBoost  0.9991    NaN   0.9994            NaN
               DART      0.9541    NaN   0.9570            NaN
               EF        1.0000    NaN   1.0000            NaN
               ET        1.0000    NaN   1.0000            NaN
...                         ...    ...      ...            ...
v sıvı (çıktı) GP        0.9595 0.9668   0.9565         0.9630
               KNN       0.9992 0.9964   0.9991         0.9950
               LightGBM  0.9346 0.8852   0.9710         0.9362
               RF        0.9994 0.9980   0.9993         0.9973
               XGBoost   0.9966 0.9911   0.9965         0.9890

[77 rows x 4 columns]

### 3.3 Doymuş Buhar — Hedef Bazlı Detay

Her bir hedef değişken için detaylı pivot tablo;

In [8]:
target_summary(df_doymus_results, 'P(çıktı)')

Senaryo     Base  STGP-EF
Algoritma
AdaBoost  0.9959   0.9939
CatBoost  0.9991   0.9994
DART      0.9541   0.9570
EF        1.0000   1.0000
ET        1.0000   1.0000
GBDT      0.9991   0.9992
GP        0.9702   0.9802
KNN       0.9998   0.9998
LightGBM  0.9651   0.9664
RF        0.9997   0.9997
XGBoost   0.9982   0.9982

In [9]:
target_summary(df_doymus_results, 'v sıvı (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9943 0.9790   0.9967         0.9870
CatBoost  0.9981 0.9976   0.9987         0.9974
DART      0.9252 0.8980   0.9392         0.9384
EF        1.0000 0.9995   1.0000         0.9995
ET        1.0000 0.9997   1.0000         0.9996
GBDT      0.9980 0.9967   0.9986         0.9971
GP        0.9595 0.9668   0.9565         0.9630
KNN       0.9992 0.9964   0.9991         0.9950
LightGBM  0.9346 0.8852   0.9710         0.9362
RF        0.9994 0.9980   0.9993         0.9973
XGBoost   0.9966 0.9911   0.9965         0.9890

In [10]:
target_summary(df_doymus_results, 'v buhar (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9875 0.9917   0.9883         0.9927
CatBoost  0.9966 0.9972   0.9975         0.9977
DART      0.7834 0.9502   0.8682         0.9533
EF        0.9987 0.9988   0.9990         0.9985
ET        0.9991 0.9988   0.9992         0.9988
GBDT      0.9959 0.9967   0.9975         0.9968
GP        0.9758 0.9500   0.9900         0.9887
KNN       0.9915 0.9922   0.9912         0.9934
LightGBM  0.7845 0.9641   0.9146         0.9671
RF        0.9965 0.9970   0.9967         0.9968
XGBoost   0.9929 0.9918   0.9934         0.9918

In [11]:
target_summary(df_doymus_results, 'h sıvı (çıktı)')

Senaryo     Base  STGP-EF
Algoritma
AdaBoost  0.9989   0.9988
CatBoost  0.9993   0.9994
DART      0.9667   0.9699
EF        0.9999   1.0000
ET        1.0000   1.0000
GBDT      0.9993   0.9995
GP        0.9955   0.9955
KNN       0.9997   0.9995
LightGBM  0.9753   0.9826
RF        0.9997   0.9998
XGBoost   0.9986   0.9983

In [12]:
target_summary(df_doymus_results, 'h buhar (çıktı)')

Senaryo     Base  STGP-EF
Algoritma
AdaBoost  0.9948   0.9968
CatBoost  0.9991   0.9994
DART      0.9639   0.9703
EF        0.9999   0.9999
ET        1.0000   1.0000
GBDT      0.9991   0.9994
GP        0.9573   0.9917
KNN       0.9994   0.9991
LightGBM  0.9709   0.9782
RF        0.9996   0.9996
XGBoost   0.9985   0.9982

In [13]:
target_summary(df_doymus_results, 's sıvı (çıktı)')

Senaryo     Base  STGP-EF
Algoritma
AdaBoost  0.9991   0.9990
CatBoost  0.9991   0.9995
DART      0.9655   0.9696
EF        1.0000   0.9999
ET        1.0000   1.0000
GBDT      0.9993   0.9995
GP        0.9998   0.9998
KNN       0.9996   0.9995
LightGBM  0.9734   0.9779
RF        0.9997   0.9997
XGBoost   0.9986   0.9986

In [14]:
target_summary(df_doymus_results, 's buhar (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9108 0.8746   0.9616         0.6942
CatBoost  0.9829 0.9803   0.9905         0.9307
DART      0.4696 0.7338   0.8764         0.8710
EF        0.9995 0.9982   0.9947         0.9301
ET        0.9997 0.9987   0.9891         0.8290
GBDT      0.9808 0.9721   0.9857         0.9293
GP        0.3077 0.5129   0.9193         0.6063
KNN       0.9886 0.9369   0.9818         0.8995
LightGBM  0.4773 0.8042   0.8366         0.8822
RF        0.9939 0.9640   0.9935         0.8965
XGBoost   0.9708 0.8809   0.9715         0.9164

---
## 4. Kızgın Buhar — Eğitim

**Girdiler:** T (girdi), P (girdi)  
**Çıktılar (her biri ayrı ayrı):** v, h, s

In [15]:
kizgin_results = run_kizgin_analysis(df_kizgin)

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  KIZGIN BUHAR ANALİZİ
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

============================================================
  Hedef: v (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 74/74 [00:00<00:00, 266.23it/s]
synth_matrix: 100%|##########| 74/74 [00:00<00:00, 1247.14it/s]
r_index: 100%|##########| 54/54 [00:00<00:00, 1487.27it/s]

  [3/4] STGP-EF eğitim...
  [4/4] SMOGN + STGP-EF eğitim...
  Tamamlandı.


============================================================
  Hedef: h (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 49/49 [00:00<00:00, 346.69it/s]
synth_matrix: 100%|##########| 49/49 [00:00<00:00, 745.07it/s]
r_index: 100%|##########| 5/5 [00:00<?, ?it/s]

  [3/4] STGP-EF eğitim...
  [4/4] SMOGN + STGP-EF eğitim...
  Tamamlandı.


============================================================
  Hedef: s (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 53/53 [00:00<00:00, 332.59it/s]
synth_matrix: 100%|##########| 53/53 [00:00<00:00, 814.10it/s]
r_index: 100%|##########| 43/43 [00:00<00:00, 2045.77it/s]

  [3/4] STGP-EF eğitim...
  [4/4] SMOGN + STGP-EF eğitim...
  Tamamlandı.

### 4.1 Kızgın Buhar — Sonuç Tablosu

In [16]:
df_kizgin_results = build_results_table(kizgin_results)
df_kizgin_results

         Hedef        Senaryo Algoritma  Train_R2  Test_R2  Train_RMSE  Test_RMSE  Train_MAPE  Test_MAPE
0    v (çıktı)           Base  AdaBoost    0.9928   0.9891      0.0849     0.0984      1.0603     0.2023
1    v (çıktı)           Base  CatBoost    0.9999   0.9996      0.0073     0.0177      0.0532     0.0266
2    v (çıktı)           Base      DART    0.8654   0.8862      0.3669     0.3181      0.3296     0.1550
3    v (çıktı)           Base        EF    1.0000   0.9998      0.0001     0.0133      0.0000     0.0135
4    v (çıktı)           Base        ET    1.0000   0.9998      0.0000     0.0128      0.0000     0.0133
..         ...            ...       ...       ...      ...         ...        ...         ...        ...
127  s (çıktı)  SMOGN+STGP-EF        GP    0.9423   0.8812      0.3017     0.3239      0.5647     1.5067
128  s (çıktı)  SMOGN+STGP-EF       KNN    0.9802   0.9581      0.1768     0.1924      0.2000     0.7243
129  s (çıktı)  SMOGN+STGP-EF  LightGBM    0.9939   0.9877      0.0981     0.1042      0.0774     0.4798
130  s (çıktı)  SMOGN+STGP-EF        RF    0.9937   0.9828      0.0996     0.1233      0.0721     0.4910
131  s (çıktı)  SMOGN+STGP-EF   XGBoost    0.9953   0.9852      0.0863     0.1144      0.0124     0.5178

[132 rows x 9 columns]

### 4.2 Kızgın Buhar — Senaryo Karşılaştırması

In [17]:
compare_scenarios(df_kizgin_results)

Senaryo               Base   SMOGN  STGP-EF  SMOGN+STGP-EF
Hedef     Algoritma
h (çıktı) AdaBoost  0.9662  0.9632   0.9927         0.9922
          CatBoost  0.9980  0.9955   0.9989         0.9972
          DART      0.9604  0.9590   0.9757         0.9837
          EF        0.9995  0.9989   0.9995         0.9989
          ET        0.9994  0.9971   0.9993         0.9982
          GBDT      0.9977  0.9941   0.9989         0.9970
          GP        0.9553  0.8314   0.9864         0.9384
          KNN       0.9934  0.9867   0.9968         0.9866
          LightGBM  0.9729  0.9719   0.9872         0.9966
          RF        0.9973  0.9908   0.9988         0.9963
          XGBoost   0.9979  0.9943   0.9984         0.9970
s (çıktı) AdaBoost  0.8883  0.8588   0.9645         0.9300
          CatBoost  0.9957  0.9593   0.9955         0.9647
          DART      0.9382  0.8412   0.9789         0.9664
          EF        0.9982  0.9880   0.9941         0.9847
          ET        0.9972  0.9641   0.9945         0.9831
          GBDT      0.9922  0.9630   0.9949         0.9867
          GP        0.7252  0.7686   0.8307         0.8812
          KNN       0.9686  0.9385   0.9731         0.9581
          LightGBM  0.9529  0.8536   0.9880         0.9877
          RF        0.9843  0.9369   0.9905         0.9828
          XGBoost   0.9927  0.9504   0.9918         0.9852
v (çıktı) AdaBoost  0.9891  0.9652   0.9866         0.9654
          CatBoost  0.9996  0.9991   0.9998         0.9996
          DART      0.8862  0.9829   0.9408         0.9830
          EF        0.9998  0.9977   0.9998         0.9986
          ET        0.9998  0.9992   0.9998         0.9989
          GBDT      0.9994  0.9994   0.9994         0.9995
          GP        0.0405 -1.9946   0.8612         0.9553
          KNN       0.7909  0.7739   0.9978         0.9944
          LightGBM  0.8781  0.9951   0.9780         0.9955
          RF        0.9994  0.9986   0.9994         0.9986
          XGBoost   0.9990  0.9989   0.9990         0.9989

### 4.3 Doymuş Buhar — Hedef Bazlı Detay

Her bir hedef değişken için detaylı pivot tablo;

In [18]:
target_summary(df_kizgin_results, 'v (çıktı)')

Senaryo     Base   SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9891  0.9652   0.9866         0.9654
CatBoost  0.9996  0.9991   0.9998         0.9996
DART      0.8862  0.9829   0.9408         0.9830
EF        0.9998  0.9977   0.9998         0.9986
ET        0.9998  0.9992   0.9998         0.9989
GBDT      0.9994  0.9994   0.9994         0.9995
GP        0.0405 -1.9946   0.8612         0.9553
KNN       0.7909  0.7739   0.9978         0.9944
LightGBM  0.8781  0.9951   0.9780         0.9955
RF        0.9994  0.9986   0.9994         0.9986
XGBoost   0.9990  0.9989   0.9990         0.9989

In [19]:
target_summary(df_kizgin_results, 'h (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9662 0.9632   0.9927         0.9922
CatBoost  0.9980 0.9955   0.9989         0.9972
DART      0.9604 0.9590   0.9757         0.9837
EF        0.9995 0.9989   0.9995         0.9989
ET        0.9994 0.9971   0.9993         0.9982
GBDT      0.9977 0.9941   0.9989         0.9970
GP        0.9553 0.8314   0.9864         0.9384
KNN       0.9934 0.9867   0.9968         0.9866
LightGBM  0.9729 0.9719   0.9872         0.9966
RF        0.9973 0.9908   0.9988         0.9963
XGBoost   0.9979 0.9943   0.9984         0.9970

In [20]:
target_summary(df_kizgin_results, 's (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.8883 0.8588   0.9645         0.9300
CatBoost  0.9957 0.9593   0.9955         0.9647
DART      0.9382 0.8412   0.9789         0.9664
EF        0.9982 0.9880   0.9941         0.9847
ET        0.9972 0.9641   0.9945         0.9831
GBDT      0.9922 0.9630   0.9949         0.9867
GP        0.7252 0.7686   0.8307         0.8812
KNN       0.9686 0.9385   0.9731         0.9581
LightGBM  0.9529 0.8536   0.9880         0.9877
RF        0.9843 0.9369   0.9905         0.9828
XGBoost   0.9927 0.9504   0.9918         0.9852

# En İyi Sonuçlar

Her hedef değişken için en iyi (Algoritma, Senaryo) kombinasyonunu döndürür.

In [21]:
show_best_results(df_doymus_results)

             Hedef  Senaryo Algoritma  Test_R2  Train_R2  Test_RMSE  Test_MAPE
0         P(çıktı)     Base        ET   1.0000    1.0000     0.0035     0.0034
1  h buhar (çıktı)     Base        ET   1.0000    1.0000     0.0062     0.0065
2   h sıvı (çıktı)     Base        ET   1.0000    1.0000     0.0044     0.0067
3  s buhar (çıktı)     Base        ET   0.9997    1.0000     0.0134     0.0325
4   s sıvı (çıktı)     Base        ET   1.0000    1.0000     0.0051     0.0079
5  v buhar (çıktı)  STGP-EF        ET   0.9992    1.0000     0.0301     0.0309
6   v sıvı (çıktı)  STGP-EF        ET   1.0000    1.0000     0.0041     0.0116

---
## 5. Genel Karşılaştırma

In [22]:

df_doymus_results['Veri Seti'] = 'Doymuş Buhar'
df_kizgin_results['Veri Seti'] = 'Kızgın Buhar'
df_all = pd.concat([df_doymus_results, df_kizgin_results], ignore_index=True)

print(f'Toplam değerlendirme sayısı: {len(df_all)}')
df_all.head(20)

Toplam değerlendirme sayısı: 440

       Hedef Senaryo Algoritma  Train_R2  Test_R2  Train_RMSE  Test_RMSE  Train_MAPE  Test_MAPE     Veri Seti
0   P(çıktı)    Base  AdaBoost    0.9964   0.9959      0.0598     0.0653      0.0706     0.1070  Doymuş Buhar
1   P(çıktı)    Base  CatBoost    0.9998   0.9991      0.0123     0.0300      0.0484     0.0844  Doymuş Buhar
2   P(çıktı)    Base      DART    0.9387   0.9541      0.2475     0.2177      0.2042     0.1343  Doymuş Buhar
3   P(çıktı)    Base        EF    1.0000   1.0000      0.0000     0.0054      0.0000     0.0077  Doymuş Buhar
4   P(çıktı)    Base        ET    1.0000   1.0000      0.0000     0.0035      0.0000     0.0034  Doymuş Buhar
5   P(çıktı)    Base      GBDT    1.0000   0.9991      0.0004     0.0308      0.0011     0.0752  Doymuş Buhar
6   P(çıktı)    Base        GP    0.9743   0.9702      0.1603     0.1753      0.3648     0.3469  Doymuş Buhar
7   P(çıktı)    Base       KNN    0.9991   0.9998      0.0304     0.0158      0.0331     0.0438  Doymuş Buhar
8   P(çıktı)    Base  LightGBM    0.9461   0.9651      0.2322     0.1898      0.1671     0.1121  Doymuş Buhar
9   P(çıktı)    Base        RF    0.9999   0.9997      0.0098     0.0181      0.0186     0.0399  Doymuş Buhar
10  P(çıktı)    Base   XGBoost    1.0000   0.9982      0.0022     0.0427      0.0034     0.0818  Doymuş Buhar
11  P(çıktı)   SMOGN  AdaBoost       NaN      NaN         NaN        NaN         NaN        NaN  Doymuş Buhar
12  P(çıktı)   SMOGN  CatBoost       NaN      NaN         NaN        NaN         NaN        NaN  Doymuş Buhar
13  P(çıktı)   SMOGN      DART       NaN      NaN         NaN        NaN         NaN        NaN  Doymuş Buhar
14  P(çıktı)   SMOGN        EF       NaN      NaN         NaN        NaN         NaN        NaN  Doymuş Buhar
15  P(çıktı)   SMOGN        ET       NaN      NaN         NaN        NaN         NaN        NaN  Doymuş Buhar
16  P(çıktı)   SMOGN      GBDT       NaN      NaN         NaN        NaN         NaN        NaN  Doymuş Buhar
17  P(çıktı)   SMOGN        GP       NaN      NaN         NaN        NaN         NaN        NaN  Doymuş Buhar
18  P(çıktı)   SMOGN       KNN       NaN      NaN         NaN        NaN         NaN        NaN  Doymuş Buhar
19  P(çıktı)   SMOGN  LightGBM       NaN      NaN         NaN        NaN         NaN        NaN  Doymuş Buhar

In [23]:
# Senaryo bazlı ortalama Test R² skorları
df_all.groupby(['Veri Seti', 'Senaryo'])['Test_R2'].mean().unstack()

Senaryo        Base  SMOGN  SMOGN+STGP-EF  STGP-EF
Veri Seti
Doymuş Buhar 0.9613 0.9452         0.9412   0.9845
Kızgın Buhar 0.9349 0.8612         0.9812   0.9815

In [24]:
# Algoritma bazlı ortalama Test R² skorları
df_all.groupby(['Veri Seti', 'Algoritma'])['Test_R2'].mean().unstack()

Algoritma     AdaBoost  CatBoost   DART     EF     ET   GBDT     GP    KNN  LightGBM     RF  XGBoost
Veri Seti
Doymuş Buhar    0.9668    0.9930 0.8962 0.9958 0.9906 0.9920 0.8993 0.9881    0.9074 0.9913   0.9835
Kızgın Buhar    0.9552    0.9919 0.9497 0.9965 0.9942 0.9935 0.5650 0.9466    0.9631 0.9895   0.9919

In [25]:
# Geniş formatlı sonuç tablosu oluştur ve kaydet
df_wide = save_wide_results(df_all, 'R515B_Ozellikler/Model_Training_Results.csv')
print('Sonuçlar R515B_Ozellikler/Model_Training_Results.csv dosyasına kaydedildi.')
print(f'Format: Geniş tablo — {len(df_wide)} satır, {len(df_wide.columns)} sütun')
df_wide

Sonuçlar R515B_Ozellikler/Model_Training_Results.csv dosyasına kaydedildi.
Format: Geniş tablo — 110 satır, 29 sütun

        Veri Seti      Hedef Algoritma  Base_Train_R2  Base_Test_R2  Base_Train_RMSE  Base_Test_RMSE  Base_Train_MAPE  Base_Test_MAPE  SMOGN_Train_R2  SMOGN_Test_R2  SMOGN_Train_RMSE  SMOGN_Test_RMSE  SMOGN_Train_MAPE  SMOGN_Test_MAPE  STGP-EF_Train_R2  STGP-EF_Test_R2  STGP-EF_Train_RMSE  STGP-EF_Test_RMSE  STGP-EF_Train_MAPE  STGP-EF_Test_MAPE  SMOGN+STGP-EF_Train_R2  SMOGN+STGP-EF_Test_R2  SMOGN+STGP-EF_Train_RMSE  SMOGN+STGP-EF_Test_RMSE  SMOGN+STGP-EF_Train_MAPE  SMOGN+STGP-EF_Test_MAPE  Max_Test_R2    Max_Senaryo
0    Doymuş Buhar   P(çıktı)  AdaBoost         0.9964        0.9959           0.0598          0.0653           0.0706          0.1070             NaN            NaN               NaN              NaN               NaN              NaN            0.9963           0.9939              0.0606             0.0795              0.0913             0.0625                     NaN                    NaN                       NaN                      NaN                       NaN                      NaN       0.9959           Base
1    Doymuş Buhar   P(çıktı)  CatBoost         0.9998        0.9991           0.0123          0.0300           0.0484          0.0844             NaN            NaN               NaN              NaN               NaN              NaN            0.9998           0.9994              0.0141             0.0245              0.0367             0.0450                     NaN                    NaN                       NaN                      NaN                       NaN                      NaN       0.9994        STGP-EF
2    Doymuş Buhar   P(çıktı)      DART         0.9387        0.9541           0.2475          0.2177           0.2042          0.1343             NaN            NaN               NaN              NaN               NaN              NaN            0.9449           0.9570              0.2347             0.2107              0.1501             0.1744                     NaN                    NaN                       NaN                      NaN                       NaN                      NaN       0.9570        STGP-EF
3    Doymuş Buhar   P(çıktı)        EF         1.0000        1.0000           0.0000          0.0054           0.0000          0.0077             NaN            NaN               NaN              NaN               NaN              NaN            1.0000           1.0000              0.0000             0.0054              0.0000             0.0076                     NaN                    NaN                       NaN                      NaN                       NaN                      NaN       1.0000           Base
4    Doymuş Buhar   P(çıktı)        ET         1.0000        1.0000           0.0000          0.0035           0.0000          0.0034             NaN            NaN               NaN              NaN               NaN              NaN            1.0000           1.0000              0.0000             0.0043              0.0000             0.0066                     NaN                    NaN                       NaN                      NaN                       NaN                      NaN       1.0000           Base
..            ...        ...       ...            ...           ...              ...             ...              ...             ...             ...            ...               ...              ...               ...              ...               ...              ...                 ...                ...                 ...                ...                     ...                    ...                       ...                      ...                       ...                      ...          ...            ...
105  Kızgın Buhar  v (çıktı)        GP         0.0484        0.0405           0.9755          0.9235           2.3504          0.7659          0.2784        -1.9946            1.2526           1.6315            2.7211           2.0493            0.9002           0.8612              0.3159             0.3513              3.8145             1.0897                  0.9486                 0.9553                    0.3344                   0.1993                    0.5345                   0.4227       0.9553  SMOGN+STGP-EF
106  Kızgın Buhar  v (çıktı)       KNN         0.8919        0.7909           0.3288          0.4311           0.4794          0.2951          0.9156         0.7739            0.4285           0.4483            0.7171           0.5596            0.9992           0.9978              0.0277             0.0438              0.2006             0.0830                  0.9759                 0.9944                    0.2288                   0.0707                    0.2432                   0.1210       0.9978        STGP-EF
107  Kızgın Buhar  v (çıktı)  LightGBM         0.8826        0.8781           0.3427          0.3291           0.2461          0.1727          0.9901         0.9951            0.1469           0.0658            0.4389           0.0942            0.9902           0.9780              0.0992             0.1400              0.0988             0.0885                  0.9903                 0.9955                    0.1449                   0.0635                    0.0607                   0.0579       0.9955  SMOGN+STGP-EF
108  Kızgın Buhar  v (çıktı)        RF         0.9999        0.9994           0.0078          0.0239           0.0455          0.0315          0.9908         0.9986            0.1415           0.0353            0.1058           0.0510            0.9999           0.9994              0.0081             0.0239              0.0416             0.0320                  0.9908                 0.9986                    0.1415                   0.0358                    0.3085                   0.0467       0.9994           Base
109  Kızgın Buhar  v (çıktı)   XGBoost         1.0000        0.9990           0.0025          0.0296           0.0242          0.0347          0.9912         0.9989            0.1385           0.0316            0.0632           0.0415            1.0000           0.9990              0.0026             0.0297              0.0160             0.0381                  0.9912                 0.9989                    0.1385                   0.0318                    0.0354                   0.0344       0.9990           Base

[110 rows x 29 columns]