# R515B Soğutucu Akışkan — Model Eğitimi

Bu notebook, Doymuş ve Kızgın buhar veri setleri için **4 farklı senaryo** ile regresyon modeli eğitimi yapar:

| # | Senaryo | Açıklama |
|---|---------|----------|
| 1 | **Base** | Orijinal veri ile temel eğitim |
| 2 | **SMOGN** | SMOGN ile veri artırma sonrası eğitim |
| 3 | **STGP-EF** | SymbolicTransformer ve Evolutionary Forest Hibrit Yöntemi ile öznitelik inşası sonrası eğitim |
| 4 | **SMOGN+STGP-EF** | Önce SMOGN, sonra STGP-EF ile birleşik eğitim |

Her senaryo **11 farklı regresyon algoritması** ile değerlendirilir: RF, ET, AdaBoost, GBDT, DART, XGBoost, LightGBM, CatBoost, KNN, GP, EF.

---

## 1. Kütüphaneler ve Fonksiyonlar

In [1]:
import sys
sys.path.insert(0, 'R515B_Ozellikler')

import pandas as pd
from Functions import (
    run_saturated_analysis,
    run_superheated_analysis,
    build_results_table,
    show_best_results,
    compare_scenarios,
    target_summary,
    save_wide_results
)

print('Fonksiyonlar başarıyla yüklendi.')

c:\Users\SGUZEY\Documents\Yüksek Lisans Dersleri\Veri Mühendisliği\Data_Engineering_Project\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-05-17 20:59:42,402 - INFO - Loading faiss with AVX2 support.
2026-05-17 20:59:42,420 - INFO - Successfully loaded faiss with AVX2 support.

Fonksiyonlar başarıyla yüklendi.

## 2. Veri Yükleme

In [2]:
df_doymus = pd.read_csv('R515B_Ozellikler/R515B_Doymus_Ozellikleri.csv')
df_kizgin = pd.read_csv('R515B_Ozellikler/R515B_Kizgin_Buhar.csv')

print(f'Doymuş Buhar: {df_doymus.shape}')
print(f'Kızgın Buhar: {df_kizgin.shape}')
print(f'\nDoymuş Sütunlar: {list(df_doymus.columns)}')
print(f'Kızgın Sütunlar: {list(df_kizgin.columns)}')

Doymuş Buhar: (136, 8)
Kızgın Buhar: (578, 5)

Doymuş Sütunlar: ['T(girdi)', 'P(çıktı)', 'v sıvı (çıktı)', 'v buhar (çıktı)', 'h sıvı (çıktı)', 'h buhar (çıktı)', 's sıvı (çıktı)', 's buhar (çıktı)']
Kızgın Sütunlar: ['T (girdi)', 'P (girdi)', 'v (çıktı)', 'h (çıktı)', 's (çıktı)']

In [3]:
df_doymus.head()

   T(girdi)  P(çıktı)  v sıvı (çıktı)  v buhar (çıktı)  h sıvı (çıktı)  h buhar (çıktı)  s sıvı (çıktı)  s buhar (çıktı)
0       -30   61.2210          0.0007           0.2726          2.7282         198.2000          0.0446           0.8486
1       -29   64.2350          0.0007           0.2606          3.9422         198.8900          0.0496           0.8481
2       -28   67.3670          0.0007           0.2492          5.1587         199.5800          0.0546           0.8476
3       -27   70.6200          0.0007           0.2385          6.3775         200.2700          0.0595           0.8472
4       -26   73.9960          0.0008           0.2282          7.5988         200.9500          0.0645           0.8468

In [4]:
df_kizgin.head()

   T (girdi)  P (girdi)  v (çıktı)  h (çıktı)  s (çıktı)
0        -30         50     0.3357   198.5500     0.8639
1        -25         50     0.3433   202.4500     0.8798
2        -20         50     0.3508   206.4000     0.8956
3        -15         50     0.3582   210.4000     0.9112
4        -10         50     0.3656   214.4300     0.9267

---
## 3. Doymuş Buhar — Eğitim

**Girdi:** T(girdi)  
**Çıktılar (her biri ayrı ayrı):** P, v sıvı, v buhar, h sıvı, h buhar, s sıvı, s buhar

In [5]:
doymus_results = run_saturated_analysis(df_doymus)

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  DOYMUŞ BUHAR ANALİZİ
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

============================================================
  Target: P(çıktı)  |  Input: ['T(girdi)']
============================================================
  [1/4] Base training...
  [2/4] SMOGN training...
Özel SMOGN Algoritması başlatılıyor (Custom Build)...
Özel SMOGN Başarılı! Orijinal: 95 -> Artırılmış/Dengelenmiş: 112

2026-05-17 21:08:22,304 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [3/4] STGP-EF training...

2026-05-17 21:08:56,418 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:08:56,422 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 21:08:56,431 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:08:56,439 - INFO -   STGP_00: (x0 + ((x0 * 0.352) * x0))
2026-05-17 21:08:56,439 - INFO -   STGP_01: (x0 + ((x0 * 0.352) * x0))
2026-05-17 21:08:56,439 - INFO -   STGP_02: (x0 + ((x0 * 0.352) * x0))
2026-05-17 21:08:56,465 - INFO -   STGP_03: (x0 + ((x0 * 0.352) * x0))
2026-05-17 21:08:56,516 - INFO -   STGP_04: (x0 + ((x0 * 0.352) * x0))
2026-05-17 21:08:56,552 - INFO -   STGP_05: (x0 + ((x0 * 0.352) * x0))
2026-05-17 21:08:56,570 - INFO -   STGP_06: (x0 + ((x0 * 0.352) * x0))
2026-05-17 21:08:56,586 - INFO -   STGP_07: (x0 + ((x0 * 0.352) * x0))
2026-05-17 21:08:56,600 - INFO -   STGP_08: (x0 + ((x0 * 0.352) * x0))
2026-05-17 21:08:56,615 - INFO -   STGP_09: (x0 + ((x0 * 0.352) * x0))
2026-05-17 21:16:58,498 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:16:58,500 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 21:16:58,502 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:16:58,507 - INFO -   EF_00: (x0 + 1) | ((0 + -1) / (x0 * x0)) | (0 * ((x0 * -1) / (0 * x0))) | ((x0 + (((-1 * 1) - x0) * ((x0 - 0) + 1))) + x0) | ((x0 + (x0 * (x0 - 0))) * 0) | (0 + 1) | x0 | (0 - (0 * 0)) | (1 / 0) | (((0 * 1) + x0) * -1)
2026-05-17 21:16:58,511 - INFO -   EF_01: ((x0 - 0) + ((x0 + x0) + (x0 / x0))) | ((0 + 0) / x0) | (0 * (0 * 1)) | (((1 * x0) - (x0 / 1)) + x0) | (0 * x0) | (x0 + x0) | (-1 * 0) | (1 + (x0 - -1)) | (((x0 * x0) / 0) / (0 - ((1 - 0) / x0))) | ((1 + ((0 - x0) / (1 / x0))) * 1)
2026-05-17 21:16:58,512 - INFO -   EF_02: ((x0 - 0) + ((1 + x0) + (x0 / x0))) | (x0 / x0) | (0 * (0 * 1)) | ((x0 + ((x0 - x0) * (x0 + 1))) + x0) | ((x0 - x0) * 0) | (x0 + x0) | (0 * -1) | ((0 + x0) + (x0 - x0)) | (((x0 * x0) / 0) / (0 - ((1 - 0) / x0))) | ((1 + ((0 - x0) / (1 / 1))) * 1)
2026-05-17 21:16:58,517 - INFO -   EF_03: (x0 + (x0 - 0)) | (x0 * 0) | (x0 / x0) | (x0 + (x0 * x0)) | (x0 / 1) | (0 / (((x0 - 0) + (x0 / x0)) - 0)) | ((1 / x0) / (0 + 1)) | (0 / ((-1 * x0) * 1)) | (0 * ((-1 * 1) - ((1 / 0) * (x0 - 0)))) | (1 / (1 / (((x0 - 0) + x0) - 0)))
2026-05-17 21:16:58,527 - INFO -   EF_04: ((1 / -1) + (x0 - 0)) | (x0 * x0) | (x0 / (x0 * x0)) | (x0 + -1) | (x0 / 1) | (0 / x0) | (1 / x0) | ((x0 + x0) / (1 + ((x0 + x0) / x0))) | ((x0 / x0) * (x0 + x0)) | (-1 / x0)
2026-05-17 21:16:58,539 - INFO -   EF_05: (x0 * (0 * x0)) | (0 * 0) | ((-1 * -1) + -1) | ((1 - x0) * 1) | (0 * x0) | (x0 + (x0 + x0)) | ((1 + (x0 * -1)) - x0) | ((((x0 * (x0 + 1)) + 1) / (x0 / 0)) - x0) | (1 - x0) | ((x0 / x0) + x0)
2026-05-17 21:16:58,558 - INFO -   EF_06: (-1 + x0) | ((1 - 1) + (x0 / x0)) | ((1 + -1) * -1) | ((1 - -1) / (1 * -1)) | (-1 + -1) | ((x0 - 0) - 0) | (0 * (-1 * 1)) | (0 / (1 * x0)) | (x0 + (1 - (((x0 - x0) + (0 + x0)) / (x0 + x0)))) | (1 + (-1 + 1))
2026-05-17 21:16:58,602 - INFO -   EF_07: (1 + ((x0 - x0) + x0)) | ((x0 - 0) / (x0 + (1 - -1))) | (((x0 - 0) + (x0 / x0)) + -1) | ((1 - (x0 / 0)) - x0) | (x0 * x0) | ((1 - 1) + ((-1 * -1) * x0)) | ((0 + 1) * (((1 + 1) - (-1 - x0)) * (0 * 0))) | ((x0 * 0) + (-1 + 1)) | ((1 - 1) + (x0 - 0)) | (x0 + 0)
2026-05-17 21:16:58,621 - INFO -   EF_08: (x0 + (0 + 1)) | ((1 - 0) / 0) | ((x0 * x0) + (x0 / x0)) | ((0 - x0) - 0) | ((x0 / x0) * x0) | ((1 - x0) + (-1 / x0)) | ((x0 + 0) * (x0 * x0)) | ((x0 * x0) + x0) | (((-1 * -1) * x0) + (x0 - 0)) | (1 + 0)
2026-05-17 21:16:58,625 - INFO -   EF_09: ((-1 * x0) + (x0 - x0)) | (-1 - x0) | ((-1 - x0) * (x0 - -1)) | (x0 / x0) | ((x0 + -1) * (x0 / x0)) | ((x0 + -1) / 0) | (x0 * x0) | (0 + 1) | (x0 + x0) | ((x0 + x0) * 1)
2026-05-17 21:18:51,596 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [4/4] SMOGN + STGP-EF training...

2026-05-17 21:18:59,144 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:18:59,145 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 21:18:59,146 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:18:59,146 - INFO -   STGP_00: ((x0 + 0.939) * (x0 + (0.939 + 0.939)))
2026-05-17 21:18:59,147 - INFO -   STGP_01: ((-0.92 - x0) * (x0 + (0.939 + 0.939)))
2026-05-17 21:18:59,147 - INFO -   STGP_02: ((-0.92 - x0) * (x0 + (0.939 + 0.939)))
2026-05-17 21:18:59,148 - INFO -   STGP_03: ((-0.92 - x0) * (x0 + (0.939 + 0.939)))
2026-05-17 21:18:59,148 - INFO -   STGP_04: ((-0.92 - x0) * (x0 + (0.939 + 0.939)))
2026-05-17 21:18:59,149 - INFO -   STGP_05: ((-0.92 - x0) * (x0 + (0.939 + 0.939)))
2026-05-17 21:18:59,149 - INFO -   STGP_06: ((-0.92 - x0) * (x0 + (0.939 + 0.939)))
2026-05-17 21:18:59,150 - INFO -   STGP_07: ((-0.92 - x0) * (x0 + (0.939 + 0.939)))
2026-05-17 21:18:59,150 - INFO -   STGP_08: ((-0.92 - x0) * (x0 + (0.939 + 0.939)))
2026-05-17 21:18:59,151 - INFO -   STGP_09: ((-0.92 - x0) * (x0 + (0.939 + 0.939)))
2026-05-17 21:27:11,786 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:27:11,792 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 21:27:11,795 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:27:11,803 - INFO -   EF_00: ((1 - x0) * x0) | ((((x0 + x0) + ((x0 * 1) - 0)) / x0) - x0) | (1 - 0) | (0 + ((1 - x0) / (-1 - x0))) | (-1 * (x0 + (0 + x0))) | (0 * x0) | (0 / (x0 + x0)) | (1 / x0) | (-1 + (-1 / x0)) | (-1 + x0)
2026-05-17 21:27:11,810 - INFO -   EF_01: (x0 + -1) | (((-1 - x0) + (x0 * x0)) + 0) | (0 * 1) | (x0 / 1) | (0 + (x0 - x0)) | (x0 - -1) | ((((1 / 1) + 0) + x0) * (x0 - x0)) | (0 / 1) | (x0 + (1 - x0)) | (1 + (0 + 1))
2026-05-17 21:27:11,839 - INFO -   EF_02: (0 * (x0 - x0)) | ((((1 - -1) + (-1 - 0)) / x0) - x0) | ((x0 + x0) - (1 - -1)) | (0 + (0 / ((0 - 0) - x0))) | ((x0 / ((x0 + -1) * (0 - x0))) * (-1 + x0)) | (x0 - (-1 + x0)) | (((0 - x0) - -1) / -1) | ((0 / -1) / (1 / (x0 * (1 / (x0 + -1))))) | (((1 + x0) + ((x0 * 1) - 0)) + (x0 / x0)) | ((x0 - (x0 + x0)) + (x0 / 0))
2026-05-17 21:27:11,842 - INFO -   EF_03: (0 * x0) | ((((x0 + x0) + ((x0 * 1) - 0)) / x0) - x0) | ((x0 + 1) - 1) | (0 + (0 / (-1 - x0))) | (-1 * (1 - -1)) | (x0 * 0) | (0 / x0) | (1 / (0 - ((x0 + 0) / x0))) | ((x0 + ((x0 + x0) - (x0 * -1))) + (-1 / x0)) | (x0 / x0)
2026-05-17 21:27:11,852 - INFO -   EF_04: ((1 / x0) + (x0 / x0)) | ((x0 / x0) + (1 / x0)) | ((1 + -1) * (x0 * 1)) | ((1 - -1) / (1 * -1)) | (-1 + (1 - x0)) | ((x0 + 1) - (x0 / x0)) | (0 * (1 - x0)) | (x0 / (x0 * 0)) | (x0 + (1 - x0)) | (1 + (-1 + x0))
2026-05-17 21:27:11,858 - INFO -   EF_05: (-1 - 0) | (((((1 - x0) + -1) * (x0 - x0)) + -1) - x0) | ((0 + x0) - x0) | ((0 + 0) + (x0 - -1)) | ((x0 / x0) * 1) | (x0 + (1 - x0)) | (((x0 + x0) / (0 + x0)) - x0) | (((1 / (0 - x0)) * (-1 / x0)) + (x0 + 0)) | ((0 * 1) / ((x0 - 0) / -1)) | (x0 - x0)
2026-05-17 21:27:11,864 - INFO -   EF_06: (0 * x0) | ((((1 + x0) + (x0 - 0)) / x0) - x0) | ((x0 + 1) - 0) | (0 + -1) | ((x0 / x0) * ((-1 + 0) + x0)) | (x0 * 0) | ((1 / 1) / -1) | (1 / -1) | ((0 - x0) + (-1 / x0)) | ((x0 - x0) + (x0 / 0))
2026-05-17 21:27:11,880 - INFO -   EF_07: (0 * x0) | ((((x0 + x0) + ((x0 * 1) - 0)) / x0) - x0) | ((x0 + 1) - 0) | (x0 + ((x0 - 0) / (-1 - x0))) | (-1 * (-1 / x0)) | (x0 * x0) | (0 / x0) | (1 / (x0 + 1)) | ((0 - x0) + (-1 / x0)) | (x0 + x0)
2026-05-17 21:27:11,888 - INFO -   EF_08: ((1 - 0) / ((-1 / x0) - x0)) | ((-1 / x0) - x0) | ((x0 + 1) - 0) | (x0 + x0) | ((x0 / x0) * (x0 + x0)) | ((x0 * 0) * 0) | ((-1 / x0) / (x0 + 0)) | (1 / -1) | ((0 - x0) + (-1 / x0)) | ((1 - 1) + (x0 / 0))
2026-05-17 21:27:11,894 - INFO -   EF_09: (0 - (-1 * x0)) | ((-1 + -1) - x0) | ((-1 + 1) - x0) | ((-1 / (-1 * x0)) + (1 - x0)) | (((x0 - 0) + 1) + ((1 * -1) - 1)) | (x0 / x0) | ((0 + x0) / (1 * (1 + -1))) | (((x0 / x0) * x0) + x0) | ((x0 - 1) / (x0 / -1)) | ((((x0 + 0) + x0) / x0) - x0)

  Completed.


============================================================
  Target: v sıvı (çıktı)  |  Input: ['T(girdi)']
============================================================
  [1/4] Base training...
  [2/4] SMOGN training...
Özel SMOGN Algoritması başlatılıyor (Custom Build)...
Özel SMOGN Başarılı! Orijinal: 95 -> Artırılmış/Dengelenmiş: 112

2026-05-17 21:31:05,270 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [3/4] STGP-EF training...

2026-05-17 21:31:12,581 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:31:12,597 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 21:31:12,598 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:31:12,598 - INFO -   STGP_00: ((((x0 - -0.981) + (x0 * x0)) + 0.984) * (-0.915 - x0))
2026-05-17 21:31:12,599 - INFO -   STGP_01: ((-0.915 - x0) * (((x0 - -0.981) + (x0 * x0)) + 0.984))
2026-05-17 21:31:12,599 - INFO -   STGP_02: ((((x0 - -0.981) + (x0 * x0)) + 0.984) * (-0.915 - x0))
2026-05-17 21:31:12,600 - INFO -   STGP_03: ((((x0 - -0.981) + (x0 * x0)) + 0.984) * (-0.915 - x0))
2026-05-17 21:31:12,600 - INFO -   STGP_04: ((((x0 - -0.981) + (x0 * x0)) + 0.984) * (-0.915 - x0))
2026-05-17 21:31:12,601 - INFO -   STGP_05: ((((x0 - -0.981) + (x0 * x0)) + 0.984) * (-0.915 - x0))
2026-05-17 21:31:12,601 - INFO -   STGP_06: ((((x0 - -0.981) + (x0 * x0)) + 0.984) * (-0.915 - x0))
2026-05-17 21:31:12,601 - INFO -   STGP_07: ((-0.915 - x0) * (((x0 - -0.981) + (x0 * x0)) + 0.984))
2026-05-17 21:31:12,602 - INFO -   STGP_08: ((((x0 - -0.981) + (x0 * x0)) + 0.984) * (-0.915 - x0))
2026-05-17 21:31:12,603 - INFO -   STGP_09: ((((x0 - -0.981) + (x0 * x0)) + 0.984) * (-0.915 - x0))
2026-05-17 21:33:12,492 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:33:12,493 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 21:33:12,493 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:33:12,494 - INFO -   EF_00: (x0 + (((-1 + -1) * (x0 + x0)) / x0)) | (x0 + (x0 - x0)) | (0 * 0) | (x0 + 0) | (x0 * x0) | ((x0 / x0) + 0) | (x0 * 0) | (((1 + 1) / x0) * (x0 * 0)) | ((x0 * 1) / ((((-1 + x0) - (1 - x0)) * 1) + (x0 + 0))) | (1 / (0 - 0))
2026-05-17 21:33:12,495 - INFO -   EF_01: (-1 + (0 / -1)) | (((x0 * 0) - (0 - 0)) + 0) | (x0 * (-1 / x0)) | (x0 + 0) | (x0 * x0) | ((x0 / (x0 / 0)) + 0) | (x0 * x0) | ((x0 + -1) * ((0 * (0 * x0)) * 0)) | (-1 / 0) | ((x0 / 0) / x0)
2026-05-17 21:33:12,496 - INFO -   EF_02: (x0 / (((x0 + 0) + (1 * 0)) + (1 * x0))) | ((x0 * 1) * x0) | (1 + 0) | ((-1 - -1) * x0) | (-1 + (0 * x0)) | (-1 + 0) | ((1 - 0) * x0) | ((1 - -1) * x0) | (0 / (0 * x0)) | (x0 - (x0 + x0))
2026-05-17 21:33:12,496 - INFO -   EF_03: ((1 - (x0 * x0)) + x0) | (x0 + 0) | (1 * x0) | (x0 + 0) | ((x0 / x0) * 1) | (0 + 0) | (x0 * x0) | ((0 + -1) * (x0 * x0)) | (0 / x0) | (x0 / (0 - 0))
2026-05-17 21:33:12,496 - INFO -   EF_04: ((1 - -1) + (x0 / x0)) | (x0 + 0) | (x0 * x0) | (1 + 0) | ((x0 / x0) * -1) | (((x0 + 1) / (x0 / 0)) + 0) | (x0 * (x0 / -1)) | ((0 + -1) * (x0 * x0)) | (((x0 * -1) - (x0 - x0)) / 1) | (x0 / (x0 - 0))
2026-05-17 21:33:12,496 - INFO -   EF_05: (0 * 1) | (x0 / 0) | (-1 / x0) | (1 + x0) | (x0 / 0) | ((((0 * x0) / (-1 - -1)) / x0) + (0 * x0)) | ((x0 - 0) / x0) | (((x0 - x0) * 0) + 0) | ((x0 * 0) * (-1 - -1)) | (-1 / (-1 * x0))
2026-05-17 21:33:12,496 - INFO -   EF_06: (x0 + x0) | ((x0 / x0) * (0 - x0)) | ((1 / x0) / (0 * 0)) | (x0 + x0) | (1 + x0) | (((x0 - x0) - (-1 * x0)) / (x0 + x0)) | (1 + -1) | (x0 / -1) | ((x0 * -1) * x0) | (0 - 0)
2026-05-17 21:33:12,496 - INFO -   EF_07: (x0 + x0) | ((x0 + x0) / (x0 * -1)) | (x0 * x0) | ((x0 + -1) + (x0 + x0)) | ((1 / 0) * (-1 * 1)) | ((-1 * x0) + (1 / x0)) | (x0 * 0) | ((-1 + -1) - ((x0 + -1) * 0)) | ((x0 / 0) / (x0 - x0)) | (-1 * -1)
2026-05-17 21:33:12,496 - INFO -   EF_08: ((0 * x0) + x0) | (-1 - (x0 + -1)) | (0 * 1) | (x0 * x0) | ((x0 / x0) / x0) | (x0 - x0) | (x0 / 0) | ((x0 * x0) * (0 + -1)) | (x0 - (((x0 / x0) / (((x0 / x0) / (x0 + x0)) + 1)) - -1)) | (0 + (x0 / x0))
2026-05-17 21:33:12,496 - INFO -   EF_09: (x0 - x0) | (-1 - x0) | (x0 / x0) | (-1 - 1) | (-1 * 1) | ((0 * 0) / x0) | (x0 - x0) | ((x0 + (1 + x0)) - x0) | (0 + x0) | ((0 * -1) / (((x0 - x0) + (-1 - x0)) / 0))
2026-05-17 21:34:11,315 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [4/4] SMOGN + STGP-EF training...

2026-05-17 21:34:18,574 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:34:18,575 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 21:34:18,576 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:34:18,577 - INFO -   STGP_00: ((((x0 - -0.981) + (x0 * x0)) * (x0 - -0.981)) + x0)
2026-05-17 21:34:18,577 - INFO -   STGP_01: ((((x0 - -0.981) + (x0 * x0)) * (x0 - -0.981)) + x0)
2026-05-17 21:34:18,577 - INFO -   STGP_02: ((((x0 - -0.981) + (x0 * x0)) * (x0 - -0.981)) + x0)
2026-05-17 21:34:18,578 - INFO -   STGP_03: ((((x0 - -0.981) + (x0 * x0)) * (x0 - -0.981)) + x0)
2026-05-17 21:34:18,578 - INFO -   STGP_04: ((((x0 - -0.981) + (x0 * x0)) * (x0 - -0.981)) + x0)
2026-05-17 21:34:18,578 - INFO -   STGP_05: ((((x0 - -0.981) + (x0 * x0)) * (x0 - -0.981)) + x0)
2026-05-17 21:34:18,578 - INFO -   STGP_06: ((((x0 - -0.981) + (x0 * x0)) * (x0 - -0.981)) + x0)
2026-05-17 21:34:18,578 - INFO -   STGP_07: ((((x0 - -0.981) + (x0 * x0)) * (x0 - -0.981)) + x0)
2026-05-17 21:34:18,578 - INFO -   STGP_08: ((((x0 - -0.981) + (x0 * x0)) * (x0 - -0.981)) + x0)
2026-05-17 21:34:18,578 - INFO -   STGP_09: ((((x0 - -0.981) + (x0 * x0)) * (x0 - -0.981)) + x0)
2026-05-17 21:36:22,701 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:36:22,702 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 21:36:22,702 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:36:22,703 - INFO -   EF_00: (((0 - x0) + x0) - -1) | ((x0 - x0) / x0) | ((0 + x0) / (x0 - x0)) | (((1 * x0) + (-1 * x0)) * (x0 * x0)) | ((-1 - x0) / 0) | (x0 + ((1 / x0) / (x0 / 0))) | ((x0 - x0) + x0) | (x0 + x0) | (x0 * (1 - (-1 * -1))) | ((x0 * 0) + (1 + x0))
2026-05-17 21:36:22,704 - INFO -   EF_01: (-1 - -1) | ((x0 - x0) / 0) | (1 / (x0 - x0)) | ((x0 - x0) * (x0 * x0)) | (-1 / 0) | (x0 / -1) | ((x0 + 1) + x0) | (0 + (x0 - x0)) | (x0 * (x0 + (0 + x0))) | (((x0 - x0) / (x0 - x0)) + x0)
2026-05-17 21:36:22,705 - INFO -   EF_02: (x0 - ((x0 - x0) + (0 + x0))) | (x0 / x0) | (x0 / x0) | ((1 * x0) * (x0 * x0)) | (x0 / (x0 * (x0 - x0))) | (x0 / 0) | ((0 - x0) + 1) | (x0 + (1 - x0)) | (x0 * x0) | (x0 + ((x0 * x0) * 1))
2026-05-17 21:36:22,706 - INFO -   EF_03: (-1 - 0) | (x0 / x0) | (((1 - x0) - (1 * -1)) / x0) | ((1 * 0) * (x0 * x0)) | (x0 / (x0 - x0)) | (x0 / (x0 * 1)) | ((1 - x0) + x0) | ((1 - x0) + x0) | (-1 * x0) | ((x0 - x0) + ((x0 / (x0 / x0)) + x0))
2026-05-17 21:36:22,706 - INFO -   EF_04: ((0 * x0) / (x0 - 0)) | ((x0 / x0) - (1 / x0)) | (-1 - (x0 - 0)) | ((1 * x0) + (0 / -1)) | ((x0 * 0) - (x0 / x0)) | (x0 * x0) | ((1 * x0) + (1 - x0)) | ((x0 - -1) - (-1 * x0)) | (x0 + 0) | (-1 * x0)
2026-05-17 21:36:22,707 - INFO -   EF_05: (-1 - -1) | ((x0 - x0) / 0) | (1 / (x0 - x0)) | (((1 * (x0 + x0)) * x0) * ((x0 / -1) * (1 * 1))) | (-1 / (x0 * (x0 * x0))) | ((x0 * -1) / x0) | ((1 - x0) + x0) | (0 + (x0 * x0)) | (((x0 - x0) + (x0 + x0)) * ((-1 * -1) + (x0 + x0))) | ((x0 * 0) + 0)
2026-05-17 21:36:22,708 - INFO -   EF_06: (0 - 0) | ((x0 - x0) / x0) | (1 / (x0 - x0)) | ((x0 - x0) * (x0 * x0)) | (-1 / 0) | (x0 / x0) | ((x0 - ((1 * x0) * (x0 / 0))) + x0) | (0 + (x0 - x0)) | (x0 * 1) | ((x0 * 0) + x0)
2026-05-17 21:36:22,708 - INFO -   EF_07: (-1 - x0) | ((1 - x0) / (x0 - x0)) | (((x0 / 1) - (x0 + 0)) / x0) | ((x0 * 0) * (x0 * x0)) | (-1 / (0 - x0)) | (0 / (x0 - (x0 - x0))) | ((1 - x0) + x0) | ((x0 - x0) + (x0 - x0)) | x0 | ((x0 - x0) + -1)
2026-05-17 21:36:22,709 - INFO -   EF_08: (-1 - x0) | (x0 / (0 / 1)) | (1 / 1) | ((x0 - x0) * 1) | (1 / x0) | (0 / 0) | (1 + x0) | (x0 + (1 - 0)) | ((x0 - ((0 * 1) - (x0 + 1))) * (x0 * x0)) | (0 + x0)
2026-05-17 21:36:22,710 - INFO -   EF_09: ((1 / -1) / (-1 / 0)) | ((-1 + x0) - (0 * x0)) | (0 / (0 * 1)) | (-1 * 1) | ((x0 + 1) - 1) | (x0 / x0) | (x0 + -1) | (((-1 - x0) / -1) + x0) | x0 | (x0 - 1)

  Completed.


============================================================
  Target: v buhar (çıktı)  |  Input: ['T(girdi)']
============================================================
  [1/4] Base training...
  [2/4] SMOGN training...
Özel SMOGN Algoritması başlatılıyor (Custom Build)...
Özel SMOGN Başarılı! Orijinal: 95 -> Artırılmış/Dengelenmiş: 112

2026-05-17 21:39:19,410 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [3/4] STGP-EF training...

2026-05-17 21:39:26,541 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:39:26,543 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 21:39:26,543 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:39:26,543 - INFO -   STGP_00: (((0.915 - x0) * (-0.81 + x0)) * x0)
2026-05-17 21:39:26,543 - INFO -   STGP_01: (((-0.81 + x0) * x0) * (0.915 - x0))
2026-05-17 21:39:26,543 - INFO -   STGP_02: (((-0.81 + x0) * x0) * (0.915 - x0))
2026-05-17 21:39:26,543 - INFO -   STGP_03: (((-0.81 + x0) * x0) * (0.915 - x0))
2026-05-17 21:39:26,543 - INFO -   STGP_04: (((0.915 - x0) * (-0.81 + x0)) * x0)
2026-05-17 21:39:26,543 - INFO -   STGP_05: (((0.915 - x0) * (-0.81 + x0)) * x0)
2026-05-17 21:39:26,543 - INFO -   STGP_06: (((0.915 - x0) * (-0.81 + x0)) * x0)
2026-05-17 21:39:26,543 - INFO -   STGP_07: (((0.915 - x0) * (-0.81 + x0)) * x0)
2026-05-17 21:39:26,543 - INFO -   STGP_08: (((0.915 - x0) * (-0.81 + x0)) * x0)
2026-05-17 21:39:26,543 - INFO -   STGP_09: (((0.915 - x0) * (-0.81 + x0)) * x0)
2026-05-17 21:41:25,402 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:41:25,406 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 21:41:25,406 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:41:25,407 - INFO -   EF_00: (x0 - -1) | (0 / x0) | (x0 * ((1 / 1) / (1 / 1))) | (1 + (0 + x0)) | (1 + x0) | (x0 - 0) | (x0 + x0) | ((1 / x0) / (-1 + 0)) | (-1 / (1 - 0)) | (x0 - x0)
2026-05-17 21:41:25,408 - INFO -   EF_01: (((-1 + 0) * -1) / (-1 + x0)) | (x0 - x0) | (x0 - ((0 + x0) + x0)) | ((x0 - 1) * (x0 + x0)) | ((-1 + (0 / -1)) - -1) | (((0 - x0) + x0) * -1) | ((x0 - (0 / -1)) - (1 * x0)) | ((x0 / x0) - ((-1 / x0) / -1)) | (-1 * (x0 - x0)) | (((x0 * x0) / x0) - (((0 + 0) + (x0 + 0)) + 1))
2026-05-17 21:41:25,409 - INFO -   EF_02: ((x0 / -1) / ((0 + x0) - x0)) | (x0 + ((x0 / x0) * x0)) | (x0 * (1 / (x0 + ((x0 - (0 * x0)) + ((x0 / x0) / -1))))) | (-1 - (x0 + -1)) | (x0 * (-1 + 0)) | ((0 + -1) * (-1 / x0)) | (((0 - x0) + (0 / -1)) + 1) | (x0 + 0) | (0 * x0) | (x0 / (x0 + x0))
2026-05-17 21:41:25,409 - INFO -   EF_03: ((1 * x0) - -1) | ((-1 + x0) / 1) | (x0 * ((x0 + x0) / 1)) | (0 + (0 + x0)) | (1 + x0) | (1 - -1) | (((x0 + x0) - x0) + -1) | ((1 * (x0 * -1)) / ((x0 / -1) + x0)) | (-1 / (1 - 0)) | (0 + 1)
2026-05-17 21:41:25,410 - INFO -   EF_04: (((x0 / (-1 + x0)) / -1) / 0) | (x0 * x0) | ((-1 / x0) / x0) | (x0 * ((0 * x0) * x0)) | (x0 - 0) | (1 + ((1 / x0) / (x0 / 0))) | (x0 * (-1 - (1 * 0))) | (x0 * 0) | ((0 * x0) / (0 * x0)) | (x0 - (((x0 * 0) + (x0 + x0)) * 0))
2026-05-17 21:41:25,411 - INFO -   EF_05: (((x0 / -1) / -1) / 0) | (x0 * -1) | ((-1 / x0) / (-1 - x0)) | (x0 * (x0 * x0)) | (x0 - 0) | (1 + x0) | (x0 * (-1 - (1 * 0))) | (x0 * (-1 + (x0 * -1))) | ((0 * x0) / (0 * x0)) | (x0 - (((x0 * 0) + (x0 + x0)) * 0))
2026-05-17 21:41:25,411 - INFO -   EF_06: ((((0 + 0) + (x0 + 0)) + 1) - -1) | (0 / 1) | ((x0 * 0) * ((1 / 1) / (1 / 1))) | (0 + (0 + x0)) | ((x0 * x0) + (x0 - x0)) | (1 - x0) | (1 + -1) | ((1 * (x0 * -1)) / (-1 + 0)) | (-1 / (1 - (x0 * -1))) | (x0 - x0)
2026-05-17 21:41:25,412 - INFO -   EF_07: ((x0 * 1) / (x0 * x0)) | ((0 / x0) - x0) | (0 - x0) | ((x0 - x0) * x0) | ((((0 + (0 * 0)) + x0) - x0) - x0) | ((x0 - x0) * x0) | (x0 - ((x0 * x0) + x0)) | (((x0 - (-1 / -1)) / x0) - (-1 / -1)) | (-1 * (x0 - x0)) | (((x0 * x0) / x0) - (((-1 * 1) + x0) + 1))
2026-05-17 21:41:25,413 - INFO -   EF_08: (((0 + 0) / x0) / (-1 + x0)) | (1 - x0) | (1 - ((x0 + x0) - 0)) | (x0 * x0) | (((0 + (0 * 1)) + 1) - x0) | ((x0 + ((x0 + -1) - 1)) * (0 + 1)) | ((x0 * ((0 * x0) * 0)) - (x0 * x0)) | ((x0 / -1) - (x0 + 0)) | ((x0 / x0) * (x0 - 0)) | (1 - (x0 + 1))
2026-05-17 21:41:25,414 - INFO -   EF_09: ((1 * -1) / 0) | (x0 - x0) | (1 - ((-1 + x0) - 1)) | (1 * x0) | ((x0 + x0) - x0) | ((-1 + x0) * (0 + 1)) | ((x0 * x0) - x0) | ((x0 / x0) - (-1 / -1)) | ((1 * -1) * (x0 - x0)) | ((0 / x0) - (-1 + 1))
2026-05-17 21:42:23,607 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [4/4] SMOGN + STGP-EF training...

2026-05-17 21:42:30,823 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:42:30,823 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 21:42:30,823 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:42:30,823 - INFO -   STGP_00: (((-0.791 + x0) * (0.915 - x0)) * x0)
2026-05-17 21:42:30,828 - INFO -   STGP_01: (((0.915 - x0) * (-0.791 + x0)) * x0)
2026-05-17 21:42:30,828 - INFO -   STGP_02: (((0.915 - x0) * (-0.791 + x0)) * x0)
2026-05-17 21:42:30,828 - INFO -   STGP_03: (((0.915 - x0) * (-0.791 + x0)) * x0)
2026-05-17 21:42:30,828 - INFO -   STGP_04: (((-0.791 + x0) * (0.915 - x0)) * x0)
2026-05-17 21:42:30,828 - INFO -   STGP_05: (((0.915 - x0) * (-0.791 + x0)) * x0)
2026-05-17 21:42:30,828 - INFO -   STGP_06: (((-0.791 + x0) * x0) * (0.915 - x0))
2026-05-17 21:42:30,828 - INFO -   STGP_07: (((0.915 - x0) * (-0.791 + x0)) * x0)
2026-05-17 21:42:30,828 - INFO -   STGP_08: (((0.915 - x0) * (-0.791 + x0)) * x0)
2026-05-17 21:42:30,828 - INFO -   STGP_09: (((0.915 - x0) * (-0.791 + x0)) * x0)
2026-05-17 21:44:32,820 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:44:32,821 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 21:44:32,822 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:44:32,823 - INFO -   EF_00: ((x0 / 0) + 1) | (x0 - (x0 + 1)) | (((x0 * x0) - (x0 * (0 + x0))) * (1 + x0)) | (((x0 - x0) * (x0 * x0)) / 0) | (((x0 - 1) - x0) - (1 - x0)) | x0 | (x0 + 1) | (x0 / 1) | (x0 / 1) | ((1 + x0) - x0)
2026-05-17 21:44:32,823 - INFO -   EF_01: (x0 + 1) | (x0 - x0) | (((x0 * x0) - (((x0 - (0 + x0)) / x0) * x0)) * (0 - 0)) | (((0 - x0) * (x0 * x0)) / 0) | ((x0 - x0) - (0 - x0)) | (x0 / (1 - x0)) | (1 + -1) | ((1 - x0) / 1) | (0 / (0 - (1 * 1))) | ((1 + x0) - (x0 * 1))
2026-05-17 21:44:32,824 - INFO -   EF_02: (x0 + -1) | ((1 / x0) - 1) | ((-1 - x0) * (0 - 0)) | (x0 / 0) | ((x0 - x0) - (x0 - x0)) | ((0 + -1) / (x0 - x0)) | (x0 + x0) | (1 / x0) | (x0 / x0) | ((1 + x0) - (x0 * 1))
2026-05-17 21:44:32,825 - INFO -   EF_03: ((0 - (((x0 - x0) + -1) + 0)) + 1) | ((x0 * x0) - (((x0 - x0) * (x0 * ((1 + x0) - -1))) + 1)) | (((x0 - x0) / 1) * x0) | (-1 / x0) | (((x0 - -1) - x0) - (0 - 0)) | ((1 + x0) / x0) | (x0 + -1) | ((1 / x0) / ((-1 * -1) - ((x0 * x0) * 0))) | (((1 / -1) * (x0 - 0)) / (x0 - (0 - -1))) | ((1 + x0) - (x0 * 0))
2026-05-17 21:44:32,825 - INFO -   EF_04: (x0 + -1) | (x0 - (1 + 1)) | (0 * x0) | (-1 / 0) | (((x0 - -1) - x0) - (x0 - (0 - -1))) | (1 / 1) | ((x0 / 1) - (1 / 1)) | ((1 / x0) / 0) | (-1 / (x0 - 1)) | ((1 + (0 - ((1 - 1) - x0))) - x0)
2026-05-17 21:44:32,826 - INFO -   EF_05: (1 + 1) | (x0 - (x0 + 1)) | (((x0 * 0) - (x0 * ((1 - 0) / (1 * x0)))) * (0 - 0)) | (((x0 - (x0 - x0)) * (x0 * x0)) / x0) | ((x0 - x0) - 1) | (x0 / (1 - 0)) | ((0 * 0) + 1) | (0 / 1) | 1 | (x0 - x0)
2026-05-17 21:44:32,826 - INFO -   EF_06: (0 + -1) | (1 + x0) | (((0 + x0) - x0) * ((1 - x0) - 0)) | (x0 / 0) | (0 - (x0 - x0)) | ((x0 + -1) / (1 - 1)) | (x0 + ((1 + x0) * 0)) | (x0 / (0 - ((x0 * x0) * 0))) | ((x0 + -1) / x0) | (x0 - (x0 * 1))
2026-05-17 21:44:32,827 - INFO -   EF_07: (x0 + 1) | (1 - (1 + (1 + -1))) | (((0 / x0) * (x0 - x0)) * (0 - 0)) | (x0 / 1) | ((x0 - x0) - x0) | ((0 + 1) / (1 - (x0 - x0))) | (1 + ((x0 * x0) * x0)) | (1 / ((1 * -1) - ((x0 * x0) * 0))) | ((1 + x0) / x0) | ((1 + x0) - (x0 * 1))
2026-05-17 21:44:32,827 - INFO -   EF_08: ((x0 / 0) + 1) | (x0 - (x0 + 1)) | (((x0 * (1 - 0)) - (1 * (0 + x0))) * (1 + x0)) | (((x0 - x0) * (x0 * x0)) / 0) | (1 - (1 - x0)) | -1 | ((x0 * x0) + x0) | (x0 / 1) | (x0 / 1) | ((1 + x0) - x0)
2026-05-17 21:44:32,828 - INFO -   EF_09: ((-1 / 1) * (-1 + -1)) | (x0 - (x0 + 1)) | (((x0 * 0) - (x0 * (1 * x0))) * (0 - 0)) | (((x0 - (x0 - (0 + 1))) * (x0 * x0)) / x0) | ((x0 - x0) - 1) | (x0 / (1 - (0 - 1))) | ((0 * 0) + 1) | ((1 - (x0 - 0)) / 1) | 1 | (x0 - 1)

  Completed.


============================================================
  Target: h sıvı (çıktı)  |  Input: ['T(girdi)']
============================================================
  [1/4] Base training...
  [2/4] SMOGN training...
Özel SMOGN Algoritması başlatılıyor (Custom Build)...
Özel SMOGN Başarılı! Orijinal: 95 -> Artırılmış/Dengelenmiş: 112

2026-05-17 21:47:29,736 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [3/4] STGP-EF training...

2026-05-17 21:47:36,637 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:47:36,638 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 21:47:36,638 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:47:36,639 - INFO -   STGP_00: x0
2026-05-17 21:47:36,639 - INFO -   STGP_01: x0
2026-05-17 21:47:36,640 - INFO -   STGP_02: x0
2026-05-17 21:47:36,640 - INFO -   STGP_03: x0
2026-05-17 21:47:36,640 - INFO -   STGP_04: x0
2026-05-17 21:47:36,640 - INFO -   STGP_05: x0
2026-05-17 21:47:36,640 - INFO -   STGP_06: x0
2026-05-17 21:47:36,640 - INFO -   STGP_07: x0
2026-05-17 21:47:36,640 - INFO -   STGP_08: x0
2026-05-17 21:47:36,640 - INFO -   STGP_09: x0
2026-05-17 21:49:37,393 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:49:37,394 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 21:49:37,394 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:49:37,395 - INFO -   EF_00: ((x0 / 0) / ((1 + x0) - (1 + x0))) | ((0 * x0) / ((0 * x0) + -1)) | ((1 * 1) / 0) | (x0 / (1 / -1)) | ((1 * x0) * x0) | (x0 - -1) | ((0 / x0) / (x0 * -1)) | (-1 - 1) | ((x0 / x0) * (1 + 1)) | (0 / (0 - 0))
2026-05-17 21:49:37,396 - INFO -   EF_01: ((x0 + x0) + (((x0 * x0) - -1) * 1)) | (x0 * x0) | (-1 - (0 * x0)) | ((x0 * x0) * -1) | ((x0 - x0) - (1 * -1)) | (x0 * (x0 / -1)) | ((x0 + x0) / 0) | (x0 / 1) | ((-1 + x0) * (-1 * -1)) | ((x0 - 0) + x0)
2026-05-17 21:49:37,396 - INFO -   EF_02: ((0 / x0) / x0) | (x0 - (-1 / x0)) | (0 - x0) | ((x0 * x0) / (x0 - (-1 / -1))) | (x0 / x0) | (x0 / (x0 / 1)) | (x0 + (x0 + (-1 + x0))) | (x0 / x0) | (1 - 0) | ((x0 / 1) * 0)
2026-05-17 21:49:37,397 - INFO -   EF_03: (x0 * x0) | ((1 - 0) - (x0 - x0)) | (x0 * x0) | ((x0 + 0) - (x0 - x0)) | ((x0 / x0) - (x0 + x0)) | (x0 / 1) | ((x0 * x0) / (x0 + x0)) | (0 + x0) | ((1 / x0) / x0) | ((x0 / x0) + (x0 - x0))
2026-05-17 21:49:37,398 - INFO -   EF_04: ((0 / x0) / x0) | (x0 - (-1 / x0)) | (0 - x0) | ((x0 * x0) / (x0 - (-1 / -1))) | (x0 / x0) | (x0 / (x0 / 1)) | (x0 + (x0 + (-1 + x0))) | (-1 / x0) | (1 - 0) | (x0 * 0)
2026-05-17 21:49:37,399 - INFO -   EF_05: ((0 / 0) + x0) | ((x0 - x0) / x0) | ((x0 - -1) * (x0 + x0)) | ((1 - x0) - (x0 / (x0 / x0))) | (0 + ((-1 - -1) + (x0 * 0))) | (x0 / -1) | ((x0 * ((x0 / x0) + (x0 / x0))) + 1) | (x0 * x0) | (1 - -1) | (0 * x0)
2026-05-17 21:49:37,399 - INFO -   EF_06: (1 / x0) | (0 - x0) | (((0 + x0) / x0) - -1) | (-1 / ((0 * x0) - (-1 / -1))) | ((-1 * x0) / -1) | (1 / (x0 / 1)) | (x0 + ((x0 - 0) + x0)) | (-1 / (x0 * x0)) | ((-1 - x0) / x0) | ((x0 / x0) * x0)
2026-05-17 21:49:37,399 - INFO -   EF_07: (x0 / (x0 - (((x0 / (1 * 0)) + x0) + 0))) | ((0 / (1 + 0)) - 1) | ((1 / ((x0 * 0) * (x0 + 0))) - -1) | (-1 / (0 - -1)) | ((x0 * x0) / (x0 + 0)) | (x0 / (0 / x0)) | (x0 + -1) | (-1 / 1) | (-1 - (0 + x0)) | (x0 * x0)
2026-05-17 21:49:37,399 - INFO -   EF_08: (-1 / x0) | (x0 * x0) | ((x0 * 1) + (0 / 1)) | ((-1 / 0) + (-1 + 0)) | ((-1 * x0) * (0 - x0)) | (0 + 0) | (-1 + (1 - -1)) | ((x0 - 1) * (1 + 0)) | (x0 - 0) | (-1 / (x0 / x0))
2026-05-17 21:49:37,399 - INFO -   EF_09: ((x0 - x0) * (0 - x0)) | ((x0 / 1) + (0 / -1)) | (-1 / 1) | ((x0 * x0) / x0) | (x0 - x0) | ((-1 + -1) / (0 / x0)) | (1 / x0) | ((x0 + 0) + x0) | ((0 * x0) / ((x0 * x0) * x0)) | (1 + ((x0 / x0) + (x0 * 0)))
2026-05-17 21:50:37,266 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [4/4] SMOGN + STGP-EF training...

2026-05-17 21:50:43,994 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:50:43,995 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 21:50:43,995 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:50:43,996 - INFO -   STGP_00: (x0 * -0.204)
2026-05-17 21:50:43,996 - INFO -   STGP_01: ((((-0.012 + 0.171) + (0.972 + -0.844)) - ((x0 / x0) + (-0.473 * x0))) + (((x0 - x0) / (x0 / x0)) / ((x0 / x0) * (-0.282 - -0.701))))
2026-05-17 21:50:43,997 - INFO -   STGP_02: x0
2026-05-17 21:50:43,997 - INFO -   STGP_03: x0
2026-05-17 21:50:43,999 - INFO -   STGP_04: x0
2026-05-17 21:50:43,999 - INFO -   STGP_05: x0
2026-05-17 21:50:44,000 - INFO -   STGP_06: x0
2026-05-17 21:50:44,000 - INFO -   STGP_07: x0
2026-05-17 21:50:44,001 - INFO -   STGP_08: x0
2026-05-17 21:50:44,002 - INFO -   STGP_09: x0
2026-05-17 21:53:06,248 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:53:06,248 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 21:53:06,248 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 21:53:06,261 - INFO -   EF_00: (1 + ((1 - x0) + 1)) | (1 + ((0 * 0) / x0)) | (x0 * (x0 * 1)) | ((1 - -1) / (1 * -1)) | (x0 + (1 - -1)) | ((x0 + ((x0 / x0) / (1 / 0))) - 0) | (x0 / (1 * 0)) | (((-1 + x0) - (1 * x0)) * 0) | ((x0 * 0) / x0) | ((-1 / x0) + 0)
2026-05-17 21:53:06,263 - INFO -   EF_01: ((x0 + -1) / (x0 + x0)) | (x0 - (x0 - x0)) | (x0 + (-1 + x0)) | ((x0 - -1) - (-1 / x0)) | (-1 - x0) | (1 / x0) | ((1 - x0) - 1) | (1 + x0) | ((1 * -1) * (0 * -1)) | (0 + -1)
2026-05-17 21:53:06,265 - INFO -   EF_02: (x0 + (-1 / x0)) | (0 / (x0 + x0)) | ((x0 + -1) + -1) | (0 / (0 + 0)) | ((0 - -1) + (-1 * 1)) | (-1 * 1) | (x0 + 0) | (x0 / (0 * -1)) | ((x0 / x0) * (-1 - 0)) | (x0 - x0)
2026-05-17 21:53:06,267 - INFO -   EF_03: (x0 + ((x0 - 0) / (x0 * x0))) | ((x0 + x0) / (0 / 0)) | (x0 * ((x0 / 0) * x0)) | (-1 / x0) | ((-1 - x0) + ((x0 + -1) - x0)) | ((1 * (0 - x0)) - -1) | (x0 * x0) | (-1 / 1) | ((x0 - x0) + x0) | (((x0 - x0) / -1) + 1)
2026-05-17 21:53:06,270 - INFO -   EF_04: ((1 + x0) + (1 * x0)) | (-1 * (1 * (1 - -1))) | ((1 * x0) * -1) | (((1 - -1) - -1) / 1) | (1 + (x0 * 1)) | ((0 * 0) / 1) | ((x0 + 1) / (-1 / (x0 - x0))) | ((0 * (x0 - 0)) + 1) | (1 * -1) | (x0 - (x0 - 1))
2026-05-17 21:53:06,275 - INFO -   EF_05: ((0 * x0) / 1) | ((x0 / x0) - 0) | ((1 / 1) - 1) | ((1 * 0) + (0 / -1)) | ((x0 * 0) - (x0 / x0)) | (x0 * x0) | ((1 * x0) + (1 - 1)) | (x0 - (-1 * x0)) | (x0 + (x0 / 0)) | (x0 * 0)
2026-05-17 21:53:06,276 - INFO -   EF_06: (-1 + (x0 + 1)) | (x0 + (1 / x0)) | ((1 + -1) * (x0 * 1)) | ((1 - -1) / (1 * -1)) | (-1 + (x0 - x0)) | ((x0 + 1) - (x0 / x0)) | (x0 * x0) | (x0 / -1) | (x0 + (1 - x0)) | (x0 + (-1 + x0))
2026-05-17 21:53:06,276 - INFO -   EF_07: ((0 + x0) / (-1 / 1)) | (x0 * 1) | (x0 - x0) | ((1 + -1) - (-1 * 0)) | (x0 - x0) | ((-1 + 1) / (x0 * x0)) | (x0 * x0) | ((1 - 1) * (x0 + 0)) | ((x0 / -1) + (0 - 0)) | (0 + -1)
2026-05-17 21:53:06,281 - INFO -   EF_08: (x0 * x0) | (x0 / (1 + 1)) | ((x0 - -1) * (x0 / x0)) | (x0 - (0 / -1)) | (x0 / x0) | (-1 - x0) | (-1 * (x0 / x0)) | (0 * ((1 - 1) / (-1 * x0))) | (x0 + (x0 * 1)) | ((-1 * 0) / x0)
2026-05-17 21:53:06,281 - INFO -   EF_09: (-1 + x0) | (-1 + (1 / 1)) | (0 * (x0 * 0)) | ((-1 / (x0 - x0)) / (x0 * (1 + -1))) | (-1 + (1 - -1)) | ((0 / -1) - (x0 / -1)) | ((0 * 0) * (1 * 1)) | (1 / 1) | (x0 + (1 - x0)) | (1 + -1)

  Completed.


============================================================
  Target: h buhar (çıktı)  |  Input: ['T(girdi)']
============================================================
  [1/4] Base training...
  [2/4] SMOGN training...
Özel SMOGN Algoritması başlatılıyor (Custom Build)...
Özel SMOGN Başarılı! Orijinal: 95 -> Artırılmış/Dengelenmiş: 112

2026-05-17 21:59:54,499 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [3/4] STGP-EF training...

2026-05-17 22:00:01,853 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:00:01,853 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 22:00:01,853 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:00:01,853 - INFO -   STGP_00: (((-0.919 - x0) + (x0 / 0.831)) * x0)
2026-05-17 22:00:01,853 - INFO -   STGP_01: (((-0.919 - x0) + (x0 / 0.831)) * x0)
2026-05-17 22:00:01,853 - INFO -   STGP_02: (x0 * ((-0.919 - x0) + (x0 / 0.831)))
2026-05-17 22:00:01,853 - INFO -   STGP_03: (((-0.919 - x0) + (x0 / 0.831)) * x0)
2026-05-17 22:00:01,853 - INFO -   STGP_04: (((-0.919 - x0) + (x0 / 0.831)) * x0)
2026-05-17 22:00:01,853 - INFO -   STGP_05: (((-0.919 - x0) + (x0 / 0.831)) * x0)
2026-05-17 22:00:01,853 - INFO -   STGP_06: (((-0.919 - x0) + (x0 / 0.831)) * x0)
2026-05-17 22:00:01,853 - INFO -   STGP_07: (((-0.919 - x0) + (x0 / 0.831)) * x0)
2026-05-17 22:00:01,853 - INFO -   STGP_08: (((-0.919 - x0) + (x0 / 0.831)) * x0)
2026-05-17 22:00:01,853 - INFO -   STGP_09: (((-0.919 - x0) + (x0 / 0.831)) * x0)
2026-05-17 22:02:04,935 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:02:04,936 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 22:02:04,936 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:02:04,937 - INFO -   EF_00: (((x0 + x0) * (x0 / x0)) * x0) | (((-1 * x0) / -1) - 0) | ((x0 / (1 + x0)) / x0) | ((x0 / x0) / (1 + x0)) | (0 - x0) | ((x0 + x0) - (x0 / -1)) | (0 + 0) | (x0 - x0) | ((x0 - x0) + (0 / -1)) | (-1 / -1)
2026-05-17 22:02:04,938 - INFO -   EF_01: ((0 * 0) * ((-1 + 1) - -1)) | ((x0 - 1) - x0) | (x0 / 1) | ((x0 / x0) / (1 + (0 + x0))) | ((-1 + 1) - (x0 * x0)) | (((x0 - x0) * x0) - ((-1 * (0 + 1)) / -1)) | (x0 + 0) | ((1 * 1) - x0) | (1 + (x0 / -1)) | (-1 + x0)
2026-05-17 22:02:04,938 - INFO -   EF_02: ((0 * (x0 - -1)) * (0 / -1)) | x0 | ((x0 / 0) / (1 - 0)) | ((x0 / x0) / (1 + x0)) | ((x0 + ((x0 + -1) / (-1 / -1))) - (x0 * 0)) | (x0 - x0) | (0 + x0) | (x0 - (x0 * 0)) | (-1 + (0 / -1)) | ((x0 - 1) + 0)
2026-05-17 22:02:04,939 - INFO -   EF_03: (x0 * x0) | ((0 - 1) - ((0 + x0) + (1 + -1))) | (1 / x0) | ((x0 / x0) / (1 + x0)) | (x0 - (x0 - 1)) | ((0 * ((1 * 1) * (x0 + x0))) - ((0 / x0) / x0)) | ((1 + 1) + x0) | (x0 - (x0 * 0)) | (1 + (0 * (x0 / (x0 * 0)))) | (x0 + (0 / (1 + x0)))
2026-05-17 22:02:04,939 - INFO -   EF_04: ((0 * 0) * (1 - -1)) | ((x0 - 1) - (-1 + x0)) | (x0 / (0 + 1)) | ((x0 / x0) / (1 + (0 + x0))) | ((-1 + 1) - x0) | (((x0 - x0) * x0) - ((-1 * (0 + 1)) / -1)) | (0 + x0) | (0 - x0) | (1 + (x0 / -1)) | (x0 + x0)
2026-05-17 22:02:04,940 - INFO -   EF_05: (((x0 + 0) * (x0 / 0)) * (x0 / (1 + x0))) | ((0 + 1) * (1 * x0)) | (x0 - 0) | ((x0 / x0) / (x0 - (x0 / x0))) | (0 - (x0 * x0)) | (1 - -1) | (((x0 / x0) * (x0 / x0)) + 1) | 1 | ((x0 - (((0 - x0) + (x0 / 1)) * 0)) + 0) | ((x0 * x0) * (x0 + x0))
2026-05-17 22:02:04,940 - INFO -   EF_06: ((x0 / 0) / (x0 * x0)) | ((0 * x0) / (0 + x0)) | (0 + -1) | (-1 / x0) | (1 * -1) | (x0 - ((x0 / 1) - (1 - x0))) | ((0 / x0) / (x0 * -1)) | ((0 / -1) - x0) | x0 | ((1 - x0) / (0 - x0))
2026-05-17 22:02:04,941 - INFO -   EF_07: ((0 * x0) * (1 - -1)) | ((x0 - 1) - (0 - x0)) | (1 / x0) | ((x0 / x0) / (1 + x0)) | ((-1 + x0) - (x0 * x0)) | ((0 * x0) - (x0 / x0)) | ((x0 + 1) + x0) | (x0 - x0) | (1 + (x0 / -1)) | (0 + x0)
2026-05-17 22:02:04,941 - INFO -   EF_08: (x0 * (1 - -1)) | (1 - (0 - -1)) | (1 / x0) | ((x0 / x0) / (1 + x0)) | ((0 / -1) - (x0 * 0)) | ((0 * x0) - (x0 / x0)) | ((x0 + 1) + x0) | (x0 - x0) | (1 + (x0 / -1)) | (-1 + ((x0 + 0) / (-1 + x0)))
2026-05-17 22:02:04,942 - INFO -   EF_09: (-1 * x0) | 0 | ((x0 / (1 + x0)) / x0) | ((x0 / x0) / (1 + x0)) | (((x0 * x0) / -1) - x0) | ((x0 + x0) - x0) | ((0 + 1) + 0) | ((((1 * 1) + (x0 - x0)) * (0 / (x0 + x0))) - 1) | (0 + (0 / (x0 + x0))) | (-1 + 1)
2026-05-17 22:03:02,855 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [4/4] SMOGN + STGP-EF training...

2026-05-17 22:03:09,712 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:03:09,713 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 22:03:09,713 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:03:09,714 - INFO -   STGP_00: x0
2026-05-17 22:03:09,716 - INFO -   STGP_01: x0
2026-05-17 22:03:09,717 - INFO -   STGP_02: x0
2026-05-17 22:03:09,717 - INFO -   STGP_03: x0
2026-05-17 22:03:09,718 - INFO -   STGP_04: x0
2026-05-17 22:03:09,718 - INFO -   STGP_05: x0
2026-05-17 22:03:09,719 - INFO -   STGP_06: x0
2026-05-17 22:03:09,719 - INFO -   STGP_07: x0
2026-05-17 22:03:09,721 - INFO -   STGP_08: x0
2026-05-17 22:03:09,721 - INFO -   STGP_09: x0
2026-05-17 22:05:14,686 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:05:14,686 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 22:05:14,686 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:05:14,686 - INFO -   EF_00: (x0 + (((x0 / x0) / ((x0 / -1) * ((0 + x0) - (1 / 1)))) - x0)) | (-1 - 1) | ((-1 - -1) * 1) | (0 / ((-1 * -1) * (-1 + ((x0 / -1) * (0 - (1 / -1)))))) | ((x0 - x0) - (0 * x0)) | (1 / (1 - x0)) | ((x0 - -1) - (x0 + 0)) | (-1 / -1) | ((x0 - x0) - (1 / 0)) | (x0 - x0)
2026-05-17 22:05:14,686 - INFO -   EF_01: (x0 + (((x0 / x0) / ((x0 / (1 / -1)) * ((0 + x0) - (1 / 1)))) - x0)) | ((x0 + 0) - x0) | ((-1 - -1) * 1) | (0 / ((-1 + -1) * (-1 + ((x0 / -1) * ((0 + x0) - (1 / -1)))))) | ((0 - x0) - (x0 + x0)) | ((0 + -1) / (1 - x0)) | (0 - x0) | ((-1 * 1) / x0) | ((x0 - -1) - (1 / 0)) | (x0 - (x0 - x0))
2026-05-17 22:05:14,692 - INFO -   EF_02: (((0 + x0) - (-1 + -1)) + (((x0 / x0) / ((x0 / -1) * ((0 + x0) - (1 / x0)))) - x0)) | ((1 / 1) - x0) | ((-1 - (0 + 1)) * 1) | (0 / x0) | ((x0 - x0) - (x0 - x0)) | ((0 + -1) / (1 - x0)) | ((x0 - -1) - (x0 + 0)) | (1 / ((1 / 1) / x0)) | ((1 + x0) / x0) | ((1 + x0) - x0)
2026-05-17 22:05:14,692 - INFO -   EF_03: (1 * ((x0 / x0) - x0)) | (((x0 - 1) - (0 * -1)) - x0) | ((x0 / x0) / (1 + x0)) | (((x0 - -1) / x0) / 1) | (1 - 0) | (x0 - (x0 / -1)) | ((x0 + 1) + 1) | (x0 - 1) | (1 - ((1 / 1) / (x0 / -1))) | (((0 * 0) + x0) + x0)
2026-05-17 22:05:14,693 - INFO -   EF_04: (x0 + (((x0 / x0) / ((x0 / -1) * ((0 + x0) - (1 / -1)))) - x0)) | ((((0 / x0) - 0) / 1) - x0) | ((-1 - (1 / x0)) * 1) | -1 | ((1 - x0) - (0 - -1)) | ((0 + -1) / (x0 - 1)) | ((x0 - -1) - x0) | ((x0 - 0) * (0 + 1)) | (x0 / 0) | (0 - x0)
2026-05-17 22:05:14,694 - INFO -   EF_05: (x0 + (((x0 / x0) / ((x0 / -1) * (((-1 - -1) + x0) - ((x0 - 1) / 1)))) - x0)) | (-1 - x0) | (((x0 / x0) * (x0 * 1)) * 1) | (0 / ((-1 * -1) * (x0 + (x0 * (0 - (1 / (1 - 1))))))) | (((x0 - x0) - x0) - (0 * x0)) | (1 / (1 - x0)) | (x0 - x0) | (-1 / (x0 - 1)) | (1 - (1 / 0)) | ((x0 + -1) - x0)
2026-05-17 22:05:14,694 - INFO -   EF_06: (x0 + (((x0 / x0) / ((x0 / (1 / -1)) * ((0 + x0) - (1 / 1)))) - x0)) | ((-1 - (x0 - 0)) - x0) | ((-1 - -1) * x0) | (0 / ((-1 + -1) * (-1 + ((x0 / -1) * ((0 + x0) - (1 / -1)))))) | ((0 - x0) - ((0 / x0) + x0)) | (0 / (1 - x0)) | (0 - (((x0 / x0) / ((x0 / (0 * 0)) * ((0 + x0) - (1 / 1)))) + 0)) | (((x0 * x0) * 0) / x0) | (x0 - (1 / x0)) | (x0 - x0)
2026-05-17 22:05:14,695 - INFO -   EF_07: (x0 + (x0 - x0)) | ((1 / 1) - 1) | ((-1 - x0) * 1) | (x0 / 0) | ((x0 - x0) - (x0 - x0)) | ((0 + -1) / (1 - x0)) | (-1 + x0) | (1 / x0) | (x0 / x0) | ((1 + x0) - (x0 * 1))
2026-05-17 22:05:14,695 - INFO -   EF_08: ((0 * 0) * (1 - -1)) | ((x0 - 1) - x0) | ((-1 - x0) * (x0 - 0)) | ((x0 / x0) / x0) | (((1 + 0) + 1) - (x0 * 0)) | (((x0 / x0) / (x0 * 1)) - 1) | (-1 + x0) | (((x0 / -1) + (-1 * x0)) - 1) | (1 + (0 / -1)) | (0 + (0 + -1))
2026-05-17 22:05:14,696 - INFO -   EF_09: (x0 + (((x0 / x0) / ((x0 / -1) * ((0 + x0) - (1 / (x0 * x0))))) - x0)) | ((((-1 - -1) + x0) / -1) - -1) | (1 * 1) | ((-1 + -1) / (0 * x0)) | (((-1 * -1) - x0) - (x0 - -1)) | (((-1 - (0 + 1)) + -1) / (1 - x0)) | ((x0 - -1) - (x0 + 0)) | (x0 / 0) | (-1 / (0 * (x0 + x0))) | (0 - (0 + -1))

  Completed.


============================================================
  Target: s sıvı (çıktı)  |  Input: ['T(girdi)']
============================================================
  [1/4] Base training...
  [2/4] SMOGN training...
Özel SMOGN Algoritması başlatılıyor (Custom Build)...
Özel SMOGN Başarılı! Orijinal: 95 -> Artırılmış/Dengelenmiş: 112

2026-05-17 22:08:08,592 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [3/4] STGP-EF training...

2026-05-17 22:08:15,400 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:08:15,400 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 22:08:15,400 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:08:15,400 - INFO -   STGP_00: (x0 * -0.204)
2026-05-17 22:08:15,400 - INFO -   STGP_01: ((((-0.012 + 0.171) + (0.972 + -0.844)) - ((x0 / x0) + (-0.473 * x0))) + (((x0 - x0) / (x0 / x0)) / ((x0 / x0) * (-0.282 - -0.701))))
2026-05-17 22:08:15,400 - INFO -   STGP_02: x0
2026-05-17 22:08:15,400 - INFO -   STGP_03: x0
2026-05-17 22:08:15,400 - INFO -   STGP_04: x0
2026-05-17 22:08:15,400 - INFO -   STGP_05: x0
2026-05-17 22:08:15,400 - INFO -   STGP_06: x0
2026-05-17 22:08:15,400 - INFO -   STGP_07: x0
2026-05-17 22:08:15,400 - INFO -   STGP_08: x0
2026-05-17 22:08:15,400 - INFO -   STGP_09: x0
2026-05-17 22:10:16,593 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:10:16,593 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 22:10:16,594 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:10:16,595 - INFO -   EF_00: ((-1 - x0) - x0) | ((x0 + x0) - 0) | ((x0 - -1) - (x0 / 1)) | ((x0 * x0) + (1 - -1)) | (x0 * -1) | ((1 / x0) + x0) | ((x0 + 0) - (0 / x0)) | ((x0 + 0) + 1) | (((x0 - 1) * 1) / ((x0 / 0) + (1 + (x0 / x0)))) | ((0 / x0) - x0)
2026-05-17 22:10:16,595 - INFO -   EF_01: x0 | ((x0 + -1) * (x0 * (1 - 0))) | (1 / x0) | ((x0 - x0) + x0) | (x0 + -1) | ((0 - x0) - -1) | ((0 + (0 / (1 / x0))) - x0) | (1 * x0) | (1 * x0) | (x0 * (-1 / 0))
2026-05-17 22:10:16,596 - INFO -   EF_02: (((x0 + x0) + 0) * (x0 / x0)) | 1 | ((-1 - 0) + (x0 + x0)) | (0 / (x0 / 1)) | ((x0 + x0) + (x0 + 0)) | ((1 * x0) - x0) | ((x0 * x0) / (0 + ((-1 + x0) / (x0 * x0)))) | ((1 + -1) - 1) | (-1 - x0) | (0 * x0)
2026-05-17 22:10:16,597 - INFO -   EF_03: ((((1 - x0) - (-1 + x0)) - (x0 / 1)) - (x0 - x0)) | ((x0 - -1) * ((1 / x0) / (-1 + 0))) | (x0 / ((((1 - x0) - (-1 + x0)) - 1) - (x0 / (1 + -1)))) | (x0 + ((x0 + -1) / (1 + -1))) | (x0 + -1) | (x0 - ((x0 / x0) - x0)) | (x0 - (1 / 1)) | (-1 * (1 + 0)) | (x0 * (1 * 0)) | ((((x0 * (x0 * 0)) - -1) - (x0 - -1)) * -1)
2026-05-17 22:10:16,597 - INFO -   EF_04: (((-1 - x0) / x0) - 1) | (1 + (x0 - 1)) | (((x0 * x0) / (x0 - x0)) / (0 / x0)) | ((1 + x0) + 0) | (1 + x0) | ((x0 - 0) - (x0 - x0)) | ((x0 + -1) - x0) | ((1 - x0) * -1) | ((x0 * x0) - (x0 - -1)) | (0 / ((1 / x0) - x0))
2026-05-17 22:10:16,599 - INFO -   EF_05: ((x0 - (1 * x0)) - (1 - x0)) | (1 * 0) | (x0 / ((1 / x0) - -1)) | (((0 - x0) + x0) + (x0 / (1 + -1))) | (1 + x0) | ((0 - x0) - (x0 - x0)) | ((1 + x0) - (1 / x0)) | (-1 * x0) | (1 * ((x0 / x0) * 0)) | (((1 - -1) - (x0 - -1)) * -1)
2026-05-17 22:10:16,599 - INFO -   EF_06: ((x0 - 0) - (1 - x0)) | ((x0 + x0) * (x0 * (x0 * (0 - x0)))) | (1 / ((-1 / -1) - -1)) | (((x0 / x0) * (x0 + 0)) / (x0 / x0)) | (x0 + x0) | ((x0 - x0) - x0) | (0 - (x0 + 1)) | (x0 * 0) | x0 | ((x0 + 0) * x0)
2026-05-17 22:10:16,600 - INFO -   EF_07: ((((x0 - x0) - (-1 + x0)) - (x0 * x0)) - (1 - x0)) | (x0 * ((1 / x0) / (-1 + 0))) | (x0 / 0) | (((0 - x0) + x0) + ((x0 + -1) / (1 + -1))) | ((1 - -1) + x0) | (0 - (0 - x0)) | (x0 - (1 / 1)) | (-1 * (x0 + 0)) | (1 * (1 * 0)) | ((((x0 * (x0 * 0)) - -1) - (-1 - -1)) * -1)
2026-05-17 22:10:16,601 - INFO -   EF_08: ((x0 + (x0 - -1)) * -1) | (1 - 1) | (((x0 + x0) - -1) * x0) | (x0 / 1) | (-1 * (1 / x0)) | ((1 / x0) + x0) | ((1 * x0) + ((1 / 0) + 0)) | ((x0 + 1) / 0) | (x0 / (x0 / 0)) | (x0 - x0)
2026-05-17 22:10:16,601 - INFO -   EF_09: (x0 - (1 - x0)) | (1 * ((x0 + -1) / (x0 * x0))) | (x0 / (0 - ((1 / x0) * 0))) | (((0 - x0) + x0) + ((x0 + 1) / (1 + -1))) | ((x0 / x0) + -1) | (1 - x0) | ((1 + x0) - x0) | (-1 * x0) | (1 * ((1 / x0) * 0)) | (((1 - -1) - (x0 - -1)) * -1)
2026-05-17 22:11:14,260 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [4/4] SMOGN + STGP-EF training...

2026-05-17 22:11:21,103 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:11:21,103 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 22:11:21,103 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:11:21,103 - INFO -   STGP_00: ((((-0.012 + 0.171) + (0.972 + -0.844)) - ((x0 / x0) + (-0.473 * x0))) + (((x0 - x0) / (x0 / x0)) / ((x0 / x0) * (-0.282 - -0.701))))
2026-05-17 22:11:21,103 - INFO -   STGP_01: (x0 * -0.204)
2026-05-17 22:11:21,103 - INFO -   STGP_02: x0
2026-05-17 22:11:21,103 - INFO -   STGP_03: x0
2026-05-17 22:11:21,103 - INFO -   STGP_04: x0
2026-05-17 22:11:21,103 - INFO -   STGP_05: x0
2026-05-17 22:11:21,103 - INFO -   STGP_06: x0
2026-05-17 22:11:21,103 - INFO -   STGP_07: x0
2026-05-17 22:11:21,103 - INFO -   STGP_08: x0
2026-05-17 22:11:21,103 - INFO -   STGP_09: x0
2026-05-17 22:13:24,346 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:13:24,347 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 22:13:24,347 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:13:24,348 - INFO -   EF_00: (x0 / x0) | (x0 / -1) | ((x0 / x0) + (x0 / x0)) | (-1 * x0) | (x0 - x0) | ((x0 * 1) + (x0 - -1)) | (0 + x0) | ((0 + -1) - 1) | ((-1 * (0 - x0)) / x0) | (0 + x0)
2026-05-17 22:13:24,349 - INFO -   EF_01: ((0 + 1) * (x0 * 1)) | ((x0 - -1) + 0) | (x0 / 0) | ((-1 + x0) - (-1 + -1)) | (x0 / x0) | (x0 * ((x0 * 0) / (1 / x0))) | ((-1 / -1) / 0) | (x0 + x0) | ((x0 - x0) / (0 / -1)) | (x0 + 0)
2026-05-17 22:13:24,350 - INFO -   EF_02: ((x0 * (((0 * x0) / (x0 - -1)) * x0)) + -1) | ((x0 / x0) - (x0 + x0)) | (((x0 - -1) - (0 - (1 - -1))) * x0) | (x0 / ((x0 * x0) + 1)) | ((((1 - x0) - (x0 * -1)) + -1) - (x0 / 1)) | (((0 - (x0 * -1)) + -1) / ((x0 - 1) / (0 + x0))) | ((-1 - x0) + ((x0 - x0) * (x0 - -1))) | (x0 / x0) | (x0 / x0) | (((x0 * x0) + 1) - (x0 * 1))
2026-05-17 22:13:24,350 - INFO -   EF_03: (-1 - (1 * 1)) | ((x0 + -1) - (x0 + 0)) | (1 - (x0 / x0)) | (-1 + (1 - -1)) | ((-1 * 1) * 0) | (1 + (1 - x0)) | (x0 - (x0 / x0)) | ((-1 / 1) - (x0 * x0)) | ((x0 * 1) - (x0 + 0)) | ((x0 + x0) - 1)
2026-05-17 22:13:24,351 - INFO -   EF_04: (((x0 / 1) * ((x0 / x0) * -1)) + -1) | (0 - (1 + 1)) | (x0 * (1 * x0)) | (x0 - x0) | ((x0 + 0) - x0) | ((((1 - x0) - (x0 * -1)) + -1) / (1 - x0)) | (0 + ((x0 - x0) * ((x0 * 1) - -1))) | (x0 / x0) | (x0 / x0) | (((x0 * x0) + 1) - (x0 * 1))
2026-05-17 22:13:24,351 - INFO -   EF_05: ((0 * x0) / (x0 - 0)) | ((x0 / x0) - (1 / x0)) | ((1 / 1) - (x0 - 0)) | ((1 * 0) + (0 / -1)) | ((x0 * 0) - (x0 / x0)) | (x0 * x0) | ((1 * x0) + 0) | (x0 - (-1 * x0)) | (x0 + 0) | (-1 * 1)
2026-05-17 22:13:24,351 - INFO -   EF_06: (-1 - -1) | ((x0 + -1) - (x0 + 0)) | ((0 + x0) - (x0 / 1)) | ((x0 * x0) + x0) | (1 * x0) | ((-1 / 0) + (1 - x0)) | ((x0 + 0) - (0 / x0)) | ((x0 * x0) + (x0 + 0)) | ((0 * 1) / (1 - x0)) | (x0 - (x0 / 1))
2026-05-17 22:13:24,353 - INFO -   EF_07: ((0 - x0) + 0) | ((((-1 - x0) + (-1 / 0)) * x0) / 0) | ((-1 * ((x0 + x0) - 1)) * x0) | ((0 * x0) / x0) | (((x0 - -1) / (1 + 0)) * (x0 + -1)) | ((x0 * 1) * (0 - x0)) | ((x0 + x0) - 1) | ((0 * x0) * (1 / 1)) | (0 / 1) | (0 / 0)
2026-05-17 22:13:24,354 - INFO -   EF_08: ((x0 + x0) + -1) | (((x0 + ((1 / x0) + (x0 * -1))) / 1) - x0) | (-1 * (0 - 0)) | (((x0 + -1) - x0) / ((x0 - -1) * (0 - -1))) | (x0 - x0) | ((x0 / 1) / -1) | ((x0 - x0) + ((0 - x0) * (x0 / 1))) | ((0 * x0) - (-1 + x0)) | (x0 / (x0 + (1 + x0))) | (1 - (x0 * x0))
2026-05-17 22:13:24,355 - INFO -   EF_09: (-1 - ((x0 - 0) + 1)) | ((x0 + -1) - x0) | (((0 * 1) + x0) - (x0 / 1)) | ((-1 + x0) + x0) | (1 * 0) | ((-1 / 0) + (1 - x0)) | (1 - (1 - x0)) | ((x0 * x0) + (x0 + 0)) | ((0 * 1) / (1 / x0)) | (x0 - (x0 / 1))

  Completed.


============================================================
  Target: s buhar (çıktı)  |  Input: ['T(girdi)']
============================================================
  [1/4] Base training...
  [2/4] SMOGN training...
Özel SMOGN Algoritması başlatılıyor (Custom Build)...
Özel SMOGN Başarılı! Orijinal: 95 -> Artırılmış/Dengelenmiş: 112

2026-05-17 22:16:23,724 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [3/4] STGP-EF training...

2026-05-17 22:16:32,044 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:16:32,045 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 22:16:32,045 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:16:32,046 - INFO -   STGP_00: (((((x0 * x0) + (0.888 + x0)) + (0.888 + x0)) + (0.888 + (((x0 * x0) + (0.888 + (0.888 + x0))) + 0.888))) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:16:32,046 - INFO -   STGP_01: ((((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) + (0.888 + (0.888 + x0))) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:16:32,047 - INFO -   STGP_02: ((((x0 * x0) + (0.888 + x0)) + (0.888 + 0.888)) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:16:32,048 - INFO -   STGP_03: ((((x0 * x0) + (0.888 + (0.888 + x0))) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:16:32,048 - INFO -   STGP_04: ((((x0 * x0) + (0.888 + (0.888 + x0))) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:16:32,048 - INFO -   STGP_05: ((((x0 * x0) + (0.888 + (0.888 + x0))) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:16:32,048 - INFO -   STGP_06: ((((x0 * x0) + (0.888 + (0.888 + x0))) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:16:32,048 - INFO -   STGP_07: ((((x0 * x0) + (0.888 + (0.888 + x0))) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:16:32,048 - INFO -   STGP_08: ((((x0 * x0) + (0.888 + (0.888 + x0))) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:16:32,048 - INFO -   STGP_09: ((((x0 * x0) + (0.888 + (0.888 + x0))) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:18:34,482 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:18:34,482 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 22:18:34,483 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:18:34,484 - INFO -   EF_00: (x0 / (-1 - ((x0 * x0) * x0))) | (-1 / (-1 - (0 + x0))) | (0 / ((x0 / -1) + (x0 / x0))) | ((-1 - x0) / (x0 * x0)) | (0 + x0) | -1 | (x0 - x0) | (x0 / (x0 - x0)) | ((-1 + (x0 * -1)) / (x0 * (x0 * x0))) | (x0 - 0)
2026-05-17 22:18:34,485 - INFO -   EF_01: ((1 * -1) / x0) | (x0 / x0) | (x0 / x0) | (x0 / x0) | (x0 + x0) | ((x0 - -1) + 1) | (x0 - -1) | (((x0 - x0) - (x0 - x0)) / -1) | ((x0 * ((1 * x0) - (x0 / x0))) - (x0 / x0)) | ((x0 / x0) - 1)
2026-05-17 22:18:34,486 - INFO -   EF_02: (-1 / x0) | (x0 / 1) | (1 / x0) | ((-1 - (0 + x0)) / ((x0 * x0) * x0)) | ((x0 - -1) + 0) | ((x0 - -1) + (x0 * x0)) | (-1 - (-1 / 0)) | (x0 / 1) | (((-1 - 1) - x0) / 1) | (x0 - 1)
2026-05-17 22:18:34,488 - INFO -   EF_03: ((1 + x0) / x0) | (x0 - (-1 - x0)) | (1 / x0) | ((-1 - x0) / ((x0 * x0) * x0)) | (((x0 / x0) * (x0 / 0)) + x0) | (1 + 1) | (x0 - x0) | (0 / (-1 - ((-1 - x0) + x0))) | (x0 / x0) | ((-1 - x0) - 1)
2026-05-17 22:18:34,488 - INFO -   EF_04: ((0 / 0) - (x0 / x0)) | (x0 * 0) | (-1 - x0) | ((0 * 1) - (-1 + x0)) | (1 * x0) | (-1 * (-1 + 1)) | (0 * 1) | (0 / x0) | ((x0 / x0) / x0) | ((0 * 0) * (-1 / x0))
2026-05-17 22:18:34,489 - INFO -   EF_05: ((-1 + x0) / x0) | (x0 - 0) | (1 / x0) | ((-1 - x0) / x0) | (1 + 0) | ((x0 - -1) + 1) | (x0 - x0) | (0 / x0) | ((x0 - x0) / (x0 / x0)) | (x0 - 1)
2026-05-17 22:18:34,490 - INFO -   EF_06: (x0 / (-1 - 1)) | (-1 / -1) | ((-1 - (0 + x0)) / x0) | ((-1 - x0) / (x0 * x0)) | (-1 + x0) | -1 | (x0 - x0) | (1 / (x0 - -1)) | ((-1 + (x0 * -1)) / (x0 * (x0 * x0))) | (x0 - 1)
2026-05-17 22:18:34,490 - INFO -   EF_07: ((-1 + x0) / ((-1 - (0 + 0)) - ((x0 * x0) + x0))) | (-1 - 0) | ((0 / (-1 - x0)) + 0) | ((-1 - x0) / ((x0 * x0) * x0)) | (1 + (x0 - x0)) | (1 + x0) | (x0 - ((-1 + (-1 - x0)) / x0)) | ((-1 - x0) / x0) | ((1 - 1) / (-1 / x0)) | (0 - x0)
2026-05-17 22:18:34,491 - INFO -   EF_08: (x0 / (-1 - 1)) | (-1 / (-1 - (0 + x0))) | (0 / 1) | ((-1 - x0) / (x0 * (x0 * x0))) | ((x0 - (x0 * -1)) + (-1 * -1)) | (x0 + 1) | (x0 - (0 - 0)) | (1 / (x0 - -1)) | ((-1 + (x0 * -1)) / (x0 * (x0 * x0))) | (0 - 1)
2026-05-17 22:18:34,491 - INFO -   EF_09: ((x0 - -1) / (-1 - 1)) | (-1 / x0) | (0 / ((0 + x0) / x0)) | ((-1 - x0) / (1 * (x0 - x0))) | (x0 + x0) | ((1 * -1) + (0 - x0)) | ((x0 * x0) / (x0 * 1)) | (1 / (x0 - -1)) | ((-1 + (x0 * -1)) / (x0 * (x0 * x0))) | (x0 - 1)
2026-05-17 22:19:33,119 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [4/4] SMOGN + STGP-EF training...

2026-05-17 22:19:41,370 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:19:41,371 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 22:19:41,371 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:19:41,371 - INFO -   STGP_00: (((((x0 * -0.133) / (-0.233 / x0)) + (0.888 + x0)) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:19:41,372 - INFO -   STGP_01: (((((x0 * -0.133) / (-0.233 / x0)) + (0.888 + x0)) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:19:41,373 - INFO -   STGP_02: ((((x0 * x0) + (0.888 + (0.888 + x0))) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:19:41,374 - INFO -   STGP_03: (((((x0 * x0) + (0.888 + x0)) + 0.888) + (0.209 - -0.839)) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:19:41,375 - INFO -   STGP_04: ((((((x0 * x0) + (0.888 + x0)) + 0.888) + (0.888 + x0)) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:19:41,375 - INFO -   STGP_05: (((((((x0 * x0) + (0.888 + x0)) + 0.888) + (0.888 + x0)) + 0.888) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:19:41,376 - INFO -   STGP_06: (((((x0 * x0) + (0.888 + x0)) + (0.888 + x0)) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:19:41,376 - INFO -   STGP_07: ((((x0 * x0) + ((0.209 - -0.839) + x0)) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:19:41,377 - INFO -   STGP_08: ((((x0 * x0) + ((((x0 * x0) + ((0.209 - -0.839) + x0)) + 0.888) + (0.888 + x0))) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:19:41,377 - INFO -   STGP_09: ((((x0 * x0) + (0.888 + x0)) + 0.888) * ((((x0 * -0.133) / (-0.233 / x0)) - (0.209 - -0.839)) * (0.888 + x0)))
2026-05-17 22:21:45,744 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:21:45,745 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 22:21:45,745 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:21:45,746 - INFO -   EF_00: (0 / (x0 * x0)) | (0 / x0) | (((1 - x0) * (x0 * x0)) * (1 / -1)) | ((x0 + x0) - x0) | (1 + ((x0 * x0) + x0)) | ((1 * x0) - -1) | (x0 + (1 - x0)) | (0 / x0) | ((x0 / x0) / (1 - x0)) | (x0 - ((x0 * -1) + x0))
2026-05-17 22:21:45,746 - INFO -   EF_01: (x0 + -1) | (x0 - 0) | ((x0 - x0) - (x0 - x0)) | (x0 / -1) | (1 / (0 - x0)) | (0 - x0) | ((x0 * x0) * (1 - x0)) | (x0 / x0) | ((x0 / x0) * (-1 / x0)) | ((0 + x0) * (x0 * (1 * (x0 / -1))))
2026-05-17 22:21:45,747 - INFO -   EF_02: ((-1 + (x0 * x0)) - x0) | (x0 / (0 / 0)) | (x0 * -1) | (0 - (1 - 1)) | (1 + ((x0 / -1) * x0)) | ((1 - x0) - 1) | (x0 + ((1 - (1 - x0)) * ((x0 - -1) / (-1 / x0)))) | ((0 / x0) / 0) | ((1 - x0) / (1 - ((1 * x0) * x0))) | (x0 - ((((x0 * x0) - (x0 * x0)) - 1) - (0 + 1)))
2026-05-17 22:21:45,748 - INFO -   EF_03: ((-1 + (x0 * x0)) - ((1 - x0) - 1)) | ((x0 / x0) / (0 / 0)) | (1 * 1) | (0 - 0) | (1 + 0) | (1 - 1) | (x0 + ((1 - (1 - x0)) * ((x0 - -1) / 0))) | (x0 / (x0 + x0)) | ((1 - x0) / (1 - (x0 * x0))) | (((x0 - x0) - (x0 - -1)) - ((((x0 * x0) - (x0 * x0)) - 1) - (x0 + 1)))
2026-05-17 22:21:45,748 - INFO -   EF_04: (x0 + x0) | (x0 - x0) | (-1 - 1) | (x0 / -1) | ((0 + x0) / 0) | (x0 - (x0 - x0)) | ((x0 * x0) * (1 - x0)) | ((x0 * 1) / (x0 * x0)) | ((1 / x0) * (-1 / x0)) | (x0 * (-1 * -1))
2026-05-17 22:21:45,749 - INFO -   EF_05: (x0 - 0) | ((x0 / x0) / (0 / 0)) | (x0 * 1) | (x0 - 0) | (x0 + 0) | (1 - -1) | (x0 + ((1 - (1 - x0)) * 0)) | ((0 - (x0 + 1)) / (x0 + (0 * (1 / -1)))) | ((1 - x0) / (1 - (x0 * x0))) | (((x0 - x0) - ((1 - (1 - x0)) - -1)) - ((((x0 * x0) - (x0 * x0)) - 1) - (x0 + 1)))
2026-05-17 22:21:45,749 - INFO -   EF_06: (0 - (x0 - x0)) | (x0 / (0 / x0)) | (1 * (1 / -1)) | (x0 - x0) | (1 + x0) | (1 - -1) | (x0 + (1 - (1 - x0))) | ((0 / x0) / (x0 + (x0 * x0))) | ((x0 / x0) / (1 - x0)) | ((x0 * x0) - x0)
2026-05-17 22:21:45,751 - INFO -   EF_07: ((x0 / 0) + x0) | ((0 * x0) - (0 * x0)) | ((x0 - (0 * (1 - (1 * x0)))) - (x0 - x0)) | (1 / -1) | ((x0 - 0) + (1 - 0)) | (x0 - 1) | ((x0 * x0) * (1 - ((1 * x0) / (x0 + -1)))) | ((-1 * (x0 * x0)) / (0 + x0)) | x0 | ((x0 - x0) * x0)
2026-05-17 22:21:45,751 - INFO -   EF_08: (x0 + (1 - 1)) | ((1 * (x0 + x0)) - x0) | (0 - x0) | (0 / (1 - x0)) | (((x0 * -1) + x0) / 1) | (0 - (x0 / x0)) | ((x0 * x0) * (1 - x0)) | ((x0 * 1) / (x0 * x0)) | ((x0 / x0) * (x0 * 1)) | ((0 + (0 * x0)) * x0)
2026-05-17 22:21:45,752 - INFO -   EF_09: ((-1 + (x0 * (x0 / (1 - x0)))) - ((1 - x0) - 1)) | (x0 / ((1 - x0) / 0)) | (1 * 1) | (0 - 0) | (1 + 0) | (1 - 1) | (x0 + ((1 - (1 - x0)) * ((x0 - -1) / (-1 / x0)))) | ((((0 / 0) - x0) / x0) / (x0 + x0)) | ((x0 - x0) / 1) | (((x0 - x0) - (x0 - -1)) - ((((x0 * x0) - (x0 * x0)) - 0) - (x0 + 1)))

  Completed.

### 3.1 Doymuş Buhar — Sonuç Tablosu

In [6]:
df_doymus_results = build_results_table(doymus_results)
df_doymus_results

              Target       Scenario Algorithm  Train_R2  Test_R2  Train_RMSE  Test_RMSE  Train_MAPE  Test_MAPE
0           P(çıktı)           Base  AdaBoost    0.9964   0.9959      0.0598     0.0653      0.0706     0.1070
1           P(çıktı)           Base  CatBoost    0.9998   0.9991      0.0123     0.0300      0.0484     0.0844
2           P(çıktı)           Base      DART    0.9387   0.9541      0.2475     0.2177      0.2042     0.1343
3           P(çıktı)           Base        EF    1.0000   1.0000      0.0000     0.0054      0.0000     0.0077
4           P(çıktı)           Base        ET    1.0000   1.0000      0.0000     0.0035      0.0000     0.0034
..               ...            ...       ...       ...      ...         ...        ...         ...        ...
303  s buhar (çıktı)  SMOGN+STGP-EF        GP    0.9727   0.9350      0.2045     0.1943      0.5887     0.4809
304  s buhar (çıktı)  SMOGN+STGP-EF       KNN    0.9954   0.9935      0.0836     0.0613      0.1426     0.1212
305  s buhar (çıktı)  SMOGN+STGP-EF  LightGBM    0.8438   0.8265      0.4892     0.3175      0.2619     0.2665
306  s buhar (çıktı)  SMOGN+STGP-EF        RF    0.9992   0.9974      0.0352     0.0388      0.0369     0.0850
307  s buhar (çıktı)  SMOGN+STGP-EF   XGBoost    1.0000   0.9909      0.0017     0.0726      0.0038     0.1460

[308 rows x 9 columns]

### 3.2 Doymuş Buhar — Senaryo Karşılaştırması

In [7]:
compare_scenarios(df_doymus_results)

Scenario                   Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Target         Algorithm
P(çıktı)       AdaBoost  0.9959 0.9978   0.9980         0.9939
               CatBoost  0.9991 0.9993   0.9996         0.9995
               DART      0.9541 0.9883   0.9569         0.9895
               EF        1.0000 0.9999   1.0000         1.0000
               ET        1.0000 1.0000   1.0000         1.0000
...                         ...    ...      ...            ...
v sıvı (çıktı) GP        0.9595 0.9525   0.8472         0.8915
               KNN       0.9992 0.9992   0.9987         0.9994
               LightGBM  0.9346 0.9914   0.9699         0.9925
               RF        0.9994 0.9990   0.9996         0.9990
               XGBoost   0.9966 0.9973   0.9966         0.9971

[77 rows x 4 columns]

### 3.3 Doymuş Buhar — Hedef Bazlı Detay

Her bir hedef değişken için detaylı pivot tablo;

In [8]:
target_summary(df_doymus_results, 'P(çıktı)')

Scenario    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algorithm
AdaBoost  0.9959 0.9978   0.9980         0.9939
CatBoost  0.9991 0.9993   0.9996         0.9995
DART      0.9541 0.9883   0.9569         0.9895
EF        1.0000 0.9999   1.0000         1.0000
ET        1.0000 1.0000   1.0000         1.0000
GBDT      0.9991 0.9992   0.9993         0.9993
GP        0.9702 0.9702   0.9952         0.8904
KNN       0.9998 0.9994   0.9996         0.9995
LightGBM  0.9651 0.9962   0.9669         0.9982
RF        0.9997 0.9995   0.9997         0.9996
XGBoost   0.9982 0.9981   0.9981         0.9980

In [9]:
target_summary(df_doymus_results, 'v sıvı (çıktı)')

Scenario    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algorithm
AdaBoost  0.9943 0.9957   0.9968         0.9931
CatBoost  0.9981 0.9980   0.9990         0.9985
DART      0.9252 0.9845   0.9386         0.9853
EF        1.0000 0.9996   1.0000         0.9998
ET        1.0000 0.9997   1.0000         0.9997
GBDT      0.9980 0.9976   0.9987         0.9978
GP        0.9595 0.9525   0.8472         0.8915
KNN       0.9992 0.9992   0.9987         0.9994
LightGBM  0.9346 0.9914   0.9699         0.9925
RF        0.9994 0.9990   0.9996         0.9990
XGBoost   0.9966 0.9973   0.9966         0.9971

In [10]:
target_summary(df_doymus_results, 'v buhar (çıktı)')

Scenario    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algorithm
AdaBoost  0.9875 0.9878   0.9921         0.9918
CatBoost  0.9966 0.9977   0.9977         0.9979
DART      0.7834 0.9386   0.8122         0.9425
EF        0.9987 0.9991   0.9991         0.9985
ET        0.9991 0.9991   0.9992         0.9991
GBDT      0.9959 0.9966   0.9978         0.9979
GP        0.9758 0.9758   0.8517         0.9094
KNN       0.9915 0.9932   0.9912         0.9943
LightGBM  0.7845 0.9470   0.8152         0.9485
RF        0.9965 0.9970   0.9970         0.9974
XGBoost   0.9929 0.9929   0.9928         0.9929

In [11]:
target_summary(df_doymus_results, 'h sıvı (çıktı)')

Scenario    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algorithm
AdaBoost  0.9989 0.9980   0.9988         0.9987
CatBoost  0.9993 0.9994   0.9993         0.9993
DART      0.9667 0.9889   0.9702         0.9903
EF        0.9999 1.0000   1.0000         1.0000
ET        1.0000 1.0000   1.0000         1.0000
GBDT      0.9993 0.9993   0.9994         0.9994
GP        0.9955 0.9955   0.9955         0.9955
KNN       0.9997 0.9993   0.9996         0.9994
LightGBM  0.9753 0.9960   0.9787         0.9979
RF        0.9997 0.9996   0.9998         0.9996
XGBoost   0.9986 0.9984   0.9986         0.9981

In [12]:
target_summary(df_doymus_results, 'h buhar (çıktı)')

Scenario    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algorithm
AdaBoost  0.9948 0.9937   0.9983         0.9953
CatBoost  0.9991 0.9993   0.9994         0.9994
DART      0.9639 0.9881   0.9702         0.9891
EF        0.9999 0.9999   0.9998         0.9999
ET        1.0000 0.9999   0.9999         1.0000
GBDT      0.9991 0.9989   0.9994         0.9993
GP        0.9573 0.9573   0.9573         0.9573
KNN       0.9994 0.9991   0.9992         0.9991
LightGBM  0.9709 0.9945   0.9871         0.9978
RF        0.9996 0.9994   0.9996         0.9994
XGBoost   0.9985 0.9977   0.9984         0.9965

In [13]:
target_summary(df_doymus_results, 's sıvı (çıktı)')

Scenario    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algorithm
AdaBoost  0.9991 0.9983   0.9993         0.9968
CatBoost  0.9991 0.9994   0.9993         0.9994
DART      0.9655 0.9887   0.9696         0.9897
EF        1.0000 1.0000   1.0000         0.9999
ET        1.0000 1.0000   1.0000         1.0000
GBDT      0.9993 0.9992   0.9995         0.9993
GP        0.9998 0.9998   0.9998         0.9998
KNN       0.9996 0.9992   0.9995         0.9993
LightGBM  0.9734 0.9955   0.9779         0.9969
RF        0.9997 0.9995   0.9998         0.9996
XGBoost   0.9986 0.9983   0.9986         0.9983

In [14]:
target_summary(df_doymus_results, 's buhar (çıktı)')

Scenario    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algorithm
AdaBoost  0.9108 0.8847   0.9686         0.9755
CatBoost  0.9829 0.9854   0.9871         0.9956
DART      0.4696 0.3690   0.9230         0.8605
EF        0.9995 0.9981   0.9996         0.9985
ET        0.9997 0.9979   0.9990         0.9990
GBDT      0.9808 0.9800   0.9901         0.9935
GP        0.3077 0.8857   0.9676         0.9350
KNN       0.9886 0.9934   0.9822         0.9935
LightGBM  0.4773 0.2950   0.9660         0.8265
RF        0.9939 0.9930   0.9955         0.9974
XGBoost   0.9708 0.9785   0.9724         0.9909

---
## 4. Kızgın Buhar — Eğitim

**Girdiler:** T (girdi), P (girdi)  
**Çıktılar (her biri ayrı ayrı):** v, h, s

In [15]:
kizgin_results = run_superheated_analysis(df_kizgin)

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  KIZGIN BUHAR ANALİZİ
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

============================================================
  Target: v (çıktı)  |  Input: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base training...
  [2/4] SMOGN training...
Özel SMOGN Algoritması başlatılıyor (Custom Build)...
Özel SMOGN Başarılı! Orijinal: 404 -> Artırılmış/Dengelenmiş: 470

2026-05-17 22:25:05,378 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [3/4] STGP-EF training...

2026-05-17 22:25:13,127 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:25:13,128 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 22:25:13,128 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:25:13,129 - INFO -   STGP_00: ((x1 - (x1 * (x1 * 0.398))) * ((x1 * ((x1 - -0.624) - (x1 * (x1 * 0.398)))) * ((((x1 - (x1 * (x1 * 0.398))) * ((x1 * ((x1 - -0.624) - (x1 * (x1 * 0.398)))) * (((x1 * x1) - (x1 + x1)) * x1))) - (x1 + x1)) * x1)))
2026-05-17 22:25:13,129 - INFO -   STGP_01: ((x1 - (x1 * (x1 * 0.398))) * ((x1 * ((x1 - -0.624) - (x1 * (x1 * 0.398)))) * (((x1 * (x1 - (x1 * (x1 * 0.398)))) * (-0.251 + ((x1 * x1) - (x1 + x1)))) * x1)))
2026-05-17 22:25:13,130 - INFO -   STGP_02: (((x1 * x1) - (x1 + x1)) * ((x1 * ((x1 - -0.624) - (x1 * (x1 * 0.398)))) * ((x1 * ((x1 - -0.624) - (x1 * (x1 * 0.398)))) * (((x1 * x1) - (x1 + x1)) * x1))))
2026-05-17 22:25:13,131 - INFO -   STGP_03: ((x1 - (x1 * (x1 * 0.398))) * ((x1 * ((x1 - -0.624) - ((x1 - (x1 * (x1 * 0.398))) * ((x1 * ((x1 - -0.624) - (x1 * (x1 * 0.398)))) * (((x1 * x1) - (x1 + x1)) * x1))))) * (((x1 * x1) - (x1 + x1)) * x1)))
2026-05-17 22:25:13,131 - INFO -   STGP_04: ((x1 * x1) * ((x1 - ((x1 - (x1 * (x1 * 0.398))) * ((x1 * ((x1 - -0.624) - (x1 * (x1 * 0.398)))) * (((x1 * x1) - (x1 + x1)) * x1)))) * (x1 + ((x1 * (x1 - (x1 * (x1 * 0.398)))) * ((x1 * x1) - (x1 + x1))))))
2026-05-17 22:25:13,131 - INFO -   STGP_05: ((x1 - (x1 * (x1 * 0.398))) * ((x1 * (((x1 * x1) - (x1 + x1)) - (x1 * (x1 * 0.398)))) * ((x1 * (x1 - (x1 * (x1 * 0.398)))) * ((x1 * x1) - x1))))
2026-05-17 22:25:13,131 - INFO -   STGP_06: ((x1 * x1) * ((x1 - (x1 * (x1 * 0.398))) * (x1 + ((x1 * (x1 - ((x1 * ((x1 - -0.624) - (x1 * (x1 * 0.398)))) * (((x1 * x1) - (x1 + x1)) * x1)))) * (-0.251 + ((x1 * x1) - (x1 + x1)))))))
2026-05-17 22:25:13,131 - INFO -   STGP_07: ((x1 - (x1 * (x1 * 0.398))) * ((x1 * ((x1 - -0.624) - (x1 * ((x1 * x1) * ((x1 - (x1 * (x1 * 0.398))) * (x1 + ((x1 * (x1 - (x1 * (x1 * 0.398)))) * (-0.251 + ((x1 * x1) - (x1 + x1)))))))))) * (((x1 * x1) - (x1 + x1)) * x1)))
2026-05-17 22:25:13,131 - INFO -   STGP_08: ((x1 * x1) * ((x1 - (x1 * (x1 * 0.398))) * (x1 + ((x1 * (x1 - (x1 * (x1 * 0.398)))) * (-0.251 + ((((x1 * x1) - (x1 + x1)) * x1) - (x1 + x1)))))))
2026-05-17 22:25:13,131 - INFO -   STGP_09: ((x1 - (x1 * ((x1 * x1) * ((x1 - (x1 * (x1 * 0.398))) * (x1 + ((x1 * (x1 - (x1 * (x1 * 0.398)))) * ((x1 * x1) - (x1 + x1)))))))) * ((x1 * ((x1 - -0.624) - (x1 * (x1 * 0.398)))) * (((x1 * x1) - (x1 + x1)) * x1)))
2026-05-17 22:27:41,789 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:27:41,789 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 22:27:41,789 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:27:41,789 - INFO -   EF_00: ((x0 / -1) - (((((x1 / (x0 * ((x1 + -1) / x1))) - x1) - x1) - x1) - x1)) | (x1 - (-1 - (x1 * (((x0 - x1) - -1) - x0)))) | (x1 - ((x0 - x0) / x0)) | (((0 + -1) / x1) / -1) | ((0 / x0) / (x1 + (-1 + (((x0 - x1) - x1) - x1)))) | (x1 / (x0 / -1)) | ((x1 * ((x1 / -1) / x0)) + (x1 * (x1 * x0))) | (0 * (((x1 * -1) * 1) / -1)) | (x1 - ((((x0 - x1) - x1) / (x1 + x0)) * x1)) | ((-1 - (x0 - -1)) * x1)
2026-05-17 22:27:41,789 - INFO -   EF_01: ((x0 / -1) - (x0 - x1)) | (x0 - x0) | (x0 - 1) | (x0 / x1) | ((0 / x1) / (x1 + x0)) | (x1 / x1) | ((x1 * 1) + (x0 + -1)) | (0 * (x0 / -1)) | (x1 - (x1 * -1)) | (x1 * x1)
2026-05-17 22:27:41,789 - INFO -   EF_02: ((x0 / ((x1 + x1) / (x1 / 0))) - (((x0 - x1) - -1) - x1)) | (x0 - x0) | (x1 - x1) | (x1 / x1) | ((0 / 0) / x0) | (x1 / x1) | (x1 + (-1 + -1)) | (0 * (x1 / x1)) | (x1 - ((x0 / x1) * ((x1 + -1) / ((x0 + x0) - (1 + x1))))) | ((-1 - ((x1 / x0) * (x1 - x0))) * x1)
2026-05-17 22:27:41,789 - INFO -   EF_03: ((x0 / -1) - ((x0 - -1) - x1)) | (x0 - x0) | (x1 - 1) | (x1 / x1) | ((0 / x0) / (x1 / x1)) | (-1 / -1) | ((x1 * 1) + x1) | (0 * ((-1 - ((x1 / x0) * (x1 - x0))) / -1)) | (x1 - (x1 * -1)) | ((-1 - ((x1 / x0) * (x1 - x0))) * x1)
2026-05-17 22:27:41,789 - INFO -   EF_04: ((x0 / -1) - (((x0 - x1) - -1) - x1)) | (x0 - x0) | (x1 - x1) | (x1 / x1) | ((0 / x0) / (x1 + (-1 + x0))) | (x1 / x1) | ((x1 * (x0 / x0)) + (-1 + -1)) | (0 * (x1 / -1)) | (x1 - ((x1 / x1) * x1)) | ((-1 - ((x1 / x0) * (x1 - x0))) * x1)
2026-05-17 22:27:41,789 - INFO -   EF_05: ((x0 / -1) - (((((x0 - x1) - ((x1 - 1) - (-1 * 0))) / x1) - -1) - x1)) | (x0 - x0) | (1 - x1) | ((x1 * (x0 / x0)) / x1) | (x0 / (x0 / x0)) | (x1 / x1) | ((x1 * (x0 / x1)) + (-1 + (x1 * x0))) | (0 * ((x0 - x1) / (x1 * ((x1 + -1) / x1)))) | (x0 - ((x1 / x1) * x0)) | (x1 * x1)
2026-05-17 22:27:41,789 - INFO -   EF_06: ((x0 / -1) - ((((-1 + x0) - x1) - -1) - x1)) | ((x0 - x1) - x0) | (-1 - -1) | (x1 / 0) | ((x0 / x0) / (x1 + x0)) | (x1 / x0) | ((x1 * (x0 / x0)) + ((x0 * x1) * (x1 * x0))) | (0 * (((x0 * x1) * (x1 * -1)) / -1)) | (x1 - (x1 - x1)) | ((-1 - ((x1 / x1) * (x1 - x0))) * x1)
2026-05-17 22:27:41,789 - INFO -   EF_07: (1 - 0) | ((x1 - -1) - x1) | (0 / x0) | ((x1 + x1) + (-1 / 1)) | (x1 / 1) | ((x0 - x0) - (x1 / x1)) | (x1 + 1) | (-1 / x1) | ((x0 - x0) * x0) | ((x1 - x0) + (x0 / x0))
2026-05-17 22:27:41,789 - INFO -   EF_08: x1 | (x0 - (x1 + x0)) | (x1 * x1) | ((x1 + x0) + (x0 * ((x1 + -1) / (x1 + x1)))) | (x0 / x0) | (x0 + (1 / x0)) | (x1 - (x1 / 0)) | (-1 / x1) | ((x1 * x1) / (-1 + x0)) | ((-1 + x0) - (x0 / x1))
2026-05-17 22:27:41,800 - INFO -   EF_09: (x0 - ((((x0 - x1) - (1 - 1)) - x1) - x1)) | (x1 - (-1 - (x1 * (x1 - x0)))) | (x1 - ((x0 - x0) / x0)) | (x1 / x1) | ((0 / x0) / (x1 + (-1 + x0))) | (x1 / (x1 * (x0 - x1))) | ((x1 * x1) + (x1 * (x1 * x0))) | (0 * ((x0 * x0) / -1)) | (x1 - ((((x0 - x1) - x1) / (x1 + x0)) * x1)) | ((x1 - x1) * x1)
2026-05-17 22:28:49,029 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [4/4] SMOGN + STGP-EF training...

2026-05-17 22:28:56,688 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:28:56,688 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 22:28:56,688 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:28:56,688 - INFO -   STGP_00: ((((x1 * x1) * (-0.251 + (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1))) * ((x1 * (((x1 + ((0.557 - x1) * (-0.251 + x1))) + x1) * (x1 * x1))) - (x1 - x0))) * (x1 + ((x1 + ((0.557 - x1) * (-0.251 + x1))) * (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1))))
2026-05-17 22:28:56,688 - INFO -   STGP_01: ((x1 * ((x1 * ((x1 * x1) * (-0.251 + (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1)))) - (x1 - x0))) * (x1 + (((x1 + ((0.557 - x1) * (-0.251 + x1))) * (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1)) * (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1))))
2026-05-17 22:28:56,688 - INFO -   STGP_02: (((0.557 - x1) * ((x1 * ((x1 * x1) * (-0.251 + (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1)))) - (x1 - x0))) * (x1 + (((x0 + x1) - ((x1 + ((x1 + ((0.557 - x1) * x1)) * (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1))) - (x1 - x0))) * (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1))))
2026-05-17 22:28:56,688 - INFO -   STGP_03: ((x1 * ((x1 * (-0.251 + (((0.557 - x1) * ((x1 * (((x1 + ((0.557 - x1) * (-0.251 + x1))) + x1) * (x1 * x1))) - (x1 - x0))) * (x1 + ((x1 + ((0.557 - x1) * (-0.251 + x1))) * (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1)))))) - (x1 - x0))) * (x1 + ((x1 + ((0.557 - x1) * (-0.251 + x1))) * (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1))))
2026-05-17 22:28:56,688 - INFO -   STGP_04: (((0.557 - (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1)) * ((x1 * (((x1 + ((0.557 - x1) * ((x0 + x1) - ((x1 * x1) - (x1 - x0))))) + x1) * (x1 * x1))) - (x1 - x0))) * (x1 + ((x1 + ((0.557 - x1) * (-0.251 + x1))) * (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1))))
2026-05-17 22:28:56,688 - INFO -   STGP_05: ((x1 * ((x1 * ((x1 * x1) * (-0.251 + (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1)))) - (x1 - x0))) * (x1 + ((x1 + ((0.557 - x1) * x1)) * ((x1 + ((x1 + ((0.557 - x1) * x1)) * (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1))) + x1))))
2026-05-17 22:28:56,688 - INFO -   STGP_06: (((0.557 - x1) * ((x1 * ((x1 * ((x1 * ((x1 * x1) * (-0.251 + (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1)))) - (x1 - x0))) * (-0.251 + (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1)))) - (x1 - x0))) * (x1 + ((x1 + ((0.557 - x1) * x1)) * ((x1 + ((0.557 - x1) * (-0.251 + x1))) + x1))))
2026-05-17 22:28:56,688 - INFO -   STGP_07: (((x1 + ((0.557 - ((x1 * ((x1 * x1) * (-0.251 + (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1)))) - (x1 - x0))) * x1)) * ((x1 * ((((x1 * x1) - (x1 + 0.718)) + (0.392 - x1)) * (-0.251 + (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1)))) - (x1 - x0))) * ((x0 + x1) - ((x1 * x1) - (x1 - x0))))
2026-05-17 22:28:56,688 - INFO -   STGP_08: (((0.557 - x1) * ((x1 * ((x1 * x1) * (((x1 + ((0.557 - x1) * x1)) * ((x1 * ((((x1 * x1) - (x1 + 0.718)) + (0.392 - x1)) * (-0.251 + (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1)))) - (x1 - x0))) + x1))) - (x1 - x0))) * (x1 + ((x1 + ((0.557 - x1) * (-0.251 + x1))) * (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1))))
2026-05-17 22:28:56,688 - INFO -   STGP_09: ((x1 * ((x1 * ((x1 * x1) * (-0.251 + (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1)))) - (x1 - x0))) * (x1 + ((x1 + ((0.557 - x1) * (-0.251 + x1))) * (((x0 + x1) - ((x1 * x1) - (x1 - x0))) + x1))))
2026-05-17 22:31:33,425 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:31:33,426 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 22:31:33,427 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:31:33,427 - INFO -   EF_00: (-1 + 0) | (x1 / (x0 + x1)) | (x1 / (x0 + -1)) | (x0 + -1) | (x1 * (x0 - x1)) | (x1 * x1) | (x0 - -1) | (x1 * 1) | (1 + 1) | ((1 / -1) + (x0 + -1))
2026-05-17 22:31:33,429 - INFO -   EF_01: ((0 - x1) / (-1 - x0)) | ((x1 * -1) + (x0 / 1)) | (x1 + (x0 * 0)) | ((x1 - 0) * x1) | ((x1 + x0) * (x1 - 0)) | (x0 * x0) | (x0 / (x0 + 0)) | (x1 * (1 - 0)) | (x0 / -1) | (-1 * x1)
2026-05-17 22:31:33,429 - INFO -   EF_02: ((x1 + (x1 / -1)) + 0) | ((x1 * x1) / (x0 + x1)) | ((x1 - x1) / x0) | (x1 * -1) | (x1 * (x1 * -1)) | (1 * x1) | (x0 - -1) | (-1 * x1) | (1 + 1) | (0 + (x1 + x1))
2026-05-17 22:31:33,429 - INFO -   EF_03: (1 - 0) | (1 - x1) | (0 / x1) | ((x1 + x1) + (x1 * x0)) | (0 / x0) | (x1 - (x1 / x1)) | (x1 + x0) | (-1 / -1) | ((x0 - x0) * x0) | ((x1 - x0) + (x0 / x0))
2026-05-17 22:31:33,430 - INFO -   EF_04: (x1 * x1) | (0 - x0) | (x1 * (x0 / x1)) | (1 + (x1 * x0)) | (0 / x1) | ((1 + x1) + (1 / x0)) | ((x0 / x0) - x0) | (-1 / (x0 - x0)) | ((x1 * x1) / (-1 + x0)) | (1 - x1)
2026-05-17 22:31:33,430 - INFO -   EF_05: (-1 + (x0 - 0)) | ((x1 * x1) / (x0 + x1)) | (x0 / x0) | (x0 * -1) | (x1 * (x0 - x1)) | (1 * x0) | (x0 - x1) | (x0 * 1) | (x1 + 1) | ((1 / -1) + (x1 * x1))
2026-05-17 22:31:33,431 - INFO -   EF_06: (x0 + x0) | ((x1 + x1) / (x0 - (1 - 1))) | (x1 / (x0 + -1)) | (x1 * x1) | (x1 * (x1 - (((x1 - -1) * (1 / x1)) - x1))) | (0 - x1) | (x0 - x0) | (x0 * 1) | ((-1 + x1) + 1) | (x0 + (x1 * 0))
2026-05-17 22:31:33,431 - INFO -   EF_07: ((0 - x1) / (-1 - x0)) | ((x1 * -1) + (x1 / 1)) | ((-1 + x1) + (x1 + x1)) | ((x0 + x1) * -1) | ((1 - x1) * (x1 - 0)) | ((x1 / -1) * (x0 - 0)) | ((-1 - x0) / x0) | (-1 * x1) | (x0 / -1) | (x1 * -1)
2026-05-17 22:31:33,431 - INFO -   EF_08: ((x0 / x0) - (x0 - x1)) | (0 * -1) | ((x1 * x1) - x1) | (x0 / x0) | (((x1 / x1) / x1) / x1) | (x1 / ((x1 * x1) / (x1 / x1))) | ((-1 * 1) + (x0 + x0)) | (x0 * x1) | (x1 - (x0 * x1)) | (-1 * (x1 / x1))
2026-05-17 22:31:33,431 - INFO -   EF_09: ((((x1 / 0) * (1 / x1)) + x1) / x1) | (-1 + (x0 / x0)) | ((x1 * x0) - (x0 * x1)) | (x1 * (x1 - x0)) | (0 / x0) | (x1 - 1) | (x1 / (-1 * 1)) | ((0 / x0) - (((-1 - x0) * x1) + -1)) | ((x1 * x1) * (-1 + x0)) | (1 + x1)

  Completed.


============================================================
  Target: h (çıktı)  |  Input: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base training...
  [2/4] SMOGN training...
Özel SMOGN Algoritması başlatılıyor (Custom Build)...
Özel SMOGN Başarılı! Orijinal: 404 -> Artırılmış/Dengelenmiş: 470

2026-05-17 22:35:14,080 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [3/4] STGP-EF training...

2026-05-17 22:35:20,667 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:35:20,668 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 22:35:20,669 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:35:20,670 - INFO -   STGP_00: ((x0 / 0.483) - x1)
2026-05-17 22:35:20,670 - INFO -   STGP_01: ((x0 / 0.483) - x1)
2026-05-17 22:35:20,671 - INFO -   STGP_02: ((x0 / 0.483) - x1)
2026-05-17 22:35:20,671 - INFO -   STGP_03: ((x0 / 0.483) - x1)
2026-05-17 22:35:20,672 - INFO -   STGP_04: ((x0 / 0.483) - x1)
2026-05-17 22:35:20,672 - INFO -   STGP_05: ((x0 / 0.483) - x1)
2026-05-17 22:35:20,672 - INFO -   STGP_06: (x1 - (x0 / 0.483))
2026-05-17 22:35:20,673 - INFO -   STGP_07: (x1 - (x0 / 0.483))
2026-05-17 22:35:20,673 - INFO -   STGP_08: (x1 - (x0 / 0.483))
2026-05-17 22:35:20,674 - INFO -   STGP_09: ((x0 / 0.483) - x1)
2026-05-17 22:37:51,709 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:37:51,709 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 22:37:51,709 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:37:51,709 - INFO -   EF_00: ((((-1 * x0) + (x1 / 1)) - x1) + x1) | ((x0 + x0) - x1) | (x0 + ((1 * ((x0 - x1) - -1)) / -1)) | (x0 / (x1 / 1)) | ((x0 + x0) - (x1 / 1)) | (x0 - x0) | (x1 * ((1 * ((x1 - x1) - -1)) / -1)) | (((1 - -1) + x1) - (-1 * x0)) | ((x0 - x0) - ((x0 + (x0 / 1)) - x1)) | (-1 - ((-1 - x0) + (x1 - x0)))
2026-05-17 22:37:51,709 - INFO -   EF_01: (((x0 + (x0 / 1)) - x1) + x1) | ((x0 + ((x0 + x0) - x0)) - x1) | (x0 + ((1 * ((x0 - x1) - -1)) / -1)) | ((0 / -1) / ((x1 - x0) - -1)) | ((x0 + x0) - (x1 / 1)) | (-1 - (-1 * x0)) | ((x0 - x1) * x0) | ((1 + x1) - (x0 * x0)) | ((1 - x0) - ((x0 + (x0 / (x1 - x0))) - x1)) | ((x0 + x0) - x1)
2026-05-17 22:37:51,709 - INFO -   EF_02: (((x0 + (x0 / 1)) - x1) + x1) | ((x0 + x0) - x1) | (x0 + ((1 * ((x0 - x1) - -1)) / -1)) | ((((1 * ((x0 - x1) - -1)) / -1) / x1) / x1) | ((x0 + x0) - (x1 / 1)) | ((0 * x0) - (-1 * x0)) | (x0 * -1) | ((x0 / x1) - (((x0 / x0) - (0 + x1)) * x0)) | ((1 - x0) - ((x0 + (x0 / x1)) - x1)) | (x1 - (x1 - x1))
2026-05-17 22:37:51,714 - INFO -   EF_03: ((x0 + x0) - (x1 - x0)) | ((-1 / ((x1 + x0) + (x1 - x1))) / x1) | ((x0 + -1) * (0 / x1)) | (1 * (-1 + x0)) | (x1 - (x0 + x0)) | (((x1 - x0) / 1) - x0) | ((x0 - x1) + x0) | (-1 * x0) | ((x1 / (x1 * x0)) / ((x0 - x1) - 0)) | (1 + x0)
2026-05-17 22:37:51,715 - INFO -   EF_04: ((x0 + x0) - (x1 - x0)) | ((x1 / ((1 + x0) * x1)) / x1) | ((x0 + x0) * (0 / x1)) | (1 * x0) | (x1 - (x0 + x0)) | (((x1 - x0) / 1) - x0) | ((x0 - x1) + x0) | (((x0 - x0) + (x1 - x0)) * ((x1 / x1) + x0)) | (x0 / x0) | (1 + 1)
2026-05-17 22:37:51,717 - INFO -   EF_05: (x0 + -1) | ((x0 + x0) - x1) | (x0 + ((1 * ((x0 - x1) - -1)) / -1)) | (x0 / -1) | ((x0 + x0) - (x1 / 1)) | (-1 - (-1 * x0)) | (x1 * -1) | (((x1 + x0) + x1) - (-1 * x0)) | (((x0 + x0) / -1) / x0) | (x0 - x1)
2026-05-17 22:37:51,717 - INFO -   EF_06: ((x1 + x1) * (x0 - x0)) | ((x0 + x0) - x1) | (x0 + ((1 * ((x0 - x1) - -1)) / -1)) | (x0 / ((x0 / x1) / (x0 * x0))) | ((x0 + x0) - 1) | (-1 - (-1 * x0)) | ((x0 / x1) * x0) | (((1 - -1) + -1) - (-1 * -1)) | ((1 - x0) - ((x0 + (x0 / x1)) - x1)) | (1 - -1)
2026-05-17 22:37:51,718 - INFO -   EF_07: (((x0 + (x0 / 1)) - x1) + 1) | ((x0 + x0) - x1) | (x0 + ((1 * ((x0 - x1) - -1)) / -1)) | ((x0 / x1) / x1) | ((x0 + x0) - (x1 / 1)) | ((0 * x0) - (x0 * x0)) | (((x1 / 1) + x0) * (x1 - x0)) | ((x0 / x1) - (((x0 / x0) - (0 + 1)) * x0)) | ((1 - x0) - ((x0 + (x0 / x1)) - x1)) | (x1 - (x1 - x1))
2026-05-17 22:37:51,719 - INFO -   EF_08: ((x0 + x1) * (x0 - x0)) | ((x0 + x0) - x1) | (x0 + ((1 * ((x0 - x1) - -1)) / -1)) | (x0 / x0) | ((x0 + x0) - (x1 / 1)) | (x0 - (-1 * -1)) | ((x0 / x0) * x0) | (((1 - -1) + -1) - (x0 * x0)) | ((1 - x0) - ((x0 + (x0 / 1)) - x1)) | (1 - -1)
2026-05-17 22:37:51,719 - INFO -   EF_09: ((x0 + x0) - (x1 - x0)) | ((-1 / ((x1 + x0) + (x1 - x1))) / x1) | ((x0 + x0) * (0 / (x0 - -1))) | (x0 * 1) | (x1 - (x0 + x0)) | (((x1 - x0) / 1) - x0) | ((x0 - x1) + x0) | (((-1 - x0) + (x1 - x0)) * x0) | x1 | (1 + 1)
2026-05-17 22:39:04,917 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [4/4] SMOGN + STGP-EF training...

2026-05-17 22:39:11,613 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:39:11,613 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 22:39:11,613 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:39:11,613 - INFO -   STGP_00: (x1 - (x0 / 0.483))
2026-05-17 22:39:11,618 - INFO -   STGP_01: (x1 - (x0 / 0.483))
2026-05-17 22:39:11,618 - INFO -   STGP_02: ((x0 / 0.483) - x1)
2026-05-17 22:39:11,619 - INFO -   STGP_03: ((x0 / 0.483) - x1)
2026-05-17 22:39:11,619 - INFO -   STGP_04: (x1 - (x0 / 0.483))
2026-05-17 22:39:11,620 - INFO -   STGP_05: (x1 - (x0 / 0.483))
2026-05-17 22:39:11,621 - INFO -   STGP_06: (x1 - (x0 / 0.483))
2026-05-17 22:39:11,621 - INFO -   STGP_07: ((x0 / 0.483) - x1)
2026-05-17 22:39:11,621 - INFO -   STGP_08: (x1 - (x0 / 0.483))
2026-05-17 22:39:11,623 - INFO -   STGP_09: ((x0 / 0.483) - x1)
2026-05-17 22:41:51,672 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:41:51,683 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 22:41:51,684 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:41:51,685 - INFO -   EF_00: (((x0 - (x0 + x0)) + x0) - x0) | (x0 / x0) | (x0 * x0) | ((((x1 + x0) / (x0 / x0)) + x0) * x1) | (x0 - (0 / x0)) | (((x0 - x1) + ((x0 + x0) + x0)) - 0) | ((x0 - x1) + (x0 + x0)) | ((x0 - (x1 / 1)) * x0) | (((x0 - x1) + (x0 - (-1 - x0))) / x0) | (1 + (((x0 - x1) + ((x0 / x0) / 1)) + x0))
2026-05-17 22:41:51,685 - INFO -   EF_01: (((x0 - (x0 + x0)) + x0) - (x1 / x1)) | (x0 / (x0 + (x0 + ((x1 - x1) + (0 / x0))))) | (x0 * x0) | ((((x1 + x0) / (x0 / x0)) + x0) * x1) | (x0 - (x0 / x1)) | (((x0 - x1) + ((x0 + x0) + x0)) - 0) | ((x0 - x1) + (x0 + x0)) | ((x0 - (x1 / 1)) * x0) | (((x0 - x1) + ((x1 / x0) / (-1 - x0))) / x0) | (1 + (((x0 - x1) + ((x0 / x0) / 1)) + x0))
2026-05-17 22:41:51,686 - INFO -   EF_02: ((x0 + x0) - (x1 / x1)) | (x0 / x0) | (((x0 + (x0 / x0)) - x1) * x0) | ((((x1 + ((x0 + x0) - x1)) / (x0 / x0)) + x0) * x1) | (x0 - (x0 / x1)) | (((x0 - x1) + ((x0 + x0) + x0)) - 0) | ((x0 - x1) + (x0 + x0)) | ((x0 - (x1 / x0)) * x0) | (x0 / x0) | (1 + (((x0 - x1) + ((x0 / x0) / 1)) + x0))
2026-05-17 22:41:51,686 - INFO -   EF_03: (x0 * 1) | (1 - ((x1 - x1) + x0)) | ((x0 + ((x0 - x0) + x0)) * 1) | (((x0 - x1) + x0) + (x0 / 1)) | (-1 / (x0 / x0)) | ((1 + ((x0 - x1) + (x0 + x0))) + (x0 / x0)) | (x0 - x1) | ((-1 + 0) / 1) | (x0 / (-1 + x1)) | (x0 - (x1 / -1))
2026-05-17 22:41:51,687 - INFO -   EF_04: ((x0 + x0) - (x1 / x1)) | ((x0 - 0) * (0 + x0)) | (x0 * x0) | ((((x1 + ((x0 + x0) - x1)) / (x0 / x0)) + x0) * x1) | (x0 - (x0 / x1)) | (((x0 - x1) + ((x0 + x0) + x0)) - 0) | ((x0 - x1) + (x0 + x0)) | ((x0 - (x1 / 1)) * x0) | (x1 / x0) | (1 + (((x0 - x1) + ((x0 / x0) / 1)) + x0))
2026-05-17 22:41:51,688 - INFO -   EF_05: ((x0 + ((x0 - x1) + x0)) * x0) | (1 - ((x0 - x1) + x0)) | ((x0 + ((x0 - x1) + x0)) * 1) | (((x0 - x1) + x0) + (x0 / 1)) | (((x0 - x1) + ((x1 / x0) / (-1 - (x0 + ((x1 - 0) / (x0 + x0)))))) / x1) | ((1 + ((x0 - x1) + (x0 + x0))) + (x0 / 0)) | (x1 - x1) | (x0 / -1) | (((x0 + x0) + x0) / x0) | (1 - 1)
2026-05-17 22:41:51,689 - INFO -   EF_06: ((x0 + x0) * x1) | (1 - (((x1 + -1) - x1) + x0)) | ((x0 + ((x0 - x1) + x0)) * 1) | (((x0 - x1) + x0) + (x0 / 1)) | (((x0 - x1) + ((x1 / x0) / (-1 - (x0 + ((x1 - 0) / (x0 + x0)))))) / x1) | ((1 + ((x0 - x1) + (x0 + x0))) + (x0 / 0)) | (x1 - x1) | (x1 / -1) | (x1 / x0) | (1 - 1)
2026-05-17 22:41:51,689 - INFO -   EF_07: (1 - x0) | (x0 / x0) | (x0 * (x0 + x0)) | (-1 * (x0 - (-1 - x0))) | (((x0 - x1) + x0) - 0) | ((((x1 - x0) + (0 - 1)) / x0) - x0) | (((-1 / x0) - x1) + ((x0 + x0) + x0)) | (0 * x0) | (1 / (x0 * x0)) | ((x0 + ((x0 - x1) + (0 / x0))) + (x0 + x0))
2026-05-17 22:41:51,690 - INFO -   EF_08: (((x0 - (x0 + x0)) + x0) - x0) | (x0 / x0) | (x0 * x0) | ((((x1 + x0) / (x0 / x0)) + x0) * x1) | (x0 - (x0 / x0)) | (((x0 - x1) + ((x0 + x0) + x0)) - 0) | ((x0 - x1) + (x0 + x0)) | ((x0 - (x1 / 1)) * ((x0 - x1) + x0)) | (((x0 - x1) + (x0 - (-1 - x0))) / x0) | (1 + (((x0 - x1) + ((x0 / x0) / 1)) + x0))
2026-05-17 22:41:51,691 - INFO -   EF_09: (x1 * x0) | (1 - ((x1 - x1) + x1)) | ((x0 + ((x0 - x1) + (x0 / x0))) * 1) | (((x0 - x1) + x0) + (x0 / 1)) | (-1 / (x0 / x1)) | ((1 + ((x0 - x1) + (x0 + x0))) + (x0 / x0)) | (1 - x1) | ((x0 + 0) / 1) | (x1 / x0) | (1 - (x1 / -1))

  Completed.


============================================================
  Target: s (çıktı)  |  Input: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base training...
  [2/4] SMOGN training...
Özel SMOGN Algoritması başlatılıyor (Custom Build)...
Özel SMOGN Başarılı! Orijinal: 404 -> Artırılmış/Dengelenmiş: 470

2026-05-17 22:45:37,841 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [3/4] STGP-EF training...

2026-05-17 22:45:45,228 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:45:45,229 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 22:45:45,230 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:45:45,231 - INFO -   STGP_00: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:45:45,232 - INFO -   STGP_01: ((((x0 * 0.31) * x1) + x0) - x1)
2026-05-17 22:45:45,232 - INFO -   STGP_02: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:45:45,233 - INFO -   STGP_03: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:45:45,234 - INFO -   STGP_04: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:45:45,234 - INFO -   STGP_05: ((((x0 * 0.31) * x1) + x0) - x1)
2026-05-17 22:45:45,234 - INFO -   STGP_06: ((((x0 * 0.31) * x1) + x0) - x1)
2026-05-17 22:45:45,235 - INFO -   STGP_07: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:45:45,235 - INFO -   STGP_08: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:45:45,235 - INFO -   STGP_09: ((((x0 * 0.31) * x1) + x0) - x1)
2026-05-17 22:48:22,439 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:48:22,439 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 22:48:22,440 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:48:22,442 - INFO -   EF_00: x1 | ((x1 - x0) / x1) | ((x1 + (x1 - x0)) * x1) | (x1 - x1) | (((x0 / 0) / x0) - x0) | ((x1 - ((x0 / x1) / x1)) - ((x1 / x1) * x1)) | (x1 * x1) | ((((x1 * x0) - ((x1 - x0) / 1)) * 0) * (x1 + (x1 - x0))) | ((x1 - x0) - (-1 / ((x1 / 0) / (1 * x1)))) | (x0 / (x1 * (x1 / x0)))
2026-05-17 22:48:22,443 - INFO -   EF_01: x1 | ((x1 - x0) / (x1 / 1)) | (((0 + x0) + (x1 - x1)) * (x1 * x1)) | (x1 - x1) | ((x1 / x0) - x0) | ((x1 - ((x0 - x1) / x1)) - (x1 * x1)) | (x1 * (x1 + -1)) | (x1 * (x1 + (x1 - x0))) | ((x1 - x0) - (-1 / ((x1 / 0) / -1))) | (x0 / (x1 - x1))
2026-05-17 22:48:22,443 - INFO -   EF_02: x1 | ((x1 - (0 + x1)) / (x1 / (x1 * x0))) | ((x1 + (x1 - x0)) * (x1 * x1)) | (x1 - x1) | ((x1 / x0) - x0) | ((x1 - ((x0 - x1) / x1)) - (x1 * x1)) | (x1 * (x1 + -1)) | ((((x1 * x0) - ((x1 - x0) / 1)) * 0) * (x1 + (x1 - x0))) | ((x1 - x0) - (-1 / ((x1 / 0) / -1))) | (x1 / (x1 - x1))
2026-05-17 22:48:22,444 - INFO -   EF_03: x1 | ((x1 - x0) / x1) | ((x1 + (x1 - x0)) * x1) | (x1 - x1) | (x1 - (-1 * x1)) | ((x1 - ((x0 - x1) / x1)) - (x1 * x1)) | ((x0 - x0) * x1) | ((((x1 * x0) - ((x1 - x0) / 1)) * 0) * (x1 + (x1 - x0))) | ((x1 - x0) - (-1 / ((x1 / (x0 + -1)) / (1 * x1)))) | (x0 / (x1 * (x1 / x0)))
2026-05-17 22:48:22,445 - INFO -   EF_04: (x1 * -1) | ((x1 + 1) / -1) | (x1 * x1) | ((((x1 - 1) / x0) * -1) - 1) | (x0 - (x1 / x0)) | ((x1 - x0) - (x1 * x1)) | ((x1 / 1) * (0 + (0 * -1))) | (1 * x1) | ((x1 - x0) - (-1 / x1)) | ((1 + x1) / 0)
2026-05-17 22:48:22,445 - INFO -   EF_05: (-1 * x1) | ((x1 - x0) / x1) | (-1 * x1) | (x0 - ((x1 + x1) - (x0 - x0))) | (x0 - (x1 / x1)) | ((x1 - x0) - (x1 * x1)) | ((x1 * x1) * (x1 + 1)) | (x1 * (x1 * x1)) | ((x1 - x0) - (-1 / x1)) | (((x0 - 1) / x0) / (x0 * x0))
2026-05-17 22:48:22,446 - INFO -   EF_06: ((0 * x1) / (x1 - x0)) | ((-1 / x1) - (x1 / 0)) | (x1 * (1 * x0)) | ((x1 - ((-1 - 1) / (x0 * -1))) - (x1 / x0)) | (x0 - (x1 / 1)) | ((x1 - (x1 + (x0 / x1))) - (x1 * x1)) | (x0 * (-1 / x1)) | ((-1 / x1) * (x1 + 1)) | ((x1 - x0) - (-1 / x1)) | (((x1 * x1) / x1) / x1)
2026-05-17 22:48:22,447 - INFO -   EF_07: x1 | ((x1 - (0 + x1)) / x1) | ((x1 + (x1 - x0)) * x1) | (x1 - x1) | (x1 - (-1 * x1)) | ((x1 - ((x0 - x1) / x1)) - (x1 * x1)) | ((x0 - x0) * x1) | ((((x1 * x0) - (x0 / 1)) * 0) * (x1 + (x1 - x0))) | ((x1 - x0) - (-1 / ((x1 / (x0 - x1)) / (1 * x1)))) | (x0 / (x1 * (x1 / x0)))
2026-05-17 22:48:22,448 - INFO -   EF_08: (x1 * x1) | ((1 + x1) / x0) | (x1 * (x0 - x0)) | (x0 - (x0 - x1)) | (x0 - (x1 / (x1 / x0))) | ((x1 - x0) - (x1 * x1)) | (-1 * x1) | (x1 * (x1 * ((x0 - x1) - x1))) | ((x1 - x0) - (-1 / x1)) | (((x0 - x1) / x1) / x1)
2026-05-17 22:48:22,448 - INFO -   EF_09: x1 | ((x1 - x0) / (x1 / 1)) | (((0 + x0) + (x1 - x1)) * (x1 * x1)) | (x1 - x1) | ((x1 / x0) - (x1 + (x1 - (x1 - 1)))) | ((x1 - ((x0 - x1) / x1)) - (x1 * x1)) | (x1 * (x1 + -1)) | ((((x1 * x0) - x0) * 0) * (x1 + (x1 - x0))) | ((x1 - x0) - (-1 / ((x1 / 0) / -1))) | (x0 / (x1 - x1))
2026-05-17 22:49:37,452 - INFO - Hibrit Özellik İnşası (STGP-EF) Başlatılıyor...

  [4/4] SMOGN + STGP-EF training...

2026-05-17 22:49:59,333 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:49:59,335 - INFO - SYMBOLIC REGRESSION (STGP) - Generated Features (10 of 10)
2026-05-17 22:49:59,337 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 22:49:59,337 - INFO -   STGP_00: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:49:59,337 - INFO -   STGP_01: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:49:59,337 - INFO -   STGP_02: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:49:59,337 - INFO -   STGP_03: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:49:59,350 - INFO -   STGP_04: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:49:59,352 - INFO -   STGP_05: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:49:59,356 - INFO -   STGP_06: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:49:59,363 - INFO -   STGP_07: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:49:59,365 - INFO -   STGP_08: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 22:49:59,374 - INFO -   STGP_09: (((x1 * (x0 * 0.31)) + x0) - x1)
2026-05-17 23:01:49,964 - INFO -
──────────────────────────────────────────────────────────────────────────────
2026-05-17 23:01:49,967 - INFO - EVOLUTIONARY FOREST (EF) - Generated Features (10 of 100)
2026-05-17 23:01:49,968 - INFO - ──────────────────────────────────────────────────────────────────────────────
2026-05-17 23:01:49,970 - INFO -   EF_00: (-1 * x1) | (x1 * 1) | (x0 * 0) | (-1 - x1) | (((x1 * x1) / (1 - x0)) - x1) | ((x1 - x0) - ((0 + x1) * x1)) | ((x1 / x1) * -1) | (((x0 - x0) + x0) * 1) | ((x1 - x0) - (-1 / ((x0 * x1) / (x0 / ((x1 / x0) - (x1 * x0)))))) | (x0 / (x0 * ((x1 * x1) + x1)))
2026-05-17 23:01:49,972 - INFO -   EF_01: (-1 * x1) | ((-1 - x0) / ((x1 / x0) - (x1 * x0))) | (0 * 0) | (-1 - (x0 - (x0 / x1))) | (((((x1 + x0) - (x0 + 1)) * (-1 + (x1 + x1))) / (1 - x0)) - x1) | ((x1 - x0) - ((0 + x1) * x1)) | (x0 * -1) | (-1 * 1) | ((x1 - x0) - (-1 / ((x0 * x1) / (x0 / (x1 - (x1 * x0)))))) | ((x0 - x1) / 1)
2026-05-17 23:01:49,973 - INFO -   EF_02: (-1 * x1) | ((-1 - x1) / ((x1 / x0) - (x1 * x0))) | (x0 * x1) | (-1 - 1) | (((x1 * (-1 + x1)) / (1 - x0)) - x1) | ((x1 - x0) - ((0 + x1) * x1)) | (x0 * -1) | (((x0 - x0) + x0) * 1) | ((x1 - x0) - (-1 / ((x0 * x1) / (x0 / ((x1 / x0) - (x1 * x0)))))) | (x1 / (x0 * ((x1 * x1) + x1)))
2026-05-17 23:01:49,978 - INFO -   EF_03: (x1 * x1) | ((-1 - x1) / ((x1 / x0) - (x1 * (x1 / x0)))) | (x0 * (-1 / ((x0 * x1) / (x0 / ((((x1 / x0) - 0) / x0) - (x1 * x0)))))) | (-1 - 1) | (((x1 * (-1 + x1)) / (1 - x0)) - x1) | ((x1 - x0) - ((x1 + x1) * x1)) | (((x0 / x1) / 0) * -1) | (((x0 - x0) + x0) * x1) | ((x1 - x0) - (-1 / ((x0 * x1) / (x0 / ((x1 / x0) - (x1 * x0)))))) | (x1 / (x0 * ((x1 * x1) + 1)))
2026-05-17 23:01:49,981 - INFO -   EF_04: (-1 * x1) | ((x1 - x0) / ((x1 / x1) - (x1 * x0))) | (x0 * 0) | x1 | (((x1 * x1) / (1 - x0)) - x1) | ((x1 - x0) - ((0 + x1) * x1)) | (x0 * -1) | ((1 + x1) * 1) | ((x1 - x0) - (-1 / ((x0 * x1) / (x0 / ((x1 / x0) - (x1 * x0)))))) | (x1 / (x0 * 1))
2026-05-17 23:01:49,988 - INFO -   EF_05: (1 * (x1 - ((0 + x1) * x1))) | (x1 / x1) | ((((x1 - x0) / (x1 - 1)) * x1) * 0) | (x1 - 1) | ((x0 * 0) - x0) | ((x1 - x0) - (x1 * x1)) | ((0 * (x1 - -1)) * (x0 + x1)) | (x0 * (x1 + 1)) | ((x1 - x0) - (-1 / ((x0 * x1) / x0))) | (0 / x0)
2026-05-17 23:01:49,994 - INFO -   EF_06: (x1 * x0) | ((x1 - x0) / x1) | (-1 * 0) | (1 - 1) | (x1 - x1) | ((x1 - x0) - (x1 * x1)) | ((0 * x1) * (x0 + x1)) | (-1 * (x1 + 1)) | ((x1 - x0) - (-1 / ((x0 * x1) / x1))) | ((x1 / x1) / x0)
2026-05-17 23:01:49,998 - INFO -   EF_07: (-1 * x1) | ((-1 - x1) / ((x1 / x0) - (x1 * x0))) | (x0 * 0) | (-1 - x1) | (((x1 * (-1 + x1)) / (1 - x0)) - x1) | ((x1 - x0) - ((0 + x1) * x1)) | ((x1 / x1) * -1) | (((x0 - x0) + -1) * 1) | ((x1 - x0) - (-1 / ((x0 * x1) / (x0 / ((x1 / x0) - (x1 * x0)))))) | (x0 / (x0 * ((x1 * x1) + x1)))
2026-05-17 23:01:50,002 - INFO -   EF_08: (-1 * x1) | ((-1 - x1) / ((x1 / x0) - (x1 * x0))) | (x1 * 0) | (-1 - 1) | (((x1 * (-1 + x1)) / (1 - x0)) - x1) | ((x1 - x0) - ((0 + x1) * x1)) | ((x1 / 0) * -1) | (((x0 - x0) + x0) * 1) | ((x1 - x0) - (-1 / ((x0 * x1) / (x0 / ((x1 / x0) - (x1 * x0)))))) | (x1 / (x0 * ((x1 * x1) + x1)))
2026-05-17 23:01:50,006 - INFO -   EF_09: (-1 * x1) | (x1 * 1) | (x0 * 0) | (-1 - (x1 * 0)) | (((x1 * (-1 + x1)) / (1 - x0)) - x1) | ((x1 - x0) - x1) | ((x1 / x1) * -1) | (((x0 - x0) + x1) * 1) | ((x1 - x0) - (-1 / ((x0 * x1) / (x0 / ((x1 / x0) - (x1 * x0)))))) | (x0 / (x0 * ((x1 * x1) + x1)))

  Completed.

### 4.1 Kızgın Buhar — Sonuç Tablosu

In [16]:
df_kizgin_results = build_results_table(kizgin_results)
df_kizgin_results

        Target       Scenario Algorithm  Train_R2  Test_R2  Train_RMSE  Test_RMSE  Train_MAPE  Test_MAPE
0    v (çıktı)           Base  AdaBoost    0.9928   0.9891      0.0849     0.0984      1.0603     0.2023
1    v (çıktı)           Base  CatBoost    0.9999   0.9996      0.0073     0.0177      0.0532     0.0266
2    v (çıktı)           Base      DART    0.8654   0.8862      0.3669     0.3181      0.3296     0.1550
3    v (çıktı)           Base        EF    1.0000   0.9998      0.0001     0.0133      0.0000     0.0135
4    v (çıktı)           Base        ET    1.0000   0.9998      0.0000     0.0128      0.0000     0.0133
..         ...            ...       ...       ...      ...         ...        ...         ...        ...
127  s (çıktı)  SMOGN+STGP-EF        GP    0.8181   0.8439      0.5154     0.3712      0.3333     0.6943
128  s (çıktı)  SMOGN+STGP-EF       KNN    0.9942   0.9813      0.0921     0.1286      0.1183     0.2880
129  s (çıktı)  SMOGN+STGP-EF  LightGBM    0.9996   0.9945      0.0235     0.0695      0.0355     0.3514
130  s (çıktı)  SMOGN+STGP-EF        RF    0.9995   0.9930      0.0283     0.0785      0.0405     0.3872
131  s (çıktı)  SMOGN+STGP-EF   XGBoost    1.0000   0.9950      0.0017     0.0664      0.0042     0.2925

[132 rows x 9 columns]

### 4.2 Kızgın Buhar — Senaryo Karşılaştırması

In [17]:
compare_scenarios(df_kizgin_results)

Scenario              Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Target    Algorithm
h (çıktı) AdaBoost  0.9662 0.9671   0.9972         0.9965
          CatBoost  0.9980 0.9974   0.9989         0.9986
          DART      0.9604 0.9738   0.9750         0.9865
          EF        0.9995 0.9993   0.9990         0.9995
          ET        0.9994 0.9994   0.9994         0.9995
          GBDT      0.9977 0.9975   0.9990         0.9992
          GP        0.9553 0.9783   0.9881         0.9662
          KNN       0.9934 0.9929   0.9976         0.9981
          LightGBM  0.9729 0.9851   0.9857         0.9949
          RF        0.9973 0.9968   0.9989         0.9992
          XGBoost   0.9979 0.9979   0.9987         0.9988
s (çıktı) AdaBoost  0.8883 0.8816   0.9735         0.9748
          CatBoost  0.9957 0.9956   0.9973         0.9978
          DART      0.9382 0.9591   0.9783         0.9850
          EF        0.9982 0.9975   0.9950         0.9965
          ET        0.9972 0.9979   0.9924         0.9956
          GBDT      0.9922 0.9888   0.9969         0.9963
          GP        0.7252 0.7686   0.8439         0.8439
          KNN       0.9686 0.9659   0.9862         0.9813
          LightGBM  0.9529 0.9761   0.9884         0.9945
          RF        0.9843 0.9877   0.9890         0.9930
          XGBoost   0.9927 0.9914   0.9944         0.9950
v (çıktı) AdaBoost  0.9891 0.9808   0.9897         0.9909
          CatBoost  0.9996 0.9987   0.9997         0.9978
          DART      0.8862 0.9889   0.9709         0.9927
          EF        0.9998 0.9988   0.9929         0.9948
          ET        0.9998 0.9992   0.9972         0.9975
          GBDT      0.9994 0.9995   0.9987         0.9985
          GP        0.0405 0.3516   0.8734         0.6103
          KNN       0.7909 0.6580   0.9706         0.9977
          LightGBM  0.8781 0.9980   0.9945         0.9970
          RF        0.9994 0.9980   0.9982         0.9974
          XGBoost   0.9990 0.9988   0.9990         0.9983

### 4.3 Doymuş Buhar — Hedef Bazlı Detay

Her bir hedef değişken için detaylı pivot tablo;

In [18]:
target_summary(df_kizgin_results, 'v (çıktı)')

Scenario    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algorithm
AdaBoost  0.9891 0.9808   0.9897         0.9909
CatBoost  0.9996 0.9987   0.9997         0.9978
DART      0.8862 0.9889   0.9709         0.9927
EF        0.9998 0.9988   0.9929         0.9948
ET        0.9998 0.9992   0.9972         0.9975
GBDT      0.9994 0.9995   0.9987         0.9985
GP        0.0405 0.3516   0.8734         0.6103
KNN       0.7909 0.6580   0.9706         0.9977
LightGBM  0.8781 0.9980   0.9945         0.9970
RF        0.9994 0.9980   0.9982         0.9974
XGBoost   0.9990 0.9988   0.9990         0.9983

In [19]:
target_summary(df_kizgin_results, 'h (çıktı)')

Scenario    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algorithm
AdaBoost  0.9662 0.9671   0.9972         0.9965
CatBoost  0.9980 0.9974   0.9989         0.9986
DART      0.9604 0.9738   0.9750         0.9865
EF        0.9995 0.9993   0.9990         0.9995
ET        0.9994 0.9994   0.9994         0.9995
GBDT      0.9977 0.9975   0.9990         0.9992
GP        0.9553 0.9783   0.9881         0.9662
KNN       0.9934 0.9929   0.9976         0.9981
LightGBM  0.9729 0.9851   0.9857         0.9949
RF        0.9973 0.9968   0.9989         0.9992
XGBoost   0.9979 0.9979   0.9987         0.9988

In [20]:
target_summary(df_kizgin_results, 's (çıktı)')

Scenario    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algorithm
AdaBoost  0.8883 0.8816   0.9735         0.9748
CatBoost  0.9957 0.9956   0.9973         0.9978
DART      0.9382 0.9591   0.9783         0.9850
EF        0.9982 0.9975   0.9950         0.9965
ET        0.9972 0.9979   0.9924         0.9956
GBDT      0.9922 0.9888   0.9969         0.9963
GP        0.7252 0.7686   0.8439         0.8439
KNN       0.9686 0.9659   0.9862         0.9813
LightGBM  0.9529 0.9761   0.9884         0.9945
RF        0.9843 0.9877   0.9890         0.9930
XGBoost   0.9927 0.9914   0.9944         0.9950

# En İyi Sonuçlar

Her hedef değişken için en iyi (Algoritma, Senaryo) kombinasyonunu döndürür.

In [21]:
show_best_results(df_doymus_results)

            Target Scenario Algorithm  Test_R2  Train_R2  Test_RMSE  Test_MAPE
0         P(çıktı)     Base        ET   1.0000    1.0000     0.0035     0.0034
1  h buhar (çıktı)     Base        ET   1.0000    1.0000     0.0062     0.0065
2   h sıvı (çıktı)  STGP-EF        ET   1.0000    1.0000     0.0044     0.0131
3  s buhar (çıktı)     Base        ET   0.9997    1.0000     0.0134     0.0325
4   s sıvı (çıktı)  STGP-EF        ET   1.0000    1.0000     0.0049     0.0082
5  v buhar (çıktı)  STGP-EF        ET   0.9992    1.0000     0.0299     0.0151
6   v sıvı (çıktı)  STGP-EF        ET   1.0000    1.0000     0.0051     0.0112

---
## 5. Genel Karşılaştırma

In [22]:

df_doymus_results['Veri Seti'] = 'Doymuş Buhar'
df_kizgin_results['Veri Seti'] = 'Kızgın Buhar'
df_all = pd.concat([df_doymus_results, df_kizgin_results], ignore_index=True)

print(f'Toplam değerlendirme sayısı: {len(df_all)}')
df_all.head(20)

Toplam değerlendirme sayısı: 440

      Target Scenario Algorithm  Train_R2  Test_R2  Train_RMSE  Test_RMSE  Train_MAPE  Test_MAPE     Veri Seti
0   P(çıktı)     Base  AdaBoost    0.9964   0.9959      0.0598     0.0653      0.0706     0.1070  Doymuş Buhar
1   P(çıktı)     Base  CatBoost    0.9998   0.9991      0.0123     0.0300      0.0484     0.0844  Doymuş Buhar
2   P(çıktı)     Base      DART    0.9387   0.9541      0.2475     0.2177      0.2042     0.1343  Doymuş Buhar
3   P(çıktı)     Base        EF    1.0000   1.0000      0.0000     0.0054      0.0000     0.0077  Doymuş Buhar
4   P(çıktı)     Base        ET    1.0000   1.0000      0.0000     0.0035      0.0000     0.0034  Doymuş Buhar
5   P(çıktı)     Base      GBDT    1.0000   0.9991      0.0004     0.0308      0.0011     0.0752  Doymuş Buhar
6   P(çıktı)     Base        GP    0.9743   0.9702      0.1603     0.1753      0.3648     0.3469  Doymuş Buhar
7   P(çıktı)     Base       KNN    0.9991   0.9998      0.0304     0.0158      0.0331     0.0438  Doymuş Buhar
8   P(çıktı)     Base  LightGBM    0.9461   0.9651      0.2322     0.1898      0.1671     0.1121  Doymuş Buhar
9   P(çıktı)     Base        RF    0.9999   0.9997      0.0098     0.0181      0.0186     0.0399  Doymuş Buhar
10  P(çıktı)     Base   XGBoost    1.0000   0.9982      0.0022     0.0427      0.0034     0.0818  Doymuş Buhar
11  P(çıktı)    SMOGN  AdaBoost    0.9987   0.9978      0.0416     0.0478      0.0432     0.0568  Doymuş Buhar
12  P(çıktı)    SMOGN  CatBoost    0.9998   0.9993      0.0166     0.0276      0.0321     0.0685  Doymuş Buhar
13  P(çıktı)    SMOGN      DART    0.9826   0.9883      0.1545     0.1097      0.1450     0.0910  Doymuş Buhar
14  P(çıktı)    SMOGN        EF    1.0000   0.9999      0.0000     0.0075      0.0000     0.0149  Doymuş Buhar
15  P(çıktı)    SMOGN        ET    1.0000   1.0000      0.0000     0.0047      0.0000     0.0035  Doymuş Buhar
16  P(çıktı)    SMOGN      GBDT    1.0000   0.9992      0.0010     0.0291      0.0012     0.0755  Doymuş Buhar
17  P(çıktı)    SMOGN        GP    0.9788   0.9702      0.1707     0.1753      0.3160     0.3469  Doymuş Buhar
18  P(çıktı)    SMOGN       KNN    0.9996   0.9994      0.0238     0.0244      0.0292     0.0565  Doymuş Buhar
19  P(çıktı)    SMOGN  LightGBM    0.9901   0.9962      0.1164     0.0625      0.1239     0.0772  Doymuş Buhar

In [23]:
# Senaryo bazlı ortalama Test R² skorları
df_all.groupby(['Veri Seti', 'Senaryo'])['Test_R2'].mean().unstack()

KeyError: 'Senaryo'

In [ ]:
# Algoritma bazlı ortalama Test R² skorları
df_all.groupby(['Veri Seti', 'Algoritma'])['Test_R2'].mean().unstack()

In [ ]:
# Geniş formatlı sonuç tablosu oluştur ve kaydet
df_wide = save_wide_results(df_all, 'R515B_Ozellikler/Model_Training_Results.csv')
print('Sonuçlar R515B_Ozellikler/Model_Training_Results.csv dosyasına kaydedildi.')
print(f'Format: Geniş tablo — {len(df_wide)} satır, {len(df_wide.columns)} sütun')
df_wide