# Data Processing

Bu notebook'ta, R515B soğutucu akışkanına ait **Doymuş Buhar** ve **Kızgın Buhar** veri setlerindeki sütunların veri tipi dönüşümleri gerçekleştirilmektedir.

In [1]:
import pandas as pd
import numpy as np

## Veri Setlerinin Yüklenmesi

Her iki veri setini Excel dosyalarından okuyoruz.

In [2]:
df_doymus = pd.read_excel("R515B_Ozellikler/R515B_Doymus_Ozellikleri.xlsx")
df_kizgin = pd.read_excel("R515B_Ozellikler/R515B_Kizgin_Buhar.xlsx")

## Mevcut Veri Tiplerinin İncelenmesi

Her iki veri setindeki sütunların mevcut veri tiplerini inceliyoruz. Excel dosyalarında ondalık ayırıcı olarak virgül (`,`) kullanıldığından, tüm sütunlar `object` (metin) tipinde okunmuştur.

In [3]:
df_doymus.dtypes

T(girdi)           object
P(çıktı)           object
v sıvı (çıktı)     object
v buhar (çıktı)    object
h sıvı (çıktı)     object
h buhar (çıktı)    object
s sıvı (çıktı)     object
s buhar (çıktı)    object
dtype: object

In [4]:
df_kizgin.dtypes

T (girdi)    object
P (girdi)    object
v (çıktı)    object
h (çıktı)    object
s (çıktı)    object
state        object
dtype: object

## İlk Satırın Silinmesi

Her iki veri setindeki ilk satır, sütun açıklamalarını (girdi/çıktı bilgisi) içermekte olup gerçek veri değildir. Sayısal dönüşüme geçmeden önce bu satırları her iki DataFrame'den kaldırıyoruz.

In [5]:
df_doymus = df_doymus.iloc[1:].reset_index(drop=True)
df_kizgin = df_kizgin.iloc[1:].reset_index(drop=True)

df_doymus.head()

,T(girdi),P(çıktı),v sıvı (çıktı),v buhar (çıktı),h sıvı (çıktı),h buhar (çıktı),s sıvı (çıktı),s buhar (çıktı)
0,-30,61.221,0.000745,0.27264,2.7282,198.2,0.04464,0.84856
1,-29,64.235,0.000746,0.26063,3.9422,198.89,0.049614,0.84809
2,-28,67.367,0.000748,0.24925,5.1587,199.58,0.054576,0.84764
3,-27,70.62,0.000749,0.23847,6.3775,200.27,0.059528,0.84721
4,-26,73.996,0.000751,0.22824,7.5988,200.95,0.064469,0.84681

In [6]:
df_kizgin.head()

  T (girdi) P (girdi) v (çıktı) h (çıktı) s (çıktı)        state
0       -30        50   0.33575    198.55   0.86391  Superheated
1       -25        50   0.34327    202.45   0.87981  Superheated
2       -20        50   0.35075     206.4   0.89557  Superheated
3       -15        50   0.35821     210.4    0.9112  Superheated
4       -10        50   0.36564    214.43   0.92669  Superheated

## Doymuş Buhar Özellikleri — Sayısal Tipe Dönüşüm

Doymuş buhar veri setindeki tüm sütunlar `object` (metin) tipinde okunmuştur. Ondalık ayırıcı olarak virgül (`,`) kullanıldığından, virgülleri noktaya (`.`) çevirerek tüm sütunları `pd.to_numeric` ile sayısal (`numeric`) tipe dönüştürüyoruz.

In [7]:
df_doymus = df_doymus.apply(lambda col: pd.to_numeric(col.astype(str).str.replace(",", "."), errors="coerce"))
df_doymus.dtypes

T(girdi)             int64
P(çıktı)           float64
v sıvı (çıktı)     float64
v buhar (çıktı)    float64
h sıvı (çıktı)     float64
h buhar (çıktı)    float64
s sıvı (çıktı)     float64
s buhar (çıktı)    float64
dtype: object

In [8]:
df_doymus.head()

,T(girdi),P(çıktı),v sıvı (çıktı),v buhar (çıktı),h sıvı (çıktı),h buhar (çıktı),s sıvı (çıktı),s buhar (çıktı)
0,-30,61.221,0.000745,0.27264,2.7282,198.20,0.044640,0.84856
1,-29,64.235,0.000746,0.26063,3.9422,198.89,0.049614,0.84809
2,-28,67.367,0.000748,0.24925,5.1587,199.58,0.054576,0.84764
3,-27,70.620,0.000749,0.23847,6.3775,200.27,0.059528,0.84721
4,-26,73.996,0.000751,0.22824,7.5988,200.95,0.064469,0.84681

## Kızgın Buhar Özellikleri — Sayısal Tipe Dönüşüm

Kızgın buhar veri setindeki sütunlar da aynı şekilde `object` tipinde okunmuştur. Virgülleri noktaya çevirerek sayısal tipe dönüştürüyoruz.

> **Not:** `state` sütunu kategorik/metin bilgisi içerdiğinden, sayısal dönüşüm sonrasında `NaN` değerler alacaktır. Bu sütun bir sonraki adımda veri setinden kaldırılacaktır.

In [9]:
df_kizgin = df_kizgin.apply(lambda col: pd.to_numeric(col.astype(str).str.replace(",", "."), errors="coerce"))
df_kizgin.dtypes

T (girdi)      int64
P (girdi)      int64
v (çıktı)    float64
h (çıktı)    float64
s (çıktı)    float64
state        float64
dtype: object

In [10]:
df_kizgin.head()

   T (girdi)  P (girdi)  v (çıktı)  h (çıktı)  s (çıktı)  state
0        -30         50    0.33575     198.55    0.86391    NaN
1        -25         50    0.34327     202.45    0.87981    NaN
2        -20         50    0.35075     206.40    0.89557    NaN
3        -15         50    0.35821     210.40    0.91120    NaN
4        -10         50    0.36564     214.43    0.92669    NaN

## `state` Sütununun Kaldırılması

Kızgın buhar veri setinde bulunan `state` sütunu, sayısal bir değer içermeyip kategorik/metin bilgisi taşımaktadır (örn. *superheated vapor*). Sayısal dönüşüm sonrası bu sütun tamamen `NaN` değerler içermektedir ve modelleme ile analiz süreçlerinde kullanılamaz. Bu nedenle veri setinden kaldırıyoruz.

In [11]:
df_kizgin = df_kizgin.drop(columns=["state"])
df_kizgin.head()

   T (girdi)  P (girdi)  v (çıktı)  h (çıktı)  s (çıktı)
0        -30         50    0.33575     198.55    0.86391
1        -25         50    0.34327     202.45    0.87981
2        -20         50    0.35075     206.40    0.89557
3        -15         50    0.35821     210.40    0.91120
4        -10         50    0.36564     214.43    0.92669

## Dönüşüm Sonrası Doğrulama

Her iki veri setinin son durumunu kontrol ediyoruz. Tüm sütunların sayısal tipe dönüştüğünü, `state` sütununun kaldırıldığını ve dönüşüm sırasında oluşmuş olabilecek `NaN` değerleri doğruluyoruz.

### Doymuş Buhar — Genel Bilgi

In [12]:
df_doymus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   T(girdi)         136 non-null    int64
 1   P(çıktı)         136 non-null    float64
 2   v sıvı (çıktı)   136 non-null    float64
 3   v buhar (çıktı)  136 non-null    float64
 4   h sıvı (çıktı)   136 non-null    float64
 5   h buhar (çıktı)  136 non-null    float64
 6   s sıvı (çıktı)   136 non-null    float64
 7   s buhar (çıktı)  136 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 8.6 KB

### Kızgın Buhar — Genel Bilgi

In [17]:
df_doymus.describe()

,T(girdi),P(çıktı),v sıvı (çıktı),v buhar (çıktı),h sıvı (çıktı),h buhar (çıktı),s sıvı (çıktı),s buhar (çıktı)
count,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000,136.000000
mean,37.500000,1042.864324,0.000926,0.054111,94.706654,238.523456,0.361161,0.847033
std,39.403892,935.850024,0.000158,0.064105,57.724829,20.551542,0.182512,0.006818
min,-30.000000,61.221000,0.000745,0.003320,2.728200,198.200000,0.044640,0.814680
25%,3.750000,248.537500,0.000802,0.010188,45.102750,221.165000,0.207153,0.843540
50%,37.500000,716.865000,0.000881,0.025510,90.801500,242.470000,0.361425,0.846980
75%,71.250000,1658.925000,0.001009,0.072487,141.517500,258.047500,0.513530,0.852463
max,105.000000,3342.500000,0.001426,0.272640,207.610000,263.000000,0.690430,0.855230

In [13]:
df_kizgin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 578 entries, 0 to 577
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   T (girdi)  578 non-null    int64
 1   P (girdi)  578 non-null    int64
 2   v (çıktı)  578 non-null    float64
 3   h (çıktı)  578 non-null    float64
 4   s (çıktı)  578 non-null    float64
dtypes: float64(3), int64(2)
memory usage: 22.7 KB

In [18]:
df_kizgin.describe()

        T (girdi)    P (girdi)   v (çıktı)   h (çıktı)   s (çıktı)
count  578.000000   578.000000  578.000000  578.000000  578.000000
mean    73.027682   987.283737    0.064798  275.340035    0.957587
std     28.295040   773.162310    0.098803   22.994860    0.080835
min    -30.000000    50.000000    0.003632  198.550000    0.827400
25%     55.000000   350.000000    0.013404  261.940000    0.893705
50%     80.000000   800.000000    0.026924  276.900000    0.941040
75%     95.000000  1500.000000    0.064513  292.270000    1.004250
max    105.000000  3300.000000    0.532510  318.950000    1.254100

### Eksik Değer Kontrolü

Dönüşüm sırasında `errors="coerce"` parametresi nedeniyle sayısal olmayan değerler `NaN`'a dönüştürülmüş olabilir. Her iki veri setindeki eksik değerleri kontrol ediyoruz.

In [14]:
df_doymus.isnull().sum()

T(girdi)           0
P(çıktı)           0
v sıvı (çıktı)     0
v buhar (çıktı)    0
h sıvı (çıktı)     0
h buhar (çıktı)    0
s sıvı (çıktı)     0
s buhar (çıktı)    0
dtype: int64

In [15]:
df_kizgin.isnull().sum()

T (girdi)    0
P (girdi)    0
v (çıktı)    0
h (çıktı)    0
s (çıktı)    0
dtype: int64

## Veri Setlerinin CSV Olarak Kaydedilmesi

Tüm veri tipi dönüşümleri ve temizlik işlemleri tamamlandıktan sonra, her iki veri setini `.csv` formatında kaydediyoruz.

In [ ]:
# df_doymus.to_csv("R515B_Ozellikler/R515B_Doymus_Ozellikleri.csv", index=False)
# df_kizgin.to_csv("R515B_Ozellikler/R515B_Kizgin_Buhar.csv", index=False)