# R515B Soğutucu Akışkan — Model Eğitimi

Bu notebook, Doymuş ve Kızgın buhar veri setleri için **4 farklı senaryo** ile regresyon modeli eğitimi yapar:

| # | Senaryo | Açıklama |
|---|---------|----------|
| 1 | **Base** | Orijinal veri ile temel eğitim |
| 2 | **SMOGN** | SMOGN ile veri artırma sonrası eğitim |
| 3 | **STGP-EF** | SymbolicTransformer  ve Evolutionary Forest Hibrit Yöntemi ile öznitelik inşası sonrası eğitim |
| 4 | **SMOGN+STGP-EF** | Önce SMOGN, sonra STGP-EF ile birleşik eğitim |

Her senaryo **8 farklı regresyon algoritması** ile değerlendirilir (RF, ET, AdaBoost, GBDT, DART, XGBoost, LightGBM, CatBoost).

---

## 1. Kütüphaneler ve Fonksiyonlar

In [1]:
import sys
sys.path.insert(0, 'R515B_Ozellikler')

import pandas as pd
import numpy as np
from Functions import (
    run_doymus_analysis,
    run_kizgin_analysis,
    build_results_table,
    show_best_results,
    compare_scenarios,
    target_summary,
    save_wide_results
)

print('Fonksiyonlar başarıyla yüklendi.')

c:\Users\SGUZEY\Documents\Yüksek Lisans Dersleri\Veri Mühendisliği\Data_Engineering_Project\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Fonksiyonlar başarıyla yüklendi.

## 2. Veri Yükleme

In [2]:
df_doymus = pd.read_csv('R515B_Ozellikler/R515B_Doymus_Ozellikleri.csv')
df_kizgin = pd.read_csv('R515B_Ozellikler/R515B_Kizgin_Buhar.csv')

print(f'Doymuş Buhar: {df_doymus.shape}')
print(f'Kızgın Buhar: {df_kizgin.shape}')
print(f'\nDoymuş Sütunlar: {list(df_doymus.columns)}')
print(f'Kızgın Sütunlar: {list(df_kizgin.columns)}')

Doymuş Buhar: (136, 8)
Kızgın Buhar: (578, 5)

Doymuş Sütunlar: ['T(girdi)', 'P(çıktı)', 'v sıvı (çıktı)', 'v buhar (çıktı)', 'h sıvı (çıktı)', 'h buhar (çıktı)', 's sıvı (çıktı)', 's buhar (çıktı)']
Kızgın Sütunlar: ['T (girdi)', 'P (girdi)', 'v (çıktı)', 'h (çıktı)', 's (çıktı)']

In [3]:
df_doymus.head()

   T(girdi)  P(çıktı)  v sıvı (çıktı)  v buhar (çıktı)  h sıvı (çıktı)  h buhar (çıktı)  s sıvı (çıktı)  s buhar (çıktı)
0       -30   61.2210          0.0007           0.2726          2.7282         198.2000          0.0446           0.8486
1       -29   64.2350          0.0007           0.2606          3.9422         198.8900          0.0496           0.8481
2       -28   67.3670          0.0007           0.2492          5.1587         199.5800          0.0546           0.8476
3       -27   70.6200          0.0007           0.2385          6.3775         200.2700          0.0595           0.8472
4       -26   73.9960          0.0008           0.2282          7.5988         200.9500          0.0645           0.8468

In [4]:
df_kizgin.head()

   T (girdi)  P (girdi)  v (çıktı)  h (çıktı)  s (çıktı)
0        -30         50     0.3357   198.5500     0.8639
1        -25         50     0.3433   202.4500     0.8798
2        -20         50     0.3508   206.4000     0.8956
3        -15         50     0.3582   210.4000     0.9112
4        -10         50     0.3656   214.4300     0.9267

---
## 3. Doymuş Buhar — Eğitim

**Girdi:** T(girdi)  
**Çıktılar (her biri ayrı ayrı):** P, v sıvı, v buhar, h sıvı, h buhar, s sıvı, s buhar

In [5]:
doymus_results = run_doymus_analysis(df_doymus)

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  DOYMUŞ BUHAR ANALİZİ
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

============================================================
  Hedef: P(çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 2.585763454437256 seconds
population_evaluation took 7.747295379638672 seconds
population_evaluation took 9.289340734481812 seconds
population_evaluation took 9.97340726852417 seconds
population_evaluation took 14.114552974700928 seconds
population_evaluation took 17.595920085906982 seconds
population_evaluation took 13.023355484008789 seconds
population_evaluation took 12.635209798812866 seconds
population_evaluation took 12.501970052719116 seconds
population_evaluation took 17.262735843658447 seconds
population_evaluation took 12.890641450881958 seconds
population_evaluation took 10.38206958770752 seconds
population_evaluation took 9.862647294998169 seconds
population_evaluation took 2.400588035583496 seconds
population_evaluation took 2.256927490234375 seconds
population_evaluation took 6.6994242668151855 seconds
population_evaluation took 3.1773147583007812 seconds
population_evaluation took 4.7619242668151855 seconds
population_evaluation took 6.574150562286377 seconds
population_evaluation took 6.55286169052124 seconds
population_evaluation took 10.121506690979004 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 25/25 [00:00<00:00, 504.99it/s]
r_index: 100%|##########| 23/23 [00:00<00:00, 1140.77it/s]

population_evaluation took 2.1913363933563232 seconds
population_evaluation took 2.308389186859131 seconds
population_evaluation took 2.033172369003296 seconds
population_evaluation took 9.367775678634644 seconds
population_evaluation took 12.872122764587402 seconds
population_evaluation took 16.305608987808228 seconds
population_evaluation took 14.199645757675171 seconds
population_evaluation took 13.862366199493408 seconds
population_evaluation took 16.81130814552307 seconds
population_evaluation took 16.162931442260742 seconds
population_evaluation took 16.066697597503662 seconds
population_evaluation took 16.167412519454956 seconds
population_evaluation took 15.800586462020874 seconds
population_evaluation took 12.804928302764893 seconds
population_evaluation took 15.62870168685913 seconds
population_evaluation took 17.664909601211548 seconds
population_evaluation took 14.628138542175293 seconds
population_evaluation took 16.146612405776978 seconds
population_evaluation took 14.820373058319092 seconds
population_evaluation took 15.700330972671509 seconds
population_evaluation took 11.367762088775635 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 6.9712419509887695 seconds
population_evaluation took 6.866076707839966 seconds
population_evaluation took 9.996660470962524 seconds
population_evaluation took 11.092594861984253 seconds
population_evaluation took 7.537140130996704 seconds
population_evaluation took 9.966809749603271 seconds
population_evaluation took 11.717057943344116 seconds
population_evaluation took 13.1219482421875 seconds
population_evaluation took 8.39195990562439 seconds
population_evaluation took 7.375748634338379 seconds
population_evaluation took 10.957922220230103 seconds
population_evaluation took 12.659502267837524 seconds
population_evaluation took 14.204279661178589 seconds
population_evaluation took 11.980390310287476 seconds
population_evaluation took 6.327428579330444 seconds
population_evaluation took 6.178074598312378 seconds
population_evaluation took 10.520497560501099 seconds
population_evaluation took 14.975643396377563 seconds
population_evaluation took 5.421339750289917 seconds
population_evaluation took 12.685094833374023 seconds
population_evaluation took 11.634679794311523 seconds
population_evaluation took 13.09413480758667 seconds
population_evaluation took 13.3862464427948 seconds
population_evaluation took 12.273114442825317 seconds
population_evaluation took 13.02655291557312 seconds
population_evaluation took 12.430563688278198 seconds
population_evaluation took 12.285534143447876 seconds
population_evaluation took 3.8392579555511475 seconds
population_evaluation took 2.1261603832244873 seconds
population_evaluation took 2.070685863494873 seconds
population_evaluation took 2.249195098876953 seconds
population_evaluation took 2.181759834289551 seconds
population_evaluation took 4.411030292510986 seconds
population_evaluation took 12.123110294342041 seconds
population_evaluation took 11.935701608657837 seconds
population_evaluation took 13.138406991958618 seconds
population_evaluation took 12.520158290863037 seconds
population_evaluation took 8.451341152191162 seconds
population_evaluation took 2.8621490001678467 seconds
population_evaluation took 2.9724655151367188 seconds
population_evaluation took 2.698734760284424 seconds
population_evaluation took 6.091837167739868 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 8.884926557540894 seconds
population_evaluation took 1.9777648448944092 seconds
population_evaluation took 2.3839449882507324 seconds
population_evaluation took 2.1834237575531006 seconds
population_evaluation took 2.001188278198242 seconds
population_evaluation took 2.1359219551086426 seconds
population_evaluation took 2.0193254947662354 seconds
population_evaluation took 2.1941535472869873 seconds
population_evaluation took 2.129763603210449 seconds
population_evaluation took 2.218806028366089 seconds
population_evaluation took 1.8557348251342773 seconds
population_evaluation took 2.079854965209961 seconds
population_evaluation took 2.050157308578491 seconds
population_evaluation took 2.06170654296875 seconds
population_evaluation took 2.099637508392334 seconds
population_evaluation took 1.9582066535949707 seconds
population_evaluation took 2.4442076683044434 seconds
population_evaluation took 2.4351844787597656 seconds
population_evaluation took 2.0216259956359863 seconds
population_evaluation took 2.4751696586608887 seconds
population_evaluation took 2.924067974090576 seconds
population_evaluation took 2.45466947555542 seconds
population_evaluation took 2.4506993293762207 seconds
population_evaluation took 2.361640691757202 seconds
population_evaluation took 2.3451638221740723 seconds
population_evaluation took 2.2132604122161865 seconds
population_evaluation took 2.210538864135742 seconds
population_evaluation took 2.2061173915863037 seconds
population_evaluation took 2.2452168464660645 seconds
population_evaluation took 2.636091947555542 seconds
population_evaluation took 2.950319290161133 seconds
population_evaluation took 2.034822702407837 seconds
population_evaluation took 2.2952587604522705 seconds
population_evaluation took 2.472865581512451 seconds
population_evaluation took 2.2851364612579346 seconds
population_evaluation took 2.390557050704956 seconds
population_evaluation took 2.4228384494781494 seconds
population_evaluation took 2.321237087249756 seconds
population_evaluation took 2.7641916275024414 seconds
population_evaluation took 3.1195080280303955 seconds
population_evaluation took 2.945067882537842 seconds
population_evaluation took 3.4385182857513428 seconds
  Tamamlandı.


============================================================
  Hedef: v sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 3.094322443008423 seconds
population_evaluation took 3.7858028411865234 seconds
population_evaluation took 3.5370771884918213 seconds
population_evaluation took 3.6389212608337402 seconds
population_evaluation took 3.6909048557281494 seconds
population_evaluation took 3.1806180477142334 seconds
population_evaluation took 3.5549049377441406 seconds
population_evaluation took 2.1055877208709717 seconds
population_evaluation took 2.184887647628784 seconds
population_evaluation took 2.091494560241699 seconds
population_evaluation took 2.1946046352386475 seconds
population_evaluation took 2.339789867401123 seconds
population_evaluation took 2.1835436820983887 seconds
population_evaluation took 2.034053325653076 seconds
population_evaluation took 1.9860882759094238 seconds
population_evaluation took 2.078726053237915 seconds
population_evaluation took 1.9531056880950928 seconds
population_evaluation took 1.975074291229248 seconds
population_evaluation took 1.9527709484100342 seconds
population_evaluation took 2.030733823776245 seconds
population_evaluation took 2.0300278663635254 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 14/14 [00:00<00:00, 127.76it/s]
synth_matrix: 100%|##########| 14/14 [00:00<00:00, 126.43it/s]
r_index: 100%|##########| 5/5 [00:00<00:00, 402.37it/s]

population_evaluation took 10.445185422897339 seconds
population_evaluation took 8.547324895858765 seconds
population_evaluation took 7.844213247299194 seconds
population_evaluation took 8.70201563835144 seconds
population_evaluation took 10.28566288948059 seconds
population_evaluation took 11.110479354858398 seconds
population_evaluation took 11.444716930389404 seconds
population_evaluation took 9.342709064483643 seconds
population_evaluation took 7.40928840637207 seconds
population_evaluation took 6.926941871643066 seconds
population_evaluation took 7.183553457260132 seconds
population_evaluation took 7.5968897342681885 seconds
population_evaluation took 7.125135660171509 seconds
population_evaluation took 7.069199085235596 seconds
population_evaluation took 6.81180214881897 seconds
population_evaluation took 6.694202899932861 seconds
population_evaluation took 6.847358465194702 seconds
population_evaluation took 6.749945878982544 seconds
population_evaluation took 6.542315244674683 seconds
population_evaluation took 6.2123260498046875 seconds
population_evaluation took 6.960824966430664 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 12.387845039367676 seconds
population_evaluation took 7.691855192184448 seconds
population_evaluation took 6.1334099769592285 seconds
population_evaluation took 7.39060115814209 seconds
population_evaluation took 11.44050931930542 seconds
population_evaluation took 9.655286312103271 seconds
population_evaluation took 8.668235063552856 seconds
population_evaluation took 11.58086347579956 seconds
population_evaluation took 8.727070569992065 seconds
population_evaluation took 8.841688871383667 seconds
population_evaluation took 9.776782512664795 seconds
population_evaluation took 12.112387418746948 seconds
population_evaluation took 8.331239700317383 seconds
population_evaluation took 2.0889759063720703 seconds
population_evaluation took 2.0201337337493896 seconds
population_evaluation took 2.20892333984375 seconds
population_evaluation took 2.120208501815796 seconds
population_evaluation took 2.130063772201538 seconds
population_evaluation took 2.021176338195801 seconds
population_evaluation took 2.1375186443328857 seconds
population_evaluation took 9.149713039398193 seconds
population_evaluation took 9.323866605758667 seconds
population_evaluation took 7.9008002281188965 seconds
population_evaluation took 6.1580047607421875 seconds
population_evaluation took 7.055987596511841 seconds
population_evaluation took 2.8980624675750732 seconds
population_evaluation took 7.94670295715332 seconds
population_evaluation took 8.959368705749512 seconds
population_evaluation took 9.674385786056519 seconds
population_evaluation took 13.215008020401001 seconds
population_evaluation took 14.014302968978882 seconds
population_evaluation took 11.945284843444824 seconds
population_evaluation took 9.926838636398315 seconds
population_evaluation took 8.902198791503906 seconds
population_evaluation took 11.40017294883728 seconds
population_evaluation took 8.74001407623291 seconds
population_evaluation took 8.444437265396118 seconds
population_evaluation took 8.468060731887817 seconds
population_evaluation took 8.081859827041626 seconds
population_evaluation took 10.064392805099487 seconds
population_evaluation took 10.118581771850586 seconds
population_evaluation took 9.48656678199768 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 9.811285257339478 seconds
population_evaluation took 8.597155094146729 seconds
population_evaluation took 9.178768396377563 seconds
population_evaluation took 11.250791072845459 seconds
population_evaluation took 14.454947710037231 seconds
population_evaluation took 7.550464868545532 seconds
population_evaluation took 6.949496030807495 seconds
population_evaluation took 6.80349326133728 seconds
population_evaluation took 5.106282472610474 seconds
population_evaluation took 2.1115899085998535 seconds
population_evaluation took 2.6265108585357666 seconds
population_evaluation took 2.3539929389953613 seconds
population_evaluation took 2.4340507984161377 seconds
population_evaluation took 2.348198890686035 seconds
population_evaluation took 2.0650320053100586 seconds
population_evaluation took 2.1939265727996826 seconds
population_evaluation took 2.0041191577911377 seconds
population_evaluation took 1.8367977142333984 seconds
population_evaluation took 1.9335556030273438 seconds
population_evaluation took 6.678326368331909 seconds
population_evaluation took 6.919494867324829 seconds
population_evaluation took 7.398860931396484 seconds
population_evaluation took 7.4205238819122314 seconds
population_evaluation took 6.920286417007446 seconds
population_evaluation took 8.36118221282959 seconds
population_evaluation took 12.49599838256836 seconds
population_evaluation took 10.95316219329834 seconds
population_evaluation took 10.29812502861023 seconds
population_evaluation took 10.844047784805298 seconds
population_evaluation took 10.12543249130249 seconds
population_evaluation took 9.726152420043945 seconds
population_evaluation took 11.276102542877197 seconds
population_evaluation took 11.59470534324646 seconds
population_evaluation took 7.423352956771851 seconds
population_evaluation took 2.074531078338623 seconds
population_evaluation took 2.0064003467559814 seconds
population_evaluation took 2.8532259464263916 seconds
population_evaluation took 2.3663673400878906 seconds
population_evaluation took 3.0274932384490967 seconds
population_evaluation took 2.439225196838379 seconds
population_evaluation took 1.9350783824920654 seconds
population_evaluation took 2.835949659347534 seconds
  Tamamlandı.


============================================================
  Hedef: v buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 1.9484519958496094 seconds
population_evaluation took 1.976938009262085 seconds
population_evaluation took 1.9781975746154785 seconds
population_evaluation took 1.9573876857757568 seconds
population_evaluation took 1.9963805675506592 seconds
population_evaluation took 2.0390255451202393 seconds
population_evaluation took 1.937549352645874 seconds
population_evaluation took 1.9500277042388916 seconds
population_evaluation took 1.9691283702850342 seconds
population_evaluation took 1.9517707824707031 seconds
population_evaluation took 1.9385395050048828 seconds
population_evaluation took 1.9595162868499756 seconds
population_evaluation took 1.986100196838379 seconds
population_evaluation took 1.9415762424468994 seconds
population_evaluation took 2.0064616203308105 seconds
population_evaluation took 2.0699188709259033 seconds
population_evaluation took 2.003934383392334 seconds
population_evaluation took 1.943009614944458 seconds
population_evaluation took 1.9982640743255615 seconds
population_evaluation took 2.0315423011779785 seconds
population_evaluation took 1.9384043216705322 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 18/18 [00:00<00:00, 301.27it/s]
synth_matrix: 100%|##########| 18/18 [00:00<00:00, 720.94it/s]
r_index: 100%|##########| 11/11 [00:00<00:00, 403.32it/s]

population_evaluation took 9.646026611328125 seconds
population_evaluation took 10.92254900932312 seconds
population_evaluation took 15.173593521118164 seconds
population_evaluation took 14.061874151229858 seconds
population_evaluation took 12.059619426727295 seconds
population_evaluation took 6.881608724594116 seconds
population_evaluation took 2.007378578186035 seconds
population_evaluation took 2.380220413208008 seconds
population_evaluation took 2.752535104751587 seconds
population_evaluation took 2.8256821632385254 seconds
population_evaluation took 2.245892286300659 seconds
population_evaluation took 1.958397626876831 seconds
population_evaluation took 2.5163772106170654 seconds
population_evaluation took 3.4137609004974365 seconds
population_evaluation took 3.380099296569824 seconds
population_evaluation took 3.6343183517456055 seconds
population_evaluation took 3.383395195007324 seconds
population_evaluation took 2.851430892944336 seconds
population_evaluation took 3.145988702774048 seconds
population_evaluation took 2.5199339389801025 seconds
population_evaluation took 3.2971551418304443 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 1.9942619800567627 seconds
population_evaluation took 1.9303059577941895 seconds
population_evaluation took 1.9649229049682617 seconds
population_evaluation took 1.9737310409545898 seconds
population_evaluation took 6.8184332847595215 seconds
population_evaluation took 14.657405138015747 seconds
population_evaluation took 13.129035949707031 seconds
population_evaluation took 11.648690700531006 seconds
population_evaluation took 11.291823863983154 seconds
population_evaluation took 10.860060691833496 seconds
population_evaluation took 8.520806789398193 seconds
population_evaluation took 8.782602071762085 seconds
population_evaluation took 8.899636507034302 seconds
population_evaluation took 14.39020848274231 seconds
population_evaluation took 11.719931840896606 seconds
population_evaluation took 11.338810205459595 seconds
population_evaluation took 10.42304539680481 seconds
population_evaluation took 10.764600992202759 seconds
population_evaluation took 9.53406286239624 seconds
population_evaluation took 9.062695980072021 seconds
population_evaluation took 9.964003324508667 seconds
population_evaluation took 10.28657341003418 seconds
population_evaluation took 10.709524154663086 seconds
population_evaluation took 8.70819354057312 seconds
population_evaluation took 9.329772710800171 seconds
population_evaluation took 12.290390968322754 seconds
population_evaluation took 11.935747385025024 seconds
population_evaluation took 10.10216736793518 seconds
population_evaluation took 11.230193614959717 seconds
population_evaluation took 10.455971717834473 seconds
population_evaluation took 9.842784404754639 seconds
population_evaluation took 9.946036577224731 seconds
population_evaluation took 10.678796291351318 seconds
population_evaluation took 10.240690469741821 seconds
population_evaluation took 12.48634648323059 seconds
population_evaluation took 13.327452421188354 seconds
population_evaluation took 7.6503050327301025 seconds
population_evaluation took 2.017289876937866 seconds
population_evaluation took 1.9847900867462158 seconds
population_evaluation took 2.1204800605773926 seconds
population_evaluation took 1.9587745666503906 seconds
population_evaluation took 6.974406957626343 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 1.991506814956665 seconds
population_evaluation took 1.9229416847229004 seconds
population_evaluation took 1.9323508739471436 seconds
population_evaluation took 1.9430298805236816 seconds
population_evaluation took 1.9433050155639648 seconds
population_evaluation took 1.9101715087890625 seconds
population_evaluation took 1.9737904071807861 seconds
population_evaluation took 1.9582090377807617 seconds
population_evaluation took 1.9398298263549805 seconds
population_evaluation took 2.0204291343688965 seconds
population_evaluation took 1.9271705150604248 seconds
population_evaluation took 1.9436354637145996 seconds
population_evaluation took 1.9454452991485596 seconds
population_evaluation took 1.9105229377746582 seconds
population_evaluation took 1.9088435173034668 seconds
population_evaluation took 1.9248476028442383 seconds
population_evaluation took 2.394432544708252 seconds
population_evaluation took 1.9016809463500977 seconds
population_evaluation took 1.941004753112793 seconds
population_evaluation took 1.8887851238250732 seconds
population_evaluation took 1.883176565170288 seconds
population_evaluation took 2.173835039138794 seconds
population_evaluation took 1.922363042831421 seconds
population_evaluation took 1.979564905166626 seconds
population_evaluation took 1.9255702495574951 seconds
population_evaluation took 1.9529566764831543 seconds
population_evaluation took 1.919283390045166 seconds
population_evaluation took 1.9165740013122559 seconds
population_evaluation took 1.9571504592895508 seconds
population_evaluation took 1.9897398948669434 seconds
population_evaluation took 2.070462226867676 seconds
population_evaluation took 2.0561106204986572 seconds
population_evaluation took 2.1421115398406982 seconds
population_evaluation took 2.000375270843506 seconds
population_evaluation took 1.947875738143921 seconds
population_evaluation took 2.1528337001800537 seconds
population_evaluation took 1.9493379592895508 seconds
population_evaluation took 1.908130407333374 seconds
population_evaluation took 2.031735420227051 seconds
population_evaluation took 1.9001796245574951 seconds
population_evaluation took 1.9374175071716309 seconds
population_evaluation took 7.64031982421875 seconds
  Tamamlandı.


============================================================
  Hedef: h sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 1.8961303234100342 seconds
population_evaluation took 1.7103235721588135 seconds
population_evaluation took 1.94608736038208 seconds
population_evaluation took 1.8853998184204102 seconds
population_evaluation took 1.7532885074615479 seconds
population_evaluation took 1.8233985900878906 seconds
population_evaluation took 1.852358341217041 seconds
population_evaluation took 1.7627737522125244 seconds
population_evaluation took 1.835028886795044 seconds
population_evaluation took 1.8414549827575684 seconds
population_evaluation took 1.979419469833374 seconds
population_evaluation took 1.8894116878509521 seconds
population_evaluation took 1.9501192569732666 seconds
population_evaluation took 2.1667590141296387 seconds
population_evaluation took 2.053325891494751 seconds
population_evaluation took 2.044772148132324 seconds
population_evaluation took 5.051110506057739 seconds
population_evaluation took 7.722140073776245 seconds
population_evaluation took 1.9590420722961426 seconds
population_evaluation took 2.115372896194458 seconds
population_evaluation took 1.7553739547729492 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 24/24 [00:00<00:00, 513.83it/s]
synth_matrix: 100%|##########| 24/24 [00:00<00:00, 1275.33it/s]

population_evaluation took 2.0614430904388428 seconds
population_evaluation took 2.0250844955444336 seconds
population_evaluation took 2.007805585861206 seconds
population_evaluation took 2.048295259475708 seconds
population_evaluation took 2.0803956985473633 seconds
population_evaluation took 1.9889633655548096 seconds
population_evaluation took 1.977332592010498 seconds
population_evaluation took 1.9437518119812012 seconds
population_evaluation took 1.9513463973999023 seconds
population_evaluation took 1.897432565689087 seconds
population_evaluation took 1.9087746143341064 seconds
population_evaluation took 2.0561230182647705 seconds
population_evaluation took 2.0328609943389893 seconds
population_evaluation took 1.9258742332458496 seconds
population_evaluation took 1.9077949523925781 seconds
population_evaluation took 2.006420850753784 seconds
population_evaluation took 2.0752899646759033 seconds
population_evaluation took 1.9762423038482666 seconds
population_evaluation took 2.0030555725097656 seconds
population_evaluation took 1.9474287033081055 seconds
population_evaluation took 1.921799898147583 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 2.180013656616211 seconds
population_evaluation took 2.121131181716919 seconds
population_evaluation took 3.1181910037994385 seconds
population_evaluation took 2.161411762237549 seconds
population_evaluation took 2.1214046478271484 seconds
population_evaluation took 2.1186633110046387 seconds
population_evaluation took 2.122485637664795 seconds
population_evaluation took 2.166006326675415 seconds
population_evaluation took 2.0126664638519287 seconds
population_evaluation took 2.0426390171051025 seconds
population_evaluation took 2.104217529296875 seconds
population_evaluation took 2.076183557510376 seconds
population_evaluation took 2.09063720703125 seconds
population_evaluation took 2.0554802417755127 seconds
population_evaluation took 2.1721904277801514 seconds
population_evaluation took 2.0344583988189697 seconds
population_evaluation took 2.0627565383911133 seconds
population_evaluation took 2.032282829284668 seconds
population_evaluation took 1.750502109527588 seconds
population_evaluation took 1.9566588401794434 seconds
population_evaluation took 2.075923204421997 seconds
population_evaluation took 4.7403388023376465 seconds
population_evaluation took 8.603671312332153 seconds
population_evaluation took 2.0352437496185303 seconds
population_evaluation took 6.567799091339111 seconds
population_evaluation took 13.633985042572021 seconds
population_evaluation took 13.315839290618896 seconds
population_evaluation took 11.447363138198853 seconds
population_evaluation took 12.285861492156982 seconds
population_evaluation took 11.769303560256958 seconds
population_evaluation took 14.866662979125977 seconds
population_evaluation took 11.89389705657959 seconds
population_evaluation took 14.868475198745728 seconds
population_evaluation took 12.982849597930908 seconds
population_evaluation took 10.969943284988403 seconds
population_evaluation took 16.22774624824524 seconds
population_evaluation took 15.293166399002075 seconds
population_evaluation took 4.610372543334961 seconds
population_evaluation took 2.033052682876587 seconds
population_evaluation took 2.149729013442993 seconds
population_evaluation took 2.1335368156433105 seconds
population_evaluation took 2.2274911403656006 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 1.9779815673828125 seconds
population_evaluation took 1.9755620956420898 seconds
population_evaluation took 2.0360782146453857 seconds
population_evaluation took 2.0384647846221924 seconds
population_evaluation took 2.7412431240081787 seconds
population_evaluation took 2.193462371826172 seconds
population_evaluation took 2.321765899658203 seconds
population_evaluation took 2.1244401931762695 seconds
population_evaluation took 2.4906575679779053 seconds
population_evaluation took 2.5107553005218506 seconds
population_evaluation took 2.6423428058624268 seconds
population_evaluation took 1.966059923171997 seconds
population_evaluation took 2.323992967605591 seconds
population_evaluation took 2.3803465366363525 seconds
population_evaluation took 3.142035722732544 seconds
population_evaluation took 2.236159324645996 seconds
population_evaluation took 2.2022111415863037 seconds
population_evaluation took 1.9830529689788818 seconds
population_evaluation took 2.0909054279327393 seconds
population_evaluation took 1.974910020828247 seconds
population_evaluation took 2.504784345626831 seconds
population_evaluation took 2.3622429370880127 seconds
population_evaluation took 2.331467628479004 seconds
population_evaluation took 2.0669198036193848 seconds
population_evaluation took 1.936471939086914 seconds
population_evaluation took 2.034214496612549 seconds
population_evaluation took 4.106017112731934 seconds
population_evaluation took 8.877544641494751 seconds
population_evaluation took 2.088988780975342 seconds
population_evaluation took 2.105215072631836 seconds
population_evaluation took 2.093135118484497 seconds
population_evaluation took 1.9212417602539062 seconds
population_evaluation took 2.010664939880371 seconds
population_evaluation took 2.0105135440826416 seconds
population_evaluation took 2.032224178314209 seconds
population_evaluation took 2.1195383071899414 seconds
population_evaluation took 2.4200727939605713 seconds
population_evaluation took 2.1567940711975098 seconds
population_evaluation took 2.1339938640594482 seconds
population_evaluation took 2.2483253479003906 seconds
population_evaluation took 2.11580491065979 seconds
population_evaluation took 2.166506767272949 seconds
  Tamamlandı.


============================================================
  Hedef: h buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 15.197946786880493 seconds
population_evaluation took 8.948378562927246 seconds
population_evaluation took 2.1600630283355713 seconds
population_evaluation took 2.0697431564331055 seconds
population_evaluation took 2.1751019954681396 seconds
population_evaluation took 2.1406631469726562 seconds
population_evaluation took 2.1727471351623535 seconds
population_evaluation took 2.096616744995117 seconds
population_evaluation took 1.9926247596740723 seconds
population_evaluation took 2.005429744720459 seconds
population_evaluation took 2.002864360809326 seconds
population_evaluation took 2.1124989986419678 seconds
population_evaluation took 2.0768463611602783 seconds
population_evaluation took 2.159867286682129 seconds
population_evaluation took 2.137524127960205 seconds
population_evaluation took 2.138352870941162 seconds
population_evaluation took 2.2147672176361084 seconds
population_evaluation took 2.0134379863739014 seconds
population_evaluation took 2.1124229431152344 seconds
population_evaluation took 2.050175905227661 seconds
population_evaluation took 2.161398410797119 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 28/28 [00:00<00:00, 110.07it/s]
r_index: 100%|##########| 19/19 [00:00<00:00, 644.17it/s]

population_evaluation took 8.721091508865356 seconds
population_evaluation took 12.212337732315063 seconds
population_evaluation took 6.016903638839722 seconds
population_evaluation took 2.0658481121063232 seconds
population_evaluation took 2.232199192047119 seconds
population_evaluation took 2.009509801864624 seconds
population_evaluation took 2.13136887550354 seconds
population_evaluation took 2.1933655738830566 seconds
population_evaluation took 2.10412859916687 seconds
population_evaluation took 2.185792922973633 seconds
population_evaluation took 2.080188512802124 seconds
population_evaluation took 11.352880239486694 seconds
population_evaluation took 2.3951215744018555 seconds
population_evaluation took 2.0218985080718994 seconds
population_evaluation took 2.587240695953369 seconds
population_evaluation took 2.0023674964904785 seconds
population_evaluation took 4.7351953983306885 seconds
population_evaluation took 4.389004230499268 seconds
population_evaluation took 2.1005632877349854 seconds
population_evaluation took 6.839061975479126 seconds
population_evaluation took 2.0853471755981445 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 3.5239741802215576 seconds
population_evaluation took 3.658228635787964 seconds
population_evaluation took 3.4712114334106445 seconds
population_evaluation took 4.91255521774292 seconds
population_evaluation took 2.125082015991211 seconds
population_evaluation took 7.35870885848999 seconds
population_evaluation took 2.8005518913269043 seconds
population_evaluation took 4.249165773391724 seconds
population_evaluation took 2.0741639137268066 seconds
population_evaluation took 3.3273589611053467 seconds
population_evaluation took 4.707125425338745 seconds
population_evaluation took 5.541643142700195 seconds
population_evaluation took 2.2147514820098877 seconds
population_evaluation took 5.18049168586731 seconds
population_evaluation took 2.4370477199554443 seconds
population_evaluation took 4.2474071979522705 seconds
population_evaluation took 3.8231475353240967 seconds
population_evaluation took 6.08025598526001 seconds
population_evaluation took 2.1312053203582764 seconds
population_evaluation took 3.778949022293091 seconds
population_evaluation took 2.815983772277832 seconds
population_evaluation took 6.2322609424591064 seconds
population_evaluation took 3.692145586013794 seconds
population_evaluation took 3.139519691467285 seconds
population_evaluation took 4.588685989379883 seconds
population_evaluation took 2.1152515411376953 seconds
population_evaluation took 2.1843159198760986 seconds
population_evaluation took 2.1160550117492676 seconds
population_evaluation took 2.182572603225708 seconds
population_evaluation took 2.160327434539795 seconds
population_evaluation took 2.2273237705230713 seconds
population_evaluation took 2.0260612964630127 seconds
population_evaluation took 2.062589645385742 seconds
population_evaluation took 2.0483474731445312 seconds
population_evaluation took 2.1197566986083984 seconds
population_evaluation took 2.0480592250823975 seconds
population_evaluation took 2.022679090499878 seconds
population_evaluation took 2.0479748249053955 seconds
population_evaluation took 2.0210676193237305 seconds
population_evaluation took 1.9373841285705566 seconds
population_evaluation took 2.01106595993042 seconds
population_evaluation took 2.0484185218811035 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 2.4721555709838867 seconds
population_evaluation took 2.1199066638946533 seconds
population_evaluation took 2.1819586753845215 seconds
population_evaluation took 2.447596788406372 seconds
population_evaluation took 2.6302995681762695 seconds
population_evaluation took 2.776108741760254 seconds
population_evaluation took 2.264895439147949 seconds
population_evaluation took 2.083225727081299 seconds
population_evaluation took 2.235949754714966 seconds
population_evaluation took 2.0419106483459473 seconds
population_evaluation took 2.9213814735412598 seconds
population_evaluation took 3.085172176361084 seconds
population_evaluation took 2.3869519233703613 seconds
population_evaluation took 2.1955947875976562 seconds
population_evaluation took 2.2501914501190186 seconds
population_evaluation took 2.1081783771514893 seconds
population_evaluation took 2.13423228263855 seconds
population_evaluation took 2.141263484954834 seconds
population_evaluation took 2.1406290531158447 seconds
population_evaluation took 2.1560490131378174 seconds
population_evaluation took 2.168771743774414 seconds
population_evaluation took 2.1384706497192383 seconds
population_evaluation took 2.145517349243164 seconds
population_evaluation took 2.1598269939422607 seconds
population_evaluation took 2.084012746810913 seconds
population_evaluation took 3.2509849071502686 seconds
population_evaluation took 5.120832204818726 seconds
population_evaluation took 2.0231950283050537 seconds
population_evaluation took 2.0318522453308105 seconds
population_evaluation took 1.979902744293213 seconds
population_evaluation took 2.0046226978302 seconds
population_evaluation took 1.9967808723449707 seconds
population_evaluation took 2.0987422466278076 seconds
population_evaluation took 2.012831926345825 seconds
population_evaluation took 2.000828742980957 seconds
population_evaluation took 2.062530755996704 seconds
population_evaluation took 2.2040047645568848 seconds
population_evaluation took 2.156575918197632 seconds
population_evaluation took 2.0765857696533203 seconds
population_evaluation took 2.4234976768493652 seconds
population_evaluation took 2.8015379905700684 seconds
population_evaluation took 2.2604990005493164 seconds
  Tamamlandı.


============================================================
  Hedef: s sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 2.204458475112915 seconds
population_evaluation took 2.005174160003662 seconds
population_evaluation took 2.047840118408203 seconds
population_evaluation took 2.1526131629943848 seconds
population_evaluation took 2.110119104385376 seconds
population_evaluation took 2.0008275508880615 seconds
population_evaluation took 2.0132083892822266 seconds
population_evaluation took 2.054438829421997 seconds
population_evaluation took 1.9904422760009766 seconds
population_evaluation took 2.048938512802124 seconds
population_evaluation took 2.0615768432617188 seconds
population_evaluation took 2.0102620124816895 seconds
population_evaluation took 2.1597650051116943 seconds
population_evaluation took 2.1570916175842285 seconds
population_evaluation took 2.274991035461426 seconds
population_evaluation took 2.153135299682617 seconds
population_evaluation took 2.1588311195373535 seconds
population_evaluation took 2.212254047393799 seconds
population_evaluation took 2.1086409091949463 seconds
population_evaluation took 1.9648890495300293 seconds
population_evaluation took 2.2384097576141357 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 27/27 [00:00<00:00, 464.13it/s]
r_index: 100%|##########| 4/4 [00:00<00:00, 1033.59it/s]
dist_matrix: 100%|##########| 22/22 [00:00<00:00, 1364.26it/s]
r_index: 100%|##########| 10/10 [00:00<00:00, 1375.86it/s]

population_evaluation took 2.057922124862671 seconds
population_evaluation took 2.0716419219970703 seconds
population_evaluation took 2.148937940597534 seconds
population_evaluation took 2.1114912033081055 seconds
population_evaluation took 2.1842868328094482 seconds
population_evaluation took 2.168062210083008 seconds
population_evaluation took 2.177525043487549 seconds
population_evaluation took 2.1776621341705322 seconds
population_evaluation took 2.1215178966522217 seconds
population_evaluation took 2.2276575565338135 seconds
population_evaluation took 1.8646907806396484 seconds
population_evaluation took 2.034296989440918 seconds
population_evaluation took 2.072934865951538 seconds
population_evaluation took 2.1113619804382324 seconds
population_evaluation took 2.159773349761963 seconds
population_evaluation took 2.133406400680542 seconds
population_evaluation took 2.118065357208252 seconds
population_evaluation took 2.175489902496338 seconds
population_evaluation took 2.1046347618103027 seconds
population_evaluation took 1.9545104503631592 seconds
population_evaluation took 1.9386670589447021 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 2.220853805541992 seconds
population_evaluation took 3.4621682167053223 seconds
population_evaluation took 2.0400962829589844 seconds
population_evaluation took 2.010357141494751 seconds
population_evaluation took 2.1702024936676025 seconds
population_evaluation took 2.2341666221618652 seconds
population_evaluation took 2.416703224182129 seconds
population_evaluation took 2.256472587585449 seconds
population_evaluation took 2.194021701812744 seconds
population_evaluation took 1.9945712089538574 seconds
population_evaluation took 2.0300683975219727 seconds
population_evaluation took 2.002812623977661 seconds
population_evaluation took 1.9973273277282715 seconds
population_evaluation took 2.017028570175171 seconds
population_evaluation took 2.1599557399749756 seconds
population_evaluation took 2.1215708255767822 seconds
population_evaluation took 2.312950849533081 seconds
population_evaluation took 2.5703959465026855 seconds
population_evaluation took 2.2838478088378906 seconds
population_evaluation took 2.263622760772705 seconds
population_evaluation took 2.229444742202759 seconds
population_evaluation took 2.281203269958496 seconds
population_evaluation took 2.3236935138702393 seconds
population_evaluation took 2.2927958965301514 seconds
population_evaluation took 2.159428834915161 seconds
population_evaluation took 2.1781861782073975 seconds
population_evaluation took 2.3114206790924072 seconds
population_evaluation took 2.2715160846710205 seconds
population_evaluation took 2.319614887237549 seconds
population_evaluation took 2.316953182220459 seconds
population_evaluation took 2.152757167816162 seconds
population_evaluation took 2.1878128051757812 seconds
population_evaluation took 2.283202886581421 seconds
population_evaluation took 2.1389007568359375 seconds
population_evaluation took 2.2988078594207764 seconds
population_evaluation took 2.302557945251465 seconds
population_evaluation took 2.2540829181671143 seconds
population_evaluation took 2.2588953971862793 seconds
population_evaluation took 2.1778597831726074 seconds
population_evaluation took 2.286848306655884 seconds
population_evaluation took 2.229736566543579 seconds
population_evaluation took 2.277653932571411 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 2.3148672580718994 seconds
population_evaluation took 2.067599296569824 seconds
population_evaluation took 2.4315476417541504 seconds
population_evaluation took 2.2545278072357178 seconds
population_evaluation took 2.3161988258361816 seconds
population_evaluation took 1.9766192436218262 seconds
population_evaluation took 2.566584825515747 seconds
population_evaluation took 2.1085898876190186 seconds
population_evaluation took 2.2734806537628174 seconds
population_evaluation took 2.0230119228363037 seconds
population_evaluation took 2.440221071243286 seconds
population_evaluation took 2.297234296798706 seconds
population_evaluation took 1.9123742580413818 seconds
population_evaluation took 2.185077428817749 seconds
population_evaluation took 1.9919848442077637 seconds
population_evaluation took 1.791321039199829 seconds
population_evaluation took 1.8693902492523193 seconds
population_evaluation took 3.5866916179656982 seconds
population_evaluation took 9.84786581993103 seconds
population_evaluation took 8.019219636917114 seconds
population_evaluation took 8.498777627944946 seconds
population_evaluation took 10.088274955749512 seconds
population_evaluation took 15.385488986968994 seconds
population_evaluation took 14.037076950073242 seconds
population_evaluation took 14.835707426071167 seconds
population_evaluation took 11.762516260147095 seconds
population_evaluation took 11.27104902267456 seconds
population_evaluation took 14.551895380020142 seconds
population_evaluation took 11.929795742034912 seconds
population_evaluation took 11.547377347946167 seconds
population_evaluation took 14.751897096633911 seconds
population_evaluation took 14.124770879745483 seconds
population_evaluation took 15.054101943969727 seconds
population_evaluation took 11.04104232788086 seconds
population_evaluation took 9.753269672393799 seconds
population_evaluation took 10.44914197921753 seconds
population_evaluation took 7.338098526000977 seconds
population_evaluation took 10.727255821228027 seconds
population_evaluation took 8.44521951675415 seconds
population_evaluation took 9.373134851455688 seconds
population_evaluation took 12.790456295013428 seconds
population_evaluation took 1.9063501358032227 seconds
  Tamamlandı.


============================================================
  Hedef: s buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 2.0991086959838867 seconds
population_evaluation took 2.1595420837402344 seconds
population_evaluation took 2.0350632667541504 seconds
population_evaluation took 2.139061450958252 seconds
population_evaluation took 2.14318585395813 seconds
population_evaluation took 2.0162274837493896 seconds
population_evaluation took 2.074692726135254 seconds
population_evaluation took 2.2431163787841797 seconds
population_evaluation took 2.1738297939300537 seconds
population_evaluation took 2.1679062843322754 seconds
population_evaluation took 2.206437110900879 seconds
population_evaluation took 2.203505516052246 seconds
population_evaluation took 6.403284788131714 seconds
population_evaluation took 10.562141418457031 seconds
population_evaluation took 8.668788433074951 seconds
population_evaluation took 9.632266521453857 seconds
population_evaluation took 10.287110090255737 seconds
population_evaluation took 9.282491683959961 seconds
population_evaluation took 9.916964769363403 seconds
population_evaluation took 10.262356996536255 seconds
population_evaluation took 7.260011434555054 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 5/5 [00:00<00:00, 2497.20it/s]
synth_matrix: 100%|##########| 5/5 [00:00<00:00, 256.36it/s]
r_index: 100%|##########| 2/2 [00:00<00:00, 997.93it/s]

population_evaluation took 2.2170445919036865 seconds
population_evaluation took 2.0866825580596924 seconds
population_evaluation took 2.146817922592163 seconds
population_evaluation took 2.0792064666748047 seconds
population_evaluation took 1.9992079734802246 seconds
population_evaluation took 2.0420641899108887 seconds
population_evaluation took 1.974050760269165 seconds
population_evaluation took 2.206493616104126 seconds
population_evaluation took 2.124319553375244 seconds
population_evaluation took 2.1994409561157227 seconds
population_evaluation took 2.190984010696411 seconds
population_evaluation took 2.1746599674224854 seconds
population_evaluation took 2.1734707355499268 seconds
population_evaluation took 2.1663320064544678 seconds
population_evaluation took 2.0431792736053467 seconds
population_evaluation took 2.0381271839141846 seconds
population_evaluation took 2.053549289703369 seconds
population_evaluation took 1.9979760646820068 seconds
population_evaluation took 2.1362342834472656 seconds
population_evaluation took 2.0183205604553223 seconds
population_evaluation took 7.436302900314331 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 11.648820161819458 seconds
population_evaluation took 9.104559183120728 seconds
population_evaluation took 10.473407983779907 seconds
population_evaluation took 10.24385952949524 seconds
population_evaluation took 9.620578050613403 seconds
population_evaluation took 9.405526161193848 seconds
population_evaluation took 8.834114074707031 seconds
population_evaluation took 12.221863269805908 seconds
population_evaluation took 10.485026597976685 seconds
population_evaluation took 4.425781726837158 seconds
population_evaluation took 2.2699122428894043 seconds
population_evaluation took 3.1156346797943115 seconds
population_evaluation took 5.194167375564575 seconds
population_evaluation took 2.0216500759124756 seconds
population_evaluation took 2.005194664001465 seconds
population_evaluation took 1.9944021701812744 seconds
population_evaluation took 2.0185158252716064 seconds
population_evaluation took 2.0205230712890625 seconds
population_evaluation took 2.1000332832336426 seconds
population_evaluation took 2.797853469848633 seconds
population_evaluation took 2.822880983352661 seconds
population_evaluation took 3.9394795894622803 seconds
population_evaluation took 3.073525905609131 seconds
population_evaluation took 2.3820316791534424 seconds
population_evaluation took 2.8430864810943604 seconds
population_evaluation took 2.6314828395843506 seconds
population_evaluation took 1.9901094436645508 seconds
population_evaluation took 2.221883773803711 seconds
population_evaluation took 2.0618577003479004 seconds
population_evaluation took 2.0238022804260254 seconds
population_evaluation took 1.9148383140563965 seconds
population_evaluation took 2.083442449569702 seconds
population_evaluation took 1.9330496788024902 seconds
population_evaluation took 1.9554557800292969 seconds
population_evaluation took 1.9171619415283203 seconds
population_evaluation took 1.9796547889709473 seconds
population_evaluation took 1.9193973541259766 seconds
population_evaluation took 1.9795784950256348 seconds
population_evaluation took 2.001038074493408 seconds
population_evaluation took 2.160349130630493 seconds
population_evaluation took 1.913088321685791 seconds
population_evaluation took 1.9321417808532715 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 2.1140799522399902 seconds
population_evaluation took 2.1604180335998535 seconds
population_evaluation took 2.121584892272949 seconds
population_evaluation took 2.0294997692108154 seconds
population_evaluation took 2.247105598449707 seconds
population_evaluation took 2.092073678970337 seconds
population_evaluation took 2.159701108932495 seconds
population_evaluation took 2.1751270294189453 seconds
population_evaluation took 2.1655664443969727 seconds
population_evaluation took 2.166729688644409 seconds
population_evaluation took 2.0152642726898193 seconds
population_evaluation took 1.8239381313323975 seconds
population_evaluation took 1.8867073059082031 seconds
population_evaluation took 1.9251258373260498 seconds
population_evaluation took 1.8093223571777344 seconds
population_evaluation took 1.849989891052246 seconds
population_evaluation took 1.8564302921295166 seconds
population_evaluation took 1.7869744300842285 seconds
population_evaluation took 1.8188397884368896 seconds
population_evaluation took 1.7744414806365967 seconds
population_evaluation took 1.7713510990142822 seconds
population_evaluation took 1.8477063179016113 seconds
population_evaluation took 1.9297895431518555 seconds
population_evaluation took 1.875000238418579 seconds
population_evaluation took 1.8631675243377686 seconds
population_evaluation took 1.8256897926330566 seconds
population_evaluation took 1.973808765411377 seconds
population_evaluation took 2.050856113433838 seconds
population_evaluation took 2.0562021732330322 seconds
population_evaluation took 1.9214072227478027 seconds
population_evaluation took 1.984710693359375 seconds
population_evaluation took 2.100982904434204 seconds
population_evaluation took 2.0736148357391357 seconds
population_evaluation took 2.028120279312134 seconds
population_evaluation took 2.141350746154785 seconds
population_evaluation took 2.045896291732788 seconds
population_evaluation took 1.960892915725708 seconds
population_evaluation took 2.1715967655181885 seconds
population_evaluation took 1.8219244480133057 seconds
population_evaluation took 1.9299635887145996 seconds
population_evaluation took 1.7603960037231445 seconds
population_evaluation took 1.7732789516448975 seconds
  Tamamlandı.

### 3.1 Doymuş Buhar — Sonuç Tablosu

In [6]:
df_doymus_results = build_results_table(doymus_results)
df_doymus_results

               Hedef        Senaryo Algoritma  Train_R2  Test_R2  Train_RMSE  Test_RMSE  Train_MAPE  Test_MAPE
0           P(çıktı)           Base  AdaBoost    0.9964   0.9959      0.0598     0.0653      0.0706     0.1070
1           P(çıktı)           Base  CatBoost    0.9998   0.9991      0.0123     0.0300      0.0484     0.0844
2           P(çıktı)           Base      DART    0.9387   0.9541      0.2475     0.2177      0.2042     0.1343
3           P(çıktı)           Base        EF    1.0000   1.0000      0.0000     0.0054      0.0000     0.0077
4           P(çıktı)           Base        ET    1.0000   1.0000      0.0000     0.0035      0.0000     0.0034
..               ...            ...       ...       ...      ...         ...        ...         ...        ...
303  s buhar (çıktı)  SMOGN+STGP-EF        GP    0.9705   0.6063      0.3162     0.4783      0.7271     1.1128
304  s buhar (çıktı)  SMOGN+STGP-EF       KNN    0.9972   0.8995      0.0979     0.2417      0.2470     0.6403
305  s buhar (çıktı)  SMOGN+STGP-EF  LightGBM    0.9948   0.8822      0.1332     0.2617      0.4324     0.6919
306  s buhar (çıktı)  SMOGN+STGP-EF        RF    0.9998   0.8965      0.0249     0.2453      0.0397     0.3615
307  s buhar (çıktı)  SMOGN+STGP-EF   XGBoost    1.0000   0.9164      0.0018     0.2204      0.0021     0.5231

[308 rows x 9 columns]

### 3.2 Doymuş Buhar — Senaryo Karşılaştırması

In [7]:
compare_scenarios(df_doymus_results)

Senaryo                    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Hedef          Algoritma
P(çıktı)       AdaBoost  0.9959 0.9967   0.9939         0.9975
               CatBoost  0.9991 0.9989   0.9994         0.9989
               DART      0.9541 0.9145   0.9570         0.9147
               EF        1.0000 0.9998   1.0000         0.9998
               ET        1.0000 0.9998   1.0000         0.9998
...                         ...    ...      ...            ...
v sıvı (çıktı) GP        0.9595 0.9668   0.9565         0.9630
               KNN       0.9992 0.9964   0.9991         0.9950
               LightGBM  0.9346 0.8852   0.9710         0.9362
               RF        0.9994 0.9980   0.9993         0.9973
               XGBoost   0.9966 0.9911   0.9965         0.9890

[77 rows x 4 columns]

### 3.3 Doymuş Buhar — Hedef Bazlı Detay

Her bir hedef değişken için detaylı pivot tablo;

In [8]:
target_summary(df_doymus_results, 'P(çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9959 0.9967   0.9939         0.9975
CatBoost  0.9991 0.9989   0.9994         0.9989
DART      0.9541 0.9145   0.9570         0.9147
EF        1.0000 0.9998   1.0000         0.9998
ET        1.0000 0.9998   1.0000         0.9998
GBDT      0.9991 0.9989   0.9992         0.9989
GP        0.9702 0.9253   0.9802         0.9788
KNN       0.9998 0.9987   0.9998         0.9969
LightGBM  0.9651 0.9166   0.9664         0.9166
RF        0.9997 0.9993   0.9997         0.9991
XGBoost   0.9982 0.9974   0.9982         0.9974

In [9]:
target_summary(df_doymus_results, 'v sıvı (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9943 0.9790   0.9967         0.9870
CatBoost  0.9981 0.9976   0.9987         0.9974
DART      0.9252 0.8980   0.9392         0.9384
EF        1.0000 0.9995   1.0000         0.9995
ET        1.0000 0.9997   1.0000         0.9996
GBDT      0.9980 0.9967   0.9986         0.9971
GP        0.9595 0.9668   0.9565         0.9630
KNN       0.9992 0.9964   0.9991         0.9950
LightGBM  0.9346 0.8852   0.9710         0.9362
RF        0.9994 0.9980   0.9993         0.9973
XGBoost   0.9966 0.9911   0.9965         0.9890

In [10]:
target_summary(df_doymus_results, 'v buhar (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9875 0.9917   0.9883         0.9927
CatBoost  0.9966 0.9972   0.9975         0.9977
DART      0.7834 0.9502   0.8682         0.9533
EF        0.9987 0.9988   0.9990         0.9985
ET        0.9991 0.9988   0.9992         0.9988
GBDT      0.9959 0.9967   0.9975         0.9968
GP        0.9758 0.9500   0.9900         0.9887
KNN       0.9915 0.9922   0.9912         0.9934
LightGBM  0.7845 0.9641   0.9146         0.9671
RF        0.9965 0.9970   0.9967         0.9968
XGBoost   0.9929 0.9918   0.9934         0.9918

In [11]:
target_summary(df_doymus_results, 'h sıvı (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9989 0.9972   0.9988         0.9964
CatBoost  0.9993 0.9984   0.9994         0.9974
DART      0.9667 0.7640   0.9699         0.7656
EF        0.9999 0.9995   1.0000         0.9995
ET        1.0000 0.9997   1.0000         0.9997
GBDT      0.9993 0.9980   0.9995         0.9982
GP        0.9955 0.9955   0.9955         0.9955
KNN       0.9997 0.9969   0.9995         0.9968
LightGBM  0.9753 0.7623   0.9826         0.7640
RF        0.9997 0.9990   0.9998         0.9989
XGBoost   0.9986 0.9948   0.9983         0.9936

In [12]:
target_summary(df_doymus_results, 'h buhar (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9948 0.9896   0.9968         0.9922
CatBoost  0.9991 0.9960   0.9994         0.9972
DART      0.9639 0.7182   0.9703         0.7098
EF        0.9999 0.9994   0.9999         0.9992
ET        1.0000 0.9994   1.0000         0.9996
GBDT      0.9991 0.9951   0.9994         0.9965
GP        0.9573 0.9866   0.9917         0.9367
KNN       0.9994 0.9944   0.9991         0.9940
LightGBM  0.9709 0.7142   0.9782         0.7037
RF        0.9996 0.9969   0.9996         0.9975
XGBoost   0.9985 0.9870   0.9982         0.9868

In [13]:
target_summary(df_doymus_results, 's sıvı (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9991 0.9835   0.9990         0.9871
CatBoost  0.9991 0.9963   0.9995         0.9974
DART      0.9655 0.9503   0.9696         0.9545
EF        1.0000 0.9997   0.9999         0.9982
ET        1.0000 0.9999   1.0000         0.9999
GBDT      0.9993 0.9936   0.9995         0.9951
GP        0.9998 0.9998   0.9998         0.9998
KNN       0.9996 0.9943   0.9995         0.9942
LightGBM  0.9734 0.9566   0.9779         0.9651
RF        0.9997 0.9950   0.9997         0.9951
XGBoost   0.9986 0.9725   0.9986         0.9725

In [14]:
target_summary(df_doymus_results, 's buhar (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9108 0.8746   0.9616         0.6942
CatBoost  0.9829 0.9803   0.9905         0.9307
DART      0.4696 0.7338   0.8764         0.8710
EF        0.9995 0.9982   0.9947         0.9301
ET        0.9997 0.9987   0.9891         0.8290
GBDT      0.9808 0.9721   0.9857         0.9293
GP        0.3077 0.5129   0.9193         0.6063
KNN       0.9886 0.9369   0.9818         0.8995
LightGBM  0.4773 0.8042   0.8366         0.8822
RF        0.9939 0.9640   0.9935         0.8965
XGBoost   0.9708 0.8809   0.9715         0.9164

---
## 4. Kızgın Buhar — Eğitim

**Girdiler:** T (girdi), P (girdi)  
**Çıktılar (her biri ayrı ayrı):** v, h, s

In [15]:
kizgin_results = run_kizgin_analysis(df_kizgin)

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  KIZGIN BUHAR ANALİZİ
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

============================================================
  Hedef: v (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 2.8196961879730225 seconds
population_evaluation took 2.789928913116455 seconds
population_evaluation took 2.776762008666992 seconds
population_evaluation took 2.7494142055511475 seconds
population_evaluation took 2.736222505569458 seconds
population_evaluation took 2.6730029582977295 seconds
population_evaluation took 2.6133549213409424 seconds
population_evaluation took 2.6890628337860107 seconds
population_evaluation took 2.609168529510498 seconds
population_evaluation took 2.7154383659362793 seconds
population_evaluation took 2.522637367248535 seconds
population_evaluation took 2.519247531890869 seconds
population_evaluation took 2.4882960319519043 seconds
population_evaluation took 2.499302387237549 seconds
population_evaluation took 2.5540401935577393 seconds
population_evaluation took 2.5138344764709473 seconds
population_evaluation took 2.5439186096191406 seconds
population_evaluation took 2.4372498989105225 seconds
population_evaluation took 2.592397451400757 seconds
population_evaluation took 2.672883987426758 seconds
population_evaluation took 2.6608002185821533 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 74/74 [00:00<00:00, 291.80it/s]
synth_matrix: 100%|##########| 74/74 [00:00<00:00, 2220.18it/s]
r_index: 100%|##########| 54/54 [00:00<00:00, 2559.24it/s]

population_evaluation took 2.380265712738037 seconds
population_evaluation took 2.4668264389038086 seconds
population_evaluation took 2.4600064754486084 seconds
population_evaluation took 2.4024739265441895 seconds
population_evaluation took 2.4972727298736572 seconds
population_evaluation took 2.4902520179748535 seconds
population_evaluation took 2.4975452423095703 seconds
population_evaluation took 2.4595465660095215 seconds
population_evaluation took 2.3377773761749268 seconds
population_evaluation took 2.2169597148895264 seconds
population_evaluation took 2.2698819637298584 seconds
population_evaluation took 2.264248847961426 seconds
population_evaluation took 2.296003580093384 seconds
population_evaluation took 2.2469003200531006 seconds
population_evaluation took 2.2653870582580566 seconds
population_evaluation took 2.242122173309326 seconds
population_evaluation took 2.3294548988342285 seconds
population_evaluation took 2.240751266479492 seconds
population_evaluation took 2.319715738296509 seconds
population_evaluation took 2.261414051055908 seconds
population_evaluation took 2.7972254753112793 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 2.54150652885437 seconds
population_evaluation took 2.529555082321167 seconds
population_evaluation took 2.533216714859009 seconds
population_evaluation took 2.5744946002960205 seconds
population_evaluation took 2.5139455795288086 seconds
population_evaluation took 2.449472427368164 seconds
population_evaluation took 2.549907922744751 seconds
population_evaluation took 2.553835868835449 seconds
population_evaluation took 2.470245361328125 seconds
population_evaluation took 2.5167934894561768 seconds
population_evaluation took 2.54248046875 seconds
population_evaluation took 2.511754035949707 seconds
population_evaluation took 2.4907491207122803 seconds
population_evaluation took 2.532616138458252 seconds
population_evaluation took 2.7241904735565186 seconds
population_evaluation took 2.6528687477111816 seconds
population_evaluation took 2.651432752609253 seconds
population_evaluation took 2.676668882369995 seconds
population_evaluation took 2.6953680515289307 seconds
population_evaluation took 2.6663074493408203 seconds
population_evaluation took 2.6033761501312256 seconds
population_evaluation took 2.3040711879730225 seconds
population_evaluation took 2.3611037731170654 seconds
population_evaluation took 2.42071270942688 seconds
population_evaluation took 2.431159257888794 seconds
population_evaluation took 2.4434046745300293 seconds
population_evaluation took 2.3792009353637695 seconds
population_evaluation took 2.4556713104248047 seconds
population_evaluation took 2.3994967937469482 seconds
population_evaluation took 2.421527862548828 seconds
population_evaluation took 2.418262481689453 seconds
population_evaluation took 2.440460681915283 seconds
population_evaluation took 2.4234352111816406 seconds
population_evaluation took 2.447422742843628 seconds
population_evaluation took 2.4198102951049805 seconds
population_evaluation took 2.433544158935547 seconds
population_evaluation took 2.3980326652526855 seconds
population_evaluation took 2.393667221069336 seconds
population_evaluation took 2.4191670417785645 seconds
population_evaluation took 2.394296407699585 seconds
population_evaluation took 2.3849539756774902 seconds
population_evaluation took 2.386542320251465 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 2.4722790718078613 seconds
population_evaluation took 2.3649940490722656 seconds
population_evaluation took 2.3150172233581543 seconds
population_evaluation took 2.3486077785491943 seconds
population_evaluation took 2.3084025382995605 seconds
population_evaluation took 2.3105666637420654 seconds
population_evaluation took 2.3044681549072266 seconds
population_evaluation took 2.3315725326538086 seconds
population_evaluation took 2.3133997917175293 seconds
population_evaluation took 2.3021183013916016 seconds
population_evaluation took 2.3598780632019043 seconds
population_evaluation took 2.317795515060425 seconds
population_evaluation took 2.2900707721710205 seconds
population_evaluation took 2.291564702987671 seconds
population_evaluation took 2.2679805755615234 seconds
population_evaluation took 2.304591655731201 seconds
population_evaluation took 2.2291617393493652 seconds
population_evaluation took 2.27693510055542 seconds
population_evaluation took 2.3075337409973145 seconds
population_evaluation took 2.304863214492798 seconds
population_evaluation took 2.241149663925171 seconds
population_evaluation took 2.2971994876861572 seconds
population_evaluation took 2.3152153491973877 seconds
population_evaluation took 2.271381378173828 seconds
population_evaluation took 2.274569034576416 seconds
population_evaluation took 2.3536877632141113 seconds
population_evaluation took 2.3024091720581055 seconds
population_evaluation took 2.3631834983825684 seconds
population_evaluation took 2.308441400527954 seconds
population_evaluation took 2.3412814140319824 seconds
population_evaluation took 2.2830405235290527 seconds
population_evaluation took 2.342299222946167 seconds
population_evaluation took 2.3356218338012695 seconds
population_evaluation took 2.3722002506256104 seconds
population_evaluation took 2.2608792781829834 seconds
population_evaluation took 2.34032940864563 seconds
population_evaluation took 2.294405460357666 seconds
population_evaluation took 2.3659379482269287 seconds
population_evaluation took 2.3152639865875244 seconds
population_evaluation took 2.2925865650177 seconds
population_evaluation took 2.289463520050049 seconds
population_evaluation took 2.318826675415039 seconds
  Tamamlandı.


============================================================
  Hedef: h (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 2.5698344707489014 seconds
population_evaluation took 2.5663509368896484 seconds
population_evaluation took 2.625363826751709 seconds
population_evaluation took 2.596869707107544 seconds
population_evaluation took 2.6397664546966553 seconds
population_evaluation took 2.6202425956726074 seconds
population_evaluation took 2.6332788467407227 seconds
population_evaluation took 2.6336216926574707 seconds
population_evaluation took 2.6113524436950684 seconds
population_evaluation took 2.6248185634613037 seconds
population_evaluation took 2.7109920978546143 seconds
population_evaluation took 2.6203629970550537 seconds
population_evaluation took 2.6072211265563965 seconds
population_evaluation took 2.652332067489624 seconds
population_evaluation took 2.6471633911132812 seconds
population_evaluation took 2.630758762359619 seconds
population_evaluation took 2.652547597885132 seconds
population_evaluation took 2.5997188091278076 seconds
population_evaluation took 2.651257276535034 seconds
population_evaluation took 2.5024592876434326 seconds
population_evaluation took 2.5976624488830566 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 49/49 [00:00<00:00, 367.50it/s]
synth_matrix: 100%|##########| 49/49 [00:00<00:00, 880.81it/s]
r_index: 100%|##########| 5/5 [00:00<?, ?it/s]

population_evaluation took 2.4570629596710205 seconds
population_evaluation took 2.4217350482940674 seconds
population_evaluation took 2.498004674911499 seconds
population_evaluation took 2.474952220916748 seconds
population_evaluation took 2.491593360900879 seconds
population_evaluation took 2.504971981048584 seconds
population_evaluation took 2.538557767868042 seconds
population_evaluation took 2.558326005935669 seconds
population_evaluation took 2.551748514175415 seconds
population_evaluation took 2.8361573219299316 seconds
population_evaluation took 2.630699872970581 seconds
population_evaluation took 2.5643203258514404 seconds
population_evaluation took 2.7548675537109375 seconds
population_evaluation took 2.5818450450897217 seconds
population_evaluation took 2.530623435974121 seconds
population_evaluation took 2.5974323749542236 seconds
population_evaluation took 2.580812692642212 seconds
population_evaluation took 2.550654172897339 seconds
population_evaluation took 2.5287892818450928 seconds
population_evaluation took 2.5443809032440186 seconds
population_evaluation took 2.5412721633911133 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 2.5557610988616943 seconds
population_evaluation took 2.6174707412719727 seconds
population_evaluation took 2.5748305320739746 seconds
population_evaluation took 2.638106107711792 seconds
population_evaluation took 2.6151013374328613 seconds
population_evaluation took 2.6291604042053223 seconds
population_evaluation took 2.6027345657348633 seconds
population_evaluation took 2.6110236644744873 seconds
population_evaluation took 2.6168856620788574 seconds
population_evaluation took 2.584320545196533 seconds
population_evaluation took 2.6318185329437256 seconds
population_evaluation took 2.5951263904571533 seconds
population_evaluation took 2.6739342212677 seconds
population_evaluation took 2.6170084476470947 seconds
population_evaluation took 2.667470932006836 seconds
population_evaluation took 2.7125298976898193 seconds
population_evaluation took 2.610114336013794 seconds
population_evaluation took 2.597771406173706 seconds
population_evaluation took 2.65110182762146 seconds
population_evaluation took 2.6596930027008057 seconds
population_evaluation took 2.603903293609619 seconds
population_evaluation took 2.6519079208374023 seconds
population_evaluation took 2.701866388320923 seconds
population_evaluation took 2.7181692123413086 seconds
population_evaluation took 2.7958030700683594 seconds
population_evaluation took 2.7372970581054688 seconds
population_evaluation took 2.7426841259002686 seconds
population_evaluation took 2.762953281402588 seconds
population_evaluation took 2.7009308338165283 seconds
population_evaluation took 2.7354705333709717 seconds
population_evaluation took 2.6904702186584473 seconds
population_evaluation took 2.748946189880371 seconds
population_evaluation took 2.7970852851867676 seconds
population_evaluation took 2.7001569271087646 seconds
population_evaluation took 2.7311785221099854 seconds
population_evaluation took 2.6895711421966553 seconds
population_evaluation took 2.7122201919555664 seconds
population_evaluation took 2.6845595836639404 seconds
population_evaluation took 2.737947463989258 seconds
population_evaluation took 2.6682746410369873 seconds
population_evaluation took 2.7071802616119385 seconds
population_evaluation took 2.7309558391571045 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 2.5860819816589355 seconds
population_evaluation took 2.5296478271484375 seconds
population_evaluation took 2.4592316150665283 seconds
population_evaluation took 2.472944974899292 seconds
population_evaluation took 2.5548343658447266 seconds
population_evaluation took 2.5253450870513916 seconds
population_evaluation took 2.502983570098877 seconds
population_evaluation took 2.568079948425293 seconds
population_evaluation took 2.518261671066284 seconds
population_evaluation took 2.5620968341827393 seconds
population_evaluation took 2.532250165939331 seconds
population_evaluation took 2.512047290802002 seconds
population_evaluation took 2.5629560947418213 seconds
population_evaluation took 2.583273410797119 seconds
population_evaluation took 2.5323147773742676 seconds
population_evaluation took 2.5165932178497314 seconds
population_evaluation took 2.5494894981384277 seconds
population_evaluation took 2.5471737384796143 seconds
population_evaluation took 2.5540504455566406 seconds
population_evaluation took 2.8767950534820557 seconds
population_evaluation took 2.575009822845459 seconds
population_evaluation took 2.4631171226501465 seconds
population_evaluation took 2.6388938426971436 seconds
population_evaluation took 2.554823637008667 seconds
population_evaluation took 2.5693392753601074 seconds
population_evaluation took 2.5395922660827637 seconds
population_evaluation took 2.5062122344970703 seconds
population_evaluation took 2.625523090362549 seconds
population_evaluation took 2.5583059787750244 seconds
population_evaluation took 2.557072401046753 seconds
population_evaluation took 2.5802457332611084 seconds
population_evaluation took 2.574585437774658 seconds
population_evaluation took 2.562446117401123 seconds
population_evaluation took 2.540738821029663 seconds
population_evaluation took 2.568127393722534 seconds
population_evaluation took 2.537729501724243 seconds
population_evaluation took 2.5946152210235596 seconds
population_evaluation took 2.519946813583374 seconds
population_evaluation took 2.6124467849731445 seconds
population_evaluation took 2.776174783706665 seconds
population_evaluation took 2.686771869659424 seconds
population_evaluation took 2.770071268081665 seconds
  Tamamlandı.


============================================================
  Hedef: s (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 2.595734119415283 seconds
population_evaluation took 2.6145451068878174 seconds
population_evaluation took 2.878364086151123 seconds
population_evaluation took 2.797720193862915 seconds
population_evaluation took 2.830894708633423 seconds
population_evaluation took 2.8789730072021484 seconds
population_evaluation took 2.852308511734009 seconds
population_evaluation took 3.017752170562744 seconds
population_evaluation took 2.996140480041504 seconds
population_evaluation took 2.8975532054901123 seconds
population_evaluation took 2.8867619037628174 seconds
population_evaluation took 2.7594540119171143 seconds
population_evaluation took 2.9002883434295654 seconds
population_evaluation took 2.9415435791015625 seconds
population_evaluation took 2.87760329246521 seconds
population_evaluation took 3.2463951110839844 seconds
population_evaluation took 3.0841166973114014 seconds
population_evaluation took 3.1020638942718506 seconds
population_evaluation took 2.911604642868042 seconds
population_evaluation took 2.9028775691986084 seconds
population_evaluation took 2.8803787231445312 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 53/53 [00:00<00:00, 351.95it/s]
synth_matrix: 100%|##########| 53/53 [00:00<00:00, 1278.27it/s]
r_index: 100%|##########| 43/43 [00:00<00:00, 2395.89it/s]
dist_matrix: 100%|##########| 53/53 [00:00<00:00, 508.30it/s]
synth_matrix: 100%|##########| 53/53 [00:00<00:00, 1252.74it/s]
r_index: 100%|##########| 43/43 [00:00<00:00, 2753.34it/s]

population_evaluation took 2.49955677986145 seconds
population_evaluation took 2.6844024658203125 seconds
population_evaluation took 2.700653314590454 seconds
population_evaluation took 2.6291630268096924 seconds
population_evaluation took 2.570375919342041 seconds
population_evaluation took 2.4580867290496826 seconds
population_evaluation took 2.4976861476898193 seconds
population_evaluation took 2.5490529537200928 seconds
population_evaluation took 2.491100549697876 seconds
population_evaluation took 2.4626924991607666 seconds
population_evaluation took 2.5143401622772217 seconds
population_evaluation took 2.4794223308563232 seconds
population_evaluation took 2.5041286945343018 seconds
population_evaluation took 2.513803243637085 seconds
population_evaluation took 2.4989442825317383 seconds
population_evaluation took 2.4753360748291016 seconds
population_evaluation took 2.4635274410247803 seconds
population_evaluation took 2.525700569152832 seconds
population_evaluation took 2.5223920345306396 seconds
population_evaluation took 2.505042791366577 seconds
population_evaluation took 2.4880354404449463 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 2.5503621101379395 seconds
population_evaluation took 2.645690441131592 seconds
population_evaluation took 2.7343244552612305 seconds
population_evaluation took 2.6092424392700195 seconds
population_evaluation took 2.6837713718414307 seconds
population_evaluation took 2.6692490577697754 seconds
population_evaluation took 2.6527223587036133 seconds
population_evaluation took 2.6259214878082275 seconds
population_evaluation took 2.6637072563171387 seconds
population_evaluation took 2.627471685409546 seconds
population_evaluation took 2.7331652641296387 seconds
population_evaluation took 2.650960683822632 seconds
population_evaluation took 2.6347367763519287 seconds
population_evaluation took 2.685493230819702 seconds
population_evaluation took 2.6331191062927246 seconds
population_evaluation took 2.7106330394744873 seconds
population_evaluation took 2.6566309928894043 seconds
population_evaluation took 2.688981056213379 seconds
population_evaluation took 2.69238018989563 seconds
population_evaluation took 2.616349935531616 seconds
population_evaluation took 2.7061004638671875 seconds
population_evaluation took 2.733781099319458 seconds
population_evaluation took 2.734248399734497 seconds
population_evaluation took 2.734356164932251 seconds
population_evaluation took 2.740839719772339 seconds
population_evaluation took 2.8059587478637695 seconds
population_evaluation took 2.7363548278808594 seconds
population_evaluation took 2.7818517684936523 seconds
population_evaluation took 2.703071117401123 seconds
population_evaluation took 2.720247745513916 seconds
population_evaluation took 2.7509663105010986 seconds
population_evaluation took 2.728163480758667 seconds
population_evaluation took 2.763939380645752 seconds
population_evaluation took 2.7015011310577393 seconds
population_evaluation took 2.711507558822632 seconds
population_evaluation took 2.7413442134857178 seconds
population_evaluation took 2.7067911624908447 seconds
population_evaluation took 2.7471961975097656 seconds
population_evaluation took 2.680328369140625 seconds
population_evaluation took 2.7420663833618164 seconds
population_evaluation took 2.737950563430786 seconds
population_evaluation took 2.777681589126587 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 2.4840590953826904 seconds
population_evaluation took 2.5818030834198 seconds
population_evaluation took 2.4874236583709717 seconds
population_evaluation took 2.458449125289917 seconds
population_evaluation took 2.502173900604248 seconds
population_evaluation took 2.487443685531616 seconds
population_evaluation took 2.5085391998291016 seconds
population_evaluation took 2.509307384490967 seconds
population_evaluation took 2.4968268871307373 seconds
population_evaluation took 2.5185444355010986 seconds
population_evaluation took 2.478893518447876 seconds
population_evaluation took 2.4838900566101074 seconds
population_evaluation took 2.4322845935821533 seconds
population_evaluation took 2.4747211933135986 seconds
population_evaluation took 2.435706615447998 seconds
population_evaluation took 2.5350069999694824 seconds
population_evaluation took 2.467742681503296 seconds
population_evaluation took 2.532410144805908 seconds
population_evaluation took 2.423184871673584 seconds
population_evaluation took 2.502136468887329 seconds
population_evaluation took 2.564171075820923 seconds
population_evaluation took 2.560997724533081 seconds
population_evaluation took 2.593677282333374 seconds
population_evaluation took 2.6040127277374268 seconds
population_evaluation took 2.577984094619751 seconds
population_evaluation took 2.5388550758361816 seconds
population_evaluation took 2.588183879852295 seconds
population_evaluation took 2.583873748779297 seconds
population_evaluation took 2.5165276527404785 seconds
population_evaluation took 2.562997579574585 seconds
population_evaluation took 2.548395872116089 seconds
population_evaluation took 2.6058425903320312 seconds
population_evaluation took 2.5755319595336914 seconds
population_evaluation took 2.5952556133270264 seconds
population_evaluation took 2.5631515979766846 seconds
population_evaluation took 2.616769313812256 seconds
population_evaluation took 2.5658347606658936 seconds
population_evaluation took 2.596543550491333 seconds
population_evaluation took 2.6673741340637207 seconds
population_evaluation took 2.6277740001678467 seconds
population_evaluation took 2.581415891647339 seconds
population_evaluation took 2.6058740615844727 seconds
  Tamamlandı.

### 4.1 Kızgın Buhar — Sonuç Tablosu

In [16]:
df_kizgin_results = build_results_table(kizgin_results)
df_kizgin_results

         Hedef        Senaryo Algoritma  Train_R2  Test_R2  Train_RMSE  Test_RMSE  Train_MAPE  Test_MAPE
0    v (çıktı)           Base  AdaBoost    0.9928   0.9891      0.0849     0.0984      1.0603     0.2023
1    v (çıktı)           Base  CatBoost    0.9999   0.9996      0.0073     0.0177      0.0532     0.0266
2    v (çıktı)           Base      DART    0.8654   0.8862      0.3669     0.3181      0.3296     0.1550
3    v (çıktı)           Base        EF    1.0000   0.9998      0.0001     0.0133      0.0000     0.0135
4    v (çıktı)           Base        ET    1.0000   0.9998      0.0000     0.0128      0.0000     0.0133
..         ...            ...       ...       ...      ...         ...        ...         ...        ...
127  s (çıktı)  SMOGN+STGP-EF        GP    0.8864   0.7079      0.4252     0.5078      0.8674     1.3577
128  s (çıktı)  SMOGN+STGP-EF       KNN    0.9844   0.9625      0.1577     0.1820      0.1383     0.4497
129  s (çıktı)  SMOGN+STGP-EF  LightGBM    0.9963   0.9884      0.0765     0.1012      0.0857     0.3560
130  s (çıktı)  SMOGN+STGP-EF        RF    0.9968   0.9727      0.0715     0.1552      0.0747     0.3753
131  s (çıktı)  SMOGN+STGP-EF   XGBoost    0.9984   0.9778      0.0506     0.1400      0.0072     0.3741

[132 rows x 9 columns]

### 4.2 Kızgın Buhar — Senaryo Karşılaştırması

In [17]:
compare_scenarios(df_kizgin_results)

Senaryo               Base   SMOGN  STGP-EF  SMOGN+STGP-EF
Hedef     Algoritma
h (çıktı) AdaBoost  0.9662  0.9632   0.9927         0.9922
          CatBoost  0.9980  0.9955   0.9989         0.9972
          DART      0.9604  0.9590   0.9757         0.9837
          EF        0.9995  0.9989   0.9995         0.9989
          ET        0.9994  0.9971   0.9993         0.9982
          GBDT      0.9977  0.9941   0.9989         0.9970
          GP        0.9553  0.8314   0.9864         0.9384
          KNN       0.9934  0.9867   0.9968         0.9866
          LightGBM  0.9729  0.9719   0.9872         0.9966
          RF        0.9973  0.9908   0.9988         0.9963
          XGBoost   0.9979  0.9943   0.9984         0.9970
s (çıktı) AdaBoost  0.8883  0.8939   0.9645         0.9399
          CatBoost  0.9957  0.9856   0.9955         0.9937
          DART      0.9382  0.8845   0.9789         0.9625
          EF        0.9982  0.9927   0.9941         0.9912
          ET        0.9972  0.9929   0.9945         0.9825
          GBDT      0.9922  0.9849   0.9949         0.9875
          GP        0.7252  0.7686   0.8307         0.7079
          KNN       0.9686  0.9330   0.9731         0.9625
          LightGBM  0.9529  0.8975   0.9880         0.9884
          RF        0.9843  0.9767   0.9905         0.9727
          XGBoost   0.9927  0.9847   0.9918         0.9778
v (çıktı) AdaBoost  0.9891  0.9628   0.9866         0.9634
          CatBoost  0.9996  0.9988   0.9998         0.9978
          DART      0.8862  0.9811   0.9408         0.9889
          EF        0.9998  0.9956   0.9998         0.9992
          ET        0.9998  0.9990   0.9998         0.9991
          GBDT      0.9994  0.9993   0.9994         0.9986
          GP        0.0405 -1.9946   0.8612         0.9310
          KNN       0.7909  0.7742   0.9978         0.9947
          LightGBM  0.8781  0.9946   0.9780         0.9956
          RF        0.9994  0.9983   0.9994         0.9979
          XGBoost   0.9990  0.9978   0.9990         0.9972

### 4.3 Doymuş Buhar — Hedef Bazlı Detay

Her bir hedef değişken için detaylı pivot tablo;

In [18]:
target_summary(df_kizgin_results, 'v (çıktı)')

Senaryo     Base   SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9891  0.9628   0.9866         0.9634
CatBoost  0.9996  0.9988   0.9998         0.9978
DART      0.8862  0.9811   0.9408         0.9889
EF        0.9998  0.9956   0.9998         0.9992
ET        0.9998  0.9990   0.9998         0.9991
GBDT      0.9994  0.9993   0.9994         0.9986
GP        0.0405 -1.9946   0.8612         0.9310
KNN       0.7909  0.7742   0.9978         0.9947
LightGBM  0.8781  0.9946   0.9780         0.9956
RF        0.9994  0.9983   0.9994         0.9979
XGBoost   0.9990  0.9978   0.9990         0.9972

In [19]:
target_summary(df_kizgin_results, 'h (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9662 0.9632   0.9927         0.9922
CatBoost  0.9980 0.9955   0.9989         0.9972
DART      0.9604 0.9590   0.9757         0.9837
EF        0.9995 0.9989   0.9995         0.9989
ET        0.9994 0.9971   0.9993         0.9982
GBDT      0.9977 0.9941   0.9989         0.9970
GP        0.9553 0.8314   0.9864         0.9384
KNN       0.9934 0.9867   0.9968         0.9866
LightGBM  0.9729 0.9719   0.9872         0.9966
RF        0.9973 0.9908   0.9988         0.9963
XGBoost   0.9979 0.9943   0.9984         0.9970

In [20]:
target_summary(df_kizgin_results, 's (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.8883 0.8939   0.9645         0.9399
CatBoost  0.9957 0.9856   0.9955         0.9937
DART      0.9382 0.8845   0.9789         0.9625
EF        0.9982 0.9927   0.9941         0.9912
ET        0.9972 0.9929   0.9945         0.9825
GBDT      0.9922 0.9849   0.9949         0.9875
GP        0.7252 0.7686   0.8307         0.7079
KNN       0.9686 0.9330   0.9731         0.9625
LightGBM  0.9529 0.8975   0.9880         0.9884
RF        0.9843 0.9767   0.9905         0.9727
XGBoost   0.9927 0.9847   0.9918         0.9778

# En İyi Sonuçlar

Her hedef değişken için en iyi (Algoritma, Senaryo) kombinasyonunu döndürür.

In [21]:
show_best_results(df_doymus_results)

             Hedef  Senaryo Algoritma  Test_R2  Train_R2  Test_RMSE  Test_MAPE
0         P(çıktı)     Base        ET   1.0000    1.0000     0.0035     0.0034
1  h buhar (çıktı)     Base        ET   1.0000    1.0000     0.0062     0.0065
2   h sıvı (çıktı)     Base        ET   1.0000    1.0000     0.0044     0.0067
3  s buhar (çıktı)     Base        ET   0.9997    1.0000     0.0134     0.0325
4   s sıvı (çıktı)     Base        ET   1.0000    1.0000     0.0051     0.0079
5  v buhar (çıktı)  STGP-EF        ET   0.9992    1.0000     0.0301     0.0309
6   v sıvı (çıktı)  STGP-EF        ET   1.0000    1.0000     0.0041     0.0116

---
## 5. Genel Karşılaştırma

In [22]:

df_doymus_results['Veri Seti'] = 'Doymuş Buhar'
df_kizgin_results['Veri Seti'] = 'Kızgın Buhar'
df_all = pd.concat([df_doymus_results, df_kizgin_results], ignore_index=True)

print(f'Toplam değerlendirme sayısı: {len(df_all)}')
df_all.head(20)

Toplam değerlendirme sayısı: 440

       Hedef Senaryo Algoritma  Train_R2  Test_R2  Train_RMSE  Test_RMSE  Train_MAPE  Test_MAPE     Veri Seti
0   P(çıktı)    Base  AdaBoost    0.9964   0.9959      0.0598     0.0653      0.0706     0.1070  Doymuş Buhar
1   P(çıktı)    Base  CatBoost    0.9998   0.9991      0.0123     0.0300      0.0484     0.0844  Doymuş Buhar
2   P(çıktı)    Base      DART    0.9387   0.9541      0.2475     0.2177      0.2042     0.1343  Doymuş Buhar
3   P(çıktı)    Base        EF    1.0000   1.0000      0.0000     0.0054      0.0000     0.0077  Doymuş Buhar
4   P(çıktı)    Base        ET    1.0000   1.0000      0.0000     0.0035      0.0000     0.0034  Doymuş Buhar
5   P(çıktı)    Base      GBDT    1.0000   0.9991      0.0004     0.0308      0.0011     0.0752  Doymuş Buhar
6   P(çıktı)    Base        GP    0.9743   0.9702      0.1603     0.1753      0.3648     0.3469  Doymuş Buhar
7   P(çıktı)    Base       KNN    0.9991   0.9998      0.0304     0.0158      0.0331     0.0438  Doymuş Buhar
8   P(çıktı)    Base  LightGBM    0.9461   0.9651      0.2322     0.1898      0.1671     0.1121  Doymuş Buhar
9   P(çıktı)    Base        RF    0.9999   0.9997      0.0098     0.0181      0.0186     0.0399  Doymuş Buhar
10  P(çıktı)    Base   XGBoost    1.0000   0.9982      0.0022     0.0427      0.0034     0.0818  Doymuş Buhar
11  P(çıktı)   SMOGN  AdaBoost    0.9984   0.9967      0.0442     0.0584      0.1290     0.1706  Doymuş Buhar
12  P(çıktı)   SMOGN  CatBoost    0.9998   0.9989      0.0158     0.0344      0.0533     0.0549  Doymuş Buhar
13  P(çıktı)   SMOGN      DART    0.9423   0.9145      0.2631     0.2971      1.3052     1.4380  Doymuş Buhar
14  P(çıktı)   SMOGN        EF    1.0000   0.9998      0.0004     0.0140      0.0000     0.0181  Doymuş Buhar
15  P(çıktı)   SMOGN        ET    1.0000   0.9998      0.0000     0.0132      0.0000     0.0226  Doymuş Buhar
16  P(çıktı)   SMOGN      GBDT    1.0000   0.9989      0.0002     0.0330      0.0002     0.0844  Doymuş Buhar
17  P(çıktı)   SMOGN        GP    0.9810   0.9253      0.1510     0.2777      0.6546     0.8598  Doymuş Buhar
18  P(çıktı)   SMOGN       KNN    0.9991   0.9987      0.0331     0.0364      0.2210     0.1588  Doymuş Buhar
19  P(çıktı)   SMOGN  LightGBM    0.9531   0.9166      0.2372     0.2935      1.4017     1.5541  Doymuş Buhar

In [28]:
# Senaryo bazlı ortalama Test R² skorları
df_all.groupby(['Veri Seti', 'Senaryo'])['Test_R2'].mean().unstack()

Senaryo        Base  SMOGN  SMOGN+STGP-EF  STGP-EF
Veri Seti
Doymuş Buhar 0.9613 0.9567         0.9550   0.9845
Kızgın Buhar 0.9349 0.8692         0.9761   0.9815

In [29]:
# Algoritma bazlı ortalama Test R² skorları
df_all.groupby(['Veri Seti', 'Algoritma'])['Test_R2'].mean().unstack()

Algoritma     AdaBoost  CatBoost   DART     EF     ET   GBDT     GP    KNN  LightGBM     RF  XGBoost
Veri Seti
Doymuş Buhar    0.9741    0.9943 0.8791 0.9968 0.9932 0.9934 0.9216 0.9903    0.8874 0.9931   0.9847
Kızgın Buhar    0.9586    0.9963 0.9533 0.9973 0.9966 0.9953 0.5485 0.9465    0.9668 0.9919   0.9940

In [26]:
# Geniş formatlı sonuç tablosu oluştur ve kaydet
df_wide = save_wide_results(df_all, 'R515B_Ozellikler/Model_Training_Results.csv')
print('Sonuçlar R515B_Ozellikler/Model_Training_Results.csv dosyasına kaydedildi.')
print(f'Format: Geniş tablo — {len(df_wide)} satır, {len(df_wide.columns)} sütun')
df_wide

Sonuçlar R515B_Ozellikler/Model_Training_Results.csv dosyasına kaydedildi.
Format: Geniş tablo — 110 satır, 29 sütun

        Veri Seti      Hedef Algoritma  Base_Train_R2  Base_Test_R2  Base_Train_RMSE  Base_Test_RMSE  Base_Train_MAPE  Base_Test_MAPE  SMOGN_Train_R2  SMOGN_Test_R2  SMOGN_Train_RMSE  SMOGN_Test_RMSE  SMOGN_Train_MAPE  SMOGN_Test_MAPE  STGP-EF_Train_R2  STGP-EF_Test_R2  STGP-EF_Train_RMSE  STGP-EF_Test_RMSE  STGP-EF_Train_MAPE  STGP-EF_Test_MAPE  SMOGN+STGP-EF_Train_R2  SMOGN+STGP-EF_Test_R2  SMOGN+STGP-EF_Train_RMSE  SMOGN+STGP-EF_Test_RMSE  SMOGN+STGP-EF_Train_MAPE  SMOGN+STGP-EF_Test_MAPE  Max_Test_R2    Max_Senaryo
0    Doymuş Buhar   P(çıktı)  AdaBoost         0.9964        0.9959           0.0598          0.0653           0.0706          0.1070          0.9984         0.9967            0.0442           0.0584            0.1290           0.1706            0.9963           0.9939              0.0606             0.0795              0.0913             0.0625                  0.9988                 0.9975                    0.0385                   0.0508                    0.1765                   0.2224       0.9975  SMOGN+STGP-EF
1    Doymuş Buhar   P(çıktı)  CatBoost         0.9998        0.9991           0.0123          0.0300           0.0484          0.0844          0.9998         0.9989            0.0158           0.0344            0.0533           0.0549            0.9998           0.9994              0.0141             0.0245              0.0367             0.0450                  0.9997                 0.9989                    0.0176                   0.0340                    0.0807                   0.0702       0.9994        STGP-EF
2    Doymuş Buhar   P(çıktı)      DART         0.9387        0.9541           0.2475          0.2177           0.2042          0.1343          0.9423         0.9145            0.2631           0.2971            1.3052           1.4380            0.9449           0.9570              0.2347             0.2107              0.1501             0.1744                  0.9429                 0.9147                    0.2618                   0.2967                    1.3045                   1.4393       0.9570        STGP-EF
3    Doymuş Buhar   P(çıktı)        EF         1.0000        1.0000           0.0000          0.0054           0.0000          0.0077          1.0000         0.9998            0.0004           0.0140            0.0000           0.0181            1.0000           1.0000              0.0000             0.0054              0.0000             0.0076                  1.0000                 0.9998                    0.0000                   0.0138                    0.0000                   0.0139       1.0000           Base
4    Doymuş Buhar   P(çıktı)        ET         1.0000        1.0000           0.0000          0.0035           0.0000          0.0034          1.0000         0.9998            0.0000           0.0132            0.0000           0.0226            1.0000           1.0000              0.0000             0.0043              0.0000             0.0066                  1.0000                 0.9998                    0.0000                   0.0139                    0.0000                   0.0184       1.0000           Base
..            ...        ...       ...            ...           ...              ...             ...              ...             ...             ...            ...               ...              ...               ...              ...               ...              ...                 ...                ...                 ...                ...                     ...                    ...                       ...                      ...                       ...                      ...          ...            ...
105  Kızgın Buhar  v (çıktı)        GP         0.0484        0.0405           0.9755          0.9235           2.3504          0.7659          0.2623        -1.9946            1.3464           1.6315            2.7197           2.0493            0.9002           0.8612              0.3159             0.3513              3.8145             1.0897                  0.8960                 0.9310                    0.5056                   0.2477                    0.9702                   0.6330       0.9310  SMOGN+STGP-EF
106  Kızgın Buhar  v (çıktı)       KNN         0.8919        0.7909           0.3288          0.4311           0.4794          0.2951          0.8927         0.7742            0.5135           0.4480            0.7262           0.5594            0.9992           0.9978              0.0277             0.0438              0.2006             0.0830                  0.9376                 0.9947                    0.3916                   0.0683                    0.2533                   0.1298       0.9978        STGP-EF
107  Kızgın Buhar  v (çıktı)  LightGBM         0.8826        0.8781           0.3427          0.3291           0.2461          0.1727          0.9661         0.9946            0.2886           0.0692            0.2676           0.0938            0.9902           0.9780              0.0992             0.1400              0.0988             0.0885                  0.9676                 0.9956                    0.2820                   0.0624                    0.0858                   0.0898       0.9956  SMOGN+STGP-EF
108  Kızgın Buhar  v (çıktı)        RF         0.9999        0.9994           0.0078          0.0239           0.0455          0.0315          0.9701         0.9983            0.2709           0.0392            0.0999           0.0556            0.9999           0.9994              0.0081             0.0239              0.0416             0.0320                  0.9701                 0.9979                    0.2709                   0.0435                    0.3345                   0.0606       0.9994           Base
109  Kızgın Buhar  v (çıktı)   XGBoost         1.0000        0.9990           0.0025          0.0296           0.0242          0.0347          0.9720         0.9978            0.2621           0.0438            0.0724           0.0558            1.0000           0.9990              0.0026             0.0297              0.0160             0.0381                  0.9720                 0.9972                    0.2621                   0.0501                    0.0430                   0.0696       0.9990           Base

[110 rows x 29 columns]