# R515B Soğutucu Akışkan — Model Eğitimi

Bu notebook, Doymuş ve Kızgın buhar veri setleri için **4 farklı senaryo** ile regresyon modeli eğitimi yapar:

| # | Senaryo | Açıklama |
|---|---------|----------|
| 1 | **Base** | Orijinal veri ile temel eğitim |
| 2 | **SMOGN** | SMOGN ile veri artırma sonrası eğitim |
| 3 | **STGP-EF** | SymbolicTransformer ile öznitelik çıkarımı sonrası eğitim |
| 4 | **SMOGN+STGP-EF** | Önce SMOGN, sonra STGP-EF ile birleşik eğitim |

Her senaryo **8 farklı regresyon algoritması** ile değerlendirilir (RF, ET, AdaBoost, GBDT, DART, XGBoost, LightGBM, CatBoost).

---

## 1. Kütüphaneler ve Fonksiyonlar

In [1]:
import sys
sys.path.insert(0, 'R515B_Ozellikler')

import pandas as pd
import numpy as np
from Functions import (
    run_doymus_analysis,
    run_kizgin_analysis,
    build_results_table,
    compare_scenarios,
    show_best_results,
    target_summary,
    save_wide_results
)

print('Fonksiyonlar başarıyla yüklendi.')

c:\Users\SGUZEY\Documents\Yüksek Lisans Dersleri\Veri Mühendisliği\Data_Engineering_Project\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Fonksiyonlar başarıyla yüklendi.

## 2. Veri Yükleme

In [2]:
df_doymus = pd.read_csv('R515B_Ozellikler/R515B_Doymus_Ozellikleri.csv')
df_kizgin = pd.read_csv('R515B_Ozellikler/R515B_Kizgin_Buhar.csv')

print(f'Doymuş Buhar: {df_doymus.shape}')
print(f'Kızgın Buhar: {df_kizgin.shape}')
print(f'\nDoymuş Sütunlar: {list(df_doymus.columns)}')
print(f'Kızgın Sütunlar: {list(df_kizgin.columns)}')

Doymuş Buhar: (136, 8)
Kızgın Buhar: (578, 5)

Doymuş Sütunlar: ['T(girdi)', 'P(çıktı)', 'v sıvı (çıktı)', 'v buhar (çıktı)', 'h sıvı (çıktı)', 'h buhar (çıktı)', 's sıvı (çıktı)', 's buhar (çıktı)']
Kızgın Sütunlar: ['T (girdi)', 'P (girdi)', 'v (çıktı)', 'h (çıktı)', 's (çıktı)']

In [3]:
df_doymus.head()

   T(girdi)  P(çıktı)  v sıvı (çıktı)  v buhar (çıktı)  h sıvı (çıktı)  h buhar (çıktı)  s sıvı (çıktı)  s buhar (çıktı)
0       -30   61.2210          0.0007           0.2726          2.7282         198.2000          0.0446           0.8486
1       -29   64.2350          0.0007           0.2606          3.9422         198.8900          0.0496           0.8481
2       -28   67.3670          0.0007           0.2492          5.1587         199.5800          0.0546           0.8476
3       -27   70.6200          0.0007           0.2385          6.3775         200.2700          0.0595           0.8472
4       -26   73.9960          0.0008           0.2282          7.5988         200.9500          0.0645           0.8468

In [4]:
df_kizgin.head()

   T (girdi)  P (girdi)  v (çıktı)  h (çıktı)  s (çıktı)
0        -30         50     0.3357   198.5500     0.8639
1        -25         50     0.3433   202.4500     0.8798
2        -20         50     0.3508   206.4000     0.8956
3        -15         50     0.3582   210.4000     0.9112
4        -10         50     0.3656   214.4300     0.9267

---
## 3. Doymuş Buhar — Eğitim

**Girdi:** T(girdi)  
**Çıktılar (her biri ayrı ayrı):** P, v sıvı, v buhar, h sıvı, h buhar, s sıvı, s buhar

In [5]:
doymus_results = run_doymus_analysis(df_doymus)

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  DOYMUŞ BUHAR ANALİZİ
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

============================================================
  Hedef: P(çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 29/29 [00:00<00:00, 968.08it/s]
r_index: 100%|##########| 25/25 [00:00<00:00, 2502.75it/s]

  [3/4] STGP-EF eğitim...
population_evaluation took 2.262812376022339 seconds
population_evaluation took 2.152561902999878 seconds
population_evaluation took 2.148284435272217 seconds
population_evaluation took 2.1533892154693604 seconds
population_evaluation took 2.1165802478790283 seconds
population_evaluation took 2.014248847961426 seconds
population_evaluation took 2.066349506378174 seconds
population_evaluation took 2.045196533203125 seconds
population_evaluation took 2.0403316020965576 seconds
population_evaluation took 1.996002435684204 seconds
population_evaluation took 2.0352137088775635 seconds
population_evaluation took 1.998441219329834 seconds
population_evaluation took 2.090803384780884 seconds
population_evaluation took 2.0778987407684326 seconds
population_evaluation took 2.150644063949585 seconds
population_evaluation took 2.1552162170410156 seconds
population_evaluation took 2.246729850769043 seconds
population_evaluation took 2.1555912494659424 seconds
population_evaluation took 2.3401994705200195 seconds
population_evaluation took 2.1427485942840576 seconds
population_evaluation took 2.0990982055664062 seconds
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 29/29 [00:00<00:00, 1005.89it/s]
r_index: 100%|##########| 25/25 [00:00<00:00, 1645.21it/s]

population_evaluation took 2.061805009841919 seconds
population_evaluation took 2.0292630195617676 seconds
population_evaluation took 2.054664373397827 seconds
population_evaluation took 2.0604612827301025 seconds
population_evaluation took 2.118190288543701 seconds
population_evaluation took 2.065308094024658 seconds
population_evaluation took 2.0810978412628174 seconds
population_evaluation took 2.0447845458984375 seconds
population_evaluation took 2.1123507022857666 seconds
population_evaluation took 2.0535800457000732 seconds
population_evaluation took 2.124572515487671 seconds
population_evaluation took 2.116737127304077 seconds
population_evaluation took 2.047534704208374 seconds
population_evaluation took 2.0761666297912598 seconds
population_evaluation took 2.0762901306152344 seconds
population_evaluation took 2.0771892070770264 seconds
population_evaluation took 2.0547919273376465 seconds
population_evaluation took 2.096956491470337 seconds
population_evaluation took 2.1018733978271484 seconds
population_evaluation took 2.0993940830230713 seconds
population_evaluation took 2.0816810131073 seconds
  Tamamlandı.


============================================================
  Hedef: v sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 16/16 [00:00<00:00, 1029.80it/s]
synth_matrix: 100%|##########| 16/16 [00:00<00:00, 782.56it/s]
r_index: 100%|##########| 6/6 [00:00<00:00, 8668.90it/s]

  [3/4] STGP-EF eğitim...
population_evaluation took 2.0860116481781006 seconds
population_evaluation took 2.135850429534912 seconds
population_evaluation took 2.1523072719573975 seconds
population_evaluation took 2.1245594024658203 seconds
population_evaluation took 2.182563066482544 seconds
population_evaluation took 2.1127116680145264 seconds
population_evaluation took 2.204852819442749 seconds
population_evaluation took 2.1079180240631104 seconds
population_evaluation took 2.1702053546905518 seconds
population_evaluation took 2.1098263263702393 seconds
population_evaluation took 2.207491397857666 seconds
population_evaluation took 2.1311776638031006 seconds
population_evaluation took 2.165079355239868 seconds
population_evaluation took 2.132540464401245 seconds
population_evaluation took 2.159850597381592 seconds
population_evaluation took 2.1738903522491455 seconds
population_evaluation took 2.1942331790924072 seconds
population_evaluation took 2.1790871620178223 seconds
population_evaluation took 2.0270090103149414 seconds
population_evaluation took 2.097346782684326 seconds
population_evaluation took 2.0550694465637207 seconds
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 16/16 [00:00<00:00, 1067.56it/s]
synth_matrix: 100%|##########| 16/16 [00:00<00:00, 977.66it/s]
r_index: 100%|##########| 6/6 [00:00<00:00, 986.86it/s]

population_evaluation took 1.988084077835083 seconds
population_evaluation took 1.9508302211761475 seconds
population_evaluation took 1.978299617767334 seconds
population_evaluation took 2.0134217739105225 seconds
population_evaluation took 2.0616648197174072 seconds
population_evaluation took 1.9828338623046875 seconds
population_evaluation took 2.0282013416290283 seconds
population_evaluation took 2.003905773162842 seconds
population_evaluation took 2.020162582397461 seconds
population_evaluation took 2.0079028606414795 seconds
population_evaluation took 1.9839050769805908 seconds
population_evaluation took 2.0179295539855957 seconds
population_evaluation took 1.9981045722961426 seconds
population_evaluation took 2.027735471725464 seconds
population_evaluation took 1.9890270233154297 seconds
population_evaluation took 2.0244269371032715 seconds
population_evaluation took 1.9812605381011963 seconds
population_evaluation took 2.0065419673919678 seconds
population_evaluation took 2.004667043685913 seconds
population_evaluation took 2.093626022338867 seconds
population_evaluation took 1.976766586303711 seconds
  Tamamlandı.


============================================================
  Hedef: v buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 21/21 [00:00<00:00, 1763.02it/s]
synth_matrix: 100%|##########| 21/21 [00:00<00:00, 2135.90it/s]
r_index: 100%|##########| 12/12 [00:00<00:00, 3033.49it/s]

  [3/4] STGP-EF eğitim...
population_evaluation took 2.1009140014648438 seconds
population_evaluation took 2.144352436065674 seconds
population_evaluation took 2.1217658519744873 seconds
population_evaluation took 2.145400047302246 seconds
population_evaluation took 2.1070709228515625 seconds
population_evaluation took 2.1572985649108887 seconds
population_evaluation took 2.1006767749786377 seconds
population_evaluation took 2.1663081645965576 seconds
population_evaluation took 2.2118306159973145 seconds
population_evaluation took 2.180786609649658 seconds
population_evaluation took 2.257819414138794 seconds
population_evaluation took 2.1280605792999268 seconds
population_evaluation took 2.188626766204834 seconds
population_evaluation took 2.205777168273926 seconds
population_evaluation took 2.151289463043213 seconds
population_evaluation took 2.1325228214263916 seconds
population_evaluation took 2.1721057891845703 seconds
population_evaluation took 2.1705846786499023 seconds
population_evaluation took 2.1160085201263428 seconds
population_evaluation took 2.1421611309051514 seconds
population_evaluation took 2.190368890762329 seconds
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 21/21 [00:00<00:00, 1434.49it/s]
synth_matrix: 100%|##########| 21/21 [00:00<00:00, 2036.16it/s]
r_index: 100%|##########| 12/12 [00:00<00:00, 1697.47it/s]

population_evaluation took 2.0284907817840576 seconds
population_evaluation took 2.0369455814361572 seconds
population_evaluation took 2.0574562549591064 seconds
population_evaluation took 2.0992462635040283 seconds
population_evaluation took 2.1322054862976074 seconds
population_evaluation took 2.0623626708984375 seconds
population_evaluation took 2.070901870727539 seconds
population_evaluation took 2.0439348220825195 seconds
population_evaluation took 2.0937659740448 seconds
population_evaluation took 2.12744140625 seconds
population_evaluation took 2.071061372756958 seconds
population_evaluation took 2.112616539001465 seconds
population_evaluation took 2.113054037094116 seconds
population_evaluation took 2.119457244873047 seconds
population_evaluation took 2.1037232875823975 seconds
population_evaluation took 2.1016054153442383 seconds
population_evaluation took 2.026144027709961 seconds
population_evaluation took 2.094606637954712 seconds
population_evaluation took 2.018450975418091 seconds
population_evaluation took 2.0929486751556396 seconds
population_evaluation took 2.053104877471924 seconds
  Tamamlandı.


============================================================
  Hedef: h sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 27/27 [00:00<00:00, 872.90it/s]
synth_matrix: 100%|##########| 27/27 [00:00<00:00, 1121.92it/s]

  [3/4] STGP-EF eğitim...
population_evaluation took 2.087754249572754 seconds
population_evaluation took 2.1067917346954346 seconds
population_evaluation took 2.1261801719665527 seconds
population_evaluation took 2.0903358459472656 seconds
population_evaluation took 2.2280282974243164 seconds
population_evaluation took 2.1718668937683105 seconds
population_evaluation took 2.1469695568084717 seconds
population_evaluation took 2.087101697921753 seconds
population_evaluation took 2.137028455734253 seconds
population_evaluation took 2.0902113914489746 seconds
population_evaluation took 2.1877307891845703 seconds
population_evaluation took 2.128953218460083 seconds
population_evaluation took 2.150733709335327 seconds
population_evaluation took 2.1268346309661865 seconds
population_evaluation took 2.1507575511932373 seconds
population_evaluation took 2.0832667350769043 seconds
population_evaluation took 2.120302677154541 seconds
population_evaluation took 2.1186954975128174 seconds
population_evaluation took 2.155386447906494 seconds
population_evaluation took 2.189026355743408 seconds
population_evaluation took 2.1224582195281982 seconds
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 27/27 [00:00<00:00, 669.51it/s]
synth_matrix: 100%|##########| 27/27 [00:00<00:00, 2649.78it/s]

population_evaluation took 2.0147199630737305 seconds
population_evaluation took 2.00616192817688 seconds
population_evaluation took 2.0896921157836914 seconds
population_evaluation took 2.1240532398223877 seconds
population_evaluation took 2.1369879245758057 seconds
population_evaluation took 2.0830204486846924 seconds
population_evaluation took 2.0883917808532715 seconds
population_evaluation took 2.094752788543701 seconds
population_evaluation took 2.135258197784424 seconds
population_evaluation took 2.0956859588623047 seconds
population_evaluation took 2.081669569015503 seconds
population_evaluation took 2.074988603591919 seconds
population_evaluation took 2.077303409576416 seconds
population_evaluation took 2.062836170196533 seconds
population_evaluation took 2.0455868244171143 seconds
population_evaluation took 2.1546802520751953 seconds
population_evaluation took 2.083989381790161 seconds
population_evaluation took 2.176499128341675 seconds
population_evaluation took 2.082233428955078 seconds
population_evaluation took 2.093121290206909 seconds
population_evaluation took 2.1070313453674316 seconds
  Tamamlandı.


============================================================
  Hedef: h buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 31/31 [00:00<00:00, 568.39it/s]
r_index: 100%|##########| 23/23 [00:00<00:00, 1395.39it/s]

  [3/4] STGP-EF eğitim...
population_evaluation took 2.0568156242370605 seconds
population_evaluation took 2.041013717651367 seconds
population_evaluation took 2.065953016281128 seconds
population_evaluation took 2.119537115097046 seconds
population_evaluation took 2.1449499130249023 seconds
population_evaluation took 2.1921677589416504 seconds
population_evaluation took 2.1532511711120605 seconds
population_evaluation took 2.1160404682159424 seconds
population_evaluation took 2.1772420406341553 seconds
population_evaluation took 2.1171610355377197 seconds
population_evaluation took 2.141596794128418 seconds
population_evaluation took 2.1785075664520264 seconds
population_evaluation took 2.2427191734313965 seconds
population_evaluation took 2.256870985031128 seconds
population_evaluation took 2.2896041870117188 seconds
population_evaluation took 2.124221086502075 seconds
population_evaluation took 2.371234178543091 seconds
population_evaluation took 2.182375192642212 seconds
population_evaluation took 2.1922049522399902 seconds
population_evaluation took 2.19179368019104 seconds
population_evaluation took 2.14129376411438 seconds
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 31/31 [00:00<00:00, 620.05it/s]
r_index: 100%|##########| 23/23 [00:00<00:00, 4027.09it/s]

population_evaluation took 2.139775037765503 seconds
population_evaluation took 2.1269466876983643 seconds
population_evaluation took 2.1464505195617676 seconds
population_evaluation took 2.034294366836548 seconds
population_evaluation took 2.092637062072754 seconds
population_evaluation took 2.0573482513427734 seconds
population_evaluation took 2.065171003341675 seconds
population_evaluation took 2.0650196075439453 seconds
population_evaluation took 2.1527910232543945 seconds
population_evaluation took 2.0427136421203613 seconds
population_evaluation took 2.1444456577301025 seconds
population_evaluation took 2.0505807399749756 seconds
population_evaluation took 2.076434850692749 seconds
population_evaluation took 2.044559955596924 seconds
population_evaluation took 2.296191692352295 seconds
population_evaluation took 2.1629281044006348 seconds
population_evaluation took 2.108640432357788 seconds
population_evaluation took 2.071164131164551 seconds
population_evaluation took 2.0346357822418213 seconds
population_evaluation took 2.153414726257324 seconds
population_evaluation took 2.1498260498046875 seconds
  Tamamlandı.


============================================================
  Hedef: s sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 29/29 [00:00<00:00, 1018.93it/s]
r_index: 100%|##########| 7/7 [00:00<?, ?it/s]
dist_matrix: 100%|##########| 25/25 [00:00<00:00, 875.07it/s]
r_index: 100%|##########| 10/10 [00:00<00:00, 669.40it/s]

  [3/4] STGP-EF eğitim...
population_evaluation took 2.1373090744018555 seconds
population_evaluation took 2.240644693374634 seconds
population_evaluation took 2.2456583976745605 seconds
population_evaluation took 2.212743043899536 seconds
population_evaluation took 2.1205368041992188 seconds
population_evaluation took 2.255362033843994 seconds
population_evaluation took 2.35174560546875 seconds
population_evaluation took 2.151419162750244 seconds
population_evaluation took 2.20112681388855 seconds
population_evaluation took 2.124343156814575 seconds
population_evaluation took 2.185234785079956 seconds
population_evaluation took 2.120905637741089 seconds
population_evaluation took 2.1655678749084473 seconds
population_evaluation took 2.169724225997925 seconds
population_evaluation took 2.177173137664795 seconds
population_evaluation took 2.1333727836608887 seconds
population_evaluation took 2.1627328395843506 seconds
population_evaluation took 2.0245094299316406 seconds
population_evaluation took 1.9922208786010742 seconds
population_evaluation took 1.9444160461425781 seconds
population_evaluation took 1.9913136959075928 seconds
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 29/29 [00:00<00:00, 818.86it/s]
r_index: 100%|##########| 7/7 [00:00<00:00, 2334.99it/s]
dist_matrix: 100%|##########| 25/25 [00:00<00:00, 1261.37it/s]
r_index: 100%|##########| 10/10 [00:00<00:00, 6807.83it/s]

population_evaluation took 2.1181302070617676 seconds
population_evaluation took 2.107461929321289 seconds
population_evaluation took 2.0732975006103516 seconds
population_evaluation took 2.115724802017212 seconds
population_evaluation took 2.199904441833496 seconds
population_evaluation took 2.0465314388275146 seconds
population_evaluation took 2.2075374126434326 seconds
population_evaluation took 2.156507968902588 seconds
population_evaluation took 2.195345401763916 seconds
population_evaluation took 2.1089212894439697 seconds
population_evaluation took 2.11102557182312 seconds
population_evaluation took 2.087843656539917 seconds
population_evaluation took 2.141690254211426 seconds
population_evaluation took 2.096160411834717 seconds
population_evaluation took 2.154057741165161 seconds
population_evaluation took 2.1300783157348633 seconds
population_evaluation took 2.088390827178955 seconds
population_evaluation took 2.182675361633301 seconds
population_evaluation took 2.125300407409668 seconds
population_evaluation took 2.1012070178985596 seconds
population_evaluation took 2.0486865043640137 seconds
  Tamamlandı.


============================================================
  Hedef: s buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 6/6 [00:00<00:00, 5962.05it/s]
synth_matrix: 100%|##########| 6/6 [00:00<00:00, 379.87it/s]

  [3/4] STGP-EF eğitim...
population_evaluation took 2.01419997215271 seconds
population_evaluation took 2.0396852493286133 seconds
population_evaluation took 2.0459823608398438 seconds
population_evaluation took 2.0594987869262695 seconds
population_evaluation took 2.0203733444213867 seconds
population_evaluation took 2.024625539779663 seconds
population_evaluation took 2.068958044052124 seconds
population_evaluation took 1.9944655895233154 seconds
population_evaluation took 2.0587167739868164 seconds
population_evaluation took 2.0040316581726074 seconds
population_evaluation took 2.0784332752227783 seconds
population_evaluation took 2.049217939376831 seconds
population_evaluation took 2.055417060852051 seconds
population_evaluation took 2.179905414581299 seconds
population_evaluation took 2.150815963745117 seconds
population_evaluation took 2.178053617477417 seconds
population_evaluation took 2.1319828033447266 seconds
population_evaluation took 2.0368804931640625 seconds
population_evaluation took 2.0604443550109863 seconds
population_evaluation took 2.0543088912963867 seconds
population_evaluation took 2.1362292766571045 seconds
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 6/6 [00:00<?, ?it/s]
synth_matrix: 100%|##########| 6/6 [00:00<00:00, 384.45it/s]

population_evaluation took 2.144896984100342 seconds
population_evaluation took 2.2274341583251953 seconds
population_evaluation took 2.0674068927764893 seconds
population_evaluation took 2.10146427154541 seconds
population_evaluation took 2.075481414794922 seconds
population_evaluation took 2.095302104949951 seconds
population_evaluation took 2.21990704536438 seconds
population_evaluation took 2.1604292392730713 seconds
population_evaluation took 2.1112794876098633 seconds
population_evaluation took 2.0895705223083496 seconds
population_evaluation took 2.109372854232788 seconds
population_evaluation took 1.9883744716644287 seconds
population_evaluation took 1.9853508472442627 seconds
population_evaluation took 2.021662712097168 seconds
population_evaluation took 2.021524667739868 seconds
population_evaluation took 2.0498998165130615 seconds
population_evaluation took 2.0893096923828125 seconds
population_evaluation took 2.145250082015991 seconds
population_evaluation took 2.042203426361084 seconds
population_evaluation took 2.1245269775390625 seconds
population_evaluation took 2.11039137840271 seconds
  Tamamlandı.

### 3.1 Doymuş Buhar — Sonuç Tablosu

In [6]:
df_doymus_results = build_results_table(doymus_results)
df_doymus_results

               Hedef        Senaryo Algoritma  R2_Score
0           P(çıktı)           Base        RF    0.9997
1           P(çıktı)           Base        ET    1.0000
2           P(çıktı)           Base  AdaBoost    0.9986
3           P(çıktı)           Base      GBDT    0.9992
4           P(çıktı)           Base      DART    0.9610
..               ...            ...       ...       ...
219  s buhar (çıktı)  SMOGN+STGP-EF      GBDT    0.9648
220  s buhar (çıktı)  SMOGN+STGP-EF      DART    0.9375
221  s buhar (çıktı)  SMOGN+STGP-EF   XGBoost    0.9645
222  s buhar (çıktı)  SMOGN+STGP-EF  LightGBM    0.9540
223  s buhar (çıktı)  SMOGN+STGP-EF  CatBoost    0.9517

[224 rows x 4 columns]

### 3.2 Doymuş Buhar — Senaryo Karşılaştırması

In [7]:
compare_scenarios(df_doymus_results)

Senaryo                     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Hedef           Algoritma
P(çıktı)        AdaBoost  0.9986 0.9961   0.9991         0.9979
                CatBoost  0.9995 0.9985   0.9997         0.9997
                DART      0.9610 0.8992   0.9669         0.9233
                ET        1.0000 0.9999   1.0000         1.0000
                GBDT      0.9992 0.9986   0.9994         0.9989
                LightGBM  0.9710 0.9189   0.9967         0.9942
                RF        0.9997 0.9993   0.9999         0.9989
                XGBoost   0.9991 0.9975   0.9985         0.9970
h buhar (çıktı) AdaBoost  0.9961 0.9954   0.9989         0.9933
                CatBoost  0.9993 0.9980   0.9995         0.9986
                DART      0.9765 0.8882   0.9858         0.9618
                ET        1.0000 0.9999   1.0000         0.9998
                GBDT      0.9990 0.9982   0.9994         0.9986
                LightGBM  0.9747 0.8870   0.9958         0.9885
                RF        0.9997 0.9989   0.9998         0.9985
                XGBoost   0.9986 0.9978   0.9986         0.9960
h sıvı (çıktı)  AdaBoost  0.9993 0.9954   0.9992         0.9947
                CatBoost  0.9996 0.9977   0.9995         0.9985
                DART      0.9749 0.7595   0.9827         0.8592
                ET        1.0000 0.9999   1.0000         1.0000
                GBDT      0.9993 0.9968   0.9996         0.9977
                LightGBM  0.9793 0.7753   0.9978         0.9577
                RF        0.9998 0.9987   0.9999         0.9988
                XGBoost   0.9991 0.9924   0.9988         0.9907
s buhar (çıktı) AdaBoost  0.9163 0.8439   0.9661         0.9301
                CatBoost  0.9793 0.9826   0.9979         0.9517
                DART      0.4471 0.8853   0.8510         0.9375
                ET        0.9996 0.9996   0.9997         0.8572
                GBDT      0.9737 0.9695   0.9956         0.9648
                LightGBM  0.4591 0.9098   0.9484         0.9540
                RF        0.9899 0.9824   0.9975         0.9480
                XGBoost   0.9785 0.9634   0.9748         0.9645
s sıvı (çıktı)  AdaBoost  0.9996 0.9977   0.9995         0.9963
                CatBoost  0.9995 0.9987   0.9996         0.9993
                DART      0.9753 0.9834   0.9853         0.9887
                ET        1.0000 0.9999   1.0000         0.9999
                GBDT      0.9993 0.9986   0.9996         0.9991
                LightGBM  0.9778 0.9887   0.9974         0.9979
                RF        0.9998 0.9991   0.9999         0.9993
                XGBoost   0.9990 0.9959   0.9985         0.9957
v buhar (çıktı) AdaBoost  0.9909 0.9970   0.9920         0.9973
                CatBoost  0.9971 0.9979   0.9985         0.9977
                DART      0.8327 0.9836   0.9253         0.9863
                ET        1.0000 0.9994   1.0000         0.9991
                GBDT      0.9965 0.9980   0.9988         0.9987
                LightGBM  0.8011 0.9929   0.9781         0.9975
                RF        0.9989 0.9993   0.9995         0.9993
                XGBoost   0.9951 0.9959   0.9929         0.9938
v sıvı (çıktı)  AdaBoost  0.9971 0.9979   0.9987         0.9952
                CatBoost  0.9986 0.9990   0.9994         0.9996
                DART      0.9345 0.9417   0.9492         0.9580
                ET        1.0000 0.9996   0.9999         1.0000
                GBDT      0.9978 0.9991   0.9991         0.9995
                LightGBM  0.9429 0.9394   0.9958         0.9922
                RF        0.9992 0.9993   0.9998         0.9996
                XGBoost   0.9981 0.9979   0.9978         0.9959

### 3.3 Doymuş Buhar — En İyi Sonuçlar

In [8]:
show_best_results(df_doymus_results)

             Hedef  Senaryo Algoritma  R2_Score
0         P(çıktı)     Base        ET    1.0000
1  h buhar (çıktı)     Base        ET    1.0000
2   h sıvı (çıktı)  STGP-EF        ET    1.0000
3  s buhar (çıktı)  STGP-EF        ET    0.9997
4   s sıvı (çıktı)     Base        ET    1.0000
5  v buhar (çıktı)  STGP-EF        ET    1.0000
6   v sıvı (çıktı)     Base        ET    1.0000

### 3.4 Doymuş Buhar — Hedef Bazlı Detay

Herhangi bir hedef değişken için detaylı pivot tablo görmek isterseniz:

In [9]:
# Örnek: P(çıktı) hedefi için senaryo karşılaştırması
target_summary(df_doymus_results, 'P(çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9986 0.9961   0.9991         0.9979
CatBoost  0.9995 0.9985   0.9997         0.9997
DART      0.9610 0.8992   0.9669         0.9233
ET        1.0000 0.9999   1.0000         1.0000
GBDT      0.9992 0.9986   0.9994         0.9989
LightGBM  0.9710 0.9189   0.9967         0.9942
RF        0.9997 0.9993   0.9999         0.9989
XGBoost   0.9991 0.9975   0.9985         0.9970

---
## 4. Kızgın Buhar — Eğitim

**Girdiler:** T (girdi), P (girdi)  
**Çıktılar (her biri ayrı ayrı):** v, h, s

In [10]:
kizgin_results = run_kizgin_analysis(df_kizgin)

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  KIZGIN BUHAR ANALİZİ
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

============================================================
  Hedef: v (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 90/90 [00:00<00:00, 308.21it/s]
synth_matrix: 100%|##########| 90/90 [00:00<00:00, 2581.13it/s]
r_index: 100%|##########| 51/51 [00:00<00:00, 2455.48it/s]

  [3/4] STGP-EF eğitim...
population_evaluation took 2.7741713523864746 seconds
population_evaluation took 2.7560036182403564 seconds
population_evaluation took 2.743237257003784 seconds
population_evaluation took 2.6433041095733643 seconds
population_evaluation took 2.541635036468506 seconds
population_evaluation took 2.6244754791259766 seconds
population_evaluation took 3.1254470348358154 seconds
population_evaluation took 2.6323719024658203 seconds
population_evaluation took 2.630619764328003 seconds
population_evaluation took 2.6075563430786133 seconds
population_evaluation took 2.627789258956909 seconds
population_evaluation took 2.562854051589966 seconds
population_evaluation took 2.5744121074676514 seconds
population_evaluation took 2.5415496826171875 seconds
population_evaluation took 2.4914791584014893 seconds
population_evaluation took 2.5765633583068848 seconds
population_evaluation took 2.5571227073669434 seconds
population_evaluation took 2.6175453662872314 seconds
population_evaluation took 2.5992586612701416 seconds
population_evaluation took 2.6456103324890137 seconds
population_evaluation took 2.5889594554901123 seconds
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 90/90 [00:00<00:00, 298.92it/s]
synth_matrix: 100%|##########| 90/90 [00:00<00:00, 3177.45it/s]
r_index: 100%|##########| 51/51 [00:00<00:00, 2777.50it/s]

population_evaluation took 2.5548484325408936 seconds
population_evaluation took 2.5346734523773193 seconds
population_evaluation took 2.4722788333892822 seconds
population_evaluation took 2.518064260482788 seconds
population_evaluation took 2.4404122829437256 seconds
population_evaluation took 2.4513003826141357 seconds
population_evaluation took 2.409538507461548 seconds
population_evaluation took 2.464674234390259 seconds
population_evaluation took 2.39094614982605 seconds
population_evaluation took 2.5599331855773926 seconds
population_evaluation took 2.5693767070770264 seconds
population_evaluation took 2.544420003890991 seconds
population_evaluation took 2.7823665142059326 seconds
population_evaluation took 2.5072720050811768 seconds
population_evaluation took 2.685667037963867 seconds
population_evaluation took 2.413442850112915 seconds
population_evaluation took 2.4823524951934814 seconds
population_evaluation took 2.427206516265869 seconds
population_evaluation took 2.445666790008545 seconds
population_evaluation took 2.369969367980957 seconds
population_evaluation took 2.369072914123535 seconds
  Tamamlandı.


============================================================
  Hedef: h (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 55/55 [00:00<00:00, 512.69it/s]
synth_matrix: 100%|##########| 55/55 [00:00<00:00, 905.05it/s]
r_index: 100%|##########| 11/11 [00:00<00:00, 2750.36it/s]

  [3/4] STGP-EF eğitim...
population_evaluation took 2.6882007122039795 seconds
population_evaluation took 2.7503886222839355 seconds
population_evaluation took 2.840196132659912 seconds
population_evaluation took 2.951777935028076 seconds
population_evaluation took 2.913024663925171 seconds
population_evaluation took 2.945608377456665 seconds
population_evaluation took 2.841604232788086 seconds
population_evaluation took 2.906210422515869 seconds
population_evaluation took 2.965444564819336 seconds
population_evaluation took 3.0027925968170166 seconds
population_evaluation took 2.9227471351623535 seconds
population_evaluation took 2.9398670196533203 seconds
population_evaluation took 2.9297454357147217 seconds
population_evaluation took 2.911105155944824 seconds
population_evaluation took 2.8414058685302734 seconds
population_evaluation took 2.800466537475586 seconds
population_evaluation took 2.810112953186035 seconds
population_evaluation took 2.768641710281372 seconds
population_evaluation took 4.2641518115997314 seconds
population_evaluation took 10.778064489364624 seconds
population_evaluation took 2.9583468437194824 seconds
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 55/55 [00:00<00:00, 455.29it/s]
synth_matrix: 100%|##########| 55/55 [00:00<00:00, 882.01it/s]
r_index: 100%|##########| 11/11 [00:00<?, ?it/s]
dist_matrix: 100%|##########| 55/55 [00:00<00:00, 487.01it/s]
synth_matrix: 100%|##########| 55/55 [00:00<00:00, 922.00it/s]
r_index: 100%|##########| 11/11 [00:00<?, ?it/s]
dist_matrix: 100%|##########| 119/119 [00:00<00:00, 220.50it/s]
r_index: 100%|##########| 35/35 [00:00<00:00, 6359.69it/s]
dist_matrix: 100%|##########| 118/118 [00:00<00:00, 230.32it/s]
r_index: 100%|##########| 36/36 [00:00<00:00, 3078.83it/s]

population_evaluation took 2.5013086795806885 seconds
population_evaluation took 2.544093608856201 seconds
population_evaluation took 2.587315320968628 seconds
population_evaluation took 2.670003890991211 seconds
population_evaluation took 2.620978832244873 seconds
population_evaluation took 2.6690399646759033 seconds
population_evaluation took 2.60064435005188 seconds
population_evaluation took 2.675111770629883 seconds
population_evaluation took 2.6127028465270996 seconds
population_evaluation took 2.6048266887664795 seconds
population_evaluation took 2.6348369121551514 seconds
population_evaluation took 2.527406692504883 seconds
population_evaluation took 2.692356586456299 seconds
population_evaluation took 2.5225746631622314 seconds
population_evaluation took 2.6146976947784424 seconds
population_evaluation took 2.522655487060547 seconds
population_evaluation took 2.6683108806610107 seconds
population_evaluation took 2.6269309520721436 seconds
population_evaluation took 2.797459840774536 seconds
population_evaluation took 2.662838935852051 seconds
population_evaluation took 2.66283917427063 seconds
  Tamamlandı.


============================================================
  Hedef: s (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 61/61 [00:00<00:00, 446.24it/s]
synth_matrix: 100%|##########| 61/61 [00:00<00:00, 1273.16it/s]
r_index: 100%|##########| 48/48 [00:00<00:00, 2724.86it/s]

  [3/4] STGP-EF eğitim...
population_evaluation took 2.7078025341033936 seconds
population_evaluation took 2.8488576412200928 seconds
population_evaluation took 2.843410015106201 seconds
population_evaluation took 2.9564852714538574 seconds
population_evaluation took 2.8473968505859375 seconds
population_evaluation took 2.887410879135132 seconds
population_evaluation took 2.9416933059692383 seconds
population_evaluation took 2.908872365951538 seconds
population_evaluation took 2.9249770641326904 seconds
population_evaluation took 2.8786442279815674 seconds
population_evaluation took 2.904649019241333 seconds
population_evaluation took 2.9700119495391846 seconds
population_evaluation took 2.939948558807373 seconds
population_evaluation took 2.944908380508423 seconds
population_evaluation took 2.96042799949646 seconds
population_evaluation took 2.932420015335083 seconds
population_evaluation took 2.9502525329589844 seconds
population_evaluation took 3.0202348232269287 seconds
population_evaluation took 2.951159715652466 seconds
population_evaluation took 2.903357982635498 seconds
population_evaluation took 2.9005908966064453 seconds
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 61/61 [00:00<00:00, 412.16it/s]
synth_matrix: 100%|##########| 61/61 [00:00<00:00, 1162.69it/s]
r_index: 100%|##########| 48/48 [00:00<00:00, 1519.32it/s]

population_evaluation took 2.565830707550049 seconds
population_evaluation took 2.6322672367095947 seconds
population_evaluation took 2.680692434310913 seconds
population_evaluation took 2.7274792194366455 seconds
population_evaluation took 2.692316770553589 seconds
population_evaluation took 2.756420612335205 seconds
population_evaluation took 3.060030937194824 seconds
population_evaluation took 2.7476906776428223 seconds
population_evaluation took 2.812431573867798 seconds
population_evaluation took 2.796478271484375 seconds
population_evaluation took 2.779672861099243 seconds
population_evaluation took 2.835521936416626 seconds
population_evaluation took 2.7951598167419434 seconds
population_evaluation took 2.775096893310547 seconds
population_evaluation took 2.7643210887908936 seconds
population_evaluation took 2.840796709060669 seconds
population_evaluation took 2.7847418785095215 seconds
population_evaluation took 2.7466413974761963 seconds
population_evaluation took 2.7717764377593994 seconds
population_evaluation took 2.768798351287842 seconds
population_evaluation took 2.7924609184265137 seconds
  Tamamlandı.

### 4.1 Kızgın Buhar — Sonuç Tablosu

In [11]:
df_kizgin_results = build_results_table(kizgin_results)
df_kizgin_results

        Hedef        Senaryo Algoritma  R2_Score
0   v (çıktı)           Base        RF    0.9991
1   v (çıktı)           Base        ET    0.9998
2   v (çıktı)           Base  AdaBoost    0.9822
3   v (çıktı)           Base      GBDT    0.9993
4   v (çıktı)           Base      DART    0.9908
..        ...            ...       ...       ...
91  s (çıktı)  SMOGN+STGP-EF      GBDT    0.9915
92  s (çıktı)  SMOGN+STGP-EF      DART    0.9774
93  s (çıktı)  SMOGN+STGP-EF   XGBoost    0.9844
94  s (çıktı)  SMOGN+STGP-EF  LightGBM    0.9917
95  s (çıktı)  SMOGN+STGP-EF  CatBoost    0.9891

[96 rows x 4 columns]

### 4.2 Kızgın Buhar — Senaryo Karşılaştırması

In [12]:
compare_scenarios(df_kizgin_results)

Senaryo               Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Hedef     Algoritma
h (çıktı) AdaBoost  0.9703 0.9701   0.9969         0.9367
          CatBoost  0.9988 0.9966   0.9990         0.9975
          DART      0.9776 0.9788   0.9895         0.9875
          ET        0.9997 0.9989   0.9998         0.9993
          GBDT      0.9981 0.9966   0.9994         0.9967
          LightGBM  0.9859 0.9914   0.9983         0.9971
          RF        0.9985 0.9954   0.9996         0.9979
          XGBoost   0.9988 0.9962   0.9987         0.9976
s (çıktı) AdaBoost  0.8655 0.8648   0.9785         0.9361
          CatBoost  0.9959 0.9909   0.9960         0.9891
          DART      0.9595 0.8668   0.9915         0.9774
          ET        0.9966 0.9904   0.9985         0.9868
          GBDT      0.9911 0.9783   0.9972         0.9915
          LightGBM  0.9771 0.8959   0.9964         0.9917
          RF        0.9846 0.9695   0.9927         0.9842
          XGBoost   0.9941 0.9769   0.9926         0.9844
v (çıktı) AdaBoost  0.9822 0.9729   0.9872         0.9533
          CatBoost  0.9979 0.9977   0.9995         0.9978
          DART      0.9908 0.9908   0.9949         0.9743
          ET        0.9998 0.9996   0.9998         0.9997
          GBDT      0.9993 0.9989   0.9994         0.9985
          LightGBM  0.9961 0.9952   0.9987         0.9879
          RF        0.9991 0.9990   0.9987         0.9955
          XGBoost   0.9981 0.9981   0.9977         0.9972

### 4.3 Kızgın Buhar — En İyi Sonuçlar

In [13]:
show_best_results(df_kizgin_results)

       Hedef  Senaryo Algoritma  R2_Score
0  h (çıktı)  STGP-EF        ET    0.9998
1  s (çıktı)  STGP-EF        ET    0.9985
2  v (çıktı)  STGP-EF        ET    0.9998

---
## 5. Genel Karşılaştırma

In [14]:
# Tüm sonuçları birleştir
df_doymus_results['Veri Seti'] = 'Doymuş Buhar'
df_kizgin_results['Veri Seti'] = 'Kızgın Buhar'
df_all = pd.concat([df_doymus_results, df_kizgin_results], ignore_index=True)

print(f'Toplam değerlendirme sayısı: {len(df_all)}')
df_all.head(10)

Toplam değerlendirme sayısı: 320

      Hedef Senaryo Algoritma  R2_Score     Veri Seti
0  P(çıktı)    Base        RF    0.9997  Doymuş Buhar
1  P(çıktı)    Base        ET    1.0000  Doymuş Buhar
2  P(çıktı)    Base  AdaBoost    0.9986  Doymuş Buhar
3  P(çıktı)    Base      GBDT    0.9992  Doymuş Buhar
4  P(çıktı)    Base      DART    0.9610  Doymuş Buhar
5  P(çıktı)    Base   XGBoost    0.9991  Doymuş Buhar
6  P(çıktı)    Base  LightGBM    0.9710  Doymuş Buhar
7  P(çıktı)    Base  CatBoost    0.9995  Doymuş Buhar
8  P(çıktı)   SMOGN        RF    0.9993  Doymuş Buhar
9  P(çıktı)   SMOGN        ET    0.9999  Doymuş Buhar

In [15]:
# Senaryo bazlı ortalama R² skorları
df_all.groupby(['Veri Seti', 'Senaryo'])['R2_Score'].mean().unstack()

Senaryo        Base  SMOGN  SMOGN+STGP-EF  STGP-EF
Veri Seti
Doymuş Buhar 0.9642 0.9718         0.9828   0.9902
Kızgın Buhar 0.9856 0.9754         0.9857   0.9958

In [16]:
# Algoritma bazlı ortalama R² skorları
df_all.groupby(['Veri Seti', 'Algoritma'])['R2_Score'].mean().unstack()

Algoritma     AdaBoost  CatBoost   DART     ET   GBDT  LightGBM     RF  XGBoost
Veri Seti
Doymuş Buhar    0.9850    0.9959 0.9180 0.9948 0.9954    0.9396 0.9965   0.9929
Kızgın Buhar    0.9512    0.9964 0.9733 0.9974 0.9954    0.9843 0.9929   0.9942

In [17]:
# Geniş formatlı sonuç tablosu oluştur ve kaydet
df_wide = save_wide_results(df_all, 'R515B_Ozellikler/Model_Training_Results.csv')
print('Sonuçlar R515B_Ozellikler/Model_Training_Results.csv dosyasına kaydedildi.')
print(f'Format: Geniş tablo — {len(df_wide)} satır, {len(df_wide.columns)} sütun')
df_wide

Sonuçlar R515B_Ozellikler/Model_Training_Results.csv dosyasına kaydedildi.
Format: Geniş tablo — 80 satır, 9 sütun

Senaryo     Veri Seti      Hedef Algoritma   Base  SMOGN  STGP-EF  SMOGN+STGP-EF  Maks_R2 Maks_Senaryo
0        Doymuş Buhar   P(çıktı)  AdaBoost 0.9986 0.9961   0.9991         0.9979   0.9991      STGP-EF
1        Doymuş Buhar   P(çıktı)  CatBoost 0.9995 0.9985   0.9997         0.9997   0.9997      STGP-EF
2        Doymuş Buhar   P(çıktı)      DART 0.9610 0.8992   0.9669         0.9233   0.9669      STGP-EF
3        Doymuş Buhar   P(çıktı)        ET 1.0000 0.9999   1.0000         1.0000   1.0000         Base
4        Doymuş Buhar   P(çıktı)      GBDT 0.9992 0.9986   0.9994         0.9989   0.9994      STGP-EF
..                ...        ...       ...    ...    ...      ...            ...      ...          ...
75       Kızgın Buhar  v (çıktı)        ET 0.9998 0.9996   0.9998         0.9997   0.9998      STGP-EF
76       Kızgın Buhar  v (çıktı)      GBDT 0.9993 0.9989   0.9994         0.9985   0.9994      STGP-EF
77       Kızgın Buhar  v (çıktı)  LightGBM 0.9961 0.9952   0.9987         0.9879   0.9987      STGP-EF
78       Kızgın Buhar  v (çıktı)        RF 0.9991 0.9990   0.9987         0.9955   0.9991         Base
79       Kızgın Buhar  v (çıktı)   XGBoost 0.9981 0.9981   0.9977         0.9972   0.9981        SMOGN

[80 rows x 9 columns]