# R515B Soğutucu Akışkan — Model Eğitimi

Bu notebook, Doymuş ve Kızgın buhar veri setleri için **4 farklı senaryo** ile regresyon modeli eğitimi yapar:

| # | Senaryo | Açıklama |
|---|---------|----------|
| 1 | **Base** | Orijinal veri ile temel eğitim |
| 2 | **SMOGN** | SMOGN ile veri artırma sonrası eğitim |
| 3 | **STGP-EF** | SymbolicTransformer  ve Evolutionary Forest Hibrit Yöntemi ile öznitelik inşası sonrası eğitim |
| 4 | **SMOGN+STGP-EF** | Önce SMOGN, sonra STGP-EF ile birleşik eğitim |

Her senaryo **8 farklı regresyon algoritması** ile değerlendirilir (RF, ET, AdaBoost, GBDT, DART, XGBoost, LightGBM, CatBoost).

---

## 1. Kütüphaneler ve Fonksiyonlar

In [1]:
import sys
sys.path.insert(0, 'R515B_Ozellikler')

import pandas as pd
import numpy as np
from Functions import (
    run_doymus_analysis,
    run_kizgin_analysis,
    build_results_table,
    compare_scenarios,
    show_best_results,
    target_summary,
    save_wide_results
)

print('Fonksiyonlar başarıyla yüklendi.')

c:\Users\SGUZEY\Documents\Yüksek Lisans Dersleri\Veri Mühendisliği\Data_Engineering_Project\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Fonksiyonlar başarıyla yüklendi.

## 2. Veri Yükleme

In [2]:
df_doymus = pd.read_csv('R515B_Ozellikler/R515B_Doymus_Ozellikleri.csv')
df_kizgin = pd.read_csv('R515B_Ozellikler/R515B_Kizgin_Buhar.csv')

print(f'Doymuş Buhar: {df_doymus.shape}')
print(f'Kızgın Buhar: {df_kizgin.shape}')
print(f'\nDoymuş Sütunlar: {list(df_doymus.columns)}')
print(f'Kızgın Sütunlar: {list(df_kizgin.columns)}')

Doymuş Buhar: (136, 8)
Kızgın Buhar: (578, 5)

Doymuş Sütunlar: ['T(girdi)', 'P(çıktı)', 'v sıvı (çıktı)', 'v buhar (çıktı)', 'h sıvı (çıktı)', 'h buhar (çıktı)', 's sıvı (çıktı)', 's buhar (çıktı)']
Kızgın Sütunlar: ['T (girdi)', 'P (girdi)', 'v (çıktı)', 'h (çıktı)', 's (çıktı)']

In [3]:
df_doymus.head()

   T(girdi)  P(çıktı)  v sıvı (çıktı)  v buhar (çıktı)  h sıvı (çıktı)  h buhar (çıktı)  s sıvı (çıktı)  s buhar (çıktı)
0       -30   61.2210          0.0007           0.2726          2.7282         198.2000          0.0446           0.8486
1       -29   64.2350          0.0007           0.2606          3.9422         198.8900          0.0496           0.8481
2       -28   67.3670          0.0007           0.2492          5.1587         199.5800          0.0546           0.8476
3       -27   70.6200          0.0007           0.2385          6.3775         200.2700          0.0595           0.8472
4       -26   73.9960          0.0008           0.2282          7.5988         200.9500          0.0645           0.8468

In [4]:
df_kizgin.head()

   T (girdi)  P (girdi)  v (çıktı)  h (çıktı)  s (çıktı)
0        -30         50     0.3357   198.5500     0.8639
1        -25         50     0.3433   202.4500     0.8798
2        -20         50     0.3508   206.4000     0.8956
3        -15         50     0.3582   210.4000     0.9112
4        -10         50     0.3656   214.4300     0.9267

---
## 3. Doymuş Buhar — Eğitim

**Girdi:** T(girdi)  
**Çıktılar (her biri ayrı ayrı):** P, v sıvı, v buhar, h sıvı, h buhar, s sıvı, s buhar

In [5]:
doymus_results = run_doymus_analysis(df_doymus)

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  DOYMUŞ BUHAR ANALİZİ
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

============================================================
  Hedef: P(çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 2.2484912872314453 seconds
population_evaluation took 2.0202488899230957 seconds
population_evaluation took 2.1013965606689453 seconds
population_evaluation took 2.0380985736846924 seconds
population_evaluation took 2.000495195388794 seconds
population_evaluation took 2.0354652404785156 seconds
population_evaluation took 2.006697654724121 seconds
population_evaluation took 2.0351791381835938 seconds
population_evaluation took 1.993091344833374 seconds
population_evaluation took 2.4429798126220703 seconds
population_evaluation took 1.9787423610687256 seconds
population_evaluation took 2.0279629230499268 seconds
population_evaluation took 1.9625227451324463 seconds
population_evaluation took 1.983900785446167 seconds
population_evaluation took 1.985656499862671 seconds
population_evaluation took 1.9235014915466309 seconds
population_evaluation took 2.0136842727661133 seconds
population_evaluation took 1.9575824737548828 seconds
population_evaluation took 2.000579595565796 seconds
population_evaluation took 1.9614930152893066 seconds
population_evaluation took 1.9645054340362549 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 29/29 [00:00<00:00, 431.90it/s]
r_index: 100%|##########| 25/25 [00:00<00:00, 4824.37it/s]

population_evaluation took 2.0195975303649902 seconds
population_evaluation took 2.0508830547332764 seconds
population_evaluation took 2.029853343963623 seconds
population_evaluation took 2.0646073818206787 seconds
population_evaluation took 2.021310567855835 seconds
population_evaluation took 2.0151891708374023 seconds
population_evaluation took 1.9238860607147217 seconds
population_evaluation took 1.9095563888549805 seconds
population_evaluation took 2.016615629196167 seconds
population_evaluation took 1.920316457748413 seconds
population_evaluation took 1.9194839000701904 seconds
population_evaluation took 1.9440414905548096 seconds
population_evaluation took 1.9319822788238525 seconds
population_evaluation took 1.9348206520080566 seconds
population_evaluation took 1.947054147720337 seconds
population_evaluation took 1.9397821426391602 seconds
population_evaluation took 1.9031262397766113 seconds
population_evaluation took 1.9307219982147217 seconds
population_evaluation took 1.9142136573791504 seconds
population_evaluation took 1.874807596206665 seconds
population_evaluation took 1.91658616065979 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 1.9495680332183838 seconds
population_evaluation took 1.9309368133544922 seconds
population_evaluation took 1.9519078731536865 seconds
population_evaluation took 1.976355791091919 seconds
population_evaluation took 2.0539419651031494 seconds
population_evaluation took 1.9816341400146484 seconds
population_evaluation took 2.037339925765991 seconds
population_evaluation took 1.9723596572875977 seconds
population_evaluation took 2.0699384212493896 seconds
population_evaluation took 1.905212163925171 seconds
population_evaluation took 1.949692964553833 seconds
population_evaluation took 1.995276689529419 seconds
population_evaluation took 2.005837917327881 seconds
population_evaluation took 1.9746689796447754 seconds
population_evaluation took 1.9737637042999268 seconds
population_evaluation took 2.026919364929199 seconds
population_evaluation took 1.9559953212738037 seconds
population_evaluation took 1.9456422328948975 seconds
population_evaluation took 1.9753074645996094 seconds
population_evaluation took 1.962681770324707 seconds
population_evaluation took 1.9852638244628906 seconds
population_evaluation took 1.9849615097045898 seconds
population_evaluation took 2.020233392715454 seconds
population_evaluation took 1.9910328388214111 seconds
population_evaluation took 2.0024209022521973 seconds
population_evaluation took 1.9869680404663086 seconds
population_evaluation took 2.027066230773926 seconds
population_evaluation took 2.0489766597747803 seconds
population_evaluation took 2.004476308822632 seconds
population_evaluation took 2.0163161754608154 seconds
population_evaluation took 2.029998540878296 seconds
population_evaluation took 2.0218236446380615 seconds
population_evaluation took 2.0011470317840576 seconds
population_evaluation took 2.044343948364258 seconds
population_evaluation took 1.9704523086547852 seconds
population_evaluation took 2.018092632293701 seconds
population_evaluation took 1.9820070266723633 seconds
population_evaluation took 2.011406660079956 seconds
population_evaluation took 2.022812604904175 seconds
population_evaluation took 1.9998254776000977 seconds
population_evaluation took 2.0352516174316406 seconds
population_evaluation took 1.999574899673462 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 1.8939189910888672 seconds
population_evaluation took 1.9478447437286377 seconds
population_evaluation took 2.4045939445495605 seconds
population_evaluation took 1.9669172763824463 seconds
population_evaluation took 1.9428417682647705 seconds
population_evaluation took 1.9135162830352783 seconds
population_evaluation took 1.891875982284546 seconds
population_evaluation took 2.055612087249756 seconds
population_evaluation took 2.531980514526367 seconds
population_evaluation took 2.0458717346191406 seconds
population_evaluation took 1.9982762336730957 seconds
population_evaluation took 2.002290964126587 seconds
population_evaluation took 2.0536093711853027 seconds
population_evaluation took 1.9604482650756836 seconds
population_evaluation took 1.9241857528686523 seconds
population_evaluation took 1.9194104671478271 seconds
population_evaluation took 1.8506836891174316 seconds
population_evaluation took 1.9387073516845703 seconds
population_evaluation took 1.9496331214904785 seconds
population_evaluation took 1.9329774379730225 seconds
population_evaluation took 1.8884773254394531 seconds
population_evaluation took 1.9515087604522705 seconds
population_evaluation took 1.9197540283203125 seconds
population_evaluation took 1.9121687412261963 seconds
population_evaluation took 2.1992173194885254 seconds
population_evaluation took 2.0197982788085938 seconds
population_evaluation took 1.915694236755371 seconds
population_evaluation took 1.9275622367858887 seconds
population_evaluation took 1.952401876449585 seconds
population_evaluation took 1.9020683765411377 seconds
population_evaluation took 1.9392130374908447 seconds
population_evaluation took 1.9187688827514648 seconds
population_evaluation took 1.9088094234466553 seconds
population_evaluation took 1.9753930568695068 seconds
population_evaluation took 1.9881274700164795 seconds
population_evaluation took 1.9581975936889648 seconds
population_evaluation took 1.9702868461608887 seconds
population_evaluation took 2.1467511653900146 seconds
population_evaluation took 1.9590463638305664 seconds
population_evaluation took 1.9027388095855713 seconds
population_evaluation took 2.163590908050537 seconds
population_evaluation took 1.8974997997283936 seconds
  Tamamlandı.


============================================================
  Hedef: v sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 1.9715001583099365 seconds
population_evaluation took 1.9445364475250244 seconds
population_evaluation took 1.943509578704834 seconds
population_evaluation took 1.9659833908081055 seconds
population_evaluation took 1.952348232269287 seconds
population_evaluation took 1.949967861175537 seconds
population_evaluation took 1.969806432723999 seconds
population_evaluation took 1.9358651638031006 seconds
population_evaluation took 1.952078104019165 seconds
population_evaluation took 1.9254286289215088 seconds
population_evaluation took 1.9497156143188477 seconds
population_evaluation took 1.9488959312438965 seconds
population_evaluation took 1.9771521091461182 seconds
population_evaluation took 1.9484953880310059 seconds
population_evaluation took 1.9513370990753174 seconds
population_evaluation took 1.9846808910369873 seconds
population_evaluation took 1.9960753917694092 seconds
population_evaluation took 1.997757911682129 seconds
population_evaluation took 1.9744904041290283 seconds
population_evaluation took 1.973050594329834 seconds
population_evaluation took 1.967048168182373 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 16/16 [00:00<00:00, 704.87it/s]
synth_matrix: 100%|##########| 16/16 [00:00<00:00, 770.29it/s]
r_index: 100%|##########| 6/6 [00:00<00:00, 1196.09it/s]

population_evaluation took 1.9585609436035156 seconds
population_evaluation took 1.9543445110321045 seconds
population_evaluation took 1.9855802059173584 seconds
population_evaluation took 1.9207634925842285 seconds
population_evaluation took 1.9168767929077148 seconds
population_evaluation took 1.9194867610931396 seconds
population_evaluation took 1.9446203708648682 seconds
population_evaluation took 1.8892598152160645 seconds
population_evaluation took 1.8924200534820557 seconds
population_evaluation took 1.8920671939849854 seconds
population_evaluation took 1.9197790622711182 seconds
population_evaluation took 1.913252353668213 seconds
population_evaluation took 1.8883724212646484 seconds
population_evaluation took 1.900406837463379 seconds
population_evaluation took 1.8856611251831055 seconds
population_evaluation took 1.8956804275512695 seconds
population_evaluation took 1.8674871921539307 seconds
population_evaluation took 1.8905353546142578 seconds
population_evaluation took 1.8857429027557373 seconds
population_evaluation took 1.9087493419647217 seconds
population_evaluation took 1.9027996063232422 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 1.936694860458374 seconds
population_evaluation took 1.90568208694458 seconds
population_evaluation took 1.9377031326293945 seconds
population_evaluation took 1.9269928932189941 seconds
population_evaluation took 1.935173749923706 seconds
population_evaluation took 1.9116735458374023 seconds
population_evaluation took 1.9097139835357666 seconds
population_evaluation took 1.8955817222595215 seconds
population_evaluation took 1.9830501079559326 seconds
population_evaluation took 1.9215269088745117 seconds
population_evaluation took 1.9116744995117188 seconds
population_evaluation took 1.9159235954284668 seconds
population_evaluation took 1.9365603923797607 seconds
population_evaluation took 1.9811604022979736 seconds
population_evaluation took 1.9434125423431396 seconds
population_evaluation took 1.9354019165039062 seconds
population_evaluation took 1.9291515350341797 seconds
population_evaluation took 1.92915940284729 seconds
population_evaluation took 1.9332375526428223 seconds
population_evaluation took 1.9508607387542725 seconds
population_evaluation took 1.9191112518310547 seconds
population_evaluation took 1.9724464416503906 seconds
population_evaluation took 1.9915404319763184 seconds
population_evaluation took 1.974801778793335 seconds
population_evaluation took 1.9646482467651367 seconds
population_evaluation took 1.975687026977539 seconds
population_evaluation took 1.9558699131011963 seconds
population_evaluation took 1.9553370475769043 seconds
population_evaluation took 1.9774982929229736 seconds
population_evaluation took 2.1768429279327393 seconds
population_evaluation took 2.0208089351654053 seconds
population_evaluation took 2.0847764015197754 seconds
population_evaluation took 1.9857063293457031 seconds
population_evaluation took 1.842284917831421 seconds
population_evaluation took 1.9747314453125 seconds
population_evaluation took 1.9435601234436035 seconds
population_evaluation took 1.9537382125854492 seconds
population_evaluation took 1.960306167602539 seconds
population_evaluation took 1.9415695667266846 seconds
population_evaluation took 1.7967908382415771 seconds
population_evaluation took 1.8871819972991943 seconds
population_evaluation took 1.956674337387085 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 1.7695810794830322 seconds
population_evaluation took 1.7966673374176025 seconds
population_evaluation took 1.8616528511047363 seconds
population_evaluation took 1.7207245826721191 seconds
population_evaluation took 1.7566978931427002 seconds
population_evaluation took 1.7297084331512451 seconds
population_evaluation took 1.7238404750823975 seconds
population_evaluation took 1.7866897583007812 seconds
population_evaluation took 1.7122957706451416 seconds
population_evaluation took 1.7658140659332275 seconds
population_evaluation took 1.7320828437805176 seconds
population_evaluation took 1.7179622650146484 seconds
population_evaluation took 1.7604236602783203 seconds
population_evaluation took 1.7005915641784668 seconds
population_evaluation took 1.7362844944000244 seconds
population_evaluation took 1.7694091796875 seconds
population_evaluation took 1.7027058601379395 seconds
population_evaluation took 1.7513525485992432 seconds
population_evaluation took 1.7050542831420898 seconds
population_evaluation took 1.7151947021484375 seconds
population_evaluation took 1.7548458576202393 seconds
population_evaluation took 1.742511510848999 seconds
population_evaluation took 1.7678091526031494 seconds
population_evaluation took 1.7185521125793457 seconds
population_evaluation took 1.7126705646514893 seconds
population_evaluation took 1.7706139087677002 seconds
population_evaluation took 1.7469000816345215 seconds
population_evaluation took 1.7631220817565918 seconds
population_evaluation took 1.7210733890533447 seconds
population_evaluation took 1.7720589637756348 seconds
population_evaluation took 1.7792775630950928 seconds
population_evaluation took 1.7664926052093506 seconds
population_evaluation took 1.7342941761016846 seconds
population_evaluation took 1.783217191696167 seconds
population_evaluation took 1.7572872638702393 seconds
population_evaluation took 1.818652868270874 seconds
population_evaluation took 1.9859182834625244 seconds
population_evaluation took 1.7700679302215576 seconds
population_evaluation took 1.7964484691619873 seconds
population_evaluation took 1.728480339050293 seconds
population_evaluation took 1.8005788326263428 seconds
population_evaluation took 1.7497408390045166 seconds
  Tamamlandı.


============================================================
  Hedef: v buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 1.7638986110687256 seconds
population_evaluation took 1.7113256454467773 seconds
population_evaluation took 1.7426762580871582 seconds
population_evaluation took 1.7796618938446045 seconds
population_evaluation took 1.701040267944336 seconds
population_evaluation took 1.7474212646484375 seconds
population_evaluation took 1.7255258560180664 seconds
population_evaluation took 1.7347373962402344 seconds
population_evaluation took 1.7600321769714355 seconds
population_evaluation took 1.7088043689727783 seconds
population_evaluation took 1.7276811599731445 seconds
population_evaluation took 1.7738518714904785 seconds
population_evaluation took 1.7331175804138184 seconds
population_evaluation took 1.7772223949432373 seconds
population_evaluation took 1.7174999713897705 seconds
population_evaluation took 1.729722023010254 seconds
population_evaluation took 1.757572889328003 seconds
population_evaluation took 1.7323849201202393 seconds
population_evaluation took 1.714470386505127 seconds
population_evaluation took 1.7405402660369873 seconds
population_evaluation took 1.7236664295196533 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 21/21 [00:00<00:00, 604.94it/s]
synth_matrix: 100%|##########| 21/21 [00:00<00:00, 1266.69it/s]
r_index: 100%|##########| 12/12 [00:00<00:00, 1464.70it/s]

population_evaluation took 1.731426477432251 seconds
population_evaluation took 1.6867930889129639 seconds
population_evaluation took 1.7486622333526611 seconds
population_evaluation took 1.7024545669555664 seconds
population_evaluation took 1.7035982608795166 seconds
population_evaluation took 1.7201581001281738 seconds
population_evaluation took 1.7276482582092285 seconds
population_evaluation took 1.7415862083435059 seconds
population_evaluation took 1.6867785453796387 seconds
population_evaluation took 1.6833503246307373 seconds
population_evaluation took 1.7198824882507324 seconds
population_evaluation took 1.6807336807250977 seconds
population_evaluation took 1.6866264343261719 seconds
population_evaluation took 1.734527587890625 seconds
population_evaluation took 1.70255446434021 seconds
population_evaluation took 1.7529938220977783 seconds
population_evaluation took 1.6935677528381348 seconds
population_evaluation took 1.7055327892303467 seconds
population_evaluation took 1.7327003479003906 seconds
population_evaluation took 1.7008821964263916 seconds
population_evaluation took 1.7001006603240967 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 1.7244720458984375 seconds
population_evaluation took 1.7363066673278809 seconds
population_evaluation took 1.7885632514953613 seconds
population_evaluation took 1.7345285415649414 seconds
population_evaluation took 1.783339262008667 seconds
population_evaluation took 1.7543272972106934 seconds
population_evaluation took 1.7325963973999023 seconds
population_evaluation took 1.7612638473510742 seconds
population_evaluation took 1.7378768920898438 seconds
population_evaluation took 1.784294843673706 seconds
population_evaluation took 1.751460313796997 seconds
population_evaluation took 1.7635650634765625 seconds
population_evaluation took 1.7761383056640625 seconds
population_evaluation took 1.7354285717010498 seconds
population_evaluation took 1.7420589923858643 seconds
population_evaluation took 1.754561424255371 seconds
population_evaluation took 1.734226942062378 seconds
population_evaluation took 1.7720654010772705 seconds
population_evaluation took 1.7380740642547607 seconds
population_evaluation took 1.762681245803833 seconds
population_evaluation took 1.7885832786560059 seconds
population_evaluation took 1.7859141826629639 seconds
population_evaluation took 1.812222957611084 seconds
population_evaluation took 1.8500378131866455 seconds
population_evaluation took 1.8120551109313965 seconds
population_evaluation took 1.78238844871521 seconds
population_evaluation took 1.7969698905944824 seconds
population_evaluation took 1.8360188007354736 seconds
population_evaluation took 1.7760841846466064 seconds
population_evaluation took 1.8005897998809814 seconds
population_evaluation took 1.7700912952423096 seconds
population_evaluation took 1.7716879844665527 seconds
population_evaluation took 1.8226127624511719 seconds
population_evaluation took 1.9013710021972656 seconds
population_evaluation took 2.1958134174346924 seconds
population_evaluation took 10.011053323745728 seconds
population_evaluation took 10.708989143371582 seconds
population_evaluation took 12.69771957397461 seconds
population_evaluation took 11.388280153274536 seconds
population_evaluation took 13.721594095230103 seconds
population_evaluation took 16.494559049606323 seconds
population_evaluation took 12.948656797409058 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 18.600305557250977 seconds
population_evaluation took 13.219683170318604 seconds
population_evaluation took 10.573621034622192 seconds
population_evaluation took 6.305445909500122 seconds
population_evaluation took 6.896806716918945 seconds
population_evaluation took 6.235266208648682 seconds
population_evaluation took 6.561750173568726 seconds
population_evaluation took 14.673717975616455 seconds
population_evaluation took 9.82849645614624 seconds
population_evaluation took 7.0705647468566895 seconds
population_evaluation took 7.021114110946655 seconds
population_evaluation took 11.905146837234497 seconds
population_evaluation took 15.43090033531189 seconds
population_evaluation took 11.901186466217041 seconds
population_evaluation took 12.227241516113281 seconds
population_evaluation took 14.516203880310059 seconds
population_evaluation took 12.349192142486572 seconds
population_evaluation took 14.601446866989136 seconds
population_evaluation took 13.907328128814697 seconds
population_evaluation took 18.166285514831543 seconds
population_evaluation took 13.54848599433899 seconds
population_evaluation took 11.986087083816528 seconds
population_evaluation took 12.6406409740448 seconds
population_evaluation took 8.139451742172241 seconds
population_evaluation took 9.18688178062439 seconds
population_evaluation took 8.641245365142822 seconds
population_evaluation took 7.832217693328857 seconds
population_evaluation took 10.25174880027771 seconds
population_evaluation took 19.60902214050293 seconds
population_evaluation took 18.79059934616089 seconds
population_evaluation took 16.465320110321045 seconds
population_evaluation took 13.96931505203247 seconds
population_evaluation took 10.802756071090698 seconds
population_evaluation took 15.532642364501953 seconds
population_evaluation took 2.4167215824127197 seconds
population_evaluation took 2.146035671234131 seconds
population_evaluation took 2.1887106895446777 seconds
population_evaluation took 2.0425119400024414 seconds
population_evaluation took 2.0716676712036133 seconds
population_evaluation took 2.0842578411102295 seconds
population_evaluation took 6.122622966766357 seconds
population_evaluation took 12.2374906539917 seconds
  Tamamlandı.


============================================================
  Hedef: h sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 11.993259191513062 seconds
population_evaluation took 11.26683759689331 seconds
population_evaluation took 11.316380262374878 seconds
population_evaluation took 12.600122451782227 seconds
population_evaluation took 12.851783275604248 seconds
population_evaluation took 13.908954858779907 seconds
population_evaluation took 15.18991208076477 seconds
population_evaluation took 12.898384094238281 seconds
population_evaluation took 13.16638970375061 seconds
population_evaluation took 11.721473455429077 seconds
population_evaluation took 10.041634798049927 seconds
population_evaluation took 3.3206913471221924 seconds
population_evaluation took 1.8957321643829346 seconds
population_evaluation took 1.9447224140167236 seconds
population_evaluation took 1.8954706192016602 seconds
population_evaluation took 1.915905237197876 seconds
population_evaluation took 1.9547216892242432 seconds
population_evaluation took 1.9576427936553955 seconds
population_evaluation took 1.9816269874572754 seconds
population_evaluation took 3.2943954467773438 seconds
population_evaluation took 10.298989057540894 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 27/27 [00:00<00:00, 468.19it/s]
synth_matrix: 100%|##########| 27/27 [00:00<00:00, 1290.03it/s]

population_evaluation took 1.9889166355133057 seconds
population_evaluation took 2.010706901550293 seconds
population_evaluation took 2.007131576538086 seconds
population_evaluation took 2.0032615661621094 seconds
population_evaluation took 2.0215342044830322 seconds
population_evaluation took 9.15783143043518 seconds
population_evaluation took 10.062597751617432 seconds
population_evaluation took 11.05697226524353 seconds
population_evaluation took 10.22183346748352 seconds
population_evaluation took 14.809379816055298 seconds
population_evaluation took 9.774045705795288 seconds
population_evaluation took 8.671607494354248 seconds
population_evaluation took 12.676748275756836 seconds
population_evaluation took 11.402011156082153 seconds
population_evaluation took 8.513201475143433 seconds
population_evaluation took 9.20353364944458 seconds
population_evaluation took 11.167010307312012 seconds
population_evaluation took 11.126855850219727 seconds
population_evaluation took 11.336912870407104 seconds
population_evaluation took 10.881085395812988 seconds
population_evaluation took 11.798355102539062 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 3.736112117767334 seconds
population_evaluation took 2.0721065998077393 seconds
population_evaluation took 2.1504180431365967 seconds
population_evaluation took 2.2118115425109863 seconds
population_evaluation took 2.1739251613616943 seconds
population_evaluation took 8.193447589874268 seconds
population_evaluation took 11.31106185913086 seconds
population_evaluation took 9.526439189910889 seconds
population_evaluation took 9.051923751831055 seconds
population_evaluation took 11.171327829360962 seconds
population_evaluation took 10.897635698318481 seconds
population_evaluation took 7.862133264541626 seconds
population_evaluation took 9.101333618164062 seconds
population_evaluation took 12.38782787322998 seconds
population_evaluation took 10.720130205154419 seconds
population_evaluation took 11.97708535194397 seconds
population_evaluation took 3.682100296020508 seconds
population_evaluation took 1.999889612197876 seconds
population_evaluation took 2.1004366874694824 seconds
population_evaluation took 2.0337417125701904 seconds
population_evaluation took 2.038177728652954 seconds
population_evaluation took 2.0804731845855713 seconds
population_evaluation took 2.0271222591400146 seconds
population_evaluation took 1.9994313716888428 seconds
population_evaluation took 1.9925143718719482 seconds
population_evaluation took 2.05562686920166 seconds
population_evaluation took 2.0433642864227295 seconds
population_evaluation took 2.0142104625701904 seconds
population_evaluation took 1.9860248565673828 seconds
population_evaluation took 1.9881412982940674 seconds
population_evaluation took 1.997147798538208 seconds
population_evaluation took 2.0049192905426025 seconds
population_evaluation took 1.968923568725586 seconds
population_evaluation took 1.9597322940826416 seconds
population_evaluation took 1.9807167053222656 seconds
population_evaluation took 1.9909038543701172 seconds
population_evaluation took 1.9721710681915283 seconds
population_evaluation took 1.9746325016021729 seconds
population_evaluation took 4.145077228546143 seconds
population_evaluation took 9.483135223388672 seconds
population_evaluation took 9.472630262374878 seconds
population_evaluation took 13.41173505783081 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 10.173121452331543 seconds
population_evaluation took 9.949997901916504 seconds
population_evaluation took 4.403377532958984 seconds
population_evaluation took 1.915398359298706 seconds
population_evaluation took 2.071549892425537 seconds
population_evaluation took 2.035802125930786 seconds
population_evaluation took 2.0828349590301514 seconds
population_evaluation took 2.1375555992126465 seconds
population_evaluation took 2.0900003910064697 seconds
population_evaluation took 2.0995912551879883 seconds
population_evaluation took 2.076258659362793 seconds
population_evaluation took 2.1134724617004395 seconds
population_evaluation took 2.0353193283081055 seconds
population_evaluation took 2.066498279571533 seconds
population_evaluation took 2.0434165000915527 seconds
population_evaluation took 2.1139719486236572 seconds
population_evaluation took 2.014817953109741 seconds
population_evaluation took 2.1332216262817383 seconds
population_evaluation took 2.108177423477173 seconds
population_evaluation took 2.0381267070770264 seconds
population_evaluation took 2.036510944366455 seconds
population_evaluation took 2.010204792022705 seconds
population_evaluation took 1.9845294952392578 seconds
population_evaluation took 1.9556124210357666 seconds
population_evaluation took 2.0067567825317383 seconds
population_evaluation took 1.951289176940918 seconds
population_evaluation took 1.96803617477417 seconds
population_evaluation took 2.1824612617492676 seconds
population_evaluation took 2.0694315433502197 seconds
population_evaluation took 2.067220687866211 seconds
population_evaluation took 2.032482862472534 seconds
population_evaluation took 2.051708221435547 seconds
population_evaluation took 2.0265860557556152 seconds
population_evaluation took 2.1363511085510254 seconds
population_evaluation took 2.083308458328247 seconds
population_evaluation took 2.170374631881714 seconds
population_evaluation took 2.106189250946045 seconds
population_evaluation took 2.0858240127563477 seconds
population_evaluation took 2.154353141784668 seconds
population_evaluation took 1.9468226432800293 seconds
population_evaluation took 2.3744003772735596 seconds
population_evaluation took 2.1107871532440186 seconds
  Tamamlandı.


============================================================
  Hedef: h buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 2.201739549636841 seconds
population_evaluation took 2.103273868560791 seconds
population_evaluation took 2.161012887954712 seconds
population_evaluation took 2.242476224899292 seconds
population_evaluation took 2.081357002258301 seconds
population_evaluation took 2.3379292488098145 seconds
population_evaluation took 2.0312371253967285 seconds
population_evaluation took 2.0027730464935303 seconds
population_evaluation took 2.013805389404297 seconds
population_evaluation took 2.4490981101989746 seconds
population_evaluation took 2.217167854309082 seconds
population_evaluation took 2.1702942848205566 seconds
population_evaluation took 2.580951452255249 seconds
population_evaluation took 2.2129342555999756 seconds
population_evaluation took 2.082763433456421 seconds
population_evaluation took 2.0582826137542725 seconds
population_evaluation took 2.1504061222076416 seconds
population_evaluation took 2.090643882751465 seconds
population_evaluation took 2.162339687347412 seconds
population_evaluation took 2.148169755935669 seconds
population_evaluation took 2.170055627822876 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 31/31 [00:00<00:00, 423.12it/s]
r_index: 100%|##########| 23/23 [00:00<00:00, 3667.19it/s]

population_evaluation took 2.2233073711395264 seconds
population_evaluation took 2.2340409755706787 seconds
population_evaluation took 2.0291998386383057 seconds
population_evaluation took 2.1359126567840576 seconds
population_evaluation took 2.077404022216797 seconds
population_evaluation took 2.130058765411377 seconds
population_evaluation took 2.077730894088745 seconds
population_evaluation took 2.1978914737701416 seconds
population_evaluation took 2.1069424152374268 seconds
population_evaluation took 2.106104850769043 seconds
population_evaluation took 2.1169826984405518 seconds
population_evaluation took 2.28411865234375 seconds
population_evaluation took 2.040738821029663 seconds
population_evaluation took 2.0411159992218018 seconds
population_evaluation took 2.3342199325561523 seconds
population_evaluation took 2.050597667694092 seconds
population_evaluation took 2.1658451557159424 seconds
population_evaluation took 2.105663299560547 seconds
population_evaluation took 2.2183828353881836 seconds
population_evaluation took 2.055070400238037 seconds
population_evaluation took 2.08349609375 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 2.166958808898926 seconds
population_evaluation took 2.2141034603118896 seconds
population_evaluation took 2.0862863063812256 seconds
population_evaluation took 2.0754566192626953 seconds
population_evaluation took 2.280510187149048 seconds
population_evaluation took 2.204338312149048 seconds
population_evaluation took 2.144071340560913 seconds
population_evaluation took 2.0744071006774902 seconds
population_evaluation took 2.139491558074951 seconds
population_evaluation took 2.1976704597473145 seconds
population_evaluation took 2.3050894737243652 seconds
population_evaluation took 2.26659893989563 seconds
population_evaluation took 2.24979829788208 seconds
population_evaluation took 2.171292304992676 seconds
population_evaluation took 2.2403147220611572 seconds
population_evaluation took 2.208341360092163 seconds
population_evaluation took 2.828108072280884 seconds
population_evaluation took 2.266650915145874 seconds
population_evaluation took 2.0622401237487793 seconds
population_evaluation took 2.005704164505005 seconds
population_evaluation took 2.548712968826294 seconds
population_evaluation took 2.2171518802642822 seconds
population_evaluation took 2.194028854370117 seconds
population_evaluation took 2.2880136966705322 seconds
population_evaluation took 2.0404796600341797 seconds
population_evaluation took 2.562623977661133 seconds
population_evaluation took 2.111783504486084 seconds
population_evaluation took 2.029843807220459 seconds
population_evaluation took 2.0045218467712402 seconds
population_evaluation took 1.9726126194000244 seconds
population_evaluation took 2.00756573677063 seconds
population_evaluation took 1.9443202018737793 seconds
population_evaluation took 2.0972073078155518 seconds
population_evaluation took 2.0771281719207764 seconds
population_evaluation took 2.316342353820801 seconds
population_evaluation took 2.2011404037475586 seconds
population_evaluation took 2.044311285018921 seconds
population_evaluation took 2.440415859222412 seconds
population_evaluation took 2.2013440132141113 seconds
population_evaluation took 2.181528329849243 seconds
population_evaluation took 2.1134414672851562 seconds
population_evaluation took 2.217520236968994 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 2.083472967147827 seconds
population_evaluation took 2.0763957500457764 seconds
population_evaluation took 2.4393303394317627 seconds
population_evaluation took 2.31020188331604 seconds
population_evaluation took 1.9769811630249023 seconds
population_evaluation took 2.077880620956421 seconds
population_evaluation took 2.055161714553833 seconds
population_evaluation took 2.0744822025299072 seconds
population_evaluation took 2.473278284072876 seconds
population_evaluation took 2.133206844329834 seconds
population_evaluation took 2.0216312408447266 seconds
population_evaluation took 1.979583978652954 seconds
population_evaluation took 2.109623670578003 seconds
population_evaluation took 2.1548471450805664 seconds
population_evaluation took 2.1133651733398438 seconds
population_evaluation took 2.16731595993042 seconds
population_evaluation took 2.1120474338531494 seconds
population_evaluation took 2.172952890396118 seconds
population_evaluation took 2.113845109939575 seconds
population_evaluation took 2.177403450012207 seconds
population_evaluation took 2.068134307861328 seconds
population_evaluation took 2.199504852294922 seconds
population_evaluation took 2.161400079727173 seconds
population_evaluation took 2.141554832458496 seconds
population_evaluation took 2.128843307495117 seconds
population_evaluation took 2.1670165061950684 seconds
population_evaluation took 2.1212236881256104 seconds
population_evaluation took 2.117812395095825 seconds
population_evaluation took 2.0631117820739746 seconds
population_evaluation took 2.1316566467285156 seconds
population_evaluation took 2.1576807498931885 seconds
population_evaluation took 1.9929101467132568 seconds
population_evaluation took 2.07100510597229 seconds
population_evaluation took 2.1778950691223145 seconds
population_evaluation took 2.145906925201416 seconds
population_evaluation took 2.0974369049072266 seconds
population_evaluation took 2.157540798187256 seconds
population_evaluation took 2.1236162185668945 seconds
population_evaluation took 2.0842795372009277 seconds
population_evaluation took 2.17311692237854 seconds
population_evaluation took 2.166836738586426 seconds
population_evaluation took 2.1171252727508545 seconds
  Tamamlandı.


============================================================
  Hedef: s sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 1.9947319030761719 seconds
population_evaluation took 2.060899019241333 seconds
population_evaluation took 2.0519938468933105 seconds
population_evaluation took 2.029855251312256 seconds
population_evaluation took 2.014906644821167 seconds
population_evaluation took 2.019087076187134 seconds
population_evaluation took 1.9861104488372803 seconds
population_evaluation took 2.204319477081299 seconds
population_evaluation took 2.278402090072632 seconds
population_evaluation took 2.1714038848876953 seconds
population_evaluation took 2.2521095275878906 seconds
population_evaluation took 2.1438634395599365 seconds
population_evaluation took 2.0887608528137207 seconds
population_evaluation took 2.2771692276000977 seconds
population_evaluation took 2.1890830993652344 seconds
population_evaluation took 2.17899751663208 seconds
population_evaluation took 2.2724297046661377 seconds
population_evaluation took 2.187859296798706 seconds
population_evaluation took 2.2442758083343506 seconds
population_evaluation took 2.1766693592071533 seconds
population_evaluation took 2.1303939819335938 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 29/29 [00:00<00:00, 443.12it/s]
r_index: 100%|##########| 7/7 [00:00<00:00, 1862.72it/s]
dist_matrix: 100%|##########| 25/25 [00:00<00:00, 1373.49it/s]
r_index: 100%|##########| 10/10 [00:00<00:00, 1664.87it/s]

population_evaluation took 2.1656339168548584 seconds
population_evaluation took 2.052720546722412 seconds
population_evaluation took 2.075716018676758 seconds
population_evaluation took 2.192976713180542 seconds
population_evaluation took 2.217621088027954 seconds
population_evaluation took 2.1061830520629883 seconds
population_evaluation took 2.1133806705474854 seconds
population_evaluation took 2.150775909423828 seconds
population_evaluation took 2.115088701248169 seconds
population_evaluation took 2.181460380554199 seconds
population_evaluation took 2.2224009037017822 seconds
population_evaluation took 2.139016628265381 seconds
population_evaluation took 2.0959086418151855 seconds
population_evaluation took 2.0865721702575684 seconds
population_evaluation took 1.9691977500915527 seconds
population_evaluation took 2.2127223014831543 seconds
population_evaluation took 2.1217615604400635 seconds
population_evaluation took 2.161996603012085 seconds
population_evaluation took 2.147165298461914 seconds
population_evaluation took 2.0767884254455566 seconds
population_evaluation took 2.2872681617736816 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 2.1295716762542725 seconds
population_evaluation took 2.28723406791687 seconds
population_evaluation took 2.120337724685669 seconds
population_evaluation took 2.1133501529693604 seconds
population_evaluation took 2.1727960109710693 seconds
population_evaluation took 2.09098744392395 seconds
population_evaluation took 2.107616901397705 seconds
population_evaluation took 2.089609384536743 seconds
population_evaluation took 2.076730489730835 seconds
population_evaluation took 2.0357842445373535 seconds
population_evaluation took 1.921827793121338 seconds
population_evaluation took 2.10001802444458 seconds
population_evaluation took 2.103583574295044 seconds
population_evaluation took 2.3286306858062744 seconds
population_evaluation took 2.2849514484405518 seconds
population_evaluation took 2.1562178134918213 seconds
population_evaluation took 2.1428730487823486 seconds
population_evaluation took 2.06673526763916 seconds
population_evaluation took 2.1126582622528076 seconds
population_evaluation took 2.0254201889038086 seconds
population_evaluation took 2.055054187774658 seconds
population_evaluation took 2.1767263412475586 seconds
population_evaluation took 2.0413758754730225 seconds
population_evaluation took 2.1175355911254883 seconds
population_evaluation took 2.083832025527954 seconds
population_evaluation took 2.1806201934814453 seconds
population_evaluation took 2.1903138160705566 seconds
population_evaluation took 2.1476404666900635 seconds
population_evaluation took 2.2522833347320557 seconds
population_evaluation took 2.2851998805999756 seconds
population_evaluation took 2.197136163711548 seconds
population_evaluation took 2.20947265625 seconds
population_evaluation took 2.130366325378418 seconds
population_evaluation took 2.062624454498291 seconds
population_evaluation took 2.138747215270996 seconds
population_evaluation took 2.1647162437438965 seconds
population_evaluation took 2.139075517654419 seconds
population_evaluation took 2.0486323833465576 seconds
population_evaluation took 2.1343026161193848 seconds
population_evaluation took 2.1753182411193848 seconds
population_evaluation took 2.0558433532714844 seconds
population_evaluation took 2.1081290245056152 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 2.1794474124908447 seconds
population_evaluation took 1.9652957916259766 seconds
population_evaluation took 2.0083866119384766 seconds
population_evaluation took 2.076951265335083 seconds
population_evaluation took 2.0899393558502197 seconds
population_evaluation took 2.078691244125366 seconds
population_evaluation took 2.2042038440704346 seconds
population_evaluation took 2.123131275177002 seconds
population_evaluation took 2.126441717147827 seconds
population_evaluation took 2.1039605140686035 seconds
population_evaluation took 2.1516127586364746 seconds
population_evaluation took 2.1176366806030273 seconds
population_evaluation took 2.0608224868774414 seconds
population_evaluation took 2.1181418895721436 seconds
population_evaluation took 2.0020577907562256 seconds
population_evaluation took 2.103698253631592 seconds
population_evaluation took 2.1198408603668213 seconds
population_evaluation took 2.062687873840332 seconds
population_evaluation took 2.0713112354278564 seconds
population_evaluation took 2.043311595916748 seconds
population_evaluation took 2.11283278465271 seconds
population_evaluation took 2.202244520187378 seconds
population_evaluation took 2.2553396224975586 seconds
population_evaluation took 2.100295066833496 seconds
population_evaluation took 2.111905574798584 seconds
population_evaluation took 2.1076154708862305 seconds
population_evaluation took 2.026663064956665 seconds
population_evaluation took 1.9896082878112793 seconds
population_evaluation took 1.9533541202545166 seconds
population_evaluation took 1.9751908779144287 seconds
population_evaluation took 1.9592673778533936 seconds
population_evaluation took 1.942263126373291 seconds
population_evaluation took 1.9854683876037598 seconds
population_evaluation took 1.9651010036468506 seconds
population_evaluation took 1.9764814376831055 seconds
population_evaluation took 2.0154011249542236 seconds
population_evaluation took 2.1948792934417725 seconds
population_evaluation took 2.099278688430786 seconds
population_evaluation took 1.95756196975708 seconds
population_evaluation took 2.0702035427093506 seconds
population_evaluation took 1.9924452304840088 seconds
population_evaluation took 2.0682315826416016 seconds
  Tamamlandı.


============================================================
  Hedef: s buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 2.04879093170166 seconds
population_evaluation took 2.1728084087371826 seconds
population_evaluation took 2.035490036010742 seconds
population_evaluation took 2.1178040504455566 seconds
population_evaluation took 2.0575098991394043 seconds
population_evaluation took 2.0488388538360596 seconds
population_evaluation took 1.9550285339355469 seconds
population_evaluation took 2.0781290531158447 seconds
population_evaluation took 2.0454254150390625 seconds
population_evaluation took 2.021415948867798 seconds
population_evaluation took 2.2224652767181396 seconds
population_evaluation took 2.115583896636963 seconds
population_evaluation took 2.0202083587646484 seconds
population_evaluation took 2.083252429962158 seconds
population_evaluation took 2.0911903381347656 seconds
population_evaluation took 2.074370861053467 seconds
population_evaluation took 2.1152827739715576 seconds
population_evaluation took 2.167051315307617 seconds
population_evaluation took 2.069889545440674 seconds
population_evaluation took 2.081254720687866 seconds
population_evaluation took 2.062797784805298 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 6/6 [00:00<00:00, 1254.22it/s]
synth_matrix: 100%|##########| 6/6 [00:00<00:00, 216.81it/s]

population_evaluation took 1.9288148880004883 seconds
population_evaluation took 1.9724457263946533 seconds
population_evaluation took 1.9526784420013428 seconds
population_evaluation took 1.937110424041748 seconds
population_evaluation took 1.969963788986206 seconds
population_evaluation took 1.9254176616668701 seconds
population_evaluation took 1.9897546768188477 seconds
population_evaluation took 1.975388765335083 seconds
population_evaluation took 1.9493958950042725 seconds
population_evaluation took 1.9641945362091064 seconds
population_evaluation took 1.9735887050628662 seconds
population_evaluation took 1.9016003608703613 seconds
population_evaluation took 1.9139838218688965 seconds
population_evaluation took 1.964975118637085 seconds
population_evaluation took 1.895643711090088 seconds
population_evaluation took 1.8826370239257812 seconds
population_evaluation took 1.9462268352508545 seconds
population_evaluation took 1.9004480838775635 seconds
population_evaluation took 1.89548921585083 seconds
population_evaluation took 1.9099016189575195 seconds
population_evaluation took 1.894679069519043 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 2.205662727355957 seconds
population_evaluation took 2.076282501220703 seconds
population_evaluation took 1.9536082744598389 seconds
population_evaluation took 1.974799394607544 seconds
population_evaluation took 2.0181243419647217 seconds
population_evaluation took 1.9601020812988281 seconds
population_evaluation took 2.0098352432250977 seconds
population_evaluation took 1.9503002166748047 seconds
population_evaluation took 1.999253511428833 seconds
population_evaluation took 1.9752612113952637 seconds
population_evaluation took 1.9482648372650146 seconds
population_evaluation took 2.0178115367889404 seconds
population_evaluation took 1.951167106628418 seconds
population_evaluation took 1.9591224193572998 seconds
population_evaluation took 1.953794240951538 seconds
population_evaluation took 1.9727346897125244 seconds
population_evaluation took 1.947155475616455 seconds
population_evaluation took 1.958883285522461 seconds
population_evaluation took 1.9961585998535156 seconds
population_evaluation took 1.9786124229431152 seconds
population_evaluation took 2.0283193588256836 seconds
population_evaluation took 1.9659647941589355 seconds
population_evaluation took 2.049067974090576 seconds
population_evaluation took 1.998488187789917 seconds
population_evaluation took 2.0465054512023926 seconds
population_evaluation took 1.994819164276123 seconds
population_evaluation took 1.9936020374298096 seconds
population_evaluation took 2.0036895275115967 seconds
population_evaluation took 2.009166717529297 seconds
population_evaluation took 2.032932996749878 seconds
population_evaluation took 2.0142436027526855 seconds
population_evaluation took 2.0138535499572754 seconds
population_evaluation took 1.9796507358551025 seconds
population_evaluation took 1.9692111015319824 seconds
population_evaluation took 1.992830514907837 seconds
population_evaluation took 1.9989488124847412 seconds
population_evaluation took 2.0423576831817627 seconds
population_evaluation took 2.000396490097046 seconds
population_evaluation took 2.0225183963775635 seconds
population_evaluation took 1.979074239730835 seconds
population_evaluation took 1.9651973247528076 seconds
population_evaluation took 1.9860255718231201 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 1.937999963760376 seconds
population_evaluation took 1.9213366508483887 seconds
population_evaluation took 1.9136743545532227 seconds
population_evaluation took 1.9439258575439453 seconds
population_evaluation took 1.9634203910827637 seconds
population_evaluation took 1.92722487449646 seconds
population_evaluation took 1.9810349941253662 seconds
population_evaluation took 1.9504847526550293 seconds
population_evaluation took 1.949582815170288 seconds
population_evaluation took 1.951045274734497 seconds
population_evaluation took 1.9506518840789795 seconds
population_evaluation took 1.9978337287902832 seconds
population_evaluation took 1.9478378295898438 seconds
population_evaluation took 1.9737160205841064 seconds
population_evaluation took 1.9210381507873535 seconds
population_evaluation took 1.9323081970214844 seconds
population_evaluation took 1.967968225479126 seconds
population_evaluation took 1.9305989742279053 seconds
population_evaluation took 1.9490389823913574 seconds
population_evaluation took 1.9294064044952393 seconds
population_evaluation took 1.940716028213501 seconds
population_evaluation took 1.9489707946777344 seconds
population_evaluation took 2.0009453296661377 seconds
population_evaluation took 1.9261410236358643 seconds
population_evaluation took 1.9345993995666504 seconds
population_evaluation took 1.9749202728271484 seconds
population_evaluation took 1.9690041542053223 seconds
population_evaluation took 2.0136983394622803 seconds
population_evaluation took 1.9372544288635254 seconds
population_evaluation took 1.9981515407562256 seconds
population_evaluation took 1.9846971035003662 seconds
population_evaluation took 1.9982757568359375 seconds
population_evaluation took 1.9632163047790527 seconds
population_evaluation took 1.9780781269073486 seconds
population_evaluation took 2.020237445831299 seconds
population_evaluation took 1.979151964187622 seconds
population_evaluation took 2.013972282409668 seconds
population_evaluation took 2.0031683444976807 seconds
population_evaluation took 1.977358102798462 seconds
population_evaluation took 1.9658606052398682 seconds
population_evaluation took 2.0081636905670166 seconds
population_evaluation took 1.9941303730010986 seconds
  Tamamlandı.

### 3.1 Doymuş Buhar — Sonuç Tablosu

In [6]:
df_doymus_results = build_results_table(doymus_results)
df_doymus_results

               Hedef        Senaryo Algoritma  R2_Score
0           P(çıktı)           Base  AdaBoost    0.9986
1           P(çıktı)           Base  CatBoost    0.9995
2           P(çıktı)           Base      DART    0.9610
3           P(çıktı)           Base        EF    1.0000
4           P(çıktı)           Base        ET    1.0000
..               ...            ...       ...       ...
275  s buhar (çıktı)  SMOGN+STGP-EF      GBDT    0.9865
276  s buhar (çıktı)  SMOGN+STGP-EF        GP   -2.8369
277  s buhar (çıktı)  SMOGN+STGP-EF  LightGBM    0.7334
278  s buhar (çıktı)  SMOGN+STGP-EF        RF    0.9598
279  s buhar (çıktı)  SMOGN+STGP-EF   XGBoost    0.9581

[280 rows x 4 columns]

### 3.2 Doymuş Buhar — Senaryo Karşılaştırması

In [7]:
compare_scenarios(df_doymus_results)

Senaryo                    Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Hedef          Algoritma
P(çıktı)       AdaBoost  0.9986 0.9941   0.9991         0.9967
               CatBoost  0.9995 0.9983   0.9997         0.9993
               DART      0.9610 0.8967   0.9669         0.9182
               EF        1.0000 0.9999   1.0000         0.9998
               ET        1.0000 0.9999   1.0000         0.9999
...                         ...    ...      ...            ...
v sıvı (çıktı) GBDT      0.9978 0.9980   0.9991         0.9975
               GP        0.9541 0.9901   0.9860         0.9820
               LightGBM  0.9429 0.9702   0.9958         0.9904
               RF        0.9992 0.9995   0.9998         0.9989
               XGBoost   0.9981 0.9968   0.9978         0.9962

[70 rows x 4 columns]

### 3.3 Doymuş Buhar — Hedef Bazlı Detay

Her bir hedef değişken için detaylı pivot tablo;

In [8]:
target_summary(df_doymus_results, 'P(çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9986 0.9941   0.9991         0.9967
CatBoost  0.9995 0.9983   0.9997         0.9993
DART      0.9610 0.8967   0.9669         0.9182
EF        1.0000 0.9999   1.0000         0.9998
ET        1.0000 0.9999   1.0000         0.9999
GBDT      0.9992 0.9979   0.9994         0.9980
GP        0.9737 0.9272   0.9656         0.9666
LightGBM  0.9710 0.9193   0.9967         0.9938
RF        0.9997 0.9986   0.9999         0.9990
XGBoost   0.9991 0.9932   0.9985         0.9964

In [16]:
target_summary(df_doymus_results, 'v sıvı (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9971 0.9948   0.9987         0.9942
CatBoost  0.9986 0.9986   0.9994         0.9987
DART      0.9345 0.9636   0.9492         0.9638
EF        1.0000 0.9998   1.0000         0.9998
ET        1.0000 0.9998   0.9999         0.9998
GBDT      0.9978 0.9980   0.9991         0.9975
GP        0.9541 0.9901   0.9860         0.9820
LightGBM  0.9429 0.9702   0.9958         0.9904
RF        0.9992 0.9995   0.9998         0.9989
XGBoost   0.9981 0.9968   0.9978         0.9962

In [17]:
target_summary(df_doymus_results, 'v buhar (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9909 0.9934   0.9920         0.9929
CatBoost  0.9971 0.9977   0.9985         0.9987
DART      0.8327 0.9808   0.9253         0.9858
EF        1.0000 0.9995   0.9999         0.9992
ET        1.0000 0.9996   1.0000         0.9996
GBDT      0.9965 0.9978   0.9988         0.9977
GP        0.9398 0.9725   0.9945         0.8725
LightGBM  0.8011 0.9875   0.9781         0.9941
RF        0.9989 0.9982   0.9995         0.9985
XGBoost   0.9951 0.9920   0.9929         0.9905

In [18]:
target_summary(df_doymus_results, 'h sıvı (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9993 0.9920   0.9992         0.9948
CatBoost  0.9996 0.9983   0.9995         0.9984
DART      0.9749 0.7738   0.9827         0.8217
EF        1.0000 0.9998   1.0000         0.9996
ET        1.0000 0.9998   1.0000         0.9999
GBDT      0.9993 0.9967   0.9996         0.9986
GP        0.9955 0.9955   0.9955         0.9955
LightGBM  0.9793 0.7851   0.9978         0.9747
RF        0.9998 0.9980   0.9999         0.9986
XGBoost   0.9991 0.9880   0.9988         0.9883

In [19]:
target_summary(df_doymus_results, 'h buhar (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9961 0.9955   0.9989         0.9963
CatBoost  0.9993 0.9982   0.9995         0.9986
DART      0.9765 0.9130   0.9858         0.9613
EF        1.0000 0.9994   1.0000         0.9989
ET        1.0000 0.9993   1.0000         0.9998
GBDT      0.9990 0.9979   0.9994         0.9987
GP        0.9518 0.9863   0.9819         0.9518
LightGBM  0.9747 0.9158   0.9958         0.9936
RF        0.9997 0.9988   0.9998         0.9988
XGBoost   0.9986 0.9910   0.9986         0.9901

In [20]:
target_summary(df_doymus_results, 's sıvı (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9996 0.9927   0.9995         0.9959
CatBoost  0.9995 0.9983   0.9996         0.9985
DART      0.9753 0.9809   0.9853         0.9866
EF        1.0000 0.9999   1.0000         0.9999
ET        1.0000 0.9999   1.0000         1.0000
GBDT      0.9993 0.9973   0.9996         0.9984
GP        0.9998 0.9998   0.9998         0.9998
LightGBM  0.9778 0.9861   0.9974         0.9959
RF        0.9998 0.9985   0.9999         0.9989
XGBoost   0.9990 0.9933   0.9985         0.9926

In [21]:
target_summary(df_doymus_results, 's buhar (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9163 0.8963   0.9661         0.9452
CatBoost  0.9793 0.9824   0.9979         0.9617
DART      0.4471 0.9203   0.8510         0.7076
EF        0.9999 0.9983   0.9997         0.8650
ET        0.9996 0.9997   0.9997         0.7497
GBDT      0.9737 0.9744   0.9956         0.9865
GP        0.0665 0.5884   0.7589        -2.8369
LightGBM  0.4591 0.9466   0.9484         0.7334
RF        0.9899 0.9781   0.9975         0.9598
XGBoost   0.9785 0.9621   0.9748         0.9581

---
## 4. Kızgın Buhar — Eğitim

**Girdiler:** T (girdi), P (girdi)  
**Çıktılar (her biri ayrı ayrı):** v, h, s

In [9]:
kizgin_results = run_kizgin_analysis(df_kizgin)

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  KIZGIN BUHAR ANALİZİ
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

============================================================
  Hedef: v (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 2.6332075595855713 seconds
population_evaluation took 2.55115008354187 seconds
population_evaluation took 2.5624892711639404 seconds
population_evaluation took 2.536864757537842 seconds
population_evaluation took 2.4981255531311035 seconds
population_evaluation took 2.4116363525390625 seconds
population_evaluation took 2.4894983768463135 seconds
population_evaluation took 2.4592015743255615 seconds
population_evaluation took 2.58019757270813 seconds
population_evaluation took 2.7191638946533203 seconds
population_evaluation took 2.618567943572998 seconds
population_evaluation took 2.7503106594085693 seconds
population_evaluation took 2.642406940460205 seconds
population_evaluation took 2.7420713901519775 seconds
population_evaluation took 2.77524471282959 seconds
population_evaluation took 2.741041660308838 seconds
population_evaluation took 2.6573593616485596 seconds
population_evaluation took 2.7152669429779053 seconds
population_evaluation took 2.6689486503601074 seconds
population_evaluation took 2.7400269508361816 seconds
population_evaluation took 2.850572347640991 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 90/90 [00:00<00:00, 254.92it/s]
synth_matrix: 100%|##########| 90/90 [00:00<00:00, 2014.82it/s]
r_index: 100%|##########| 51/51 [00:00<00:00, 2347.30it/s]

population_evaluation took 2.5755279064178467 seconds
population_evaluation took 2.5021469593048096 seconds
population_evaluation took 2.5073938369750977 seconds
population_evaluation took 2.449495553970337 seconds
population_evaluation took 2.4995312690734863 seconds
population_evaluation took 2.2801294326782227 seconds
population_evaluation took 2.2779674530029297 seconds
population_evaluation took 2.277756452560425 seconds
population_evaluation took 2.320113182067871 seconds
population_evaluation took 2.2237257957458496 seconds
population_evaluation took 2.2936952114105225 seconds
population_evaluation took 2.2309274673461914 seconds
population_evaluation took 2.3069095611572266 seconds
population_evaluation took 2.252730369567871 seconds
population_evaluation took 2.27310848236084 seconds
population_evaluation took 2.2481064796447754 seconds
population_evaluation took 2.2677934169769287 seconds
population_evaluation took 2.249891519546509 seconds
population_evaluation took 2.265638589859009 seconds
population_evaluation took 2.237001895904541 seconds
population_evaluation took 2.2707090377807617 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 2.525284767150879 seconds
population_evaluation took 2.5329952239990234 seconds
population_evaluation took 2.460529088973999 seconds
population_evaluation took 2.5693671703338623 seconds
population_evaluation took 2.4738709926605225 seconds
population_evaluation took 2.486499309539795 seconds
population_evaluation took 2.504840135574341 seconds
population_evaluation took 2.502561569213867 seconds
population_evaluation took 2.478666305541992 seconds
population_evaluation took 2.424685478210449 seconds
population_evaluation took 2.817870616912842 seconds
population_evaluation took 2.4769227504730225 seconds
population_evaluation took 2.4357101917266846 seconds
population_evaluation took 2.3934943675994873 seconds
population_evaluation took 2.4816579818725586 seconds
population_evaluation took 2.4599156379699707 seconds
population_evaluation took 2.4278931617736816 seconds
population_evaluation took 2.4418537616729736 seconds
population_evaluation took 2.4699060916900635 seconds
population_evaluation took 2.450747013092041 seconds
population_evaluation took 2.53053879737854 seconds
population_evaluation took 2.540680170059204 seconds
population_evaluation took 2.597097635269165 seconds
population_evaluation took 2.6211819648742676 seconds
population_evaluation took 2.573244571685791 seconds
population_evaluation took 2.698917865753174 seconds
population_evaluation took 3.027688503265381 seconds
population_evaluation took 2.814093589782715 seconds
population_evaluation took 2.8097875118255615 seconds
population_evaluation took 2.748216152191162 seconds
population_evaluation took 2.6439480781555176 seconds
population_evaluation took 2.595231294631958 seconds
population_evaluation took 2.6312942504882812 seconds
population_evaluation took 2.6364617347717285 seconds
population_evaluation took 2.6426141262054443 seconds
population_evaluation took 2.6040287017822266 seconds
population_evaluation took 2.6048920154571533 seconds
population_evaluation took 2.6170623302459717 seconds
population_evaluation took 2.576331615447998 seconds
population_evaluation took 2.606572389602661 seconds
population_evaluation took 2.6118767261505127 seconds
population_evaluation took 2.62874174118042 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 2.395841598510742 seconds
population_evaluation took 2.4171395301818848 seconds
population_evaluation took 2.4007301330566406 seconds
population_evaluation took 2.34748911857605 seconds
population_evaluation took 2.349731683731079 seconds
population_evaluation took 2.3527534008026123 seconds
population_evaluation took 2.341831684112549 seconds
population_evaluation took 2.3537726402282715 seconds
population_evaluation took 2.3189034461975098 seconds
population_evaluation took 2.3932385444641113 seconds
population_evaluation took 2.478196382522583 seconds
population_evaluation took 2.429405689239502 seconds
population_evaluation took 2.4614524841308594 seconds
population_evaluation took 2.37109637260437 seconds
population_evaluation took 2.340121030807495 seconds
population_evaluation took 2.3948628902435303 seconds
population_evaluation took 2.343346118927002 seconds
population_evaluation took 2.355743408203125 seconds
population_evaluation took 2.255343437194824 seconds
population_evaluation took 2.2997918128967285 seconds
population_evaluation took 2.306901454925537 seconds
population_evaluation took 2.488456964492798 seconds
population_evaluation took 2.4865171909332275 seconds
population_evaluation took 2.448690414428711 seconds
population_evaluation took 2.4573328495025635 seconds
population_evaluation took 2.4522624015808105 seconds
population_evaluation took 2.47788667678833 seconds
population_evaluation took 2.486572504043579 seconds
population_evaluation took 2.4309000968933105 seconds
population_evaluation took 2.430933713912964 seconds
population_evaluation took 2.4758377075195312 seconds
population_evaluation took 2.3817126750946045 seconds
population_evaluation took 2.3912839889526367 seconds
population_evaluation took 2.3588449954986572 seconds
population_evaluation took 2.4431047439575195 seconds
population_evaluation took 2.361137866973877 seconds
population_evaluation took 2.4070963859558105 seconds
population_evaluation took 2.3566014766693115 seconds
population_evaluation took 2.353731393814087 seconds
population_evaluation took 2.3603618144989014 seconds
population_evaluation took 2.3865835666656494 seconds
population_evaluation took 2.3507115840911865 seconds
  Tamamlandı.


============================================================
  Hedef: h (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 2.591024160385132 seconds
population_evaluation took 2.611314296722412 seconds
population_evaluation took 2.63205623626709 seconds
population_evaluation took 2.7000415325164795 seconds
population_evaluation took 2.697054862976074 seconds
population_evaluation took 2.6532063484191895 seconds
population_evaluation took 2.6992812156677246 seconds
population_evaluation took 2.7137980461120605 seconds
population_evaluation took 2.6913959980010986 seconds
population_evaluation took 2.6761770248413086 seconds
population_evaluation took 2.576765537261963 seconds
population_evaluation took 2.7009241580963135 seconds
population_evaluation took 2.690174102783203 seconds
population_evaluation took 2.7347099781036377 seconds
population_evaluation took 2.72654390335083 seconds
population_evaluation took 2.722306489944458 seconds
population_evaluation took 2.703312397003174 seconds
population_evaluation took 2.7154526710510254 seconds
population_evaluation took 2.6949734687805176 seconds
population_evaluation took 2.676316499710083 seconds
population_evaluation took 2.818380832672119 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 55/55 [00:00<00:00, 360.65it/s]
synth_matrix: 100%|##########| 55/55 [00:00<00:00, 739.50it/s]
r_index: 100%|##########| 11/11 [00:00<?, ?it/s]

population_evaluation took 2.4199109077453613 seconds
population_evaluation took 2.6505088806152344 seconds
population_evaluation took 2.754760503768921 seconds
population_evaluation took 2.738260269165039 seconds
population_evaluation took 2.6904613971710205 seconds
population_evaluation took 2.626786947250366 seconds
population_evaluation took 2.555506944656372 seconds
population_evaluation took 2.6258010864257812 seconds
population_evaluation took 2.5419933795928955 seconds
population_evaluation took 2.619156837463379 seconds
population_evaluation took 2.579530954360962 seconds
population_evaluation took 2.8535242080688477 seconds
population_evaluation took 2.5300676822662354 seconds
population_evaluation took 2.6349570751190186 seconds
population_evaluation took 2.5104146003723145 seconds
population_evaluation took 2.5139334201812744 seconds
population_evaluation took 2.604063034057617 seconds
population_evaluation took 2.529475450515747 seconds
population_evaluation took 2.580488920211792 seconds
population_evaluation took 2.5038485527038574 seconds
population_evaluation took 2.5287158489227295 seconds
  [3/4] STGP-EF eğitim...
population_evaluation took 2.614928960800171 seconds
population_evaluation took 2.680568218231201 seconds
population_evaluation took 2.6415655612945557 seconds
population_evaluation took 2.6681056022644043 seconds
population_evaluation took 2.703540563583374 seconds
population_evaluation took 2.6978867053985596 seconds
population_evaluation took 2.657210350036621 seconds
population_evaluation took 2.694828510284424 seconds
population_evaluation took 2.690544843673706 seconds
population_evaluation took 2.6700408458709717 seconds
population_evaluation took 2.6853995323181152 seconds
population_evaluation took 2.6800968647003174 seconds
population_evaluation took 2.724250078201294 seconds
population_evaluation took 2.6962943077087402 seconds
population_evaluation took 2.7480340003967285 seconds
population_evaluation took 2.7566421031951904 seconds
population_evaluation took 2.7036213874816895 seconds
population_evaluation took 2.6930317878723145 seconds
population_evaluation took 2.678530693054199 seconds
population_evaluation took 2.727010488510132 seconds
population_evaluation took 2.702836036682129 seconds
population_evaluation took 2.714179039001465 seconds
population_evaluation took 2.765733242034912 seconds
population_evaluation took 2.8019838333129883 seconds
population_evaluation took 2.750992774963379 seconds
population_evaluation took 2.7660136222839355 seconds
population_evaluation took 2.7209253311157227 seconds
population_evaluation took 2.749168872833252 seconds
population_evaluation took 2.773491144180298 seconds
population_evaluation took 2.754408121109009 seconds
population_evaluation took 2.876499891281128 seconds
population_evaluation took 2.9461381435394287 seconds
population_evaluation took 2.9914708137512207 seconds
population_evaluation took 3.0448617935180664 seconds
population_evaluation took 2.8205134868621826 seconds
population_evaluation took 2.855072498321533 seconds
population_evaluation took 2.8251254558563232 seconds
population_evaluation took 2.8018064498901367 seconds
population_evaluation took 2.8754351139068604 seconds
population_evaluation took 2.8171184062957764 seconds
population_evaluation took 2.854193687438965 seconds
population_evaluation took 2.770616054534912 seconds
  [4/4] SMOGN + STGP-EF eğitim...
population_evaluation took 2.553694486618042 seconds
population_evaluation took 2.59104585647583 seconds
population_evaluation took 2.562328577041626 seconds
population_evaluation took 2.558558225631714 seconds
population_evaluation took 2.5657927989959717 seconds
population_evaluation took 2.5955705642700195 seconds
population_evaluation took 2.538851737976074 seconds
population_evaluation took 2.6633410453796387 seconds
population_evaluation took 2.6206881999969482 seconds
population_evaluation took 2.5831010341644287 seconds
population_evaluation took 2.623392343521118 seconds
population_evaluation took 2.593752145767212 seconds
population_evaluation took 2.5994606018066406 seconds
population_evaluation took 2.526855707168579 seconds
population_evaluation took 2.5575757026672363 seconds
population_evaluation took 2.56615948677063 seconds
population_evaluation took 2.5950284004211426 seconds
population_evaluation took 2.544393539428711 seconds
population_evaluation took 2.531200647354126 seconds
population_evaluation took 2.53525710105896 seconds
population_evaluation took 2.5411009788513184 seconds
population_evaluation took 2.64388370513916 seconds
population_evaluation took 2.6612939834594727 seconds
population_evaluation took 2.6327626705169678 seconds
population_evaluation took 2.677337884902954 seconds
population_evaluation took 2.6693191528320312 seconds
population_evaluation took 2.6841847896575928 seconds
population_evaluation took 2.6779236793518066 seconds
population_evaluation took 2.6126482486724854 seconds
population_evaluation took 3.0255863666534424 seconds
population_evaluation took 2.6135010719299316 seconds
population_evaluation took 2.6283795833587646 seconds
population_evaluation took 2.6316301822662354 seconds
population_evaluation took 2.6655640602111816 seconds
population_evaluation took 2.6523072719573975 seconds
population_evaluation took 2.6664655208587646 seconds
population_evaluation took 2.654223680496216 seconds
population_evaluation took 2.679351568222046 seconds
population_evaluation took 2.6763246059417725 seconds
population_evaluation took 2.654250383377075 seconds
population_evaluation took 2.6750881671905518 seconds
population_evaluation took 2.6545979976654053 seconds
  Tamamlandı.


============================================================
  Hedef: s (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
population_evaluation took 2.6789042949676514 seconds
population_evaluation took 2.652655601501465 seconds
population_evaluation took 2.748436689376831 seconds
population_evaluation took 2.7240114212036133 seconds
population_evaluation took 2.740123748779297 seconds
population_evaluation took 2.7225406169891357 seconds
population_evaluation took 2.701213836669922 seconds
population_evaluation took 2.77055287361145 seconds
population_evaluation took 2.668009042739868 seconds
population_evaluation took 2.7569925785064697 seconds
population_evaluation took 2.687359571456909 seconds
population_evaluation took 2.7757697105407715 seconds
population_evaluation took 2.756603479385376 seconds
population_evaluation took 2.7085983753204346 seconds
population_evaluation took 2.792372703552246 seconds
population_evaluation took 2.736135959625244 seconds
population_evaluation took 2.7361695766448975 seconds
population_evaluation took 2.7073848247528076 seconds
population_evaluation took 2.7523391246795654 seconds
population_evaluation took 2.7408134937286377 seconds
population_evaluation took 2.7714407444000244 seconds
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 61/61 [00:00<00:00, 333.54it/s]
synth_matrix: 100%|##########| 61/61 [00:00<00:00, 1185.75it/s]
r_index: 100%|##########| 48/48 [00:00<00:00, 2376.07it/s]
dist_matrix: 100%|##########| 61/61 [00:00<00:00, 436.29it/s]
synth_matrix: 100%|##########| 61/61 [00:00<00:00, 961.54it/s]
r_index: 100%|##########| 48/48 [00:00<00:00, 3388.20it/s]
dist_matrix: 100%|##########| 112/112 [00:00<00:00, 238.43it/s]
r_index: 100%|##########| 42/42 [00:00<00:00, 2669.91it/s]
dist_matrix: 100%|##########| 86/86 [00:00<00:00, 313.12it/s]
r_index: 100%|##########| 68/68 [00:00<00:00, 2292.63it/s]

    SMOGN hatası: SMOGN: tüm relevanslık stratejileri başarısız oldu
  [3/4] STGP-EF eğitim...
population_evaluation took 2.611670970916748 seconds
population_evaluation took 2.7274551391601562 seconds
population_evaluation took 2.674403190612793 seconds
population_evaluation took 2.696038246154785 seconds
population_evaluation took 2.625917673110962 seconds
population_evaluation took 2.707873582839966 seconds
population_evaluation took 2.6572790145874023 seconds
population_evaluation took 2.615915536880493 seconds
population_evaluation took 2.686462163925171 seconds
population_evaluation took 2.6449313163757324 seconds
population_evaluation took 2.675748825073242 seconds
population_evaluation took 2.6610968112945557 seconds
population_evaluation took 2.7467422485351562 seconds
population_evaluation took 2.7272465229034424 seconds
population_evaluation took 2.6889731884002686 seconds
population_evaluation took 2.81112003326416 seconds
population_evaluation took 2.6968300342559814 seconds
population_evaluation took 2.7648422718048096 seconds
population_evaluation took 2.7223525047302246 seconds
population_evaluation took 2.755343198776245 seconds
population_evaluation took 2.7232680320739746 seconds
population_evaluation took 2.9496748447418213 seconds
population_evaluation took 2.9302468299865723 seconds
population_evaluation took 3.027421712875366 seconds
population_evaluation took 2.8578946590423584 seconds
population_evaluation took 2.81193470954895 seconds
population_evaluation took 2.980590581893921 seconds
population_evaluation took 3.077373504638672 seconds
population_evaluation took 3.0692155361175537 seconds
population_evaluation took 2.9924473762512207 seconds
population_evaluation took 2.90954327583313 seconds
population_evaluation took 2.8726186752319336 seconds
population_evaluation took 2.806903123855591 seconds
population_evaluation took 2.8566949367523193 seconds
population_evaluation took 2.883908748626709 seconds
population_evaluation took 2.8425004482269287 seconds
population_evaluation took 2.8375353813171387 seconds
population_evaluation took 2.8156256675720215 seconds
population_evaluation took 2.8610646724700928 seconds
population_evaluation took 2.8566436767578125 seconds
population_evaluation took 2.8576607704162598 seconds
population_evaluation took 2.951547622680664 seconds
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 61/61 [00:00<00:00, 321.27it/s]
synth_matrix: 100%|##########| 61/61 [00:00<00:00, 1275.76it/s]
r_index: 100%|##########| 48/48 [00:00<00:00, 2197.10it/s]

population_evaluation took 2.5467875003814697 seconds
population_evaluation took 2.5927467346191406 seconds
population_evaluation took 2.587972402572632 seconds
population_evaluation took 2.639528512954712 seconds
population_evaluation took 2.577670097351074 seconds
population_evaluation took 2.571643829345703 seconds
population_evaluation took 2.578932762145996 seconds
population_evaluation took 2.5746521949768066 seconds
population_evaluation took 2.552964687347412 seconds
population_evaluation took 2.4706873893737793 seconds
population_evaluation took 2.533400774002075 seconds
population_evaluation took 2.5693867206573486 seconds
population_evaluation took 2.5577635765075684 seconds
population_evaluation took 2.5376877784729004 seconds
population_evaluation took 2.575638771057129 seconds
population_evaluation took 2.520332098007202 seconds
population_evaluation took 2.5475785732269287 seconds
population_evaluation took 2.4856717586517334 seconds
population_evaluation took 2.555537700653076 seconds
population_evaluation took 2.4707095623016357 seconds
population_evaluation took 2.4861903190612793 seconds
population_evaluation took 2.692274332046509 seconds
population_evaluation took 2.595184087753296 seconds
population_evaluation took 2.6286838054656982 seconds
population_evaluation took 2.6311111450195312 seconds
population_evaluation took 2.563894271850586 seconds
population_evaluation took 2.6278810501098633 seconds
population_evaluation took 2.616875410079956 seconds
population_evaluation took 2.6926140785217285 seconds
population_evaluation took 2.5399208068847656 seconds
population_evaluation took 2.6835532188415527 seconds
population_evaluation took 2.664938449859619 seconds
population_evaluation took 2.7155895233154297 seconds
population_evaluation took 2.8010871410369873 seconds
population_evaluation took 2.657927989959717 seconds
population_evaluation took 2.6918036937713623 seconds
population_evaluation took 2.642066717147827 seconds
population_evaluation took 2.6637473106384277 seconds
population_evaluation took 2.642599582672119 seconds
population_evaluation took 2.588372230529785 seconds
population_evaluation took 2.642470121383667 seconds
population_evaluation took 2.6399612426757812 seconds
  Tamamlandı.

### 4.1 Kızgın Buhar — Sonuç Tablosu

In [10]:
df_kizgin_results = build_results_table(kizgin_results)
df_kizgin_results

         Hedef        Senaryo Algoritma  R2_Score
0    v (çıktı)           Base  AdaBoost    0.9822
1    v (çıktı)           Base  CatBoost    0.9979
2    v (çıktı)           Base      DART    0.9908
3    v (çıktı)           Base        EF    0.9998
4    v (çıktı)           Base        ET    0.9998
..         ...            ...       ...       ...
115  s (çıktı)  SMOGN+STGP-EF      GBDT    0.9930
116  s (çıktı)  SMOGN+STGP-EF        GP    0.7704
117  s (çıktı)  SMOGN+STGP-EF  LightGBM    0.9852
118  s (çıktı)  SMOGN+STGP-EF        RF    0.9846
119  s (çıktı)  SMOGN+STGP-EF   XGBoost    0.9818

[120 rows x 4 columns]

### 4.2 Kızgın Buhar — Senaryo Karşılaştırması

In [11]:
compare_scenarios(df_kizgin_results)

Senaryo               Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Hedef     Algoritma
h (çıktı) AdaBoost  0.9703 0.9578   0.9969         0.9836
          CatBoost  0.9988 0.9977   0.9990         0.9980
          DART      0.9776 0.9730   0.9895         0.9876
          EF        0.9998 0.9996   0.9998         0.9995
          ET        0.9997 0.9992   0.9998         0.9994
          GBDT      0.9981 0.9964   0.9994         0.9984
          GP        0.9890 0.8592   0.9844         0.8238
          LightGBM  0.9859 0.9869   0.9983         0.9982
          RF        0.9985 0.9959   0.9996         0.9974
          XGBoost   0.9988 0.9966   0.9987         0.9972
s (çıktı) AdaBoost  0.8655    NaN   0.9785         0.9561
          CatBoost  0.9959    NaN   0.9960         0.9809
          DART      0.9595    NaN   0.9915         0.9777
          EF        0.9979    NaN   0.9972         0.9946
          ET        0.9966    NaN   0.9985         0.9833
          GBDT      0.9911    NaN   0.9972         0.9930
          GP        0.7208    NaN   0.7930         0.7704
          LightGBM  0.9771    NaN   0.9964         0.9852
          RF        0.9846    NaN   0.9927         0.9846
          XGBoost   0.9941    NaN   0.9926         0.9818
v (çıktı) AdaBoost  0.9822 0.9689   0.9872         0.9677
          CatBoost  0.9979 0.9981   0.9995         0.9962
          DART      0.9908 0.9913   0.9949         0.9925
          EF        0.9998 0.9995   0.9998         0.9998
          ET        0.9998 0.9998   0.9998         0.9997
          GBDT      0.9993 0.9991   0.9994         0.9991
          GP        0.0762 0.6443   0.4148         0.0505
          LightGBM  0.9961 0.9972   0.9987         0.9982
          RF        0.9991 0.9990   0.9987         0.9977
          XGBoost   0.9981 0.9987   0.9977         0.9980

### 4.3 Doymuş Buhar — Hedef Bazlı Detay

Her bir hedef değişken için detaylı pivot tablo;

In [22]:
target_summary(df_kizgin_results, 'v (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9822 0.9689   0.9872         0.9677
CatBoost  0.9979 0.9981   0.9995         0.9962
DART      0.9908 0.9913   0.9949         0.9925
EF        0.9998 0.9995   0.9998         0.9998
ET        0.9998 0.9998   0.9998         0.9997
GBDT      0.9993 0.9991   0.9994         0.9991
GP        0.0762 0.6443   0.4148         0.0505
LightGBM  0.9961 0.9972   0.9987         0.9982
RF        0.9991 0.9990   0.9987         0.9977
XGBoost   0.9981 0.9987   0.9977         0.9980

In [23]:
target_summary(df_kizgin_results, 'h (çıktı)')

Senaryo     Base  SMOGN  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.9703 0.9578   0.9969         0.9836
CatBoost  0.9988 0.9977   0.9990         0.9980
DART      0.9776 0.9730   0.9895         0.9876
EF        0.9998 0.9996   0.9998         0.9995
ET        0.9997 0.9992   0.9998         0.9994
GBDT      0.9981 0.9964   0.9994         0.9984
GP        0.9890 0.8592   0.9844         0.8238
LightGBM  0.9859 0.9869   0.9983         0.9982
RF        0.9985 0.9959   0.9996         0.9974
XGBoost   0.9988 0.9966   0.9987         0.9972

In [24]:
target_summary(df_kizgin_results, 's (çıktı)')

Senaryo     Base  STGP-EF  SMOGN+STGP-EF
Algoritma
AdaBoost  0.8655   0.9785         0.9561
CatBoost  0.9959   0.9960         0.9809
DART      0.9595   0.9915         0.9777
EF        0.9979   0.9972         0.9946
ET        0.9966   0.9985         0.9833
GBDT      0.9911   0.9972         0.9930
GP        0.7208   0.7930         0.7704
LightGBM  0.9771   0.9964         0.9852
RF        0.9846   0.9927         0.9846
XGBoost   0.9941   0.9926         0.9818

---
## 5. Genel Karşılaştırma

In [12]:

df_doymus_results['Veri Seti'] = 'Doymuş Buhar'
df_kizgin_results['Veri Seti'] = 'Kızgın Buhar'
df_all = pd.concat([df_doymus_results, df_kizgin_results], ignore_index=True)

print(f'Toplam değerlendirme sayısı: {len(df_all)}')
df_all.head(20)

Toplam değerlendirme sayısı: 400

       Hedef Senaryo Algoritma  R2_Score     Veri Seti
0   P(çıktı)    Base  AdaBoost    0.9986  Doymuş Buhar
1   P(çıktı)    Base  CatBoost    0.9995  Doymuş Buhar
2   P(çıktı)    Base      DART    0.9610  Doymuş Buhar
3   P(çıktı)    Base        EF    1.0000  Doymuş Buhar
4   P(çıktı)    Base        ET    1.0000  Doymuş Buhar
5   P(çıktı)    Base      GBDT    0.9992  Doymuş Buhar
6   P(çıktı)    Base        GP    0.9737  Doymuş Buhar
7   P(çıktı)    Base  LightGBM    0.9710  Doymuş Buhar
8   P(çıktı)    Base        RF    0.9997  Doymuş Buhar
9   P(çıktı)    Base   XGBoost    0.9991  Doymuş Buhar
10  P(çıktı)   SMOGN  AdaBoost    0.9941  Doymuş Buhar
11  P(çıktı)   SMOGN  CatBoost    0.9983  Doymuş Buhar
12  P(çıktı)   SMOGN      DART    0.8967  Doymuş Buhar
13  P(çıktı)   SMOGN        EF    0.9999  Doymuş Buhar
14  P(çıktı)   SMOGN        ET    0.9999  Doymuş Buhar
15  P(çıktı)   SMOGN      GBDT    0.9979  Doymuş Buhar
16  P(çıktı)   SMOGN        GP    0.9272  Doymuş Buhar
17  P(çıktı)   SMOGN  LightGBM    0.9193  Doymuş Buhar
18  P(çıktı)   SMOGN        RF    0.9986  Doymuş Buhar
19  P(çıktı)   SMOGN   XGBoost    0.9932  Doymuş Buhar

In [13]:
# Senaryo bazlı ortalama R² skorları
df_all.groupby(['Veri Seti', 'Senaryo'])['R2_Score'].mean().unstack()

Senaryo        Base  SMOGN  SMOGN+STGP-EF  STGP-EF
Veri Seti
Doymuş Buhar 0.9554 0.9724         0.9182   0.9876
Kızgın Buhar 0.9480 0.9679         0.9463   0.9696

In [14]:
# Algoritma bazlı ortalama R² skorları
df_all.groupby(['Veri Seti', 'Algoritma'])['R2_Score'].mean().unstack()

Algoritma     AdaBoost  CatBoost   DART     EF     ET   GBDT     GP  LightGBM     RF  XGBoost
Veri Seti
Doymuş Buhar    0.9866    0.9962 0.9115 0.9949 0.9909 0.9961 0.7841    0.9358 0.9966   0.9913
Kızgın Buhar    0.9650    0.9962 0.9842 0.9988 0.9978 0.9973 0.6479    0.9926 0.9953   0.9957

In [15]:
# Geniş formatlı sonuç tablosu oluştur ve kaydet
df_wide = save_wide_results(df_all, 'R515B_Ozellikler/Model_Training_Results.csv')
print('Sonuçlar R515B_Ozellikler/Model_Training_Results.csv dosyasına kaydedildi.')
print(f'Format: Geniş tablo — {len(df_wide)} satır, {len(df_wide.columns)} sütun')
df_wide

Sonuçlar R515B_Ozellikler/Model_Training_Results.csv dosyasına kaydedildi.
Format: Geniş tablo — 100 satır, 9 sütun

Senaryo     Veri Seti      Hedef Algoritma   Base  SMOGN  STGP-EF  SMOGN+STGP-EF  Max_R2 Max_Senaryo
0        Doymuş Buhar   P(çıktı)  AdaBoost 0.9986 0.9941   0.9991         0.9967  0.9991     STGP-EF
1        Doymuş Buhar   P(çıktı)  CatBoost 0.9995 0.9983   0.9997         0.9993  0.9997     STGP-EF
2        Doymuş Buhar   P(çıktı)      DART 0.9610 0.8967   0.9669         0.9182  0.9669     STGP-EF
3        Doymuş Buhar   P(çıktı)        EF 1.0000 0.9999   1.0000         0.9998  1.0000     STGP-EF
4        Doymuş Buhar   P(çıktı)        ET 1.0000 0.9999   1.0000         0.9999  1.0000        Base
..                ...        ...       ...    ...    ...      ...            ...     ...         ...
95       Kızgın Buhar  v (çıktı)      GBDT 0.9993 0.9991   0.9994         0.9991  0.9994     STGP-EF
96       Kızgın Buhar  v (çıktı)        GP 0.0762 0.6443   0.4148         0.0505  0.6443       SMOGN
97       Kızgın Buhar  v (çıktı)  LightGBM 0.9961 0.9972   0.9987         0.9982  0.9987     STGP-EF
98       Kızgın Buhar  v (çıktı)        RF 0.9991 0.9990   0.9987         0.9977  0.9991        Base
99       Kızgın Buhar  v (çıktı)   XGBoost 0.9981 0.9987   0.9977         0.9980  0.9987       SMOGN

[100 rows x 9 columns]