# R515B Soğutucu Akışkan — Model Eğitimi

Bu notebook, Doymuş ve Kızgın buhar veri setleri için **4 farklı senaryo** ile regresyon modeli eğitimi yapar:

| # | Senaryo | Açıklama |
|---|---------|----------|
| 1 | **Base** | Orijinal veri ile temel eğitim |
| 2 | **SMOGN** | SMOGN ile veri artırma sonrası eğitim |
| 3 | **STGP-EF** | SymbolicTransformer ile öznitelik çıkarımı sonrası eğitim |
| 4 | **SMOGN+STGP-EF** | Önce SMOGN, sonra STGP-EF ile birleşik eğitim |

Her senaryo **8 farklı regresyon algoritması** ile değerlendirilir (RF, ET, AdaBoost, GBDT, DART, XGBoost, LightGBM, CatBoost).

---

## 1. Kütüphaneler ve Fonksiyonlar

In [1]:
import sys
sys.path.insert(0, 'R515B_Ozellikler')

import pandas as pd
import numpy as np
from Functions import (
    run_doymus_analysis,
    run_kizgin_analysis,
    build_results_table,
    compare_scenarios,
    show_best_results,
    target_summary
)

print('Fonksiyonlar başarıyla yüklendi.')

c:\Users\SGUZEY\Documents\Yüksek Lisans Dersleri\Veri Mühendisliği\Data_Engineering_Project\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Fonksiyonlar başarıyla yüklendi.

## 2. Veri Yükleme

In [2]:
df_doymus = pd.read_csv('R515B_Ozellikler/R515B_Doymus_Ozellikleri.csv')
df_kizgin = pd.read_csv('R515B_Ozellikler/R515B_Kizgin_Buhar.csv')

print(f'Doymuş Buhar: {df_doymus.shape}')
print(f'Kızgın Buhar: {df_kizgin.shape}')
print(f'\nDoymuş Sütunlar: {list(df_doymus.columns)}')
print(f'Kızgın Sütunlar: {list(df_kizgin.columns)}')

Doymuş Buhar: (136, 8)
Kızgın Buhar: (578, 5)

Doymuş Sütunlar: ['T(girdi)', 'P(çıktı)', 'v sıvı (çıktı)', 'v buhar (çıktı)', 'h sıvı (çıktı)', 'h buhar (çıktı)', 's sıvı (çıktı)', 's buhar (çıktı)']
Kızgın Sütunlar: ['T (girdi)', 'P (girdi)', 'v (çıktı)', 'h (çıktı)', 's (çıktı)']

In [3]:
df_doymus.head()

   T(girdi)  P(çıktı)  v sıvı (çıktı)  v buhar (çıktı)  h sıvı (çıktı)  h buhar (çıktı)  s sıvı (çıktı)  s buhar (çıktı)
0       -30   61.2210          0.0007           0.2726          2.7282         198.2000          0.0446           0.8486
1       -29   64.2350          0.0007           0.2606          3.9422         198.8900          0.0496           0.8481
2       -28   67.3670          0.0007           0.2492          5.1587         199.5800          0.0546           0.8476
3       -27   70.6200          0.0007           0.2385          6.3775         200.2700          0.0595           0.8472
4       -26   73.9960          0.0008           0.2282          7.5988         200.9500          0.0645           0.8468

In [4]:
df_kizgin.head()

   T (girdi)  P (girdi)  v (çıktı)  h (çıktı)  s (çıktı)
0        -30         50     0.3357   198.5500     0.8639
1        -25         50     0.3433   202.4500     0.8798
2        -20         50     0.3508   206.4000     0.8956
3        -15         50     0.3582   210.4000     0.9112
4        -10         50     0.3656   214.4300     0.9267

---
## 3. Doymuş Buhar — Eğitim

**Girdi:** T(girdi)  
**Çıktılar (her biri ayrı ayrı):** P, v sıvı, v buhar, h sıvı, h buhar, s sıvı, s buhar

In [5]:
doymus_results = run_doymus_analysis(df_doymus)

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  DOYMUŞ BUHAR ANALİZİ
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

============================================================
  Hedef: P(çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...
    SMOGN hatası: redefine phi relevance function: all points are 1
  [3/4] STGP-EF eğitim...
    STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  [4/4] SMOGN + STGP-EF eğitim...
    SMOGN+STGP-EF hatası: redefine phi relevance function: all points are 1
  Tamamlandı.


============================================================
  Hedef: v sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 16/16 [00:00<00:00, 1829.33it/s]
synth_matrix: 100%|##########| 16/16 [00:00<00:00, 2153.06it/s]
r_index: 100%|##########| 6/6 [00:00<00:00, 626.31it/s]

  [3/4] STGP-EF eğitim...
    STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 16/16 [00:00<00:00, 2282.15it/s]
synth_matrix: 100%|##########| 16/16 [00:00<00:00, 1205.30it/s]
r_index: 100%|##########| 6/6 [00:00<?, ?it/s]

    SMOGN+STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  Tamamlandı.


============================================================
  Hedef: v buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...

  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 21/21 [00:00<00:00, 1461.75it/s]
synth_matrix: 100%|##########| 21/21 [00:00<00:00, 2886.08it/s]
r_index: 100%|##########| 12/12 [00:00<00:00, 3941.71it/s]

  [3/4] STGP-EF eğitim...
    STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 21/21 [00:00<00:00, 1381.13it/s]
synth_matrix: 100%|##########| 21/21 [00:00<00:00, 1606.90it/s]
r_index: 100%|##########| 12/12 [00:00<00:00, 1678.17it/s]

    SMOGN+STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  Tamamlandı.


============================================================
  Hedef: h sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...

  [2/4] SMOGN eğitim...
    SMOGN hatası: redefine phi relevance function: all points are 1
  [3/4] STGP-EF eğitim...
    STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  [4/4] SMOGN + STGP-EF eğitim...
    SMOGN+STGP-EF hatası: redefine phi relevance function: all points are 1
  Tamamlandı.


============================================================
  Hedef: h buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...
    SMOGN hatası: redefine phi relevance function: all points are 1
  [3/4] STGP-EF eğitim...
    STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  [4/4] SMOGN + STGP-EF eğitim...
    SMOGN+STGP-EF hatası: redefine phi relevance function: all points are 1
  Tamamlandı.


============================================================
  Hedef: s sıvı (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...
    SMOGN hatası: redefine phi relevance function: all points are 1
  [3/4] STGP-EF eğitim...
    STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  [4/4] SMOGN + STGP-EF eğitim...
    SMOGN+STGP-EF hatası: redefine phi relevance function: all points are 1
  Tamamlandı.


============================================================
  Hedef: s buhar (çıktı)  |  Girdi: ['T(girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 6/6 [00:00<?, ?it/s]
synth_matrix: 100%|##########| 6/6 [00:00<00:00, 390.59it/s]

  [3/4] STGP-EF eğitim...
    STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 6/6 [00:00<00:00, 614.57it/s]
synth_matrix: 100%|##########| 6/6 [00:00<00:00, 346.62it/s]

    SMOGN+STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  Tamamlandı.

### 3.1 Doymuş Buhar — Sonuç Tablosu

In [6]:
df_doymus_results = build_results_table(doymus_results)
df_doymus_results

               Hedef        Senaryo Algoritma  R2_Score
0           P(çıktı)           Base        RF    0.9997
1           P(çıktı)           Base        ET    1.0000
2           P(çıktı)           Base  AdaBoost    0.9986
3           P(çıktı)           Base      GBDT    0.9992
4           P(çıktı)           Base      DART    0.9610
..               ...            ...       ...       ...
219  s buhar (çıktı)  SMOGN+STGP-EF      GBDT       NaN
220  s buhar (çıktı)  SMOGN+STGP-EF      DART       NaN
221  s buhar (çıktı)  SMOGN+STGP-EF   XGBoost       NaN
222  s buhar (çıktı)  SMOGN+STGP-EF  LightGBM       NaN
223  s buhar (çıktı)  SMOGN+STGP-EF  CatBoost       NaN

[224 rows x 4 columns]

### 3.2 Doymuş Buhar — Senaryo Karşılaştırması

In [7]:
compare_scenarios(df_doymus_results)

Senaryo                     Base  SMOGN
Hedef           Algoritma
P(çıktı)        AdaBoost  0.9986    NaN
                CatBoost  0.9995    NaN
                DART      0.9610    NaN
                ET        1.0000    NaN
                GBDT      0.9992    NaN
                LightGBM  0.9710    NaN
                RF        0.9997    NaN
                XGBoost   0.9991    NaN
h buhar (çıktı) AdaBoost  0.9961    NaN
                CatBoost  0.9993    NaN
                DART      0.9765    NaN
                ET        1.0000    NaN
                GBDT      0.9990    NaN
                LightGBM  0.9747    NaN
                RF        0.9997    NaN
                XGBoost   0.9986    NaN
h sıvı (çıktı)  AdaBoost  0.9993    NaN
                CatBoost  0.9996    NaN
                DART      0.9749    NaN
                ET        1.0000    NaN
                GBDT      0.9993    NaN
                LightGBM  0.9793    NaN
                RF        0.9998    NaN
                XGBoost   0.9991    NaN
s buhar (çıktı) AdaBoost  0.9163 0.8472
                CatBoost  0.9793 0.9460
                DART      0.4471 0.9211
                ET        0.9996 0.9946
                GBDT      0.9737 0.9286
                LightGBM  0.4591 0.9083
                RF        0.9899 0.9350
                XGBoost   0.9785 0.8426
s sıvı (çıktı)  AdaBoost  0.9996    NaN
                CatBoost  0.9995    NaN
                DART      0.9753    NaN
                ET        1.0000    NaN
                GBDT      0.9993    NaN
                LightGBM  0.9778    NaN
                RF        0.9998    NaN
                XGBoost   0.9990    NaN
v buhar (çıktı) AdaBoost  0.9909 0.9885
                CatBoost  0.9971 0.9967
                DART      0.8327 0.9800
                ET        1.0000 0.9994
                GBDT      0.9965 0.9931
                LightGBM  0.8011 0.9875
                RF        0.9989 0.9952
                XGBoost   0.9951 0.9848
v sıvı (çıktı)  AdaBoost  0.9971 0.9985
                CatBoost  0.9986 0.9995
                DART      0.9345 0.9378
                ET        1.0000 0.9998
                GBDT      0.9978 0.9996
                LightGBM  0.9429 0.9401
                RF        0.9992 0.9998
                XGBoost   0.9981 0.9973

### 3.3 Doymuş Buhar — En İyi Sonuçlar

In [8]:
show_best_results(df_doymus_results)

             Hedef Senaryo Algoritma  R2_Score
0         P(çıktı)    Base        ET    1.0000
1  h buhar (çıktı)    Base        ET    1.0000
2   h sıvı (çıktı)    Base        ET    1.0000
3  s buhar (çıktı)    Base        ET    0.9996
4   s sıvı (çıktı)    Base        ET    1.0000
5  v buhar (çıktı)    Base        ET    1.0000
6   v sıvı (çıktı)    Base        ET    1.0000

### 3.4 Doymuş Buhar — Hedef Bazlı Detay

Herhangi bir hedef değişken için detaylı pivot tablo görmek isterseniz:

In [9]:
# Örnek: P(çıktı) hedefi için senaryo karşılaştırması
target_summary(df_doymus_results, 'P(çıktı)')

Senaryo     Base
Algoritma
AdaBoost  0.9986
CatBoost  0.9995
DART      0.9610
ET        1.0000
GBDT      0.9992
LightGBM  0.9710
RF        0.9997
XGBoost   0.9991

---
## 4. Kızgın Buhar — Eğitim

**Girdiler:** T (girdi), P (girdi)  
**Çıktılar (her biri ayrı ayrı):** v, h, s

In [10]:
kizgin_results = run_kizgin_analysis(df_kizgin)

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  KIZGIN BUHAR ANALİZİ
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

============================================================
  Hedef: v (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 90/90 [00:00<00:00, 289.69it/s]
synth_matrix: 100%|##########| 90/90 [00:00<00:00, 2575.11it/s]
r_index: 100%|##########| 51/51 [00:00<00:00, 2148.01it/s]

  [3/4] STGP-EF eğitim...
    STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 90/90 [00:00<00:00, 282.28it/s]
synth_matrix: 100%|##########| 90/90 [00:00<00:00, 2470.01it/s]
r_index: 100%|##########| 51/51 [00:00<00:00, 2334.42it/s]

    SMOGN+STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  Tamamlandı.


============================================================
  Hedef: h (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 55/55 [00:00<00:00, 437.05it/s]
synth_matrix: 100%|##########| 55/55 [00:00<00:00, 858.10it/s]
r_index: 100%|##########| 11/11 [00:00<00:00, 1658.07it/s]

  [3/4] STGP-EF eğitim...
    STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 55/55 [00:00<00:00, 493.62it/s]
synth_matrix: 100%|##########| 55/55 [00:00<00:00, 983.81it/s]
r_index: 100%|##########| 11/11 [00:00<00:00, 2343.66it/s]

    SMOGN+STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  Tamamlandı.


============================================================
  Hedef: s (çıktı)  |  Girdi: ['T (girdi)', 'P (girdi)']
============================================================
  [1/4] Base eğitim...
  [2/4] SMOGN eğitim...

dist_matrix: 100%|##########| 61/61 [00:00<00:00, 435.58it/s]
synth_matrix: 100%|##########| 61/61 [00:00<00:00, 1464.70it/s]
r_index: 100%|##########| 48/48 [00:00<00:00, 2979.22it/s]

  [3/4] STGP-EF eğitim...
    STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  [4/4] SMOGN + STGP-EF eğitim...

dist_matrix: 100%|##########| 61/61 [00:00<00:00, 405.60it/s]
synth_matrix: 100%|##########| 61/61 [00:00<00:00, 1127.82it/s]
r_index: 100%|##########| 48/48 [00:00<00:00, 5382.78it/s]

    SMOGN+STGP-EF hatası: 'super' object has no attribute '__sklearn_tags__'
  Tamamlandı.

### 4.1 Kızgın Buhar — Sonuç Tablosu

In [11]:
df_kizgin_results = build_results_table(kizgin_results)
df_kizgin_results

        Hedef        Senaryo Algoritma  R2_Score
0   v (çıktı)           Base        RF    0.9991
1   v (çıktı)           Base        ET    0.9998
2   v (çıktı)           Base  AdaBoost    0.9822
3   v (çıktı)           Base      GBDT    0.9993
4   v (çıktı)           Base      DART    0.9908
..        ...            ...       ...       ...
91  s (çıktı)  SMOGN+STGP-EF      GBDT       NaN
92  s (çıktı)  SMOGN+STGP-EF      DART       NaN
93  s (çıktı)  SMOGN+STGP-EF   XGBoost       NaN
94  s (çıktı)  SMOGN+STGP-EF  LightGBM       NaN
95  s (çıktı)  SMOGN+STGP-EF  CatBoost       NaN

[96 rows x 4 columns]

### 4.2 Kızgın Buhar — Senaryo Karşılaştırması

In [12]:
compare_scenarios(df_kizgin_results)

Senaryo               Base  SMOGN
Hedef     Algoritma
h (çıktı) AdaBoost  0.9703 0.8915
          CatBoost  0.9988 0.9551
          DART      0.9776 0.9618
          ET        0.9997 0.9485
          GBDT      0.9981 0.9603
          LightGBM  0.9859 0.9578
          RF        0.9985 0.9483
          XGBoost   0.9988 0.9615
s (çıktı) AdaBoost  0.8655 0.8248
          CatBoost  0.9959 0.9810
          DART      0.9595 0.8609
          ET        0.9966 0.9807
          GBDT      0.9911 0.9773
          LightGBM  0.9771 0.9023
          RF        0.9846 0.9571
          XGBoost   0.9941 0.9771
v (çıktı) AdaBoost  0.9822 0.9683
          CatBoost  0.9979 0.9984
          DART      0.9908 0.9887
          ET        0.9998 0.9996
          GBDT      0.9993 0.9991
          LightGBM  0.9961 0.9955
          RF        0.9991 0.9986
          XGBoost   0.9981 0.9984

### 4.3 Kızgın Buhar — En İyi Sonuçlar

In [13]:
show_best_results(df_kizgin_results)

       Hedef Senaryo Algoritma  R2_Score
0  h (çıktı)    Base        ET    0.9997
1  s (çıktı)    Base        ET    0.9966
2  v (çıktı)    Base        ET    0.9998

---
## 5. Genel Karşılaştırma

In [14]:
# Tüm sonuçları birleştir
df_doymus_results['Veri Seti'] = 'Doymuş Buhar'
df_kizgin_results['Veri Seti'] = 'Kızgın Buhar'
df_all = pd.concat([df_doymus_results, df_kizgin_results], ignore_index=True)

print(f'Toplam değerlendirme sayısı: {len(df_all)}')
df_all.head(10)

Toplam değerlendirme sayısı: 320

      Hedef Senaryo Algoritma  R2_Score     Veri Seti
0  P(çıktı)    Base        RF    0.9997  Doymuş Buhar
1  P(çıktı)    Base        ET    1.0000  Doymuş Buhar
2  P(çıktı)    Base  AdaBoost    0.9986  Doymuş Buhar
3  P(çıktı)    Base      GBDT    0.9992  Doymuş Buhar
4  P(çıktı)    Base      DART    0.9610  Doymuş Buhar
5  P(çıktı)    Base   XGBoost    0.9991  Doymuş Buhar
6  P(çıktı)    Base  LightGBM    0.9710  Doymuş Buhar
7  P(çıktı)    Base  CatBoost    0.9995  Doymuş Buhar
8  P(çıktı)   SMOGN        RF       NaN  Doymuş Buhar
9  P(çıktı)   SMOGN        ET       NaN  Doymuş Buhar

In [15]:
# Senaryo bazlı ortalama R² skorları
df_all.groupby(['Veri Seti', 'Senaryo'])['R2_Score'].mean().unstack()

Senaryo        Base  SMOGN  SMOGN+STGP-EF  STGP-EF
Veri Seti
Doymuş Buhar 0.9642 0.9634            NaN      NaN
Kızgın Buhar 0.9856 0.9580            NaN      NaN

In [16]:
# Algoritma bazlı ortalama R² skorları
df_all.groupby(['Veri Seti', 'Algoritma'])['R2_Score'].mean().unstack()

Algoritma     AdaBoost  CatBoost   DART     ET   GBDT  LightGBM     RF  XGBoost
Veri Seti
Doymuş Buhar    0.9732    0.9915 0.8941 0.9993 0.9886    0.8942 0.9917   0.9792
Kızgın Buhar    0.9171    0.9878 0.9565 0.9875 0.9875    0.9691 0.9810   0.9880

In [17]:
# Sonuçları CSV olarak kaydet
df_all.to_csv('R515B_Ozellikler/Model_Training_Results.csv', index=False)
print('Sonuçlar R515B_Ozellikler/Model_Training_Results.csv dosyasına kaydedildi.')

Sonuçlar R515B_Ozellikler/Model_Training_Results.csv dosyasına kaydedildi.